/* gtkamlvalaparser.c generated by valac 0.56.16, the Vala compiler
 * generated from gtkamlvalaparser.vala, do not modify */

/* gtkamlvalaparser.vala
 *
 * Copyright (C) 2011 Vlad Grecescu
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public
 * License along with main.c; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor Boston, MA 02110-1301,  USA
 *
 * Author:
 *        Vlad Grecescu (b100dian@gmail.com)
 */

#include "gtkaml.h"
#include <glib.h>
#include <valagee.h>
#include <glib-object.h>
#include <vala.h>
#include <stdlib.h>
#include <string.h>
#include <glib/gstdio.h>
#include <gobject/gvaluecollector.h>

#if !defined(VALA_STRICT_C)
#if !defined(__clang__) && defined(__GNUC__) && (__GNUC__ >= 14)
#pragma GCC diagnostic warning "-Wincompatible-pointer-types"
#elif defined(__clang__) && (__clang_major__ >= 16)
#pragma clang diagnostic ignored "-Wincompatible-function-pointer-types"
#pragma clang diagnostic ignored "-Wincompatible-pointer-types"
#endif
#endif

#define _vala_code_context_unref0(var) ((var == NULL) ? NULL : (var = (vala_code_context_unref (var), NULL)))
#define _vala_iterable_unref0(var) ((var == NULL) ? NULL : (var = (vala_iterable_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
#define _vala_code_node_unref0(var) ((var == NULL) ? NULL : (var = (vala_code_node_unref (var), NULL)))
#define _vala_iterator_unref0(var) ((var == NULL) ? NULL : (var = (vala_iterator_unref (var), NULL)))
#define _vala_code_visitor_unref0(var) ((var == NULL) ? NULL : (var = (vala_code_visitor_unref (var), NULL)))
#define _vala_source_file_unref0(var) ((var == NULL) ? NULL : (var = (vala_source_file_unref (var), NULL)))
typedef struct _GtkamlParamSpecValaParser GtkamlParamSpecValaParser;

struct _GtkamlParamSpecValaParser {
	GParamSpec parent_instance;
};

static gpointer gtkaml_vala_parser_parent_class = NULL;

static ValaNamespace* gtkaml_vala_parser_parse (GtkamlValaParser* self,
                                         ValaSourceFile* original_source,
                                         const gchar* source,
                                         const gchar* temp_filename);
static void gtkaml_vala_parser_finalize (GtkamlValaParser * obj);
static GType gtkaml_vala_parser_get_type_once (void);

static gpointer
_vala_code_context_ref0 (gpointer self)
{
	return self ? vala_code_context_ref (self) : NULL;
}

GtkamlValaParser*
gtkaml_vala_parser_construct (GType object_type,
                              GtkamlCodeContext* real_context)
{
	GtkamlValaParser* self = NULL;
	GtkamlCodeContext* _tmp0_;
	g_return_val_if_fail (real_context != NULL, NULL);
	self = (GtkamlValaParser*) g_type_create_instance (object_type);
	_tmp0_ = _vala_code_context_ref0 (real_context);
	_vala_code_context_unref0 (self->real_context);
	self->real_context = _tmp0_;
	return self;
}

GtkamlValaParser*
gtkaml_vala_parser_new (GtkamlCodeContext* real_context)
{
	return gtkaml_vala_parser_construct (GTKAML_TYPE_VALA_PARSER, real_context);
}

/**
 * parses CDATA code containing class members. <br/>
 * TODO use Vala.Parser.parse_declarations in the future
 */
ValaClass*
gtkaml_vala_parser_parse_members (GtkamlValaParser* self,
                                  GtkamlMarkupClass* markup_class,
                                  const gchar* members_source)
{
	gchar* class_name = NULL;
	const gchar* _tmp0_;
	const gchar* _tmp1_;
	gchar* _tmp2_;
	gchar* temp_source = NULL;
	const gchar* _tmp3_;
	gchar* _tmp4_;
	ValaNamespace* temp_ns = NULL;
	ValaSourceReference* _tmp5_;
	ValaSourceReference* _tmp6_;
	ValaSourceFile* _tmp7_;
	ValaSourceFile* _tmp8_;
	const gchar* _tmp9_;
	const gchar* _tmp10_;
	gchar* _tmp11_;
	gchar* _tmp12_;
	ValaNamespace* _tmp13_;
	ValaNamespace* _tmp14_;
	gboolean _tmp22_ = FALSE;
	ValaNamespace* _tmp23_;
	ValaClass* result;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (markup_class != NULL, NULL);
	g_return_val_if_fail (members_source != NULL, NULL);
	_tmp0_ = vala_symbol_get_name ((ValaSymbol*) markup_class);
	_tmp1_ = _tmp0_;
	_tmp2_ = g_strdup (_tmp1_);
	class_name = _tmp2_;
	_tmp3_ = class_name;
	_tmp4_ = g_strdup_printf ("public class %s { %s }", _tmp3_, members_source);
	temp_source = _tmp4_;
	_tmp5_ = vala_code_node_get_source_reference ((ValaCodeNode*) markup_class);
	_tmp6_ = _tmp5_;
	_tmp7_ = vala_source_reference_get_file (_tmp6_);
	_tmp8_ = _tmp7_;
	_tmp9_ = temp_source;
	_tmp10_ = class_name;
	_tmp11_ = g_strconcat (_tmp10_, "-members", NULL);
	_tmp12_ = _tmp11_;
	_tmp13_ = gtkaml_vala_parser_parse (self, _tmp8_, _tmp9_, _tmp12_);
	_tmp14_ = _tmp13_;
	_g_free0 (_tmp12_);
	temp_ns = _tmp14_;
	while (TRUE) {
		ValaNamespace* _tmp15_;
		ValaList* _tmp16_;
		gint _tmp17_;
		gint _tmp18_;
		ValaNamespace* _tmp19_;
		ValaList* _tmp20_;
		gpointer _tmp21_;
		_tmp15_ = temp_ns;
		_tmp16_ = vala_namespace_get_namespaces (_tmp15_);
		_tmp17_ = vala_collection_get_size ((ValaCollection*) _tmp16_);
		_tmp18_ = _tmp17_;
		if (!(_tmp18_ > 0)) {
			break;
		}
		_tmp19_ = temp_ns;
		_tmp20_ = vala_namespace_get_namespaces (_tmp19_);
		_tmp21_ = vala_list_get (_tmp20_, 0);
		_vala_code_node_unref0 (temp_ns);
		temp_ns = (ValaNamespace*) _tmp21_;
	}
	_tmp23_ = temp_ns;
	if (G_TYPE_CHECK_INSTANCE_TYPE (_tmp23_, VALA_TYPE_NAMESPACE)) {
		ValaNamespace* _tmp24_;
		ValaList* _tmp25_;
		gint _tmp26_;
		gint _tmp27_;
		_tmp24_ = temp_ns;
		_tmp25_ = vala_namespace_get_classes (_tmp24_);
		_tmp26_ = vala_collection_get_size ((ValaCollection*) _tmp25_);
		_tmp27_ = _tmp26_;
		_tmp22_ = _tmp27_ == 1;
	} else {
		_tmp22_ = FALSE;
	}
	if (_tmp22_) {
		ValaNamespace* _tmp28_;
		ValaList* _tmp29_;
		gpointer _tmp30_;
		_tmp28_ = temp_ns;
		_tmp29_ = vala_namespace_get_classes (_tmp28_);
		_tmp30_ = vala_list_get (_tmp29_, 0);
		result = (ValaClass*) _tmp30_;
		_vala_code_node_unref0 (temp_ns);
		_g_free0 (temp_source);
		_g_free0 (class_name);
		return result;
	} else {
		ValaSourceReference* _tmp31_;
		ValaSourceReference* _tmp32_;
		_tmp31_ = vala_code_node_get_source_reference ((ValaCodeNode*) markup_class);
		_tmp32_ = _tmp31_;
		vala_report_error (_tmp32_, "There was an error parsing the code section: members");
		result = NULL;
		_vala_code_node_unref0 (temp_ns);
		_g_free0 (temp_source);
		_g_free0 (class_name);
		return result;
	}
}

/**
 * parses an attribute value that is coded as an expression.<br />
 * TODO use Vala.Parser.parse_expression in the future
 */
static gpointer
_vala_code_node_ref0 (gpointer self)
{
	return self ? vala_code_node_ref (self) : NULL;
}

ValaExpression*
gtkaml_vala_parser_parse_expression (GtkamlValaParser* self,
                                     GtkamlMarkupClass* markup_class,
                                     const gchar* target,
                                     const gchar* target_member,
                                     const gchar* expression_source)
{
	gchar* class_name = NULL;
	const gchar* _tmp0_;
	const gchar* _tmp1_;
	gchar* _tmp2_;
	gchar* temp_source = NULL;
	gchar* _tmp3_;
	ValaNamespace* temp_ns = NULL;
	ValaSourceReference* _tmp4_;
	ValaSourceReference* _tmp5_;
	ValaSourceFile* _tmp6_;
	ValaSourceFile* _tmp7_;
	const gchar* _tmp8_;
	const gchar* _tmp9_;
	gchar* _tmp10_;
	gchar* _tmp11_;
	gchar* _tmp12_;
	gchar* _tmp13_;
	gchar* _tmp14_;
	gchar* _tmp15_;
	gchar* _tmp16_;
	gchar* _tmp17_;
	gchar* _tmp18_;
	gchar* _tmp19_;
	ValaNamespace* _tmp20_;
	ValaNamespace* _tmp21_;
	gboolean _tmp22_ = FALSE;
	gboolean _tmp23_ = FALSE;
	ValaNamespace* _tmp24_;
	ValaExpression* result;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (markup_class != NULL, NULL);
	g_return_val_if_fail (target != NULL, NULL);
	g_return_val_if_fail (target_member != NULL, NULL);
	g_return_val_if_fail (expression_source != NULL, NULL);
	_tmp0_ = vala_symbol_get_name ((ValaSymbol*) markup_class);
	_tmp1_ = _tmp0_;
	_tmp2_ = g_strdup (_tmp1_);
	class_name = _tmp2_;
	_tmp3_ = g_strdup_printf ("VoidFunc voidFunc = ()=> %s;", expression_source);
	temp_source = _tmp3_;
	_tmp4_ = vala_code_node_get_source_reference ((ValaCodeNode*) markup_class);
	_tmp5_ = _tmp4_;
	_tmp6_ = vala_source_reference_get_file (_tmp5_);
	_tmp7_ = _tmp6_;
	_tmp8_ = temp_source;
	_tmp9_ = class_name;
	_tmp10_ = g_strconcat (_tmp9_, "_", NULL);
	_tmp11_ = _tmp10_;
	_tmp12_ = g_strconcat (_tmp11_, target, NULL);
	_tmp13_ = _tmp12_;
	_tmp14_ = g_strconcat (_tmp13_, "_", NULL);
	_tmp15_ = _tmp14_;
	_tmp16_ = g_strconcat (_tmp15_, target_member, NULL);
	_tmp17_ = _tmp16_;
	_tmp18_ = g_strconcat (_tmp17_, "_expression", NULL);
	_tmp19_ = _tmp18_;
	_tmp20_ = gtkaml_vala_parser_parse (self, _tmp7_, _tmp8_, _tmp19_);
	_tmp21_ = _tmp20_;
	_g_free0 (_tmp19_);
	_g_free0 (_tmp17_);
	_g_free0 (_tmp15_);
	_g_free0 (_tmp13_);
	_g_free0 (_tmp11_);
	temp_ns = _tmp21_;
	_tmp24_ = temp_ns;
	if (G_TYPE_CHECK_INSTANCE_TYPE (_tmp24_, VALA_TYPE_NAMESPACE)) {
		ValaNamespace* _tmp25_;
		ValaList* _tmp26_;
		gint _tmp27_;
		gint _tmp28_;
		_tmp25_ = temp_ns;
		_tmp26_ = vala_namespace_get_fields (_tmp25_);
		_tmp27_ = vala_collection_get_size ((ValaCollection*) _tmp26_);
		_tmp28_ = _tmp27_;
		_tmp23_ = _tmp28_ == 1;
	} else {
		_tmp23_ = FALSE;
	}
	if (_tmp23_) {
		ValaNamespace* _tmp29_;
		ValaList* _tmp30_;
		gpointer _tmp31_;
		ValaField* _tmp32_;
		ValaExpression* _tmp33_;
		ValaExpression* _tmp34_;
		_tmp29_ = temp_ns;
		_tmp30_ = vala_namespace_get_fields (_tmp29_);
		_tmp31_ = vala_list_get (_tmp30_, 0);
		_tmp32_ = (ValaField*) _tmp31_;
		_tmp33_ = vala_variable_get_initializer ((ValaVariable*) _tmp32_);
		_tmp34_ = _tmp33_;
		_tmp22_ = G_TYPE_CHECK_INSTANCE_TYPE (_tmp34_, VALA_TYPE_LAMBDA_EXPRESSION);
		_vala_code_node_unref0 (_tmp32_);
	} else {
		_tmp22_ = FALSE;
	}
	if (_tmp22_) {
		ValaLambdaExpression* temp_lambda = NULL;
		ValaNamespace* _tmp35_;
		ValaList* _tmp36_;
		gpointer _tmp37_;
		ValaField* _tmp38_;
		ValaExpression* _tmp39_;
		ValaExpression* _tmp40_;
		ValaLambdaExpression* _tmp41_;
		ValaLambdaExpression* _tmp42_;
		ValaLambdaExpression* _tmp43_;
		ValaExpression* _tmp44_;
		ValaExpression* _tmp45_;
		ValaExpression* _tmp46_;
		_tmp35_ = temp_ns;
		_tmp36_ = vala_namespace_get_fields (_tmp35_);
		_tmp37_ = vala_list_get (_tmp36_, 0);
		_tmp38_ = (ValaField*) _tmp37_;
		_tmp39_ = vala_variable_get_initializer ((ValaVariable*) _tmp38_);
		_tmp40_ = _tmp39_;
		_tmp41_ = _vala_code_node_ref0 (G_TYPE_CHECK_INSTANCE_CAST (_tmp40_, VALA_TYPE_LAMBDA_EXPRESSION, ValaLambdaExpression));
		_tmp42_ = _tmp41_;
		_vala_code_node_unref0 (_tmp38_);
		temp_lambda = _tmp42_;
		_tmp43_ = temp_lambda;
		_tmp44_ = vala_lambda_expression_get_expression_body (_tmp43_);
		_tmp45_ = _tmp44_;
		_tmp46_ = _vala_code_node_ref0 (_tmp45_);
		result = _tmp46_;
		_vala_code_node_unref0 (temp_lambda);
		_vala_code_node_unref0 (temp_ns);
		_g_free0 (temp_source);
		_g_free0 (class_name);
		return result;
	} else {
		ValaSourceReference* _tmp47_;
		ValaSourceReference* _tmp48_;
		_tmp47_ = vala_code_node_get_source_reference ((ValaCodeNode*) markup_class);
		_tmp48_ = _tmp47_;
		vala_report_error (_tmp48_, "There was an error parsing the code section: expression");
		result = NULL;
		_vala_code_node_unref0 (temp_ns);
		_g_free0 (temp_source);
		_g_free0 (class_name);
		return result;
	}
}

/**
 * parses a signal value that is coded as an expression.<br />
 * TODO use Vala.Parser.parse_block in the future
 */
ValaBlock*
gtkaml_vala_parser_parse_statements (GtkamlValaParser* self,
                                     GtkamlMarkupClass* markup_class,
                                     const gchar* target,
                                     const gchar* target_member,
                                     const gchar* statements_source)
{
	gchar* class_name = NULL;
	const gchar* _tmp0_;
	const gchar* _tmp1_;
	gchar* _tmp2_;
	gchar* temp_source = NULL;
	gchar* _tmp3_;
	ValaNamespace* temp_ns = NULL;
	ValaSourceReference* _tmp4_;
	ValaSourceReference* _tmp5_;
	ValaSourceFile* _tmp6_;
	ValaSourceFile* _tmp7_;
	const gchar* _tmp8_;
	const gchar* _tmp9_;
	gchar* _tmp10_;
	gchar* _tmp11_;
	gchar* _tmp12_;
	gchar* _tmp13_;
	gchar* _tmp14_;
	gchar* _tmp15_;
	gchar* _tmp16_;
	gchar* _tmp17_;
	gchar* _tmp18_;
	gchar* _tmp19_;
	ValaNamespace* _tmp20_;
	ValaNamespace* _tmp21_;
	gboolean _tmp22_ = FALSE;
	gboolean _tmp23_ = FALSE;
	ValaNamespace* _tmp24_;
	ValaBlock* result;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (markup_class != NULL, NULL);
	g_return_val_if_fail (target != NULL, NULL);
	g_return_val_if_fail (target_member != NULL, NULL);
	g_return_val_if_fail (statements_source != NULL, NULL);
	_tmp0_ = vala_symbol_get_name ((ValaSymbol*) markup_class);
	_tmp1_ = _tmp0_;
	_tmp2_ = g_strdup (_tmp1_);
	class_name = _tmp2_;
	_tmp3_ = g_strdup_printf ("VoidFunc voidFunc = ()=> {%s;};", statements_source);
	temp_source = _tmp3_;
	_tmp4_ = vala_code_node_get_source_reference ((ValaCodeNode*) markup_class);
	_tmp5_ = _tmp4_;
	_tmp6_ = vala_source_reference_get_file (_tmp5_);
	_tmp7_ = _tmp6_;
	_tmp8_ = temp_source;
	_tmp9_ = class_name;
	_tmp10_ = g_strconcat (_tmp9_, "_", NULL);
	_tmp11_ = _tmp10_;
	_tmp12_ = g_strconcat (_tmp11_, target, NULL);
	_tmp13_ = _tmp12_;
	_tmp14_ = g_strconcat (_tmp13_, "_", NULL);
	_tmp15_ = _tmp14_;
	_tmp16_ = g_strconcat (_tmp15_, target_member, NULL);
	_tmp17_ = _tmp16_;
	_tmp18_ = g_strconcat (_tmp17_, "_expression", NULL);
	_tmp19_ = _tmp18_;
	_tmp20_ = gtkaml_vala_parser_parse (self, _tmp7_, _tmp8_, _tmp19_);
	_tmp21_ = _tmp20_;
	_g_free0 (_tmp19_);
	_g_free0 (_tmp17_);
	_g_free0 (_tmp15_);
	_g_free0 (_tmp13_);
	_g_free0 (_tmp11_);
	temp_ns = _tmp21_;
	_tmp24_ = temp_ns;
	if (G_TYPE_CHECK_INSTANCE_TYPE (_tmp24_, VALA_TYPE_NAMESPACE)) {
		ValaNamespace* _tmp25_;
		ValaList* _tmp26_;
		gint _tmp27_;
		gint _tmp28_;
		_tmp25_ = temp_ns;
		_tmp26_ = vala_namespace_get_fields (_tmp25_);
		_tmp27_ = vala_collection_get_size ((ValaCollection*) _tmp26_);
		_tmp28_ = _tmp27_;
		_tmp23_ = _tmp28_ == 1;
	} else {
		_tmp23_ = FALSE;
	}
	if (_tmp23_) {
		ValaNamespace* _tmp29_;
		ValaList* _tmp30_;
		gpointer _tmp31_;
		ValaField* _tmp32_;
		ValaExpression* _tmp33_;
		ValaExpression* _tmp34_;
		_tmp29_ = temp_ns;
		_tmp30_ = vala_namespace_get_fields (_tmp29_);
		_tmp31_ = vala_list_get (_tmp30_, 0);
		_tmp32_ = (ValaField*) _tmp31_;
		_tmp33_ = vala_variable_get_initializer ((ValaVariable*) _tmp32_);
		_tmp34_ = _tmp33_;
		_tmp22_ = G_TYPE_CHECK_INSTANCE_TYPE (_tmp34_, VALA_TYPE_LAMBDA_EXPRESSION);
		_vala_code_node_unref0 (_tmp32_);
	} else {
		_tmp22_ = FALSE;
	}
	if (_tmp22_) {
		ValaLambdaExpression* temp_lambda = NULL;
		ValaNamespace* _tmp35_;
		ValaList* _tmp36_;
		gpointer _tmp37_;
		ValaField* _tmp38_;
		ValaExpression* _tmp39_;
		ValaExpression* _tmp40_;
		ValaLambdaExpression* _tmp41_;
		ValaLambdaExpression* _tmp42_;
		ValaLambdaExpression* _tmp43_;
		ValaBlock* _tmp44_;
		ValaBlock* _tmp45_;
		ValaBlock* _tmp46_;
		_tmp35_ = temp_ns;
		_tmp36_ = vala_namespace_get_fields (_tmp35_);
		_tmp37_ = vala_list_get (_tmp36_, 0);
		_tmp38_ = (ValaField*) _tmp37_;
		_tmp39_ = vala_variable_get_initializer ((ValaVariable*) _tmp38_);
		_tmp40_ = _tmp39_;
		_tmp41_ = _vala_code_node_ref0 (G_TYPE_CHECK_INSTANCE_CAST (_tmp40_, VALA_TYPE_LAMBDA_EXPRESSION, ValaLambdaExpression));
		_tmp42_ = _tmp41_;
		_vala_code_node_unref0 (_tmp38_);
		temp_lambda = _tmp42_;
		_tmp43_ = temp_lambda;
		_tmp44_ = vala_lambda_expression_get_statement_body (_tmp43_);
		_tmp45_ = _tmp44_;
		_tmp46_ = _vala_code_node_ref0 (_tmp45_);
		result = _tmp46_;
		_vala_code_node_unref0 (temp_lambda);
		_vala_code_node_unref0 (temp_ns);
		_g_free0 (temp_source);
		_g_free0 (class_name);
		return result;
	} else {
		ValaSourceReference* _tmp47_;
		ValaSourceReference* _tmp48_;
		_tmp47_ = vala_code_node_get_source_reference ((ValaCodeNode*) markup_class);
		_tmp48_ = _tmp47_;
		vala_report_error (_tmp48_, "There was an error parsing the code section: statements");
		result = NULL;
		_vala_code_node_unref0 (temp_ns);
		_g_free0 (temp_source);
		_g_free0 (class_name);
		return result;
	}
}

/**
 * parses the getter/setter declaration
 * TODO use Vala.Parser.parse_property_declaration in the future
 * TODO this is not used, as we don't seem to need body on getters and setters, a simple 
 * MarkupParser.parse_markup_subtag_propertyspec is used now
 */
ValaProperty*
gtkaml_vala_parser_parse_property_declaration (GtkamlValaParser* self,
                                               GtkamlMarkupClass* markup_class,
                                               const gchar* target,
                                               const gchar* target_member,
                                               const gchar* declaration)
{
	gchar* class_name = NULL;
	const gchar* _tmp0_;
	const gchar* _tmp1_;
	gchar* _tmp2_;
	gchar* temp_source = NULL;
	const gchar* _tmp3_;
	gchar* _tmp4_;
	ValaNamespace* temp_ns = NULL;
	ValaSourceReference* _tmp5_;
	ValaSourceReference* _tmp6_;
	ValaSourceFile* _tmp7_;
	ValaSourceFile* _tmp8_;
	const gchar* _tmp9_;
	const gchar* _tmp10_;
	gchar* _tmp11_;
	gchar* _tmp12_;
	ValaNamespace* _tmp13_;
	ValaNamespace* _tmp14_;
	gboolean _tmp22_ = FALSE;
	gboolean _tmp23_ = FALSE;
	ValaNamespace* _tmp24_;
	ValaProperty* result;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (markup_class != NULL, NULL);
	g_return_val_if_fail (target != NULL, NULL);
	g_return_val_if_fail (target_member != NULL, NULL);
	g_return_val_if_fail (declaration != NULL, NULL);
	_tmp0_ = vala_symbol_get_name ((ValaSymbol*) markup_class);
	_tmp1_ = _tmp0_;
	_tmp2_ = g_strdup (_tmp1_);
	class_name = _tmp2_;
	_tmp3_ = class_name;
	_tmp4_ = g_strdup_printf ("public class %s { %s { %s }}", _tmp3_, target_member, declaration);
	temp_source = _tmp4_;
	_tmp5_ = vala_code_node_get_source_reference ((ValaCodeNode*) markup_class);
	_tmp6_ = _tmp5_;
	_tmp7_ = vala_source_reference_get_file (_tmp6_);
	_tmp8_ = _tmp7_;
	_tmp9_ = temp_source;
	_tmp10_ = class_name;
	_tmp11_ = g_strconcat (_tmp10_, "-members", NULL);
	_tmp12_ = _tmp11_;
	_tmp13_ = gtkaml_vala_parser_parse (self, _tmp8_, _tmp9_, _tmp12_);
	_tmp14_ = _tmp13_;
	_g_free0 (_tmp12_);
	temp_ns = _tmp14_;
	while (TRUE) {
		ValaNamespace* _tmp15_;
		ValaList* _tmp16_;
		gint _tmp17_;
		gint _tmp18_;
		ValaNamespace* _tmp19_;
		ValaList* _tmp20_;
		gpointer _tmp21_;
		_tmp15_ = temp_ns;
		_tmp16_ = vala_namespace_get_namespaces (_tmp15_);
		_tmp17_ = vala_collection_get_size ((ValaCollection*) _tmp16_);
		_tmp18_ = _tmp17_;
		if (!(_tmp18_ > 0)) {
			break;
		}
		_tmp19_ = temp_ns;
		_tmp20_ = vala_namespace_get_namespaces (_tmp19_);
		_tmp21_ = vala_list_get (_tmp20_, 0);
		_vala_code_node_unref0 (temp_ns);
		temp_ns = (ValaNamespace*) _tmp21_;
	}
	_tmp24_ = temp_ns;
	if (G_TYPE_CHECK_INSTANCE_TYPE (_tmp24_, VALA_TYPE_NAMESPACE)) {
		ValaNamespace* _tmp25_;
		ValaList* _tmp26_;
		gint _tmp27_;
		gint _tmp28_;
		_tmp25_ = temp_ns;
		_tmp26_ = vala_namespace_get_classes (_tmp25_);
		_tmp27_ = vala_collection_get_size ((ValaCollection*) _tmp26_);
		_tmp28_ = _tmp27_;
		_tmp23_ = _tmp28_ == 1;
	} else {
		_tmp23_ = FALSE;
	}
	if (_tmp23_) {
		ValaNamespace* _tmp29_;
		ValaList* _tmp30_;
		gpointer _tmp31_;
		ValaClass* _tmp32_;
		ValaList* _tmp33_;
		gint _tmp34_;
		gint _tmp35_;
		_tmp29_ = temp_ns;
		_tmp30_ = vala_namespace_get_classes (_tmp29_);
		_tmp31_ = vala_list_get (_tmp30_, 0);
		_tmp32_ = (ValaClass*) _tmp31_;
		_tmp33_ = vala_object_type_symbol_get_properties ((ValaObjectTypeSymbol*) _tmp32_);
		_tmp34_ = vala_collection_get_size ((ValaCollection*) _tmp33_);
		_tmp35_ = _tmp34_;
		_tmp22_ = _tmp35_ == 1;
		_vala_code_node_unref0 (_tmp32_);
	} else {
		_tmp22_ = FALSE;
	}
	if (_tmp22_) {
		ValaNamespace* _tmp36_;
		ValaList* _tmp37_;
		gpointer _tmp38_;
		ValaClass* _tmp39_;
		ValaList* _tmp40_;
		gpointer _tmp41_;
		ValaProperty* _tmp42_;
		_tmp36_ = temp_ns;
		_tmp37_ = vala_namespace_get_classes (_tmp36_);
		_tmp38_ = vala_list_get (_tmp37_, 0);
		_tmp39_ = (ValaClass*) _tmp38_;
		_tmp40_ = vala_object_type_symbol_get_properties ((ValaObjectTypeSymbol*) _tmp39_);
		_tmp41_ = vala_list_get (_tmp40_, 0);
		_tmp42_ = (ValaProperty*) _tmp41_;
		_vala_code_node_unref0 (_tmp39_);
		result = _tmp42_;
		_vala_code_node_unref0 (temp_ns);
		_g_free0 (temp_source);
		_g_free0 (class_name);
		return result;
	} else {
		ValaSourceReference* _tmp43_;
		ValaSourceReference* _tmp44_;
		_tmp43_ = vala_code_node_get_source_reference ((ValaCodeNode*) markup_class);
		_tmp44_ = _tmp43_;
		vala_report_error (_tmp44_, "There was an error parsing the code section: property declaration");
		result = NULL;
		_vala_code_node_unref0 (temp_ns);
		_g_free0 (temp_source);
		_g_free0 (class_name);
		return result;
	}
}

/**
 * Makes a copy of the real context for Vala parser's use
 * 
 */
GtkamlCodeContext*
gtkaml_vala_parser_copy_context (GtkamlValaParser* self,
                                 GtkamlCodeContext* source)
{
	GtkamlCodeContext* ctx = NULL;
	GtkamlCodeContext* _tmp0_;
	GtkamlCodeContext* result;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (source != NULL, NULL);
	_tmp0_ = gtkaml_code_context_new ();
	ctx = _tmp0_;
	{
		ValaIterator* _define_it = NULL;
		ValaSet* _tmp1_;
		ValaIterator* _tmp2_;
		_tmp1_ = source->defines;
		_tmp2_ = vala_iterable_iterator ((ValaIterable*) _tmp1_);
		_define_it = _tmp2_;
		while (TRUE) {
			ValaIterator* _tmp3_;
			gchar* define = NULL;
			ValaIterator* _tmp4_;
			gpointer _tmp5_;
			GtkamlCodeContext* _tmp6_;
			const gchar* _tmp7_;
			_tmp3_ = _define_it;
			if (!vala_iterator_next (_tmp3_)) {
				break;
			}
			_tmp4_ = _define_it;
			_tmp5_ = vala_iterator_get (_tmp4_);
			define = (gchar*) _tmp5_;
			_tmp6_ = ctx;
			_tmp7_ = define;
			gtkaml_code_context_add_define (_tmp6_, _tmp7_);
			_g_free0 (define);
		}
		_vala_iterator_unref0 (_define_it);
	}
	result = ctx;
	return result;
}

/**
 * parses a vala source string temporary stored in .gtkaml/what.vala
 * returns the root namespace
 */
static ValaNamespace*
gtkaml_vala_parser_parse (GtkamlValaParser* self,
                          ValaSourceFile* original_source,
                          const gchar* source,
                          const gchar* temp_filename)
{
	GtkamlCodeContext* ctx = NULL;
	GtkamlCodeContext* _tmp0_;
	GtkamlCodeContext* _tmp1_;
	gchar* filename = NULL;
	GtkamlCodeContext* _tmp2_;
	const gchar* _tmp3_;
	const gchar* _tmp4_;
	gchar* _tmp5_;
	gchar* _tmp6_;
	gchar* _tmp7_;
	gchar* _tmp8_;
	gchar* _tmp9_;
	gchar* _tmp10_;
	GError* _inner_error0_ = NULL;
	ValaNamespace* result;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (original_source != NULL, NULL);
	g_return_val_if_fail (source != NULL, NULL);
	g_return_val_if_fail (temp_filename != NULL, NULL);
	_tmp0_ = self->real_context;
	_tmp1_ = gtkaml_vala_parser_copy_context (self, _tmp0_);
	ctx = _tmp1_;
	_tmp2_ = self->real_context;
	_tmp3_ = vala_code_context_get_directory ((ValaCodeContext*) _tmp2_);
	_tmp4_ = _tmp3_;
	_tmp5_ = g_strconcat (_tmp4_, "/.gtkaml/", NULL);
	_tmp6_ = _tmp5_;
	_tmp7_ = g_strconcat (_tmp6_, temp_filename, NULL);
	_tmp8_ = _tmp7_;
	_tmp9_ = g_strconcat (_tmp8_, ".vala", NULL);
	_tmp10_ = _tmp9_;
	_g_free0 (_tmp8_);
	_g_free0 (_tmp6_);
	filename = _tmp10_;
	{
		GtkamlCodeContext* _tmp11_;
		const gchar* _tmp12_;
		const gchar* _tmp13_;
		gchar* _tmp14_;
		gchar* _tmp15_;
		const gchar* _tmp16_;
		ValaSourceFile* temp_source_file = NULL;
		GtkamlCodeContext* _tmp17_;
		const gchar* _tmp18_;
		ValaSourceFile* _tmp19_;
		ValaList* _tmp31_;
		ValaSourceFile* _tmp32_;
		GtkamlCodeContext* _tmp33_;
		ValaSourceFile* _tmp34_;
		ValaParser* parser = NULL;
		ValaParser* _tmp35_;
		ValaParser* _tmp36_;
		GtkamlCodeContext* _tmp37_;
		GtkamlCodeContext* _tmp38_;
		ValaNamespace* _tmp39_;
		ValaNamespace* _tmp40_;
		ValaNamespace* _tmp41_;
		_tmp11_ = self->real_context;
		_tmp12_ = vala_code_context_get_directory ((ValaCodeContext*) _tmp11_);
		_tmp13_ = _tmp12_;
		_tmp14_ = g_strconcat (_tmp13_, "/.gtkaml", NULL);
		_tmp15_ = _tmp14_;
		g_mkdir_with_parents (_tmp15_, 488);
		_g_free0 (_tmp15_);
		_tmp16_ = filename;
		g_file_set_contents (_tmp16_, source, (gssize) -1, &_inner_error0_);
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
			goto __catch0_g_error;
		}
		_tmp17_ = ctx;
		_tmp18_ = filename;
		_tmp19_ = vala_source_file_new ((ValaCodeContext*) _tmp17_, VALA_SOURCE_FILE_TYPE_SOURCE, _tmp18_, source, FALSE);
		temp_source_file = _tmp19_;
		{
			ValaList* _using_directive_list = NULL;
			ValaList* _tmp20_;
			ValaList* _tmp21_;
			gint _using_directive_size = 0;
			ValaList* _tmp22_;
			gint _tmp23_;
			gint _tmp24_;
			gint _using_directive_index = 0;
			_tmp20_ = vala_source_file_get_current_using_directives (original_source);
			_tmp21_ = _tmp20_;
			_using_directive_list = _tmp21_;
			_tmp22_ = _using_directive_list;
			_tmp23_ = vala_collection_get_size ((ValaCollection*) _tmp22_);
			_tmp24_ = _tmp23_;
			_using_directive_size = _tmp24_;
			_using_directive_index = -1;
			while (TRUE) {
				gint _tmp25_;
				gint _tmp26_;
				ValaUsingDirective* using_directive = NULL;
				ValaList* _tmp27_;
				gpointer _tmp28_;
				ValaSourceFile* _tmp29_;
				ValaUsingDirective* _tmp30_;
				_using_directive_index = _using_directive_index + 1;
				_tmp25_ = _using_directive_index;
				_tmp26_ = _using_directive_size;
				if (!(_tmp25_ < _tmp26_)) {
					break;
				}
				_tmp27_ = _using_directive_list;
				_tmp28_ = vala_list_get (_tmp27_, _using_directive_index);
				using_directive = (ValaUsingDirective*) _tmp28_;
				_tmp29_ = temp_source_file;
				_tmp30_ = using_directive;
				vala_source_file_add_using_directive (_tmp29_, _tmp30_);
				_vala_code_node_unref0 (using_directive);
			}
		}
		_tmp31_ = self->temp_source_files;
		_tmp32_ = temp_source_file;
		vala_collection_add ((ValaCollection*) _tmp31_, _tmp32_);
		_tmp33_ = ctx;
		_tmp34_ = temp_source_file;
		vala_code_context_add_source_file ((ValaCodeContext*) _tmp33_, _tmp34_);
		_tmp35_ = vala_parser_new ();
		parser = _tmp35_;
		_tmp36_ = parser;
		_tmp37_ = ctx;
		vala_parser_parse (_tmp36_, (ValaCodeContext*) _tmp37_);
		_tmp38_ = ctx;
		_tmp39_ = vala_code_context_get_root ((ValaCodeContext*) _tmp38_);
		_tmp40_ = _tmp39_;
		_tmp41_ = _vala_code_node_ref0 (_tmp40_);
		result = _tmp41_;
		_vala_code_visitor_unref0 (parser);
		_vala_source_file_unref0 (temp_source_file);
		_g_free0 (filename);
		_vala_code_context_unref0 (ctx);
		return result;
	}
	goto __finally0;
	__catch0_g_error:
	{
		const gchar* _tmp42_;
		gchar* _tmp43_;
		gchar* _tmp44_;
		g_clear_error (&_inner_error0_);
		_tmp42_ = filename;
		_tmp43_ = g_strdup_printf ("There was an error writing temporary '%s'", _tmp42_);
		_tmp44_ = _tmp43_;
		vala_report_error (NULL, "%s", _tmp44_);
		_g_free0 (_tmp44_);
		result = NULL;
		_g_free0 (filename);
		_vala_code_context_unref0 (ctx);
		return result;
	}
	__finally0:
	_g_free0 (filename);
	_vala_code_context_unref0 (ctx);
	g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
	g_clear_error (&_inner_error0_);
	return NULL;
}

static void
gtkaml_value_vala_parser_init (GValue* value)
{
	value->data[0].v_pointer = NULL;
}

static void
gtkaml_value_vala_parser_free_value (GValue* value)
{
	if (value->data[0].v_pointer) {
		gtkaml_vala_parser_unref (value->data[0].v_pointer);
	}
}

static void
gtkaml_value_vala_parser_copy_value (const GValue* src_value,
                                     GValue* dest_value)
{
	if (src_value->data[0].v_pointer) {
		dest_value->data[0].v_pointer = gtkaml_vala_parser_ref (src_value->data[0].v_pointer);
	} else {
		dest_value->data[0].v_pointer = NULL;
	}
}

static gpointer
gtkaml_value_vala_parser_peek_pointer (const GValue* value)
{
	return value->data[0].v_pointer;
}

static gchar*
gtkaml_value_vala_parser_collect_value (GValue* value,
                                        guint n_collect_values,
                                        GTypeCValue* collect_values,
                                        guint collect_flags)
{
	if (collect_values[0].v_pointer) {
		GtkamlValaParser * object;
		object = collect_values[0].v_pointer;
		if (object->parent_instance.g_class == NULL) {
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		}
		value->data[0].v_pointer = gtkaml_vala_parser_ref (object);
	} else {
		value->data[0].v_pointer = NULL;
	}
	return NULL;
}

static gchar*
gtkaml_value_vala_parser_lcopy_value (const GValue* value,
                                      guint n_collect_values,
                                      GTypeCValue* collect_values,
                                      guint collect_flags)
{
	GtkamlValaParser ** object_p;
	object_p = collect_values[0].v_pointer;
	if (!object_p) {
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
	}
	if (!value->data[0].v_pointer) {
		*object_p = NULL;
	} else if (collect_flags & G_VALUE_NOCOPY_CONTENTS) {
		*object_p = value->data[0].v_pointer;
	} else {
		*object_p = gtkaml_vala_parser_ref (value->data[0].v_pointer);
	}
	return NULL;
}

GParamSpec*
gtkaml_param_spec_vala_parser (const gchar* name,
                               const gchar* nick,
                               const gchar* blurb,
                               GType object_type,
                               GParamFlags flags)
{
	GtkamlParamSpecValaParser* spec;
	g_return_val_if_fail (g_type_is_a (object_type, GTKAML_TYPE_VALA_PARSER), NULL);
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
	G_PARAM_SPEC (spec)->value_type = object_type;
	return G_PARAM_SPEC (spec);
}

gpointer
gtkaml_value_get_vala_parser (const GValue* value)
{
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, GTKAML_TYPE_VALA_PARSER), NULL);
	return value->data[0].v_pointer;
}

void
gtkaml_value_set_vala_parser (GValue* value,
                              gpointer v_object)
{
	GtkamlValaParser * old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, GTKAML_TYPE_VALA_PARSER));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, GTKAML_TYPE_VALA_PARSER));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
		gtkaml_vala_parser_ref (value->data[0].v_pointer);
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		gtkaml_vala_parser_unref (old);
	}
}

void
gtkaml_value_take_vala_parser (GValue* value,
                               gpointer v_object)
{
	GtkamlValaParser * old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, GTKAML_TYPE_VALA_PARSER));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, GTKAML_TYPE_VALA_PARSER));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		gtkaml_vala_parser_unref (old);
	}
}

static void
gtkaml_vala_parser_class_init (GtkamlValaParserClass * klass,
                               gpointer klass_data)
{
	gtkaml_vala_parser_parent_class = g_type_class_peek_parent (klass);
	((GtkamlValaParserClass *) klass)->finalize = gtkaml_vala_parser_finalize;
}

static void
gtkaml_vala_parser_instance_init (GtkamlValaParser * self,
                                  gpointer klass)
{
	GEqualFunc _tmp0_;
	ValaArrayList* _tmp1_;
	_tmp0_ = g_direct_equal;
	_tmp1_ = vala_array_list_new (VALA_TYPE_SOURCE_FILE, (GBoxedCopyFunc) vala_source_file_ref, (GDestroyNotify) vala_source_file_unref, _tmp0_);
	self->temp_source_files = (ValaList*) _tmp1_;
	self->ref_count = 1;
}

static void
gtkaml_vala_parser_finalize (GtkamlValaParser * obj)
{
	GtkamlValaParser * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, GTKAML_TYPE_VALA_PARSER, GtkamlValaParser);
	g_signal_handlers_destroy (self);
	_vala_code_context_unref0 (self->real_context);
	_vala_iterable_unref0 (self->temp_source_files);
}

/**
 * Vala.Parser wrapper.
 * Parses different kinds of code islands: class members, expressions as values of properties, statements as values of signals
 */
static GType
gtkaml_vala_parser_get_type_once (void)
{
	static const GTypeValueTable g_define_type_value_table = { gtkaml_value_vala_parser_init, gtkaml_value_vala_parser_free_value, gtkaml_value_vala_parser_copy_value, gtkaml_value_vala_parser_peek_pointer, "p", gtkaml_value_vala_parser_collect_value, "p", gtkaml_value_vala_parser_lcopy_value };
	static const GTypeInfo g_define_type_info = { sizeof (GtkamlValaParserClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) gtkaml_vala_parser_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (GtkamlValaParser), 0, (GInstanceInitFunc) gtkaml_vala_parser_instance_init, &g_define_type_value_table };
	static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
	GType gtkaml_vala_parser_type_id;
	gtkaml_vala_parser_type_id = g_type_register_fundamental (g_type_fundamental_next (), "GtkamlValaParser", &g_define_type_info, &g_define_type_fundamental_info, 0);
	return gtkaml_vala_parser_type_id;
}

GType
gtkaml_vala_parser_get_type (void)
{
	static volatile gsize gtkaml_vala_parser_type_id__once = 0;
	if (g_once_init_enter (&gtkaml_vala_parser_type_id__once)) {
		GType gtkaml_vala_parser_type_id;
		gtkaml_vala_parser_type_id = gtkaml_vala_parser_get_type_once ();
		g_once_init_leave (&gtkaml_vala_parser_type_id__once, gtkaml_vala_parser_type_id);
	}
	return gtkaml_vala_parser_type_id__once;
}

gpointer
gtkaml_vala_parser_ref (gpointer instance)
{
	GtkamlValaParser * self;
	self = instance;
	g_atomic_int_inc (&self->ref_count);
	return instance;
}

void
gtkaml_vala_parser_unref (gpointer instance)
{
	GtkamlValaParser * self;
	self = instance;
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
		GTKAML_VALA_PARSER_GET_CLASS (self)->finalize (self);
		g_type_free_instance ((GTypeInstance *) self);
	}
}

