/* gtkamlcallable.c generated by valac 0.56.16, the Vala compiler
 * generated from gtkamlcallable.vala, do not modify */

/* gtkamlcallable.vala
 *
 * Copyright (C) 2011 Vlad Grecescu
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public
 * License along with main.c; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor Boston, MA 02110-1301,  USA
 *
 * Author:
 *        Vlad Grecescu (b100dian@gmail.com)
 */

#include "gtkaml.h"
#include <vala.h>
#include <glib-object.h>
#include <glib.h>
#include <valagee.h>
#include <stdlib.h>
#include <string.h>
#include <gobject/gvaluecollector.h>

#if !defined(VALA_STRICT_C)
#if !defined(__clang__) && defined(__GNUC__) && (__GNUC__ >= 14)
#pragma GCC diagnostic warning "-Wincompatible-pointer-types"
#elif defined(__clang__) && (__clang_major__ >= 16)
#pragma clang diagnostic ignored "-Wincompatible-function-pointer-types"
#pragma clang diagnostic ignored "-Wincompatible-pointer-types"
#endif
#endif

#define _vala_code_node_unref0(var) ((var == NULL) ? NULL : (var = (vala_code_node_unref (var), NULL)))
typedef struct _GtkamlParamSpecCallable GtkamlParamSpecCallable;
#define _vala_assert(expr, msg) if G_LIKELY (expr) ; else g_assertion_message_expr (G_LOG_DOMAIN, __FILE__, __LINE__, G_STRFUNC, msg);
#define _vala_return_if_fail(expr, msg) if G_LIKELY (expr) ; else { g_return_if_fail_warning (G_LOG_DOMAIN, G_STRFUNC, msg); return; }
#define _vala_return_val_if_fail(expr, msg, val) if G_LIKELY (expr) ; else { g_return_if_fail_warning (G_LOG_DOMAIN, G_STRFUNC, msg); return val; }
#define _vala_warn_if_fail(expr, msg) if G_LIKELY (expr) ; else g_warn_message (G_LOG_DOMAIN, __FILE__, __LINE__, G_STRFUNC, msg);

struct _GtkamlCallablePrivate {
	ValaSymbol* _member;
};

struct _GtkamlParamSpecCallable {
	GParamSpec parent_instance;
};

static gint GtkamlCallable_private_offset;
static gpointer gtkaml_callable_parent_class = NULL;

static void gtkaml_callable_set_member (GtkamlCallable* self,
                                 ValaSymbol* value);
static void gtkaml_callable_finalize (GtkamlCallable * obj);
static GType gtkaml_callable_get_type_once (void);

static inline gpointer
gtkaml_callable_get_instance_private (GtkamlCallable* self)
{
	return G_STRUCT_MEMBER_P (self, GtkamlCallable_private_offset);
}

GtkamlCallable*
gtkaml_callable_construct (GType object_type,
                           ValaSymbol* member)
{
	GtkamlCallable* self = NULL;
	gboolean _tmp0_ = FALSE;
	g_return_val_if_fail (member != NULL, NULL);
	self = (GtkamlCallable*) g_type_create_instance (object_type);
	if (G_TYPE_CHECK_INSTANCE_TYPE (member, VALA_TYPE_SIGNAL)) {
		_tmp0_ = TRUE;
	} else {
		_tmp0_ = G_TYPE_CHECK_INSTANCE_TYPE (member, VALA_TYPE_METHOD);
	}
	_vala_assert (_tmp0_, "member is Vala.Signal || member is Method");
	gtkaml_callable_set_member (self, member);
	return self;
}

GtkamlCallable*
gtkaml_callable_new (ValaSymbol* member)
{
	return gtkaml_callable_construct (GTKAML_TYPE_CALLABLE, member);
}

static gpointer
_vala_iterable_ref0 (gpointer self)
{
	return self ? vala_iterable_ref (self) : NULL;
}

ValaList*
gtkaml_callable_get_parameters (GtkamlCallable* self)
{
	ValaSymbol* _tmp0_;
	ValaSymbol* _tmp4_;
	ValaList* _tmp5_;
	ValaList* _tmp6_;
	ValaList* result;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_member;
	if (G_TYPE_CHECK_INSTANCE_TYPE (_tmp0_, VALA_TYPE_METHOD)) {
		ValaSymbol* _tmp1_;
		ValaList* _tmp2_;
		ValaList* _tmp3_;
		_tmp1_ = self->priv->_member;
		_tmp2_ = vala_callable_get_parameters ((ValaCallable*) G_TYPE_CHECK_INSTANCE_CAST (_tmp1_, VALA_TYPE_METHOD, ValaMethod));
		_tmp3_ = _vala_iterable_ref0 (_tmp2_);
		result = _tmp3_;
		return result;
	}
	_tmp4_ = self->priv->_member;
	_tmp5_ = vala_callable_get_parameters ((ValaCallable*) G_TYPE_CHECK_INSTANCE_CAST (_tmp4_, VALA_TYPE_SIGNAL, ValaSignal));
	_tmp6_ = _vala_iterable_ref0 (_tmp5_);
	result = _tmp6_;
	return result;
}

ValaSymbol*
gtkaml_callable_get_member (GtkamlCallable* self)
{
	ValaSymbol* result;
	ValaSymbol* _tmp0_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_member;
	result = _tmp0_;
	return result;
}

static gpointer
_vala_code_node_ref0 (gpointer self)
{
	return self ? vala_code_node_ref (self) : NULL;
}

static void
gtkaml_callable_set_member (GtkamlCallable* self,
                            ValaSymbol* value)
{
	ValaSymbol* _tmp0_;
	g_return_if_fail (self != NULL);
	_tmp0_ = _vala_code_node_ref0 (value);
	_vala_code_node_unref0 (self->priv->_member);
	self->priv->_member = _tmp0_;
}

const gchar*
gtkaml_callable_get_name (GtkamlCallable* self)
{
	const gchar* result;
	ValaSymbol* _tmp0_;
	const gchar* _tmp1_;
	const gchar* _tmp2_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_member;
	_tmp1_ = vala_symbol_get_name (_tmp0_);
	_tmp2_ = _tmp1_;
	result = _tmp2_;
	return result;
}

ValaSymbol*
gtkaml_callable_get_parent_symbol (GtkamlCallable* self)
{
	ValaSymbol* result;
	ValaSymbol* _tmp0_;
	ValaSymbol* _tmp1_;
	ValaSymbol* _tmp2_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_member;
	_tmp1_ = vala_symbol_get_parent_symbol (_tmp0_);
	_tmp2_ = _tmp1_;
	result = _tmp2_;
	return result;
}

static void
gtkaml_value_callable_init (GValue* value)
{
	value->data[0].v_pointer = NULL;
}

static void
gtkaml_value_callable_free_value (GValue* value)
{
	if (value->data[0].v_pointer) {
		gtkaml_callable_unref (value->data[0].v_pointer);
	}
}

static void
gtkaml_value_callable_copy_value (const GValue* src_value,
                                  GValue* dest_value)
{
	if (src_value->data[0].v_pointer) {
		dest_value->data[0].v_pointer = gtkaml_callable_ref (src_value->data[0].v_pointer);
	} else {
		dest_value->data[0].v_pointer = NULL;
	}
}

static gpointer
gtkaml_value_callable_peek_pointer (const GValue* value)
{
	return value->data[0].v_pointer;
}

static gchar*
gtkaml_value_callable_collect_value (GValue* value,
                                     guint n_collect_values,
                                     GTypeCValue* collect_values,
                                     guint collect_flags)
{
	if (collect_values[0].v_pointer) {
		GtkamlCallable * object;
		object = collect_values[0].v_pointer;
		if (object->parent_instance.g_class == NULL) {
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		}
		value->data[0].v_pointer = gtkaml_callable_ref (object);
	} else {
		value->data[0].v_pointer = NULL;
	}
	return NULL;
}

static gchar*
gtkaml_value_callable_lcopy_value (const GValue* value,
                                   guint n_collect_values,
                                   GTypeCValue* collect_values,
                                   guint collect_flags)
{
	GtkamlCallable ** object_p;
	object_p = collect_values[0].v_pointer;
	if (!object_p) {
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
	}
	if (!value->data[0].v_pointer) {
		*object_p = NULL;
	} else if (collect_flags & G_VALUE_NOCOPY_CONTENTS) {
		*object_p = value->data[0].v_pointer;
	} else {
		*object_p = gtkaml_callable_ref (value->data[0].v_pointer);
	}
	return NULL;
}

GParamSpec*
gtkaml_param_spec_callable (const gchar* name,
                            const gchar* nick,
                            const gchar* blurb,
                            GType object_type,
                            GParamFlags flags)
{
	GtkamlParamSpecCallable* spec;
	g_return_val_if_fail (g_type_is_a (object_type, GTKAML_TYPE_CALLABLE), NULL);
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
	G_PARAM_SPEC (spec)->value_type = object_type;
	return G_PARAM_SPEC (spec);
}

gpointer
gtkaml_value_get_callable (const GValue* value)
{
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, GTKAML_TYPE_CALLABLE), NULL);
	return value->data[0].v_pointer;
}

void
gtkaml_value_set_callable (GValue* value,
                           gpointer v_object)
{
	GtkamlCallable * old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, GTKAML_TYPE_CALLABLE));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, GTKAML_TYPE_CALLABLE));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
		gtkaml_callable_ref (value->data[0].v_pointer);
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		gtkaml_callable_unref (old);
	}
}

void
gtkaml_value_take_callable (GValue* value,
                            gpointer v_object)
{
	GtkamlCallable * old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, GTKAML_TYPE_CALLABLE));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, GTKAML_TYPE_CALLABLE));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		gtkaml_callable_unref (old);
	}
}

static void
gtkaml_callable_class_init (GtkamlCallableClass * klass,
                            gpointer klass_data)
{
	gtkaml_callable_parent_class = g_type_class_peek_parent (klass);
	((GtkamlCallableClass *) klass)->finalize = gtkaml_callable_finalize;
	g_type_class_adjust_private_offset (klass, &GtkamlCallable_private_offset);
}

static void
gtkaml_callable_instance_init (GtkamlCallable * self,
                               gpointer klass)
{
	self->priv = gtkaml_callable_get_instance_private (self);
	self->ref_count = 1;
}

static void
gtkaml_callable_finalize (GtkamlCallable * obj)
{
	GtkamlCallable * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, GTKAML_TYPE_CALLABLE, GtkamlCallable);
	g_signal_handlers_destroy (self);
	_vala_code_node_unref0 (self->priv->_member);
}

/**
 * wrapper for Method and Signal.
 * Supports .name and .get_parameters
 */
static GType
gtkaml_callable_get_type_once (void)
{
	static const GTypeValueTable g_define_type_value_table = { gtkaml_value_callable_init, gtkaml_value_callable_free_value, gtkaml_value_callable_copy_value, gtkaml_value_callable_peek_pointer, "p", gtkaml_value_callable_collect_value, "p", gtkaml_value_callable_lcopy_value };
	static const GTypeInfo g_define_type_info = { sizeof (GtkamlCallableClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) gtkaml_callable_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (GtkamlCallable), 0, (GInstanceInitFunc) gtkaml_callable_instance_init, &g_define_type_value_table };
	static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
	GType gtkaml_callable_type_id;
	gtkaml_callable_type_id = g_type_register_fundamental (g_type_fundamental_next (), "GtkamlCallable", &g_define_type_info, &g_define_type_fundamental_info, 0);
	GtkamlCallable_private_offset = g_type_add_instance_private (gtkaml_callable_type_id, sizeof (GtkamlCallablePrivate));
	return gtkaml_callable_type_id;
}

GType
gtkaml_callable_get_type (void)
{
	static volatile gsize gtkaml_callable_type_id__once = 0;
	if (g_once_init_enter (&gtkaml_callable_type_id__once)) {
		GType gtkaml_callable_type_id;
		gtkaml_callable_type_id = gtkaml_callable_get_type_once ();
		g_once_init_leave (&gtkaml_callable_type_id__once, gtkaml_callable_type_id);
	}
	return gtkaml_callable_type_id__once;
}

gpointer
gtkaml_callable_ref (gpointer instance)
{
	GtkamlCallable * self;
	self = instance;
	g_atomic_int_inc (&self->ref_count);
	return instance;
}

void
gtkaml_callable_unref (gpointer instance)
{
	GtkamlCallable * self;
	self = instance;
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
		GTKAML_CALLABLE_GET_CLASS (self)->finalize (self);
		g_type_free_instance ((GTypeInstance *) self);
	}
}

