/* gtkamlnamespacevisitor.c generated by valac 0.56.16, the Vala compiler
 * generated from gtkamlnamespacevisitor.vala, do not modify */

/* gtkamlnamespacevisitor.vala
 *
 * Copyright (C) 2011 Vlad Grecescu
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public
 * License along with main.c; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor Boston, MA 02110-1301,  USA
 *
 * Author:
 *        Vlad Grecescu (b100dian@gmail.com)
 */

#include <vala.h>
#include <glib-object.h>
#include <valagee.h>
#include <glib.h>
#include "gtkaml.h"

#if !defined(VALA_STRICT_C)
#if !defined(__clang__) && defined(__GNUC__) && (__GNUC__ >= 14)
#pragma GCC diagnostic warning "-Wincompatible-pointer-types"
#elif defined(__clang__) && (__clang_major__ >= 16)
#pragma clang diagnostic ignored "-Wincompatible-function-pointer-types"
#pragma clang diagnostic ignored "-Wincompatible-pointer-types"
#endif
#endif

#define GTKAML_TYPE_NAMESPACE_VISITOR (gtkaml_namespace_visitor_get_type ())
#define GTKAML_NAMESPACE_VISITOR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GTKAML_TYPE_NAMESPACE_VISITOR, GtkamlNamespaceVisitor))
#define GTKAML_NAMESPACE_VISITOR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GTKAML_TYPE_NAMESPACE_VISITOR, GtkamlNamespaceVisitorClass))
#define GTKAML_IS_NAMESPACE_VISITOR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GTKAML_TYPE_NAMESPACE_VISITOR))
#define GTKAML_IS_NAMESPACE_VISITOR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GTKAML_TYPE_NAMESPACE_VISITOR))
#define GTKAML_NAMESPACE_VISITOR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GTKAML_TYPE_NAMESPACE_VISITOR, GtkamlNamespaceVisitorClass))

typedef struct _GtkamlNamespaceVisitor GtkamlNamespaceVisitor;
typedef struct _GtkamlNamespaceVisitorClass GtkamlNamespaceVisitorClass;
typedef struct _GtkamlNamespaceVisitorPrivate GtkamlNamespaceVisitorPrivate;
#define _vala_iterable_unref0(var) ((var == NULL) ? NULL : (var = (vala_iterable_unref (var), NULL)))

struct _GtkamlNamespaceVisitor {
	ValaCodeVisitor parent_instance;
	GtkamlNamespaceVisitorPrivate * priv;
};

struct _GtkamlNamespaceVisitorClass {
	ValaCodeVisitorClass parent_class;
};

struct _GtkamlNamespaceVisitorPrivate {
	ValaList* using_directives;
};

static gint GtkamlNamespaceVisitor_private_offset;
static gpointer gtkaml_namespace_visitor_parent_class = NULL;

VALA_EXTERN GType gtkaml_namespace_visitor_get_type (void) G_GNUC_CONST ;
static void gtkaml_namespace_visitor_real_visit_namespace (ValaCodeVisitor* base,
                                                    ValaNamespace* ns);
static void gtkaml_namespace_visitor_real_visit_using_directive (ValaCodeVisitor* base,
                                                          ValaUsingDirective* ns_ref);
VALA_EXTERN GtkamlNamespaceVisitor* gtkaml_namespace_visitor_new (void);
VALA_EXTERN GtkamlNamespaceVisitor* gtkaml_namespace_visitor_construct (GType object_type);
static void gtkaml_namespace_visitor_finalize (ValaCodeVisitor * obj);
static GType gtkaml_namespace_visitor_get_type_once (void);

static inline gpointer
gtkaml_namespace_visitor_get_instance_private (GtkamlNamespaceVisitor* self)
{
	return G_STRUCT_MEMBER_P (self, GtkamlNamespaceVisitor_private_offset);
}

static void
gtkaml_namespace_visitor_real_visit_namespace (ValaCodeVisitor* base,
                                               ValaNamespace* ns)
{
	GtkamlNamespaceVisitor * self;
	self = (GtkamlNamespaceVisitor*) base;
	g_return_if_fail (ns != NULL);
	vala_code_node_accept_children ((ValaCodeNode*) ns, (ValaCodeVisitor*) self);
}

static void
gtkaml_namespace_visitor_real_visit_using_directive (ValaCodeVisitor* base,
                                                     ValaUsingDirective* ns_ref)
{
	GtkamlNamespaceVisitor * self;
	ValaList* _tmp0_;
	self = (GtkamlNamespaceVisitor*) base;
	g_return_if_fail (ns_ref != NULL);
	_tmp0_ = self->priv->using_directives;
	vala_collection_add ((ValaCollection*) _tmp0_, ns_ref);
}

GtkamlNamespaceVisitor*
gtkaml_namespace_visitor_construct (GType object_type)
{
	GtkamlNamespaceVisitor* self = NULL;
	self = (GtkamlNamespaceVisitor*) vala_code_visitor_construct (object_type);
	return self;
}

GtkamlNamespaceVisitor*
gtkaml_namespace_visitor_new (void)
{
	return gtkaml_namespace_visitor_construct (GTKAML_TYPE_NAMESPACE_VISITOR);
}

static void
gtkaml_namespace_visitor_class_init (GtkamlNamespaceVisitorClass * klass,
                                     gpointer klass_data)
{
	gtkaml_namespace_visitor_parent_class = g_type_class_peek_parent (klass);
	((ValaCodeVisitorClass *) klass)->finalize = gtkaml_namespace_visitor_finalize;
	g_type_class_adjust_private_offset (klass, &GtkamlNamespaceVisitor_private_offset);
	((ValaCodeVisitorClass *) klass)->visit_namespace = (void (*) (ValaCodeVisitor*, ValaNamespace*)) gtkaml_namespace_visitor_real_visit_namespace;
	((ValaCodeVisitorClass *) klass)->visit_using_directive = (void (*) (ValaCodeVisitor*, ValaUsingDirective*)) gtkaml_namespace_visitor_real_visit_using_directive;
}

static void
gtkaml_namespace_visitor_instance_init (GtkamlNamespaceVisitor * self,
                                        gpointer klass)
{
	GEqualFunc _tmp0_;
	ValaArrayList* _tmp1_;
	self->priv = gtkaml_namespace_visitor_get_instance_private (self);
	_tmp0_ = g_direct_equal;
	_tmp1_ = vala_array_list_new (VALA_TYPE_USING_DIRECTIVE, (GBoxedCopyFunc) vala_code_node_ref, (GDestroyNotify) vala_code_node_unref, _tmp0_);
	self->priv->using_directives = (ValaList*) _tmp1_;
}

static void
gtkaml_namespace_visitor_finalize (ValaCodeVisitor * obj)
{
	GtkamlNamespaceVisitor * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, GTKAML_TYPE_NAMESPACE_VISITOR, GtkamlNamespaceVisitor);
	_vala_iterable_unref0 (self->priv->using_directives);
	VALA_CODE_VISITOR_CLASS (gtkaml_namespace_visitor_parent_class)->finalize (obj);
}

static GType
gtkaml_namespace_visitor_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (GtkamlNamespaceVisitorClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) gtkaml_namespace_visitor_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (GtkamlNamespaceVisitor), 0, (GInstanceInitFunc) gtkaml_namespace_visitor_instance_init, NULL };
	GType gtkaml_namespace_visitor_type_id;
	gtkaml_namespace_visitor_type_id = g_type_register_static (VALA_TYPE_CODE_VISITOR, "GtkamlNamespaceVisitor", &g_define_type_info, 0);
	GtkamlNamespaceVisitor_private_offset = g_type_add_instance_private (gtkaml_namespace_visitor_type_id, sizeof (GtkamlNamespaceVisitorPrivate));
	return gtkaml_namespace_visitor_type_id;
}

GType
gtkaml_namespace_visitor_get_type (void)
{
	static volatile gsize gtkaml_namespace_visitor_type_id__once = 0;
	if (g_once_init_enter (&gtkaml_namespace_visitor_type_id__once)) {
		GType gtkaml_namespace_visitor_type_id;
		gtkaml_namespace_visitor_type_id = gtkaml_namespace_visitor_get_type_once ();
		g_once_init_leave (&gtkaml_namespace_visitor_type_id__once, gtkaml_namespace_visitor_type_id);
	}
	return gtkaml_namespace_visitor_type_id__once;
}

