/* gtkamlmarkuptag.c generated by valac 0.56.16, the Vala compiler
 * generated from gtkamlmarkuptag.vala, do not modify */

/* gtkamlmarkuptag.vala
 *
 * Copyright (C) 2011 Vlad Grecescu
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public
 * License along with main.c; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor Boston, MA 02110-1301,  USA
 *
 * Author:
 *        Vlad Grecescu (b100dian@gmail.com)
 */

#include "gtkaml.h"
#include <stdlib.h>
#include <string.h>
#include <glib.h>
#include <vala.h>
#include <glib-object.h>
#include <valagee.h>

#if !defined(VALA_STRICT_C)
#if !defined(__clang__) && defined(__GNUC__) && (__GNUC__ >= 14)
#pragma GCC diagnostic warning "-Wincompatible-pointer-types"
#elif defined(__clang__) && (__clang_major__ >= 16)
#pragma clang diagnostic ignored "-Wincompatible-function-pointer-types"
#pragma clang diagnostic ignored "-Wincompatible-pointer-types"
#endif
#endif

#define GTKAML_TYPE_DATA_TYPE_PARENT (gtkaml_data_type_parent_get_type ())
#define GTKAML_DATA_TYPE_PARENT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GTKAML_TYPE_DATA_TYPE_PARENT, GtkamlDataTypeParent))
#define GTKAML_DATA_TYPE_PARENT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GTKAML_TYPE_DATA_TYPE_PARENT, GtkamlDataTypeParentClass))
#define GTKAML_IS_DATA_TYPE_PARENT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GTKAML_TYPE_DATA_TYPE_PARENT))
#define GTKAML_IS_DATA_TYPE_PARENT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GTKAML_TYPE_DATA_TYPE_PARENT))
#define GTKAML_DATA_TYPE_PARENT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GTKAML_TYPE_DATA_TYPE_PARENT, GtkamlDataTypeParentClass))

typedef struct _GtkamlDataTypeParent GtkamlDataTypeParent;
typedef struct _GtkamlDataTypeParentClass GtkamlDataTypeParentClass;
enum  {
	GTKAML_AST_MARKUP_TAG_0_PROPERTY,
	GTKAML_AST_MARKUP_TAG_TEXT_PROPERTY,
	GTKAML_AST_MARKUP_TAG_TAG_NAME_PROPERTY,
	GTKAML_AST_MARKUP_TAG_TAG_NAMESPACE_PROPERTY,
	GTKAML_AST_MARKUP_TAG_MARKUP_CLASS_PROPERTY,
	GTKAML_AST_MARKUP_TAG_SOURCE_REFERENCE_PROPERTY,
	GTKAML_AST_MARKUP_TAG_ME_PROPERTY,
	GTKAML_AST_MARKUP_TAG_DATA_TYPE_PROPERTY,
	GTKAML_AST_MARKUP_TAG_RESOLVED_TYPE_PROPERTY,
	GTKAML_AST_MARKUP_TAG_IS_RESOLVED_PROPERTY,
	GTKAML_AST_MARKUP_TAG_FULL_NAME_PROPERTY,
	GTKAML_AST_MARKUP_TAG_NUM_PROPERTIES
};
static GParamSpec* gtkaml_ast_markup_tag_properties[GTKAML_AST_MARKUP_TAG_NUM_PROPERTIES];
#define _vala_iterable_unref0(var) ((var == NULL) ? NULL : (var = (vala_iterable_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
#define _vala_code_node_unref0(var) ((var == NULL) ? NULL : (var = (vala_code_node_unref (var), NULL)))
#define _vala_source_reference_unref0(var) ((var == NULL) ? NULL : (var = (vala_source_reference_unref (var), NULL)))
#define _gtkaml_ast_markup_attribute_unref0(var) ((var == NULL) ? NULL : (var = (gtkaml_ast_markup_attribute_unref (var), NULL)))
#define _gtkaml_callable_unref0(var) ((var == NULL) ? NULL : (var = (gtkaml_callable_unref (var), NULL)))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _vala_assert(expr, msg) if G_LIKELY (expr) ; else g_assertion_message_expr (G_LOG_DOMAIN, __FILE__, __LINE__, G_STRFUNC, msg);
#define _vala_return_if_fail(expr, msg) if G_LIKELY (expr) ; else { g_return_if_fail_warning (G_LOG_DOMAIN, G_STRFUNC, msg); return; }
#define _vala_return_val_if_fail(expr, msg, val) if G_LIKELY (expr) ; else { g_return_if_fail_warning (G_LOG_DOMAIN, G_STRFUNC, msg); return val; }
#define _vala_warn_if_fail(expr, msg) if G_LIKELY (expr) ; else g_warn_message (G_LOG_DOMAIN, __FILE__, __LINE__, G_STRFUNC, msg);

struct _GtkamlAstMarkupTagPrivate {
	gchar* _text;
	gchar* _tag_name;
	GtkamlMarkupNamespace* _tag_namespace;
	GtkamlMarkupClass* _markup_class;
	ValaSourceReference* _source_reference;
	ValaDataType* _data_type;
	GtkamlDataTypeParent* _data_type_parent;
	gchar* _full_name;
};

static gint GtkamlAstMarkupTag_private_offset;
static gpointer gtkaml_ast_markup_tag_parent_class = NULL;

VALA_EXTERN GType gtkaml_data_type_parent_get_type (void) G_GNUC_CONST ;
static void gtkaml_ast_markup_tag_set_markup_class (GtkamlAstMarkupTag* self,
                                             GtkamlMarkupClass* value);
VALA_EXTERN GtkamlDataTypeParent* gtkaml_data_type_parent_new (ValaDataType* data_type);
VALA_EXTERN GtkamlDataTypeParent* gtkaml_data_type_parent_construct (GType object_type,
                                                         ValaDataType* data_type);
static void gtkaml_ast_markup_tag_real_generate_public_ast (GtkamlAstMarkupTag* self,
                                                     GtkamlCodeParserProvider* parser);
static GtkamlAstMarkupTag* gtkaml_ast_markup_tag_real_resolve (GtkamlAstMarkupTag* self,
                                                        GtkamlMarkupResolver* resolver);
static void gtkaml_ast_markup_tag_real_resolve_attributes (GtkamlAstMarkupTag* self,
                                                    GtkamlMarkupResolver* resolver);
static void gtkaml_ast_markup_tag_real_generate (GtkamlAstMarkupTag* self,
                                          GtkamlMarkupResolver* resolver);
static void gtkaml_ast_markup_tag_real_generate_attributes (GtkamlAstMarkupTag* self,
                                                     GtkamlMarkupResolver* resolver);
static void gtkaml_ast_markup_tag_real_generate_preconstruct (GtkamlAstMarkupTag* self,
                                                       GtkamlMarkupResolver* resolver);
static gchar* gtkaml_ast_markup_tag_strip_braces (GtkamlAstMarkupTag* self,
                                           const gchar* code);
static void gtkaml_ast_markup_tag_real_generate_construct (GtkamlAstMarkupTag* self,
                                                    GtkamlMarkupResolver* resolver);
static void gtkaml_ast_markup_tag_real_resolve_creation_method (GtkamlAstMarkupTag* self,
                                                         GtkamlMarkupResolver* resolver);
static void gtkaml_ast_markup_tag_real_resolve_creation_method_failed (GtkamlAstMarkupTag* self,
                                                                ValaSourceReference* source_reference,
                                                                const gchar* message);
static ValaList* gtkaml_ast_markup_tag_real_get_creation_method_candidates (GtkamlAstMarkupTag* self);
static ValaMemberAccess* gtkaml_ast_markup_tag_namespace_access (GtkamlAstMarkupTag* self,
                                                          ValaUnresolvedSymbol* ns);
VALA_EXTERN ValaDataType* gtkaml_data_type_parent_get_data_type (GtkamlDataTypeParent* self);
static void gtkaml_ast_markup_tag_finalize (GObject * obj);
static GType gtkaml_ast_markup_tag_get_type_once (void);
static void _vala_gtkaml_ast_markup_tag_get_property (GObject * object,
                                               guint property_id,
                                               GValue * value,
                                               GParamSpec * pspec);
static void _vala_gtkaml_ast_markup_tag_set_property (GObject * object,
                                               guint property_id,
                                               const GValue * value,
                                               GParamSpec * pspec);

static inline gpointer
gtkaml_ast_markup_tag_get_instance_private (GtkamlAstMarkupTag* self)
{
	return G_STRUCT_MEMBER_P (self, GtkamlAstMarkupTag_private_offset);
}

GtkamlAstMarkupTag*
gtkaml_ast_markup_tag_construct (GType object_type,
                                 GtkamlMarkupClass* markup_class,
                                 const gchar* tag_name,
                                 GtkamlMarkupNamespace* tag_namespace,
                                 ValaSourceReference* source_reference)
{
	GtkamlAstMarkupTag * self = NULL;
	const gchar* _tmp0_;
	gchar* _tmp1_;
	ValaUnresolvedSymbol* _tmp2_;
	ValaUnresolvedSymbol* _tmp3_;
	ValaUnresolvedType* _tmp4_;
	ValaUnresolvedType* _tmp5_;
	ValaDataType* _tmp6_;
	ValaDataType* _tmp7_;
	GtkamlDataTypeParent* _tmp8_;
	GEqualFunc _tmp9_;
	ValaArrayList* _tmp10_;
	g_return_val_if_fail (markup_class != NULL, NULL);
	g_return_val_if_fail (tag_name != NULL, NULL);
	g_return_val_if_fail (tag_namespace != NULL, NULL);
	self = (GtkamlAstMarkupTag*) g_object_new (object_type, NULL);
	gtkaml_ast_markup_tag_set_markup_class (self, markup_class);
	gtkaml_ast_markup_tag_set_tag_name (self, tag_name);
	gtkaml_ast_markup_tag_set_tag_namespace (self, tag_namespace);
	gtkaml_ast_markup_tag_set_source_reference (self, source_reference);
	_g_free0 (self->preconstruct_text);
	self->preconstruct_text = NULL;
	_tmp0_ = self->preconstruct_text;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->construct_text);
	self->construct_text = _tmp1_;
	_tmp2_ = vala_unresolved_symbol_new ((ValaUnresolvedSymbol*) tag_namespace, tag_name, source_reference);
	_tmp3_ = _tmp2_;
	_tmp4_ = vala_unresolved_type_new_from_symbol (_tmp3_, NULL);
	_tmp5_ = _tmp4_;
	gtkaml_ast_markup_tag_set_data_type (self, (ValaDataType*) _tmp5_);
	_vala_code_node_unref0 (_tmp5_);
	_vala_code_node_unref0 (_tmp3_);
	_tmp6_ = self->priv->_data_type;
	vala_data_type_set_value_owned (_tmp6_, TRUE);
	_tmp7_ = self->priv->_data_type;
	_tmp8_ = gtkaml_data_type_parent_new (_tmp7_);
	_vala_code_node_unref0 (self->priv->_data_type_parent);
	self->priv->_data_type_parent = _tmp8_;
	_tmp9_ = g_direct_equal;
	_tmp10_ = vala_array_list_new (GTKAML_AST_TYPE_MARKUP_ATTRIBUTE, (GBoxedCopyFunc) gtkaml_ast_markup_attribute_ref, (GDestroyNotify) gtkaml_ast_markup_attribute_unref, _tmp9_);
	_vala_iterable_unref0 (self->creation_parameters);
	self->creation_parameters = (ValaList*) _tmp10_;
	return self;
}

/**
 * Called when parsing.
 * This only generates placeholder Vala AST so that the Parser can move on.
 * e.g. the class itself, its public properties go here.
 */
static void
gtkaml_ast_markup_tag_real_generate_public_ast (GtkamlAstMarkupTag* self,
                                                GtkamlCodeParserProvider* parser)
{
	g_critical ("Type `%s' does not implement abstract method `gtkaml_ast_markup_tag_generate_public_ast'", g_type_name (G_TYPE_FROM_INSTANCE (self)));
	return;
}

void
gtkaml_ast_markup_tag_generate_public_ast (GtkamlAstMarkupTag* self,
                                           GtkamlCodeParserProvider* parser)
{
	GtkamlAstMarkupTagClass* _klass_;
	g_return_if_fail (self != NULL);
	_klass_ = GTKAML_AST_MARKUP_TAG_GET_CLASS (self);
	if (_klass_->generate_public_ast) {
		_klass_->generate_public_ast (self, parser);
	}
}

/**
 * Called when Gtkaml is resolving. 
 * Here replacements in the Gtkaml AST can be made (e.g. MarkupUnresolvedTag -> MarkupTemp).
 * Tags to remove must return 'null' here so that the SymbolResolver can remove them later
 */
static gpointer
_vala_code_node_ref0 (gpointer self)
{
	return self ? vala_code_node_ref (self) : NULL;
}

static gpointer
_g_object_ref0 (gpointer self)
{
	return self ? g_object_ref (self) : NULL;
}

static GtkamlAstMarkupTag*
gtkaml_ast_markup_tag_real_resolve (GtkamlAstMarkupTag* self,
                                    GtkamlMarkupResolver* resolver)
{
	ValaDataType* _tmp0_;
	ValaTypeSymbol* type_symbol = NULL;
	ValaDataType* _tmp1_;
	ValaDataType* _tmp2_;
	ValaTypeSymbol* _tmp3_;
	ValaTypeSymbol* _tmp4_;
	ValaTypeSymbol* _tmp5_;
	ValaTypeSymbol* _tmp6_;
	GtkamlAstMarkupTag* _tmp8_;
	GtkamlAstMarkupTag* result;
	g_return_val_if_fail (resolver != NULL, NULL);
	_tmp0_ = self->priv->_data_type;
	vala_code_node_accept ((ValaCodeNode*) _tmp0_, (ValaCodeVisitor*) resolver);
	_tmp1_ = gtkaml_ast_markup_tag_get_resolved_type (self);
	_tmp2_ = _tmp1_;
	_tmp3_ = vala_data_type_get_type_symbol (_tmp2_);
	_tmp4_ = _tmp3_;
	_tmp5_ = _vala_code_node_ref0 (_tmp4_);
	type_symbol = _tmp5_;
	_tmp6_ = type_symbol;
	if (_tmp6_ != NULL) {
		ValaTypeSymbol* _tmp7_;
		_tmp7_ = type_symbol;
		vala_code_node_accept ((ValaCodeNode*) _tmp7_, (ValaCodeVisitor*) resolver);
	}
	_tmp8_ = _g_object_ref0 (self);
	result = _tmp8_;
	_vala_code_node_unref0 (type_symbol);
	return result;
}

GtkamlAstMarkupTag*
gtkaml_ast_markup_tag_resolve (GtkamlAstMarkupTag* self,
                               GtkamlMarkupResolver* resolver)
{
	GtkamlAstMarkupTagClass* _klass_;
	g_return_val_if_fail (self != NULL, NULL);
	_klass_ = GTKAML_AST_MARKUP_TAG_GET_CLASS (self);
	if (_klass_->resolve) {
		return _klass_->resolve (self, resolver);
	}
	return NULL;
}

/**
 * Called when Gtkaml is resolving, after recursing over children
 */
static void
gtkaml_ast_markup_tag_real_resolve_attributes (GtkamlAstMarkupTag* self,
                                               GtkamlMarkupResolver* resolver)
{
	g_return_if_fail (resolver != NULL);
	gtkaml_ast_markup_tag_resolve_creation_method (self, resolver);
}

void
gtkaml_ast_markup_tag_resolve_attributes (GtkamlAstMarkupTag* self,
                                          GtkamlMarkupResolver* resolver)
{
	GtkamlAstMarkupTagClass* _klass_;
	g_return_if_fail (self != NULL);
	_klass_ = GTKAML_AST_MARKUP_TAG_GET_CLASS (self);
	if (_klass_->resolve_attributes) {
		_klass_->resolve_attributes (self, resolver);
	}
}

/** 
 * Called after Gtkaml finished resolving, before Vala resolver kicks in.
 * Final AST generation phase1 (all AST)
 */
static void
gtkaml_ast_markup_tag_real_generate (GtkamlAstMarkupTag* self,
                                     GtkamlMarkupResolver* resolver)
{
	g_critical ("Type `%s' does not implement abstract method `gtkaml_ast_markup_tag_generate'", g_type_name (G_TYPE_FROM_INSTANCE (self)));
	return;
}

void
gtkaml_ast_markup_tag_generate (GtkamlAstMarkupTag* self,
                                GtkamlMarkupResolver* resolver)
{
	GtkamlAstMarkupTagClass* _klass_;
	g_return_if_fail (self != NULL);
	_klass_ = GTKAML_AST_MARKUP_TAG_GET_CLASS (self);
	if (_klass_->generate) {
		_klass_->generate (self, resolver);
	}
}

/**
 * Called after Gtkaml finished resolving, before Vala resolver kicks in.
 * Final AST generation phase2 (attributes)
 */
static void
gtkaml_ast_markup_tag_real_generate_attributes (GtkamlAstMarkupTag* self,
                                                GtkamlMarkupResolver* resolver)
{
	g_return_if_fail (resolver != NULL);
	{
		ValaList* _attribute_list = NULL;
		ValaList* _tmp0_;
		gint _attribute_size = 0;
		ValaList* _tmp1_;
		gint _tmp2_;
		gint _tmp3_;
		gint _attribute_index = 0;
		_tmp0_ = self->creation_parameters;
		_attribute_list = _tmp0_;
		_tmp1_ = _attribute_list;
		_tmp2_ = vala_collection_get_size ((ValaCollection*) _tmp1_);
		_tmp3_ = _tmp2_;
		_attribute_size = _tmp3_;
		_attribute_index = -1;
		while (TRUE) {
			gint _tmp4_;
			gint _tmp5_;
			GtkamlAstMarkupAttribute* attribute = NULL;
			ValaList* _tmp6_;
			gpointer _tmp7_;
			GtkamlAstMarkupAttribute* _tmp8_;
			_attribute_index = _attribute_index + 1;
			_tmp4_ = _attribute_index;
			_tmp5_ = _attribute_size;
			if (!(_tmp4_ < _tmp5_)) {
				break;
			}
			_tmp6_ = _attribute_list;
			_tmp7_ = vala_list_get (_tmp6_, _attribute_index);
			attribute = (GtkamlAstMarkupAttribute*) _tmp7_;
			_tmp8_ = attribute;
			if (GTKAML_AST_IS_MARKUP_COMPLEX_ATTRIBUTE (_tmp8_)) {
				GtkamlAstMarkupAttribute* _tmp9_;
				GtkamlAstMarkupTag* _tmp10_;
				_tmp9_ = attribute;
				_tmp10_ = G_TYPE_CHECK_INSTANCE_CAST (_tmp9_, GTKAML_AST_TYPE_MARKUP_COMPLEX_ATTRIBUTE, GtkamlAstMarkupComplexAttribute)->value_tag;
				gtkaml_markup_resolver_generate_markup_tag (resolver, _tmp10_);
			}
			_gtkaml_ast_markup_attribute_unref0 (attribute);
		}
	}
	{
		ValaList* _attribute_list = NULL;
		ValaList* _tmp11_;
		gint _attribute_size = 0;
		ValaList* _tmp12_;
		gint _tmp13_;
		gint _tmp14_;
		gint _attribute_index = 0;
		_tmp11_ = self->markup_attributes;
		_attribute_list = _tmp11_;
		_tmp12_ = _attribute_list;
		_tmp13_ = vala_collection_get_size ((ValaCollection*) _tmp12_);
		_tmp14_ = _tmp13_;
		_attribute_size = _tmp14_;
		_attribute_index = -1;
		while (TRUE) {
			gint _tmp15_;
			gint _tmp16_;
			GtkamlAstMarkupAttribute* attribute = NULL;
			ValaList* _tmp17_;
			gpointer _tmp18_;
			GtkamlAstMarkupAttribute* _tmp19_;
			ValaStatement* assignment = NULL;
			GtkamlAstMarkupAttribute* _tmp22_;
			ValaStatement* _tmp23_;
			ValaStatement* _tmp24_;
			_attribute_index = _attribute_index + 1;
			_tmp15_ = _attribute_index;
			_tmp16_ = _attribute_size;
			if (!(_tmp15_ < _tmp16_)) {
				break;
			}
			_tmp17_ = _attribute_list;
			_tmp18_ = vala_list_get (_tmp17_, _attribute_index);
			attribute = (GtkamlAstMarkupAttribute*) _tmp18_;
			_tmp19_ = attribute;
			if (GTKAML_AST_IS_MARKUP_COMPLEX_ATTRIBUTE (_tmp19_)) {
				GtkamlAstMarkupAttribute* _tmp20_;
				GtkamlAstMarkupTag* _tmp21_;
				_tmp20_ = attribute;
				_tmp21_ = G_TYPE_CHECK_INSTANCE_CAST (_tmp20_, GTKAML_AST_TYPE_MARKUP_COMPLEX_ATTRIBUTE, GtkamlAstMarkupComplexAttribute)->value_tag;
				gtkaml_markup_resolver_generate_markup_tag (resolver, _tmp21_);
			}
			_tmp22_ = attribute;
			_tmp23_ = gtkaml_ast_markup_attribute_get_assignment (_tmp22_, resolver, self);
			assignment = _tmp23_;
			_tmp24_ = assignment;
			if (_tmp24_ != NULL) {
				GtkamlMarkupClass* _tmp25_;
				ValaConstructor* _tmp26_;
				ValaConstructor* _tmp27_;
				ValaBlock* _tmp28_;
				ValaBlock* _tmp29_;
				ValaStatement* _tmp30_;
				_tmp25_ = self->priv->_markup_class;
				_tmp26_ = vala_class_get_constructor ((ValaClass*) _tmp25_);
				_tmp27_ = _tmp26_;
				_tmp28_ = vala_subroutine_get_body ((ValaSubroutine*) _tmp27_);
				_tmp29_ = _tmp28_;
				_tmp30_ = assignment;
				vala_block_add_statement (_tmp29_, _tmp30_);
			}
			_vala_code_node_unref0 (assignment);
			_gtkaml_ast_markup_attribute_unref0 (attribute);
		}
	}
}

void
gtkaml_ast_markup_tag_generate_attributes (GtkamlAstMarkupTag* self,
                                           GtkamlMarkupResolver* resolver)
{
	GtkamlAstMarkupTagClass* _klass_;
	g_return_if_fail (self != NULL);
	_klass_ = GTKAML_AST_MARKUP_TAG_GET_CLASS (self);
	if (_klass_->generate_attributes) {
		_klass_->generate_attributes (self, resolver);
	}
}

static void
gtkaml_ast_markup_tag_real_generate_preconstruct (GtkamlAstMarkupTag* self,
                                                  GtkamlMarkupResolver* resolver)
{
	const gchar* _tmp0_;
	g_return_if_fail (resolver != NULL);
	_tmp0_ = self->preconstruct_text;
	if (_tmp0_ != NULL) {
		ValaBlock* stmts = NULL;
		GtkamlValaParser* _tmp1_;
		GtkamlValaParser* _tmp2_;
		GtkamlMarkupClass* _tmp3_;
		const gchar* _tmp4_;
		const gchar* _tmp5_;
		const gchar* _tmp6_;
		gchar* _tmp7_;
		gchar* _tmp8_;
		ValaBlock* _tmp9_;
		ValaBlock* _tmp10_;
		ValaBlock* _tmp11_;
		_tmp1_ = gtkaml_code_parser_provider_get_code_parser ((GtkamlCodeParserProvider*) resolver);
		_tmp2_ = _tmp1_;
		_tmp3_ = self->priv->_markup_class;
		_tmp4_ = gtkaml_ast_markup_tag_get_me (self);
		_tmp5_ = _tmp4_;
		_tmp6_ = self->preconstruct_text;
		_tmp7_ = gtkaml_ast_markup_tag_strip_braces (self, _tmp6_);
		_tmp8_ = _tmp7_;
		_tmp9_ = gtkaml_vala_parser_parse_statements (_tmp2_, _tmp3_, _tmp5_, "_preconstruct", _tmp8_);
		_tmp10_ = _tmp9_;
		_g_free0 (_tmp8_);
		stmts = _tmp10_;
		_tmp11_ = stmts;
		if (G_TYPE_CHECK_INSTANCE_TYPE (_tmp11_, VALA_TYPE_BLOCK)) {
			{
				ValaList* _stmt_list = NULL;
				ValaBlock* _tmp12_;
				ValaList* _tmp13_;
				gint _stmt_size = 0;
				ValaList* _tmp14_;
				gint _tmp15_;
				gint _tmp16_;
				gint _stmt_index = 0;
				_tmp12_ = stmts;
				_tmp13_ = vala_block_get_statements (_tmp12_);
				_stmt_list = _tmp13_;
				_tmp14_ = _stmt_list;
				_tmp15_ = vala_collection_get_size ((ValaCollection*) _tmp14_);
				_tmp16_ = _tmp15_;
				_stmt_size = _tmp16_;
				_stmt_index = -1;
				while (TRUE) {
					gint _tmp17_;
					gint _tmp18_;
					ValaStatement* stmt = NULL;
					ValaList* _tmp19_;
					gpointer _tmp20_;
					GtkamlMarkupClass* _tmp21_;
					ValaConstructor* _tmp22_;
					ValaConstructor* _tmp23_;
					ValaBlock* _tmp24_;
					ValaBlock* _tmp25_;
					ValaStatement* _tmp26_;
					_stmt_index = _stmt_index + 1;
					_tmp17_ = _stmt_index;
					_tmp18_ = _stmt_size;
					if (!(_tmp17_ < _tmp18_)) {
						break;
					}
					_tmp19_ = _stmt_list;
					_tmp20_ = vala_list_get (_tmp19_, _stmt_index);
					stmt = (ValaStatement*) _tmp20_;
					_tmp21_ = self->priv->_markup_class;
					_tmp22_ = vala_class_get_constructor ((ValaClass*) _tmp21_);
					_tmp23_ = _tmp22_;
					_tmp24_ = vala_subroutine_get_body ((ValaSubroutine*) _tmp23_);
					_tmp25_ = _tmp24_;
					_tmp26_ = stmt;
					vala_block_add_statement (_tmp25_, _tmp26_);
					_vala_code_node_unref0 (stmt);
				}
				_vala_iterable_unref0 (_stmt_list);
			}
		}
		_vala_code_node_unref0 (stmts);
	}
}

void
gtkaml_ast_markup_tag_generate_preconstruct (GtkamlAstMarkupTag* self,
                                             GtkamlMarkupResolver* resolver)
{
	GtkamlAstMarkupTagClass* _klass_;
	g_return_if_fail (self != NULL);
	_klass_ = GTKAML_AST_MARKUP_TAG_GET_CLASS (self);
	if (_klass_->generate_preconstruct) {
		_klass_->generate_preconstruct (self, resolver);
	}
}

static void
gtkaml_ast_markup_tag_real_generate_construct (GtkamlAstMarkupTag* self,
                                               GtkamlMarkupResolver* resolver)
{
	const gchar* _tmp0_;
	g_return_if_fail (resolver != NULL);
	_tmp0_ = self->construct_text;
	if (_tmp0_ != NULL) {
		ValaBlock* stmts = NULL;
		GtkamlValaParser* _tmp1_;
		GtkamlValaParser* _tmp2_;
		GtkamlMarkupClass* _tmp3_;
		const gchar* _tmp4_;
		const gchar* _tmp5_;
		const gchar* _tmp6_;
		gchar* _tmp7_;
		gchar* _tmp8_;
		ValaBlock* _tmp9_;
		ValaBlock* _tmp10_;
		ValaBlock* _tmp11_;
		_tmp1_ = gtkaml_code_parser_provider_get_code_parser ((GtkamlCodeParserProvider*) resolver);
		_tmp2_ = _tmp1_;
		_tmp3_ = self->priv->_markup_class;
		_tmp4_ = gtkaml_ast_markup_tag_get_me (self);
		_tmp5_ = _tmp4_;
		_tmp6_ = self->construct_text;
		_tmp7_ = gtkaml_ast_markup_tag_strip_braces (self, _tmp6_);
		_tmp8_ = _tmp7_;
		_tmp9_ = gtkaml_vala_parser_parse_statements (_tmp2_, _tmp3_, _tmp5_, "_construct", _tmp8_);
		_tmp10_ = _tmp9_;
		_g_free0 (_tmp8_);
		stmts = _tmp10_;
		_tmp11_ = stmts;
		if (G_TYPE_CHECK_INSTANCE_TYPE (_tmp11_, VALA_TYPE_BLOCK)) {
			{
				ValaList* _stmt_list = NULL;
				ValaBlock* _tmp12_;
				ValaList* _tmp13_;
				gint _stmt_size = 0;
				ValaList* _tmp14_;
				gint _tmp15_;
				gint _tmp16_;
				gint _stmt_index = 0;
				_tmp12_ = stmts;
				_tmp13_ = vala_block_get_statements (_tmp12_);
				_stmt_list = _tmp13_;
				_tmp14_ = _stmt_list;
				_tmp15_ = vala_collection_get_size ((ValaCollection*) _tmp14_);
				_tmp16_ = _tmp15_;
				_stmt_size = _tmp16_;
				_stmt_index = -1;
				while (TRUE) {
					gint _tmp17_;
					gint _tmp18_;
					ValaStatement* stmt = NULL;
					ValaList* _tmp19_;
					gpointer _tmp20_;
					GtkamlMarkupClass* _tmp21_;
					ValaConstructor* _tmp22_;
					ValaConstructor* _tmp23_;
					ValaBlock* _tmp24_;
					ValaBlock* _tmp25_;
					ValaStatement* _tmp26_;
					_stmt_index = _stmt_index + 1;
					_tmp17_ = _stmt_index;
					_tmp18_ = _stmt_size;
					if (!(_tmp17_ < _tmp18_)) {
						break;
					}
					_tmp19_ = _stmt_list;
					_tmp20_ = vala_list_get (_tmp19_, _stmt_index);
					stmt = (ValaStatement*) _tmp20_;
					_tmp21_ = self->priv->_markup_class;
					_tmp22_ = vala_class_get_constructor ((ValaClass*) _tmp21_);
					_tmp23_ = _tmp22_;
					_tmp24_ = vala_subroutine_get_body ((ValaSubroutine*) _tmp23_);
					_tmp25_ = _tmp24_;
					_tmp26_ = stmt;
					vala_block_add_statement (_tmp25_, _tmp26_);
					_vala_code_node_unref0 (stmt);
				}
				_vala_iterable_unref0 (_stmt_list);
			}
		}
		_vala_code_node_unref0 (stmts);
	}
}

void
gtkaml_ast_markup_tag_generate_construct (GtkamlAstMarkupTag* self,
                                          GtkamlMarkupResolver* resolver)
{
	GtkamlAstMarkupTagClass* _klass_;
	g_return_if_fail (self != NULL);
	_klass_ = GTKAML_AST_MARKUP_TAG_GET_CLASS (self);
	if (_klass_->generate_construct) {
		_klass_->generate_construct (self, resolver);
	}
}

/**
 * picks up creation method parameters and determines the creation method, if applicable
 */
static gpointer
_vala_iterable_ref0 (gpointer self)
{
	return self ? vala_iterable_ref (self) : NULL;
}

static void
gtkaml_ast_markup_tag_real_resolve_creation_method (GtkamlAstMarkupTag* self,
                                                    GtkamlMarkupResolver* resolver)
{
	ValaList* candidates = NULL;
	ValaList* _tmp0_;
	gint min = 0;
	ValaCreationMethod* min_match_method = NULL;
	ValaList* _tmp1_;
	gpointer _tmp2_;
	gint max = 0;
	ValaCreationMethod* max_match_method = NULL;
	ValaList* _tmp3_;
	gpointer _tmp4_;
	ValaList* matched_method_parameters = NULL;
	GEqualFunc _tmp5_;
	ValaArrayList* _tmp6_;
	gint i = 0;
	ValaCreationMethod* _tmp65_;
	ValaList* _tmp66_;
	gint _tmp67_;
	gint _tmp68_;
	g_return_if_fail (resolver != NULL);
	_tmp0_ = gtkaml_ast_markup_tag_get_creation_method_candidates (self);
	candidates = _tmp0_;
	min = 100;
	_tmp1_ = candidates;
	_tmp2_ = vala_list_get (_tmp1_, 0);
	min_match_method = (ValaCreationMethod*) _tmp2_;
	max = -1;
	_tmp3_ = candidates;
	_tmp4_ = vala_list_get (_tmp3_, 0);
	max_match_method = (ValaCreationMethod*) _tmp4_;
	_tmp5_ = g_direct_equal;
	_tmp6_ = vala_array_list_new (GTKAML_AST_TYPE_MARKUP_ATTRIBUTE, (GBoxedCopyFunc) gtkaml_ast_markup_attribute_ref, (GDestroyNotify) gtkaml_ast_markup_attribute_unref, _tmp5_);
	matched_method_parameters = (ValaList*) _tmp6_;
	i = 0;
	{
		gboolean _tmp7_ = FALSE;
		_tmp7_ = TRUE;
		while (TRUE) {
			ValaCreationMethod* current_candidate = NULL;
			ValaList* _tmp11_;
			gpointer _tmp12_;
			ValaList* parameters = NULL;
			const gchar* _tmp13_;
			const gchar* _tmp14_;
			ValaCreationMethod* _tmp15_;
			GtkamlCallable* _tmp16_;
			GtkamlCallable* _tmp17_;
			ValaSourceReference* _tmp18_;
			ValaList* _tmp19_;
			ValaList* _tmp20_;
			gint matches = 0;
			ValaList* _tmp40_;
			gint _tmp41_;
			gint _tmp42_;
			gint _tmp64_;
			if (!_tmp7_) {
				ValaList* _tmp8_;
				gint _tmp9_;
				gint _tmp10_;
				_tmp8_ = candidates;
				_tmp9_ = vala_collection_get_size ((ValaCollection*) _tmp8_);
				_tmp10_ = _tmp9_;
				if (!(i < _tmp10_)) {
					break;
				}
			}
			_tmp7_ = FALSE;
			_tmp11_ = candidates;
			_tmp12_ = vala_list_get (_tmp11_, i);
			current_candidate = (ValaCreationMethod*) _tmp12_;
			_tmp13_ = gtkaml_ast_markup_tag_get_full_name (self);
			_tmp14_ = _tmp13_;
			_tmp15_ = current_candidate;
			_tmp16_ = gtkaml_callable_new ((ValaSymbol*) _tmp15_);
			_tmp17_ = _tmp16_;
			_tmp18_ = self->priv->_source_reference;
			_tmp19_ = gtkaml_markup_resolver_get_default_parameters (resolver, _tmp14_, _tmp17_, _tmp18_);
			_tmp20_ = _tmp19_;
			_gtkaml_callable_unref0 (_tmp17_);
			parameters = _tmp20_;
			matches = 0;
			{
				ValaList* _parameter_list = NULL;
				ValaList* _tmp21_;
				gint _parameter_size = 0;
				ValaList* _tmp22_;
				gint _tmp23_;
				gint _tmp24_;
				gint _parameter_index = 0;
				_tmp21_ = parameters;
				_parameter_list = _tmp21_;
				_tmp22_ = _parameter_list;
				_tmp23_ = vala_collection_get_size ((ValaCollection*) _tmp22_);
				_tmp24_ = _tmp23_;
				_parameter_size = _tmp24_;
				_parameter_index = -1;
				while (TRUE) {
					gint _tmp25_;
					gint _tmp26_;
					GtkamlAstMarkupAttribute* parameter = NULL;
					ValaList* _tmp27_;
					gpointer _tmp28_;
					gboolean _tmp29_ = FALSE;
					GtkamlAstMarkupAttribute* _tmp30_;
					const gchar* _tmp31_;
					const gchar* _tmp32_;
					GtkamlAstMarkupAttribute* _tmp33_;
					GtkamlAstMarkupAttribute* _tmp34_;
					gboolean _tmp35_;
					_parameter_index = _parameter_index + 1;
					_tmp25_ = _parameter_index;
					_tmp26_ = _parameter_size;
					if (!(_tmp25_ < _tmp26_)) {
						break;
					}
					_tmp27_ = _parameter_list;
					_tmp28_ = vala_list_get (_tmp27_, _parameter_index);
					parameter = (GtkamlAstMarkupAttribute*) _tmp28_;
					_tmp30_ = parameter;
					_tmp31_ = gtkaml_ast_markup_attribute_get_attribute_name (_tmp30_);
					_tmp32_ = _tmp31_;
					_tmp33_ = gtkaml_ast_markup_tag_get_attribute (self, _tmp32_);
					_tmp34_ = _tmp33_;
					_tmp35_ = NULL != _tmp34_;
					_gtkaml_ast_markup_attribute_unref0 (_tmp34_);
					if (_tmp35_) {
						_tmp29_ = TRUE;
					} else {
						GtkamlAstMarkupAttribute* _tmp36_;
						const gchar* _tmp37_;
						const gchar* _tmp38_;
						_tmp36_ = parameter;
						_tmp37_ = gtkaml_ast_markup_attribute_get_attribute_value (_tmp36_);
						_tmp38_ = _tmp37_;
						_tmp29_ = _tmp38_ != NULL;
					}
					if (_tmp29_) {
						gint _tmp39_;
						_tmp39_ = matches;
						matches = _tmp39_ + 1;
					}
					_gtkaml_ast_markup_attribute_unref0 (parameter);
				}
			}
			_tmp40_ = parameters;
			_tmp41_ = vala_collection_get_size ((ValaCollection*) _tmp40_);
			_tmp42_ = _tmp41_;
			if (matches < _tmp42_) {
				ValaList* _tmp43_;
				gint _tmp44_;
				gint _tmp45_;
				_tmp43_ = parameters;
				_tmp44_ = vala_collection_get_size ((ValaCollection*) _tmp43_);
				_tmp45_ = _tmp44_;
				if (_tmp45_ < min) {
					ValaList* _tmp46_;
					gint _tmp47_;
					gint _tmp48_;
					ValaCreationMethod* _tmp49_;
					ValaCreationMethod* _tmp50_;
					_tmp46_ = parameters;
					_tmp47_ = vala_collection_get_size ((ValaCollection*) _tmp46_);
					_tmp48_ = _tmp47_;
					min = _tmp48_;
					_tmp49_ = current_candidate;
					_tmp50_ = _vala_code_node_ref0 (_tmp49_);
					_vala_code_node_unref0 (min_match_method);
					min_match_method = _tmp50_;
				}
			} else {
				ValaList* _tmp51_;
				gint _tmp52_;
				gint _tmp53_;
				ValaList* _tmp54_;
				gint _tmp55_;
				gint _tmp56_;
				_tmp51_ = parameters;
				_tmp52_ = vala_collection_get_size ((ValaCollection*) _tmp51_);
				_tmp53_ = _tmp52_;
				_vala_assert (matches == _tmp53_, "matches == parameters.size");
				_tmp54_ = parameters;
				_tmp55_ = vala_collection_get_size ((ValaCollection*) _tmp54_);
				_tmp56_ = _tmp55_;
				if (_tmp56_ > max) {
					ValaList* _tmp57_;
					gint _tmp58_;
					gint _tmp59_;
					ValaCreationMethod* _tmp60_;
					ValaCreationMethod* _tmp61_;
					ValaList* _tmp62_;
					ValaList* _tmp63_;
					_tmp57_ = parameters;
					_tmp58_ = vala_collection_get_size ((ValaCollection*) _tmp57_);
					_tmp59_ = _tmp58_;
					max = _tmp59_;
					_tmp60_ = current_candidate;
					_tmp61_ = _vala_code_node_ref0 (_tmp60_);
					_vala_code_node_unref0 (max_match_method);
					max_match_method = _tmp61_;
					_tmp62_ = parameters;
					_tmp63_ = _vala_iterable_ref0 (_tmp62_);
					_vala_iterable_unref0 (matched_method_parameters);
					matched_method_parameters = _tmp63_;
				}
			}
			_tmp64_ = i;
			i = _tmp64_ + 1;
			_vala_iterable_unref0 (parameters);
			_vala_code_node_unref0 (current_candidate);
		}
	}
	_tmp65_ = max_match_method;
	_tmp66_ = vala_callable_get_parameters ((ValaCallable*) _tmp65_);
	_tmp67_ = vala_collection_get_size ((ValaCollection*) _tmp66_);
	_tmp68_ = _tmp67_;
	if (_tmp68_ == max) {
		ValaCreationMethod* _tmp69_;
		ValaCreationMethod* _tmp70_;
		_tmp69_ = max_match_method;
		_tmp70_ = _vala_code_node_ref0 (_tmp69_);
		_vala_code_node_unref0 (self->creation_method);
		self->creation_method = _tmp70_;
		{
			ValaList* _parameter_list = NULL;
			ValaList* _tmp71_;
			gint _parameter_size = 0;
			ValaList* _tmp72_;
			gint _tmp73_;
			gint _tmp74_;
			gint _parameter_index = 0;
			_tmp71_ = matched_method_parameters;
			_parameter_list = _tmp71_;
			_tmp72_ = _parameter_list;
			_tmp73_ = vala_collection_get_size ((ValaCollection*) _tmp72_);
			_tmp74_ = _tmp73_;
			_parameter_size = _tmp74_;
			_parameter_index = -1;
			while (TRUE) {
				gint _tmp75_;
				gint _tmp76_;
				GtkamlAstMarkupAttribute* parameter = NULL;
				ValaList* _tmp77_;
				gpointer _tmp78_;
				GtkamlAstMarkupAttribute* explicit_attribute = NULL;
				GtkamlAstMarkupAttribute* _tmp79_;
				const gchar* _tmp80_;
				const gchar* _tmp81_;
				GtkamlAstMarkupAttribute* _tmp82_;
				GtkamlAstMarkupAttribute* _tmp83_;
				_parameter_index = _parameter_index + 1;
				_tmp75_ = _parameter_index;
				_tmp76_ = _parameter_size;
				if (!(_tmp75_ < _tmp76_)) {
					break;
				}
				_tmp77_ = _parameter_list;
				_tmp78_ = vala_list_get (_tmp77_, _parameter_index);
				parameter = (GtkamlAstMarkupAttribute*) _tmp78_;
				explicit_attribute = NULL;
				_tmp79_ = parameter;
				_tmp80_ = gtkaml_ast_markup_attribute_get_attribute_name (_tmp79_);
				_tmp81_ = _tmp80_;
				_tmp82_ = gtkaml_ast_markup_tag_get_attribute (self, _tmp81_);
				_gtkaml_ast_markup_attribute_unref0 (explicit_attribute);
				explicit_attribute = _tmp82_;
				_tmp83_ = explicit_attribute;
				if (NULL != _tmp83_) {
					GtkamlAstMarkupAttribute* _tmp84_;
					GtkamlAstMarkupAttribute* _tmp85_;
					ValaDataType* _tmp86_;
					ValaDataType* _tmp87_;
					ValaList* _tmp88_;
					GtkamlAstMarkupAttribute* _tmp89_;
					GtkamlAstMarkupAttribute* _tmp90_;
					_tmp84_ = explicit_attribute;
					_tmp85_ = parameter;
					_tmp86_ = gtkaml_ast_markup_attribute_get_target_type (_tmp85_);
					_tmp87_ = _tmp86_;
					gtkaml_ast_markup_attribute_set_target_type (_tmp84_, _tmp87_);
					_tmp88_ = self->creation_parameters;
					_tmp89_ = explicit_attribute;
					vala_collection_add ((ValaCollection*) _tmp88_, _tmp89_);
					_tmp90_ = explicit_attribute;
					gtkaml_ast_markup_tag_remove_attribute (self, _tmp90_);
				} else {
					ValaList* _tmp91_;
					GtkamlAstMarkupAttribute* _tmp92_;
					_tmp91_ = self->creation_parameters;
					_tmp92_ = parameter;
					vala_collection_add ((ValaCollection*) _tmp91_, _tmp92_);
				}
				_gtkaml_ast_markup_attribute_unref0 (explicit_attribute);
				_gtkaml_ast_markup_attribute_unref0 (parameter);
			}
		}
	} else {
		gchar* required = NULL;
		gchar* _tmp93_;
		ValaList* parameters = NULL;
		ValaCreationMethod* _tmp94_;
		ValaList* _tmp95_;
		ValaList* _tmp96_;
		const gchar* _tmp113_;
		ValaList* _tmp114_;
		gpointer _tmp115_;
		ValaParameter* _tmp116_;
		const gchar* _tmp117_;
		const gchar* _tmp118_;
		gchar* _tmp119_;
		gchar* _tmp120_;
		gchar* _tmp121_;
		gchar* _tmp122_;
		gchar* _tmp123_;
		ValaSourceReference* _tmp124_;
		const gchar* _tmp125_;
		const gchar* _tmp126_;
		const gchar* _tmp127_;
		gchar* _tmp128_;
		gchar* _tmp129_;
		_tmp93_ = g_strdup ("");
		required = _tmp93_;
		_tmp94_ = min_match_method;
		_tmp95_ = vala_callable_get_parameters ((ValaCallable*) _tmp94_);
		_tmp96_ = _vala_iterable_ref0 (_tmp95_);
		parameters = _tmp96_;
		i = 0;
		{
			gboolean _tmp97_ = FALSE;
			_tmp97_ = TRUE;
			while (TRUE) {
				ValaList* _tmp99_;
				gint _tmp100_;
				gint _tmp101_;
				const gchar* _tmp102_;
				ValaList* _tmp103_;
				gpointer _tmp104_;
				ValaParameter* _tmp105_;
				const gchar* _tmp106_;
				const gchar* _tmp107_;
				gchar* _tmp108_;
				gchar* _tmp109_;
				gchar* _tmp110_;
				gchar* _tmp111_;
				gchar* _tmp112_;
				if (!_tmp97_) {
					gint _tmp98_;
					_tmp98_ = i;
					i = _tmp98_ + 1;
				}
				_tmp97_ = FALSE;
				_tmp99_ = parameters;
				_tmp100_ = vala_collection_get_size ((ValaCollection*) _tmp99_);
				_tmp101_ = _tmp100_;
				if (!(i < (_tmp101_ - 1))) {
					break;
				}
				_tmp102_ = required;
				_tmp103_ = parameters;
				_tmp104_ = vala_list_get (_tmp103_, i);
				_tmp105_ = (ValaParameter*) _tmp104_;
				_tmp106_ = vala_symbol_get_name ((ValaSymbol*) _tmp105_);
				_tmp107_ = _tmp106_;
				_tmp108_ = g_strconcat ("'", _tmp107_, NULL);
				_tmp109_ = _tmp108_;
				_tmp110_ = g_strconcat (_tmp109_, "',", NULL);
				_tmp111_ = _tmp110_;
				_tmp112_ = g_strconcat (_tmp102_, _tmp111_, NULL);
				_g_free0 (required);
				required = _tmp112_;
				_g_free0 (_tmp111_);
				_g_free0 (_tmp109_);
				_vala_code_node_unref0 (_tmp105_);
			}
		}
		_tmp113_ = required;
		_tmp114_ = parameters;
		_tmp115_ = vala_list_get (_tmp114_, i);
		_tmp116_ = (ValaParameter*) _tmp115_;
		_tmp117_ = vala_symbol_get_name ((ValaSymbol*) _tmp116_);
		_tmp118_ = _tmp117_;
		_tmp119_ = g_strconcat ("'", _tmp118_, NULL);
		_tmp120_ = _tmp119_;
		_tmp121_ = g_strconcat (_tmp120_, "'", NULL);
		_tmp122_ = _tmp121_;
		_tmp123_ = g_strconcat (_tmp113_, _tmp122_, NULL);
		_g_free0 (required);
		required = _tmp123_;
		_g_free0 (_tmp122_);
		_g_free0 (_tmp120_);
		_vala_code_node_unref0 (_tmp116_);
		_tmp124_ = self->priv->_source_reference;
		_tmp125_ = required;
		_tmp126_ = gtkaml_ast_markup_tag_get_full_name (self);
		_tmp127_ = _tmp126_;
		_tmp128_ = g_strdup_printf ("at least %s required for %s instantiation.", _tmp125_, _tmp127_);
		_tmp129_ = _tmp128_;
		gtkaml_ast_markup_tag_resolve_creation_method_failed (self, _tmp124_, _tmp129_);
		_g_free0 (_tmp129_);
		_vala_iterable_unref0 (parameters);
		_g_free0 (required);
	}
	_vala_iterable_unref0 (matched_method_parameters);
	_vala_code_node_unref0 (max_match_method);
	_vala_code_node_unref0 (min_match_method);
	_vala_iterable_unref0 (candidates);
}

void
gtkaml_ast_markup_tag_resolve_creation_method (GtkamlAstMarkupTag* self,
                                               GtkamlMarkupResolver* resolver)
{
	GtkamlAstMarkupTagClass* _klass_;
	g_return_if_fail (self != NULL);
	_klass_ = GTKAML_AST_MARKUP_TAG_GET_CLASS (self);
	if (_klass_->resolve_creation_method) {
		_klass_->resolve_creation_method (self, resolver);
	}
}

/**
     * decides weather to halt on error or just issue an warning
     */
static void
gtkaml_ast_markup_tag_real_resolve_creation_method_failed (GtkamlAstMarkupTag* self,
                                                           ValaSourceReference* source_reference,
                                                           const gchar* message)
{
	g_return_if_fail (source_reference != NULL);
	g_return_if_fail (message != NULL);
	vala_report_error (source_reference, "%s", message);
}

void
gtkaml_ast_markup_tag_resolve_creation_method_failed (GtkamlAstMarkupTag* self,
                                                      ValaSourceReference* source_reference,
                                                      const gchar* message)
{
	GtkamlAstMarkupTagClass* _klass_;
	g_return_if_fail (self != NULL);
	_klass_ = GTKAML_AST_MARKUP_TAG_GET_CLASS (self);
	if (_klass_->resolve_creation_method_failed) {
		_klass_->resolve_creation_method_failed (self, source_reference, message);
	}
}

/**
 * returns the list of possible creation methods
 */
static ValaList*
gtkaml_ast_markup_tag_real_get_creation_method_candidates (GtkamlAstMarkupTag* self)
{
	ValaList* candidates = NULL;
	GEqualFunc _tmp0_;
	ValaArrayList* _tmp1_;
	ValaList* methods = NULL;
	ValaTypeSymbol* type_symbol = NULL;
	ValaDataType* _tmp2_;
	ValaDataType* _tmp3_;
	ValaTypeSymbol* _tmp4_;
	ValaTypeSymbol* _tmp5_;
	ValaTypeSymbol* _tmp6_;
	ValaTypeSymbol* _tmp7_;
	ValaList* _tmp31_;
	gint _tmp32_;
	gint _tmp33_;
	ValaList* result;
	_tmp0_ = g_direct_equal;
	_tmp1_ = vala_array_list_new (VALA_TYPE_CREATION_METHOD, (GBoxedCopyFunc) vala_code_node_ref, (GDestroyNotify) vala_code_node_unref, _tmp0_);
	candidates = (ValaList*) _tmp1_;
	methods = NULL;
	_tmp2_ = gtkaml_ast_markup_tag_get_resolved_type (self);
	_tmp3_ = _tmp2_;
	_tmp4_ = vala_data_type_get_type_symbol (_tmp3_);
	_tmp5_ = _tmp4_;
	_tmp6_ = _vala_code_node_ref0 (_tmp5_);
	type_symbol = _tmp6_;
	_tmp7_ = type_symbol;
	if (G_TYPE_CHECK_INSTANCE_TYPE (_tmp7_, VALA_TYPE_CLASS)) {
		ValaTypeSymbol* _tmp8_;
		ValaList* _tmp9_;
		ValaList* _tmp10_;
		_tmp8_ = type_symbol;
		_tmp9_ = vala_object_type_symbol_get_methods ((ValaObjectTypeSymbol*) G_TYPE_CHECK_INSTANCE_CAST (_tmp8_, VALA_TYPE_CLASS, ValaClass));
		_tmp10_ = _vala_iterable_ref0 (_tmp9_);
		_vala_iterable_unref0 (methods);
		methods = _tmp10_;
	} else {
		ValaTypeSymbol* _tmp11_;
		_tmp11_ = type_symbol;
		if (G_TYPE_CHECK_INSTANCE_TYPE (_tmp11_, VALA_TYPE_STRUCT)) {
			ValaTypeSymbol* _tmp12_;
			ValaList* _tmp13_;
			ValaList* _tmp14_;
			ValaCreationMethod* default_struct_creation = NULL;
			const gchar* _tmp15_;
			ValaSourceReference* _tmp16_;
			ValaCreationMethod* _tmp17_;
			ValaList* _tmp18_;
			ValaCreationMethod* _tmp19_;
			_tmp12_ = type_symbol;
			_tmp13_ = vala_struct_get_methods (G_TYPE_CHECK_INSTANCE_CAST (_tmp12_, VALA_TYPE_STRUCT, ValaStruct));
			_tmp14_ = _vala_iterable_ref0 (_tmp13_);
			_vala_iterable_unref0 (methods);
			methods = _tmp14_;
			_tmp15_ = self->priv->_tag_name;
			_tmp16_ = self->priv->_source_reference;
			_tmp17_ = vala_creation_method_new (_tmp15_, ".new", _tmp16_, NULL);
			default_struct_creation = _tmp17_;
			_tmp18_ = methods;
			_tmp19_ = default_struct_creation;
			vala_collection_add ((ValaCollection*) _tmp18_, (ValaMethod*) _tmp19_);
			_vala_code_node_unref0 (default_struct_creation);
		}
	}
	{
		ValaList* _m_list = NULL;
		ValaList* _tmp20_;
		gint _m_size = 0;
		ValaList* _tmp21_;
		gint _tmp22_;
		gint _tmp23_;
		gint _m_index = 0;
		_tmp20_ = methods;
		_m_list = _tmp20_;
		_tmp21_ = _m_list;
		_tmp22_ = vala_collection_get_size ((ValaCollection*) _tmp21_);
		_tmp23_ = _tmp22_;
		_m_size = _tmp23_;
		_m_index = -1;
		while (TRUE) {
			gint _tmp24_;
			gint _tmp25_;
			ValaMethod* m = NULL;
			ValaList* _tmp26_;
			gpointer _tmp27_;
			ValaMethod* _tmp28_;
			_m_index = _m_index + 1;
			_tmp24_ = _m_index;
			_tmp25_ = _m_size;
			if (!(_tmp24_ < _tmp25_)) {
				break;
			}
			_tmp26_ = _m_list;
			_tmp27_ = vala_list_get (_tmp26_, _m_index);
			m = (ValaMethod*) _tmp27_;
			_tmp28_ = m;
			if (G_TYPE_CHECK_INSTANCE_TYPE (_tmp28_, VALA_TYPE_CREATION_METHOD)) {
				ValaList* _tmp29_;
				ValaMethod* _tmp30_;
				_tmp29_ = candidates;
				_tmp30_ = m;
				vala_collection_add ((ValaCollection*) _tmp29_, G_TYPE_CHECK_INSTANCE_TYPE (_tmp30_, VALA_TYPE_CREATION_METHOD) ? ((ValaCreationMethod*) _tmp30_) : NULL);
			}
			_vala_code_node_unref0 (m);
		}
	}
	_tmp31_ = candidates;
	_tmp32_ = vala_collection_get_size ((ValaCollection*) _tmp31_);
	_tmp33_ = _tmp32_;
	_vala_assert (_tmp33_ > 0, "candidates.size > 0");
	result = candidates;
	_vala_code_node_unref0 (type_symbol);
	_vala_iterable_unref0 (methods);
	return result;
}

ValaList*
gtkaml_ast_markup_tag_get_creation_method_candidates (GtkamlAstMarkupTag* self)
{
	GtkamlAstMarkupTagClass* _klass_;
	g_return_val_if_fail (self != NULL, NULL);
	_klass_ = GTKAML_AST_MARKUP_TAG_GET_CLASS (self);
	if (_klass_->get_creation_method_candidates) {
		return _klass_->get_creation_method_candidates (self);
	}
	return NULL;
}

ValaList*
gtkaml_ast_markup_tag_get_child_tags (GtkamlAstMarkupTag* self)
{
	ValaList* _tmp0_;
	ValaList* _tmp1_;
	ValaList* result;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->child_tags;
	_tmp1_ = _vala_iterable_ref0 (_tmp0_);
	result = _tmp1_;
	return result;
}

void
gtkaml_ast_markup_tag_add_child_tag (GtkamlAstMarkupTag* self,
                                     GtkamlAstMarkupChildTag* child_tag)
{
	ValaList* _tmp0_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (child_tag != NULL);
	_tmp0_ = self->child_tags;
	vala_collection_add ((ValaCollection*) _tmp0_, child_tag);
	gtkaml_ast_markup_child_tag_set_parent_tag (child_tag, self);
}

/**
 * replaces a child tag and moves all its attributes and subtags to the new one
 */
void
gtkaml_ast_markup_tag_replace_child_tag (GtkamlAstMarkupTag* self,
                                         GtkamlAstMarkupChildTag* old_child,
                                         GtkamlAstMarkupChildTag* new_child)
{
	g_return_if_fail (self != NULL);
	g_return_if_fail (old_child != NULL);
	g_return_if_fail (new_child != NULL);
	{
		gint i = 0;
		i = 0;
		{
			gboolean _tmp0_ = FALSE;
			_tmp0_ = TRUE;
			while (TRUE) {
				ValaList* _tmp2_;
				gint _tmp3_;
				gint _tmp4_;
				ValaList* _tmp5_;
				gpointer _tmp6_;
				GtkamlAstMarkupChildTag* _tmp7_;
				gboolean _tmp8_;
				if (!_tmp0_) {
					gint _tmp1_;
					_tmp1_ = i;
					i = _tmp1_ + 1;
				}
				_tmp0_ = FALSE;
				_tmp2_ = self->child_tags;
				_tmp3_ = vala_collection_get_size ((ValaCollection*) _tmp2_);
				_tmp4_ = _tmp3_;
				if (!(i < _tmp4_)) {
					break;
				}
				_tmp5_ = self->child_tags;
				_tmp6_ = vala_list_get (_tmp5_, i);
				_tmp7_ = (GtkamlAstMarkupChildTag*) _tmp6_;
				_tmp8_ = _tmp7_ == old_child;
				_g_object_unref0 (_tmp7_);
				if (_tmp8_) {
					ValaList* _tmp35_;
					{
						ValaList* _child_tag_list = NULL;
						ValaList* _tmp9_;
						gpointer _tmp10_;
						GtkamlAstMarkupChildTag* _tmp11_;
						ValaList* _tmp12_;
						ValaList* _tmp13_;
						gint _child_tag_size = 0;
						ValaList* _tmp14_;
						gint _tmp15_;
						gint _tmp16_;
						gint _child_tag_index = 0;
						_tmp9_ = self->child_tags;
						_tmp10_ = vala_list_get (_tmp9_, i);
						_tmp11_ = (GtkamlAstMarkupChildTag*) _tmp10_;
						_tmp12_ = gtkaml_ast_markup_tag_get_child_tags ((GtkamlAstMarkupTag*) _tmp11_);
						_tmp13_ = _tmp12_;
						_g_object_unref0 (_tmp11_);
						_child_tag_list = _tmp13_;
						_tmp14_ = _child_tag_list;
						_tmp15_ = vala_collection_get_size ((ValaCollection*) _tmp14_);
						_tmp16_ = _tmp15_;
						_child_tag_size = _tmp16_;
						_child_tag_index = -1;
						while (TRUE) {
							gint _tmp17_;
							gint _tmp18_;
							GtkamlAstMarkupChildTag* child_tag = NULL;
							ValaList* _tmp19_;
							gpointer _tmp20_;
							GtkamlAstMarkupChildTag* _tmp21_;
							_child_tag_index = _child_tag_index + 1;
							_tmp17_ = _child_tag_index;
							_tmp18_ = _child_tag_size;
							if (!(_tmp17_ < _tmp18_)) {
								break;
							}
							_tmp19_ = _child_tag_list;
							_tmp20_ = vala_list_get (_tmp19_, _child_tag_index);
							child_tag = (GtkamlAstMarkupChildTag*) _tmp20_;
							_tmp21_ = child_tag;
							gtkaml_ast_markup_tag_add_child_tag ((GtkamlAstMarkupTag*) new_child, _tmp21_);
							_g_object_unref0 (child_tag);
						}
						_vala_iterable_unref0 (_child_tag_list);
					}
					{
						ValaList* _attribute_list = NULL;
						ValaList* _tmp22_;
						gpointer _tmp23_;
						GtkamlAstMarkupChildTag* _tmp24_;
						ValaList* _tmp25_;
						ValaList* _tmp26_;
						gint _attribute_size = 0;
						ValaList* _tmp27_;
						gint _tmp28_;
						gint _tmp29_;
						gint _attribute_index = 0;
						_tmp22_ = self->child_tags;
						_tmp23_ = vala_list_get (_tmp22_, i);
						_tmp24_ = (GtkamlAstMarkupChildTag*) _tmp23_;
						_tmp25_ = gtkaml_ast_markup_tag_get_markup_attributes ((GtkamlAstMarkupTag*) _tmp24_);
						_tmp26_ = _tmp25_;
						_g_object_unref0 (_tmp24_);
						_attribute_list = _tmp26_;
						_tmp27_ = _attribute_list;
						_tmp28_ = vala_collection_get_size ((ValaCollection*) _tmp27_);
						_tmp29_ = _tmp28_;
						_attribute_size = _tmp29_;
						_attribute_index = -1;
						while (TRUE) {
							gint _tmp30_;
							gint _tmp31_;
							GtkamlAstMarkupAttribute* attribute = NULL;
							ValaList* _tmp32_;
							gpointer _tmp33_;
							GtkamlAstMarkupAttribute* _tmp34_;
							_attribute_index = _attribute_index + 1;
							_tmp30_ = _attribute_index;
							_tmp31_ = _attribute_size;
							if (!(_tmp30_ < _tmp31_)) {
								break;
							}
							_tmp32_ = _attribute_list;
							_tmp33_ = vala_list_get (_tmp32_, _attribute_index);
							attribute = (GtkamlAstMarkupAttribute*) _tmp33_;
							_tmp34_ = attribute;
							gtkaml_ast_markup_tag_add_markup_attribute ((GtkamlAstMarkupTag*) new_child, _tmp34_);
							_gtkaml_ast_markup_attribute_unref0 (attribute);
						}
						_vala_iterable_unref0 (_attribute_list);
					}
					_tmp35_ = self->child_tags;
					vala_list_set (_tmp35_, i, new_child);
					return;
				}
			}
		}
	}
}

void
gtkaml_ast_markup_tag_remove_child_tag (GtkamlAstMarkupTag* self,
                                        GtkamlAstMarkupChildTag* old_child)
{
	ValaList* _tmp0_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (old_child != NULL);
	_tmp0_ = self->child_tags;
	vala_collection_remove ((ValaCollection*) _tmp0_, old_child);
}

ValaList*
gtkaml_ast_markup_tag_get_markup_attributes (GtkamlAstMarkupTag* self)
{
	ValaList* _tmp0_;
	ValaList* _tmp1_;
	ValaList* result;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->markup_attributes;
	_tmp1_ = _vala_iterable_ref0 (_tmp0_);
	result = _tmp1_;
	return result;
}

void
gtkaml_ast_markup_tag_add_markup_attribute (GtkamlAstMarkupTag* self,
                                            GtkamlAstMarkupAttribute* markup_attribute)
{
	ValaList* _tmp0_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (markup_attribute != NULL);
	_tmp0_ = self->markup_attributes;
	vala_collection_add ((ValaCollection*) _tmp0_, markup_attribute);
}

GtkamlAstMarkupAttribute*
gtkaml_ast_markup_tag_get_attribute (GtkamlAstMarkupTag* self,
                                     const gchar* name)
{
	GtkamlAstMarkupAttribute* result;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (name != NULL, NULL);
	{
		ValaList* _attribute_list = NULL;
		ValaList* _tmp0_;
		gint _attribute_size = 0;
		ValaList* _tmp1_;
		gint _tmp2_;
		gint _tmp3_;
		gint _attribute_index = 0;
		_tmp0_ = self->markup_attributes;
		_attribute_list = _tmp0_;
		_tmp1_ = _attribute_list;
		_tmp2_ = vala_collection_get_size ((ValaCollection*) _tmp1_);
		_tmp3_ = _tmp2_;
		_attribute_size = _tmp3_;
		_attribute_index = -1;
		while (TRUE) {
			gint _tmp4_;
			gint _tmp5_;
			GtkamlAstMarkupAttribute* attribute = NULL;
			ValaList* _tmp6_;
			gpointer _tmp7_;
			GtkamlAstMarkupAttribute* _tmp8_;
			const gchar* _tmp9_;
			const gchar* _tmp10_;
			_attribute_index = _attribute_index + 1;
			_tmp4_ = _attribute_index;
			_tmp5_ = _attribute_size;
			if (!(_tmp4_ < _tmp5_)) {
				break;
			}
			_tmp6_ = _attribute_list;
			_tmp7_ = vala_list_get (_tmp6_, _attribute_index);
			attribute = (GtkamlAstMarkupAttribute*) _tmp7_;
			_tmp8_ = attribute;
			_tmp9_ = gtkaml_ast_markup_attribute_get_attribute_name (_tmp8_);
			_tmp10_ = _tmp9_;
			if (g_strcmp0 (_tmp10_, name) == 0) {
				result = attribute;
				return result;
			}
			_gtkaml_ast_markup_attribute_unref0 (attribute);
		}
	}
	result = NULL;
	return result;
}

void
gtkaml_ast_markup_tag_remove_attribute (GtkamlAstMarkupTag* self,
                                        GtkamlAstMarkupAttribute* attribute)
{
	ValaList* _tmp0_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (attribute != NULL);
	_tmp0_ = self->markup_attributes;
	vala_collection_remove ((ValaCollection*) _tmp0_, attribute);
}

/** 
 * returns ns.ns.ns.Class member access
 */
ValaMemberAccess*
gtkaml_ast_markup_tag_get_class_expression (GtkamlAstMarkupTag* self)
{
	GtkamlMarkupNamespace* _tmp0_;
	ValaMemberAccess* _tmp1_;
	ValaMemberAccess* _tmp2_;
	const gchar* _tmp3_;
	ValaSourceReference* _tmp4_;
	ValaMemberAccess* _tmp5_;
	ValaMemberAccess* _tmp6_;
	ValaMemberAccess* result;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_tag_namespace;
	_tmp1_ = gtkaml_ast_markup_tag_namespace_access (self, (ValaUnresolvedSymbol*) _tmp0_);
	_tmp2_ = _tmp1_;
	_tmp3_ = self->priv->_tag_name;
	_tmp4_ = self->priv->_source_reference;
	_tmp5_ = vala_member_access_new ((ValaExpression*) _tmp2_, _tmp3_, _tmp4_);
	_tmp6_ = _tmp5_;
	_vala_code_node_unref0 (_tmp2_);
	result = _tmp6_;
	return result;
}

static ValaMemberAccess*
gtkaml_ast_markup_tag_namespace_access (GtkamlAstMarkupTag* self,
                                        ValaUnresolvedSymbol* ns)
{
	ValaUnresolvedSymbol* _tmp0_;
	ValaUnresolvedSymbol* _tmp1_;
	ValaMemberAccess* _tmp2_;
	ValaMemberAccess* _tmp3_;
	const gchar* _tmp4_;
	const gchar* _tmp5_;
	ValaSourceReference* _tmp6_;
	ValaMemberAccess* _tmp7_;
	ValaMemberAccess* _tmp8_;
	ValaMemberAccess* result;
	g_return_val_if_fail (self != NULL, NULL);
	if (ns == NULL) {
		result = NULL;
		return result;
	}
	_tmp0_ = vala_unresolved_symbol_get_inner (ns);
	_tmp1_ = _tmp0_;
	_tmp2_ = gtkaml_ast_markup_tag_namespace_access (self, _tmp1_);
	_tmp3_ = _tmp2_;
	_tmp4_ = vala_symbol_get_name ((ValaSymbol*) ns);
	_tmp5_ = _tmp4_;
	_tmp6_ = self->priv->_source_reference;
	_tmp7_ = vala_member_access_new ((ValaExpression*) _tmp3_, _tmp5_, _tmp6_);
	_tmp8_ = _tmp7_;
	_vala_code_node_unref0 (_tmp3_);
	result = _tmp8_;
	return result;
}

static gchar*
string_strip (const gchar* self)
{
	gchar* _result_ = NULL;
	gchar* _tmp0_;
	gchar* result;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = g_strdup (self);
	_result_ = _tmp0_;
	g_strstrip (_result_);
	result = _result_;
	return result;
}

static glong
string_strnlen (gchar* str,
                glong maxlen)
{
	gchar* end = NULL;
	gchar* _tmp0_;
	gchar* _tmp1_;
	glong result;
	_tmp0_ = memchr (str, 0, (gsize) maxlen);
	end = _tmp0_;
	_tmp1_ = end;
	if (_tmp1_ == NULL) {
		result = maxlen;
		return result;
	} else {
		gchar* _tmp2_;
		_tmp2_ = end;
		result = (glong) (_tmp2_ - str);
		return result;
	}
}

static gchar*
string_substring (const gchar* self,
                  glong offset,
                  glong len)
{
	glong string_length = 0L;
	gboolean _tmp0_ = FALSE;
	gchar* _tmp3_;
	gchar* result;
	g_return_val_if_fail (self != NULL, NULL);
	if (offset >= ((glong) 0)) {
		_tmp0_ = len >= ((glong) 0);
	} else {
		_tmp0_ = FALSE;
	}
	if (_tmp0_) {
		string_length = string_strnlen ((gchar*) self, offset + len);
	} else {
		gint _tmp1_;
		gint _tmp2_;
		_tmp1_ = strlen (self);
		_tmp2_ = _tmp1_;
		string_length = (glong) _tmp2_;
	}
	if (offset < ((glong) 0)) {
		offset = string_length + offset;
		g_return_val_if_fail (offset >= ((glong) 0), NULL);
	} else {
		g_return_val_if_fail (offset <= string_length, NULL);
	}
	if (len < ((glong) 0)) {
		len = string_length - offset;
	}
	g_return_val_if_fail ((offset + len) <= string_length, NULL);
	_tmp3_ = g_strndup (((gchar*) self) + offset, (gsize) len);
	result = _tmp3_;
	return result;
}

static gchar*
gtkaml_ast_markup_tag_strip_braces (GtkamlAstMarkupTag* self,
                                    const gchar* code)
{
	gchar* stripped_value = NULL;
	gchar* _tmp0_;
	const gchar* _tmp1_;
	gchar* result;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (code != NULL, NULL);
	_tmp0_ = string_strip (code);
	stripped_value = _tmp0_;
	_tmp1_ = stripped_value;
	if (g_str_has_prefix (_tmp1_, "{")) {
		const gchar* _tmp2_;
		_tmp2_ = stripped_value;
		if (g_str_has_suffix (_tmp2_, "}")) {
			const gchar* _tmp3_;
			const gchar* _tmp4_;
			gint _tmp5_;
			gint _tmp6_;
			gchar* _tmp7_;
			_tmp3_ = stripped_value;
			_tmp4_ = stripped_value;
			_tmp5_ = strlen (_tmp4_);
			_tmp6_ = _tmp5_;
			_tmp7_ = string_substring (_tmp3_, (glong) 1, (glong) (_tmp6_ - 2));
			result = _tmp7_;
			_g_free0 (stripped_value);
			return result;
		} else {
			ValaSourceReference* _tmp8_;
			gchar* _tmp9_;
			_tmp8_ = self->priv->_source_reference;
			vala_report_error (_tmp8_, "Unbalanced braces");
			_tmp9_ = g_strdup (code);
			result = _tmp9_;
			_g_free0 (stripped_value);
			return result;
		}
	} else {
		gchar* _tmp10_;
		_tmp10_ = g_strdup (code);
		result = _tmp10_;
		_g_free0 (stripped_value);
		return result;
	}
}

const gchar*
gtkaml_ast_markup_tag_get_text (GtkamlAstMarkupTag* self)
{
	const gchar* result;
	const gchar* _tmp0_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_text;
	result = _tmp0_;
	return result;
}

void
gtkaml_ast_markup_tag_set_text (GtkamlAstMarkupTag* self,
                                const gchar* value)
{
	gchar* old_value;
	g_return_if_fail (self != NULL);
	old_value = gtkaml_ast_markup_tag_get_text (self);
	if (g_strcmp0 (value, old_value) != 0) {
		gchar* _tmp0_;
		_tmp0_ = g_strdup (value);
		_g_free0 (self->priv->_text);
		self->priv->_text = _tmp0_;
		g_object_notify_by_pspec ((GObject *) self, gtkaml_ast_markup_tag_properties[GTKAML_AST_MARKUP_TAG_TEXT_PROPERTY]);
	}
}

const gchar*
gtkaml_ast_markup_tag_get_tag_name (GtkamlAstMarkupTag* self)
{
	const gchar* result;
	const gchar* _tmp0_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_tag_name;
	result = _tmp0_;
	return result;
}

void
gtkaml_ast_markup_tag_set_tag_name (GtkamlAstMarkupTag* self,
                                    const gchar* value)
{
	gchar* old_value;
	g_return_if_fail (self != NULL);
	old_value = gtkaml_ast_markup_tag_get_tag_name (self);
	if (g_strcmp0 (value, old_value) != 0) {
		gchar* _tmp0_;
		_tmp0_ = g_strdup (value);
		_g_free0 (self->priv->_tag_name);
		self->priv->_tag_name = _tmp0_;
		g_object_notify_by_pspec ((GObject *) self, gtkaml_ast_markup_tag_properties[GTKAML_AST_MARKUP_TAG_TAG_NAME_PROPERTY]);
	}
}

GtkamlMarkupNamespace*
gtkaml_ast_markup_tag_get_tag_namespace (GtkamlAstMarkupTag* self)
{
	GtkamlMarkupNamespace* result;
	GtkamlMarkupNamespace* _tmp0_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_tag_namespace;
	result = _tmp0_;
	return result;
}

void
gtkaml_ast_markup_tag_set_tag_namespace (GtkamlAstMarkupTag* self,
                                         GtkamlMarkupNamespace* value)
{
	GtkamlMarkupNamespace* old_value;
	g_return_if_fail (self != NULL);
	old_value = gtkaml_ast_markup_tag_get_tag_namespace (self);
	if (old_value != value) {
		GtkamlMarkupNamespace* _tmp0_;
		_tmp0_ = _vala_code_node_ref0 (value);
		_vala_code_node_unref0 (self->priv->_tag_namespace);
		self->priv->_tag_namespace = _tmp0_;
		g_object_notify_by_pspec ((GObject *) self, gtkaml_ast_markup_tag_properties[GTKAML_AST_MARKUP_TAG_TAG_NAMESPACE_PROPERTY]);
	}
}

GtkamlMarkupClass*
gtkaml_ast_markup_tag_get_markup_class (GtkamlAstMarkupTag* self)
{
	GtkamlMarkupClass* result;
	GtkamlMarkupClass* _tmp0_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_markup_class;
	result = _tmp0_;
	return result;
}

static void
gtkaml_ast_markup_tag_set_markup_class (GtkamlAstMarkupTag* self,
                                        GtkamlMarkupClass* value)
{
	GtkamlMarkupClass* old_value;
	g_return_if_fail (self != NULL);
	old_value = gtkaml_ast_markup_tag_get_markup_class (self);
	if (old_value != value) {
		self->priv->_markup_class = value;
		g_object_notify_by_pspec ((GObject *) self, gtkaml_ast_markup_tag_properties[GTKAML_AST_MARKUP_TAG_MARKUP_CLASS_PROPERTY]);
	}
}

ValaSourceReference*
gtkaml_ast_markup_tag_get_source_reference (GtkamlAstMarkupTag* self)
{
	ValaSourceReference* result;
	ValaSourceReference* _tmp0_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_source_reference;
	result = _tmp0_;
	return result;
}

static gpointer
_vala_source_reference_ref0 (gpointer self)
{
	return self ? vala_source_reference_ref (self) : NULL;
}

void
gtkaml_ast_markup_tag_set_source_reference (GtkamlAstMarkupTag* self,
                                            ValaSourceReference* value)
{
	ValaSourceReference* old_value;
	g_return_if_fail (self != NULL);
	old_value = gtkaml_ast_markup_tag_get_source_reference (self);
	if (old_value != value) {
		ValaSourceReference* _tmp0_;
		_tmp0_ = _vala_source_reference_ref0 (value);
		_vala_source_reference_unref0 (self->priv->_source_reference);
		self->priv->_source_reference = _tmp0_;
		g_object_notify_by_pspec ((GObject *) self, gtkaml_ast_markup_tag_properties[GTKAML_AST_MARKUP_TAG_SOURCE_REFERENCE_PROPERTY]);
	}
}

const gchar*
gtkaml_ast_markup_tag_get_me (GtkamlAstMarkupTag* self)
{
	GtkamlAstMarkupTagClass* _klass_;
	g_return_val_if_fail (self != NULL, NULL);
	_klass_ = GTKAML_AST_MARKUP_TAG_GET_CLASS (self);
	if (_klass_->get_me) {
		return _klass_->get_me (self);
	}
	return NULL;
}

ValaDataType*
gtkaml_ast_markup_tag_get_data_type (GtkamlAstMarkupTag* self)
{
	ValaDataType* result;
	ValaDataType* _tmp0_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_data_type;
	result = _tmp0_;
	return result;
}

void
gtkaml_ast_markup_tag_set_data_type (GtkamlAstMarkupTag* self,
                                     ValaDataType* value)
{
	ValaDataType* old_value;
	g_return_if_fail (self != NULL);
	old_value = gtkaml_ast_markup_tag_get_data_type (self);
	if (old_value != value) {
		ValaDataType* _tmp0_;
		_tmp0_ = _vala_code_node_ref0 (value);
		_vala_code_node_unref0 (self->priv->_data_type);
		self->priv->_data_type = _tmp0_;
		g_object_notify_by_pspec ((GObject *) self, gtkaml_ast_markup_tag_properties[GTKAML_AST_MARKUP_TAG_DATA_TYPE_PROPERTY]);
	}
}

ValaDataType*
gtkaml_ast_markup_tag_get_resolved_type (GtkamlAstMarkupTag* self)
{
	ValaDataType* result;
	GtkamlDataTypeParent* _tmp0_;
	ValaDataType* _tmp1_;
	ValaDataType* _tmp2_;
	GtkamlDataTypeParent* _tmp3_;
	ValaDataType* _tmp4_;
	ValaDataType* _tmp5_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_data_type_parent;
	_tmp1_ = gtkaml_data_type_parent_get_data_type (_tmp0_);
	_tmp2_ = _tmp1_;
	_vala_assert (!G_TYPE_CHECK_INSTANCE_TYPE (_tmp2_, VALA_TYPE_UNRESOLVED_TYPE), "!(_data_type_parent.data_type is UnresolvedType)");
	_tmp3_ = self->priv->_data_type_parent;
	_tmp4_ = gtkaml_data_type_parent_get_data_type (_tmp3_);
	_tmp5_ = _tmp4_;
	result = _tmp5_;
	return result;
}

gboolean
gtkaml_ast_markup_tag_get_is_resolved (GtkamlAstMarkupTag* self)
{
	gboolean result;
	GtkamlDataTypeParent* _tmp0_;
	ValaDataType* _tmp1_;
	ValaDataType* _tmp2_;
	g_return_val_if_fail (self != NULL, FALSE);
	_tmp0_ = self->priv->_data_type_parent;
	_tmp1_ = gtkaml_data_type_parent_get_data_type (_tmp0_);
	_tmp2_ = _tmp1_;
	result = !G_TYPE_CHECK_INSTANCE_TYPE (_tmp2_, VALA_TYPE_UNRESOLVED_TYPE);
	return result;
}

const gchar*
gtkaml_ast_markup_tag_get_full_name (GtkamlAstMarkupTag* self)
{
	const gchar* result;
	ValaTypeSymbol* type_symbol = NULL;
	ValaDataType* _tmp0_;
	ValaDataType* _tmp1_;
	ValaTypeSymbol* _tmp2_;
	ValaTypeSymbol* _tmp3_;
	ValaTypeSymbol* _tmp4_;
	gchar* _tmp5_ = NULL;
	ValaTypeSymbol* _tmp6_;
	gchar* _tmp12_;
	const gchar* _tmp13_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = gtkaml_ast_markup_tag_get_resolved_type (self);
	_tmp1_ = _tmp0_;
	_tmp2_ = vala_data_type_get_type_symbol (_tmp1_);
	_tmp3_ = _tmp2_;
	_tmp4_ = _vala_code_node_ref0 (_tmp3_);
	type_symbol = _tmp4_;
	_tmp6_ = type_symbol;
	if (_tmp6_ != NULL) {
		ValaTypeSymbol* _tmp7_;
		gchar* _tmp8_;
		_tmp7_ = type_symbol;
		_tmp8_ = vala_symbol_get_full_name ((ValaSymbol*) _tmp7_);
		_g_free0 (_tmp5_);
		_tmp5_ = _tmp8_;
	} else {
		ValaDataType* _tmp9_;
		ValaDataType* _tmp10_;
		gchar* _tmp11_;
		_tmp9_ = gtkaml_ast_markup_tag_get_resolved_type (self);
		_tmp10_ = _tmp9_;
		_tmp11_ = vala_data_type_to_qualified_string (_tmp10_, NULL);
		_g_free0 (_tmp5_);
		_tmp5_ = _tmp11_;
	}
	_tmp12_ = g_strdup (_tmp5_);
	_g_free0 (self->priv->_full_name);
	self->priv->_full_name = _tmp12_;
	_tmp13_ = self->priv->_full_name;
	result = _tmp13_;
	_g_free0 (_tmp5_);
	_vala_code_node_unref0 (type_symbol);
	return result;
}

static void
gtkaml_ast_markup_tag_class_init (GtkamlAstMarkupTagClass * klass,
                                  gpointer klass_data)
{
	gtkaml_ast_markup_tag_parent_class = g_type_class_peek_parent (klass);
	g_type_class_adjust_private_offset (klass, &GtkamlAstMarkupTag_private_offset);
	((GtkamlAstMarkupTagClass *) klass)->generate_public_ast = (void (*) (GtkamlAstMarkupTag*, GtkamlCodeParserProvider*)) gtkaml_ast_markup_tag_real_generate_public_ast;
	((GtkamlAstMarkupTagClass *) klass)->resolve = (GtkamlAstMarkupTag* (*) (GtkamlAstMarkupTag*, GtkamlMarkupResolver*)) gtkaml_ast_markup_tag_real_resolve;
	((GtkamlAstMarkupTagClass *) klass)->resolve_attributes = (void (*) (GtkamlAstMarkupTag*, GtkamlMarkupResolver*)) gtkaml_ast_markup_tag_real_resolve_attributes;
	((GtkamlAstMarkupTagClass *) klass)->generate = (void (*) (GtkamlAstMarkupTag*, GtkamlMarkupResolver*)) gtkaml_ast_markup_tag_real_generate;
	((GtkamlAstMarkupTagClass *) klass)->generate_attributes = (void (*) (GtkamlAstMarkupTag*, GtkamlMarkupResolver*)) gtkaml_ast_markup_tag_real_generate_attributes;
	((GtkamlAstMarkupTagClass *) klass)->generate_preconstruct = (void (*) (GtkamlAstMarkupTag*, GtkamlMarkupResolver*)) gtkaml_ast_markup_tag_real_generate_preconstruct;
	((GtkamlAstMarkupTagClass *) klass)->generate_construct = (void (*) (GtkamlAstMarkupTag*, GtkamlMarkupResolver*)) gtkaml_ast_markup_tag_real_generate_construct;
	((GtkamlAstMarkupTagClass *) klass)->resolve_creation_method = (void (*) (GtkamlAstMarkupTag*, GtkamlMarkupResolver*)) gtkaml_ast_markup_tag_real_resolve_creation_method;
	((GtkamlAstMarkupTagClass *) klass)->resolve_creation_method_failed = (void (*) (GtkamlAstMarkupTag*, ValaSourceReference*, const gchar*)) gtkaml_ast_markup_tag_real_resolve_creation_method_failed;
	((GtkamlAstMarkupTagClass *) klass)->get_creation_method_candidates = (ValaList* (*) (GtkamlAstMarkupTag*)) gtkaml_ast_markup_tag_real_get_creation_method_candidates;
	G_OBJECT_CLASS (klass)->get_property = _vala_gtkaml_ast_markup_tag_get_property;
	G_OBJECT_CLASS (klass)->set_property = _vala_gtkaml_ast_markup_tag_set_property;
	G_OBJECT_CLASS (klass)->finalize = gtkaml_ast_markup_tag_finalize;
	/**
	 * not-ignorable text nodes concatenated
	*/
	g_object_class_install_property (G_OBJECT_CLASS (klass), GTKAML_AST_MARKUP_TAG_TEXT_PROPERTY, gtkaml_ast_markup_tag_properties[GTKAML_AST_MARKUP_TAG_TEXT_PROPERTY] = g_param_spec_string ("text", "text", "text", NULL, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE));
	/**
	 * the actual tag encountered
	 */
	g_object_class_install_property (G_OBJECT_CLASS (klass), GTKAML_AST_MARKUP_TAG_TAG_NAME_PROPERTY, gtkaml_ast_markup_tag_properties[GTKAML_AST_MARKUP_TAG_TAG_NAME_PROPERTY] = g_param_spec_string ("tag-name", "tag-name", "tag-name", NULL, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE));
	/**
	 * the Vala namespace
	 */
	g_object_class_install_property (G_OBJECT_CLASS (klass), GTKAML_AST_MARKUP_TAG_TAG_NAMESPACE_PROPERTY, gtkaml_ast_markup_tag_properties[GTKAML_AST_MARKUP_TAG_TAG_NAMESPACE_PROPERTY] = vala_param_spec_code_node ("tag-namespace", "tag-namespace", "tag-namespace", GTKAML_TYPE_MARKUP_NAMESPACE, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE));
	/**
	 * references the Vala class in which this tag was defined
	 */
	g_object_class_install_property (G_OBJECT_CLASS (klass), GTKAML_AST_MARKUP_TAG_MARKUP_CLASS_PROPERTY, gtkaml_ast_markup_tag_properties[GTKAML_AST_MARKUP_TAG_MARKUP_CLASS_PROPERTY] = vala_param_spec_code_node ("markup-class", "markup-class", "markup-class", GTKAML_TYPE_MARKUPCLASS, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), GTKAML_AST_MARKUP_TAG_SOURCE_REFERENCE_PROPERTY, gtkaml_ast_markup_tag_properties[GTKAML_AST_MARKUP_TAG_SOURCE_REFERENCE_PROPERTY] = vala_param_spec_source_reference ("source-reference", "source-reference", "source-reference", VALA_TYPE_SOURCE_REFERENCE, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE));
	/**
	 * the expression to be used (either 'this', or 'property name' or 'temporary variable name') when using the tag
	 */
	g_object_class_install_property (G_OBJECT_CLASS (klass), GTKAML_AST_MARKUP_TAG_ME_PROPERTY, gtkaml_ast_markup_tag_properties[GTKAML_AST_MARKUP_TAG_ME_PROPERTY] = g_param_spec_string ("me", "me", "me", NULL, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE));
	/**
	 * usually an Unresolved data type created from the tag name/namespace
	 */
	g_object_class_install_property (G_OBJECT_CLASS (klass), GTKAML_AST_MARKUP_TAG_DATA_TYPE_PROPERTY, gtkaml_ast_markup_tag_properties[GTKAML_AST_MARKUP_TAG_DATA_TYPE_PROPERTY] = vala_param_spec_code_node ("data-type", "data-type", "data-type", VALA_TYPE_DATA_TYPE, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE));
	/**
	 * the determined data type - see resolve()
	 */
	g_object_class_install_property (G_OBJECT_CLASS (klass), GTKAML_AST_MARKUP_TAG_RESOLVED_TYPE_PROPERTY, gtkaml_ast_markup_tag_properties[GTKAML_AST_MARKUP_TAG_RESOLVED_TYPE_PROPERTY] = vala_param_spec_code_node ("resolved-type", "resolved-type", "resolved-type", VALA_TYPE_DATA_TYPE, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), GTKAML_AST_MARKUP_TAG_IS_RESOLVED_PROPERTY, gtkaml_ast_markup_tag_properties[GTKAML_AST_MARKUP_TAG_IS_RESOLVED_PROPERTY] = g_param_spec_boolean ("is-resolved", "is-resolved", "is-resolved", FALSE, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE));
	/**
	 * shortcut for resolved_type.type_symbol.get_full_name () -> for debugging
	 */
	g_object_class_install_property (G_OBJECT_CLASS (klass), GTKAML_AST_MARKUP_TAG_FULL_NAME_PROPERTY, gtkaml_ast_markup_tag_properties[GTKAML_AST_MARKUP_TAG_FULL_NAME_PROPERTY] = g_param_spec_string ("full-name", "full-name", "full-name", NULL, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE));
}

static void
gtkaml_ast_markup_tag_instance_init (GtkamlAstMarkupTag * self,
                                     gpointer klass)
{
	GEqualFunc _tmp0_;
	ValaArrayList* _tmp1_;
	GEqualFunc _tmp2_;
	ValaArrayList* _tmp3_;
	GEqualFunc _tmp4_;
	ValaArrayList* _tmp5_;
	self->priv = gtkaml_ast_markup_tag_get_instance_private (self);
	_tmp0_ = g_direct_equal;
	_tmp1_ = vala_array_list_new (GTKAML_AST_TYPE_MARKUP_CHILD_TAG, (GBoxedCopyFunc) g_object_ref, (GDestroyNotify) g_object_unref, _tmp0_);
	self->child_tags = (ValaList*) _tmp1_;
	_tmp2_ = g_direct_equal;
	_tmp3_ = vala_array_list_new (GTKAML_AST_TYPE_MARKUP_ATTRIBUTE, (GBoxedCopyFunc) gtkaml_ast_markup_attribute_ref, (GDestroyNotify) gtkaml_ast_markup_attribute_unref, _tmp2_);
	self->markup_attributes = (ValaList*) _tmp3_;
	_tmp4_ = g_direct_equal;
	_tmp5_ = vala_array_list_new (GTKAML_AST_TYPE_MARKUP_ATTRIBUTE, (GBoxedCopyFunc) gtkaml_ast_markup_attribute_ref, (GDestroyNotify) gtkaml_ast_markup_attribute_unref, _tmp4_);
	self->creation_parameters = (ValaList*) _tmp5_;
}

static void
gtkaml_ast_markup_tag_finalize (GObject * obj)
{
	GtkamlAstMarkupTag * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, GTKAML_AST_TYPE_MARKUP_TAG, GtkamlAstMarkupTag);
	_vala_iterable_unref0 (self->child_tags);
	_vala_iterable_unref0 (self->markup_attributes);
	_g_free0 (self->priv->_text);
	_g_free0 (self->priv->_tag_name);
	_vala_code_node_unref0 (self->priv->_tag_namespace);
	_vala_source_reference_unref0 (self->priv->_source_reference);
	_vala_code_node_unref0 (self->priv->_data_type);
	_vala_code_node_unref0 (self->priv->_data_type_parent);
	_g_free0 (self->construct_text);
	_g_free0 (self->preconstruct_text);
	_g_free0 (self->priv->_full_name);
	_vala_iterable_unref0 (self->creation_parameters);
	_vala_code_node_unref0 (self->creation_method);
	G_OBJECT_CLASS (gtkaml_ast_markup_tag_parent_class)->finalize (obj);
}

/**
 * A tag that is a parent of others. Can be the root tag.
 * 
 * You have to implement:
 * 
 *  * generate_public_ast
 *  * (optionally) resolve
 *  * generate
 */
static GType
gtkaml_ast_markup_tag_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (GtkamlAstMarkupTagClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) gtkaml_ast_markup_tag_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (GtkamlAstMarkupTag), 0, (GInstanceInitFunc) gtkaml_ast_markup_tag_instance_init, NULL };
	GType gtkaml_ast_markup_tag_type_id;
	gtkaml_ast_markup_tag_type_id = g_type_register_static (G_TYPE_OBJECT, "GtkamlAstMarkupTag", &g_define_type_info, G_TYPE_FLAG_ABSTRACT);
	GtkamlAstMarkupTag_private_offset = g_type_add_instance_private (gtkaml_ast_markup_tag_type_id, sizeof (GtkamlAstMarkupTagPrivate));
	return gtkaml_ast_markup_tag_type_id;
}

GType
gtkaml_ast_markup_tag_get_type (void)
{
	static volatile gsize gtkaml_ast_markup_tag_type_id__once = 0;
	if (g_once_init_enter (&gtkaml_ast_markup_tag_type_id__once)) {
		GType gtkaml_ast_markup_tag_type_id;
		gtkaml_ast_markup_tag_type_id = gtkaml_ast_markup_tag_get_type_once ();
		g_once_init_leave (&gtkaml_ast_markup_tag_type_id__once, gtkaml_ast_markup_tag_type_id);
	}
	return gtkaml_ast_markup_tag_type_id__once;
}

static void
_vala_gtkaml_ast_markup_tag_get_property (GObject * object,
                                          guint property_id,
                                          GValue * value,
                                          GParamSpec * pspec)
{
	GtkamlAstMarkupTag * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, GTKAML_AST_TYPE_MARKUP_TAG, GtkamlAstMarkupTag);
	switch (property_id) {
		case GTKAML_AST_MARKUP_TAG_TEXT_PROPERTY:
		g_value_set_string (value, gtkaml_ast_markup_tag_get_text (self));
		break;
		case GTKAML_AST_MARKUP_TAG_TAG_NAME_PROPERTY:
		g_value_set_string (value, gtkaml_ast_markup_tag_get_tag_name (self));
		break;
		case GTKAML_AST_MARKUP_TAG_TAG_NAMESPACE_PROPERTY:
		vala_value_set_code_node (value, gtkaml_ast_markup_tag_get_tag_namespace (self));
		break;
		case GTKAML_AST_MARKUP_TAG_MARKUP_CLASS_PROPERTY:
		vala_value_set_code_node (value, gtkaml_ast_markup_tag_get_markup_class (self));
		break;
		case GTKAML_AST_MARKUP_TAG_SOURCE_REFERENCE_PROPERTY:
		vala_value_set_source_reference (value, gtkaml_ast_markup_tag_get_source_reference (self));
		break;
		case GTKAML_AST_MARKUP_TAG_DATA_TYPE_PROPERTY:
		vala_value_set_code_node (value, gtkaml_ast_markup_tag_get_data_type (self));
		break;
		case GTKAML_AST_MARKUP_TAG_RESOLVED_TYPE_PROPERTY:
		vala_value_set_code_node (value, gtkaml_ast_markup_tag_get_resolved_type (self));
		break;
		case GTKAML_AST_MARKUP_TAG_IS_RESOLVED_PROPERTY:
		g_value_set_boolean (value, gtkaml_ast_markup_tag_get_is_resolved (self));
		break;
		case GTKAML_AST_MARKUP_TAG_FULL_NAME_PROPERTY:
		g_value_set_string (value, gtkaml_ast_markup_tag_get_full_name (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}

static void
_vala_gtkaml_ast_markup_tag_set_property (GObject * object,
                                          guint property_id,
                                          const GValue * value,
                                          GParamSpec * pspec)
{
	GtkamlAstMarkupTag * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, GTKAML_AST_TYPE_MARKUP_TAG, GtkamlAstMarkupTag);
	switch (property_id) {
		case GTKAML_AST_MARKUP_TAG_TEXT_PROPERTY:
		gtkaml_ast_markup_tag_set_text (self, g_value_get_string (value));
		break;
		case GTKAML_AST_MARKUP_TAG_TAG_NAME_PROPERTY:
		gtkaml_ast_markup_tag_set_tag_name (self, g_value_get_string (value));
		break;
		case GTKAML_AST_MARKUP_TAG_TAG_NAMESPACE_PROPERTY:
		gtkaml_ast_markup_tag_set_tag_namespace (self, vala_value_get_code_node (value));
		break;
		case GTKAML_AST_MARKUP_TAG_MARKUP_CLASS_PROPERTY:
		gtkaml_ast_markup_tag_set_markup_class (self, vala_value_get_code_node (value));
		break;
		case GTKAML_AST_MARKUP_TAG_SOURCE_REFERENCE_PROPERTY:
		gtkaml_ast_markup_tag_set_source_reference (self, vala_value_get_source_reference (value));
		break;
		case GTKAML_AST_MARKUP_TAG_DATA_TYPE_PROPERTY:
		gtkaml_ast_markup_tag_set_data_type (self, vala_value_get_code_node (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}

