/* gtkamlmarkupchildtag.c generated by valac 0.56.16, the Vala compiler
 * generated from gtkamlmarkupchildtag.vala, do not modify */

/* gtkamlmarkupchildtag.vala
 *
 * Copyright (C) 2011 Vlad Grecescu
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public
 * License along with main.c; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor Boston, MA 02110-1301,  USA
 *
 * Author:
 *        Vlad Grecescu (b100dian@gmail.com)
 */

#include "gtkaml.h"
#include <glib.h>
#include <valagee.h>
#include <glib-object.h>
#include <vala.h>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>

#if !defined(VALA_STRICT_C)
#if !defined(__clang__) && defined(__GNUC__) && (__GNUC__ >= 14)
#pragma GCC diagnostic warning "-Wincompatible-pointer-types"
#elif defined(__clang__) && (__clang_major__ >= 16)
#pragma clang diagnostic ignored "-Wincompatible-function-pointer-types"
#pragma clang diagnostic ignored "-Wincompatible-pointer-types"
#endif
#endif

enum  {
	GTKAML_AST_MARKUP_CHILD_TAG_0_PROPERTY,
	GTKAML_AST_MARKUP_CHILD_TAG_STANDALONE_PROPERTY,
	GTKAML_AST_MARKUP_CHILD_TAG_PARENT_TAG_PROPERTY,
	GTKAML_AST_MARKUP_CHILD_TAG_NUM_PROPERTIES
};
static GParamSpec* gtkaml_ast_markup_child_tag_properties[GTKAML_AST_MARKUP_CHILD_TAG_NUM_PROPERTIES];
#define _vala_iterable_unref0(var) ((var == NULL) ? NULL : (var = (vala_iterable_unref (var), NULL)))
#define _gtkaml_callable_unref0(var) ((var == NULL) ? NULL : (var = (gtkaml_callable_unref (var), NULL)))
#define _gtkaml_ast_markup_attribute_unref0(var) ((var == NULL) ? NULL : (var = (gtkaml_ast_markup_attribute_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
#define _vala_code_node_unref0(var) ((var == NULL) ? NULL : (var = (vala_code_node_unref (var), NULL)))
#define _vala_assert(expr, msg) if G_LIKELY (expr) ; else g_assertion_message_expr (G_LOG_DOMAIN, __FILE__, __LINE__, G_STRFUNC, msg);
#define _vala_return_if_fail(expr, msg) if G_LIKELY (expr) ; else { g_return_if_fail_warning (G_LOG_DOMAIN, G_STRFUNC, msg); return; }
#define _vala_return_val_if_fail(expr, msg, val) if G_LIKELY (expr) ; else { g_return_if_fail_warning (G_LOG_DOMAIN, G_STRFUNC, msg); return val; }
#define _vala_warn_if_fail(expr, msg) if G_LIKELY (expr) ; else g_warn_message (G_LOG_DOMAIN, __FILE__, __LINE__, G_STRFUNC, msg);

struct _GtkamlAstMarkupChildTagPrivate {
	gboolean _standalone;
	GtkamlAstMarkupTag* _parent_tag;
};

static gint GtkamlAstMarkupChildTag_private_offset;
static gpointer gtkaml_ast_markup_child_tag_parent_class = NULL;

static void gtkaml_ast_markup_child_tag_real_resolve_attributes (GtkamlAstMarkupTag* base,
                                                          GtkamlMarkupResolver* resolver);
static void gtkaml_ast_markup_child_tag_real_generate_attributes (GtkamlAstMarkupTag* base,
                                                           GtkamlMarkupResolver* resolver);
static void gtkaml_ast_markup_child_tag_real_generate_construct (GtkamlAstMarkupTag* base,
                                                          GtkamlMarkupResolver* resolver);
static ValaList* gtkaml_ast_markup_child_tag_real_get_creation_method_candidates (GtkamlAstMarkupTag* base);
static void gtkaml_ast_markup_child_tag_finalize (GObject * obj);
static GType gtkaml_ast_markup_child_tag_get_type_once (void);
static void _vala_gtkaml_ast_markup_child_tag_get_property (GObject * object,
                                                     guint property_id,
                                                     GValue * value,
                                                     GParamSpec * pspec);
static void _vala_gtkaml_ast_markup_child_tag_set_property (GObject * object,
                                                     guint property_id,
                                                     const GValue * value,
                                                     GParamSpec * pspec);

static inline gpointer
gtkaml_ast_markup_child_tag_get_instance_private (GtkamlAstMarkupChildTag* self)
{
	return G_STRUCT_MEMBER_P (self, GtkamlAstMarkupChildTag_private_offset);
}

GtkamlAstMarkupChildTag*
gtkaml_ast_markup_child_tag_construct (GType object_type,
                                       GtkamlAstMarkupTag* parent_tag,
                                       const gchar* tag_name,
                                       GtkamlMarkupNamespace* tag_namespace,
                                       ValaSourceReference* source_reference)
{
	GtkamlAstMarkupChildTag * self = NULL;
	GtkamlMarkupClass* _tmp0_;
	GtkamlMarkupClass* _tmp1_;
	g_return_val_if_fail (parent_tag != NULL, NULL);
	g_return_val_if_fail (tag_name != NULL, NULL);
	g_return_val_if_fail (tag_namespace != NULL, NULL);
	_tmp0_ = gtkaml_ast_markup_tag_get_markup_class (parent_tag);
	_tmp1_ = _tmp0_;
	self = (GtkamlAstMarkupChildTag*) gtkaml_ast_markup_tag_construct (object_type, _tmp1_, tag_name, tag_namespace, source_reference);
	gtkaml_ast_markup_child_tag_set_parent_tag (self, parent_tag);
	return self;
}

static void
gtkaml_ast_markup_child_tag_real_resolve_attributes (GtkamlAstMarkupTag* base,
                                                     GtkamlMarkupResolver* resolver)
{
	GtkamlAstMarkupChildTag * self;
	self = (GtkamlAstMarkupChildTag*) base;
	g_return_if_fail (resolver != NULL);
	gtkaml_ast_markup_tag_resolve_creation_method ((GtkamlAstMarkupTag*) self, resolver);
	gtkaml_ast_markup_child_tag_resolve_composition_method (self, resolver);
}

static void
gtkaml_ast_markup_child_tag_real_generate_attributes (GtkamlAstMarkupTag* base,
                                                      GtkamlMarkupResolver* resolver)
{
	GtkamlAstMarkupChildTag * self;
	self = (GtkamlAstMarkupChildTag*) base;
	g_return_if_fail (resolver != NULL);
	{
		ValaList* _attribute_list = NULL;
		ValaList* _tmp0_;
		gint _attribute_size = 0;
		ValaList* _tmp1_;
		gint _tmp2_;
		gint _tmp3_;
		gint _attribute_index = 0;
		_tmp0_ = self->composition_parameters;
		_attribute_list = _tmp0_;
		_tmp1_ = _attribute_list;
		_tmp2_ = vala_collection_get_size ((ValaCollection*) _tmp1_);
		_tmp3_ = _tmp2_;
		_attribute_size = _tmp3_;
		_attribute_index = -1;
		while (TRUE) {
			gint _tmp4_;
			gint _tmp5_;
			GtkamlAstMarkupAttribute* attribute = NULL;
			ValaList* _tmp6_;
			gpointer _tmp7_;
			GtkamlAstMarkupAttribute* _tmp8_;
			_attribute_index = _attribute_index + 1;
			_tmp4_ = _attribute_index;
			_tmp5_ = _attribute_size;
			if (!(_tmp4_ < _tmp5_)) {
				break;
			}
			_tmp6_ = _attribute_list;
			_tmp7_ = vala_list_get (_tmp6_, _attribute_index);
			attribute = (GtkamlAstMarkupAttribute*) _tmp7_;
			_tmp8_ = attribute;
			if (GTKAML_AST_IS_MARKUP_COMPLEX_ATTRIBUTE (_tmp8_)) {
				GtkamlAstMarkupAttribute* _tmp9_;
				GtkamlAstMarkupTag* _tmp10_;
				_tmp9_ = attribute;
				_tmp10_ = G_TYPE_CHECK_INSTANCE_CAST (_tmp9_, GTKAML_AST_TYPE_MARKUP_COMPLEX_ATTRIBUTE, GtkamlAstMarkupComplexAttribute)->value_tag;
				gtkaml_markup_resolver_generate_markup_tag (resolver, _tmp10_);
			}
			_gtkaml_ast_markup_attribute_unref0 (attribute);
		}
	}
	GTKAML_AST_MARKUP_TAG_CLASS (gtkaml_ast_markup_child_tag_parent_class)->generate_attributes (G_TYPE_CHECK_INSTANCE_CAST (self, GTKAML_AST_TYPE_MARKUP_TAG, GtkamlAstMarkupTag), resolver);
}

static void
gtkaml_ast_markup_child_tag_real_generate_construct (GtkamlAstMarkupTag* base,
                                                     GtkamlMarkupResolver* resolver)
{
	GtkamlAstMarkupChildTag * self;
	self = (GtkamlAstMarkupChildTag*) base;
	g_return_if_fail (resolver != NULL);
	GTKAML_AST_MARKUP_TAG_CLASS (gtkaml_ast_markup_child_tag_parent_class)->generate_construct (G_TYPE_CHECK_INSTANCE_CAST (self, GTKAML_AST_TYPE_MARKUP_TAG, GtkamlAstMarkupTag), resolver);
	gtkaml_ast_markup_child_tag_generate_add (self, resolver);
}

/**
 * determines the composition method to use, setting `composition_method` and `composition_parameters`
 */
static gpointer
_vala_code_node_ref0 (gpointer self)
{
	return self ? vala_code_node_ref (self) : NULL;
}

static gpointer
_gtkaml_callable_ref0 (gpointer self)
{
	return self ? gtkaml_callable_ref (self) : NULL;
}

static gpointer
_gtkaml_ast_markup_attribute_ref0 (gpointer self)
{
	return self ? gtkaml_ast_markup_attribute_ref (self) : NULL;
}

static gpointer
_vala_iterable_ref0 (gpointer self)
{
	return self ? vala_iterable_ref (self) : NULL;
}

void
gtkaml_ast_markup_child_tag_resolve_composition_method (GtkamlAstMarkupChildTag* self,
                                                        GtkamlMarkupResolver* resolver)
{
	gboolean _tmp0_;
	ValaTypeSymbol* parent_type_symbol = NULL;
	GtkamlAstMarkupTag* _tmp1_;
	ValaDataType* _tmp2_;
	ValaDataType* _tmp3_;
	ValaTypeSymbol* _tmp4_;
	ValaTypeSymbol* _tmp5_;
	ValaTypeSymbol* _tmp6_;
	ValaTypeSymbol* _tmp7_;
	ValaList* candidates = NULL;
	ValaTypeSymbol* _tmp15_;
	ValaList* _tmp16_;
	ValaList* _tmp39_;
	gint _tmp40_;
	gint _tmp41_;
	gint min = 0;
	GtkamlCallable* min_match_method = NULL;
	ValaList* _tmp51_;
	gpointer _tmp52_;
	gint max = 0;
	GtkamlCallable* max_match_method = NULL;
	ValaList* _tmp53_;
	gpointer _tmp54_;
	GtkamlAstMarkupAttribute* max_self = NULL;
	GtkamlAstMarkupAttribute* _tmp55_;
	ValaList* matched_method_parameters = NULL;
	GEqualFunc _tmp56_;
	ValaArrayList* _tmp57_;
	gint i = 0;
	GtkamlCallable* _tmp147_;
	ValaList* _tmp148_;
	ValaList* _tmp149_;
	gint _tmp150_;
	gint _tmp151_;
	gboolean _tmp152_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (resolver != NULL);
	_tmp0_ = self->priv->_standalone;
	if (_tmp0_) {
		return;
	}
	_tmp1_ = self->priv->_parent_tag;
	_tmp2_ = gtkaml_ast_markup_tag_get_resolved_type (_tmp1_);
	_tmp3_ = _tmp2_;
	_tmp4_ = vala_data_type_get_type_symbol (_tmp3_);
	_tmp5_ = _tmp4_;
	_tmp6_ = _vala_code_node_ref0 (_tmp5_);
	parent_type_symbol = _tmp6_;
	_tmp7_ = parent_type_symbol;
	if (_tmp7_ == NULL) {
		ValaSourceReference* _tmp8_;
		ValaSourceReference* _tmp9_;
		GtkamlAstMarkupTag* _tmp10_;
		const gchar* _tmp11_;
		const gchar* _tmp12_;
		gchar* _tmp13_;
		gchar* _tmp14_;
		_tmp8_ = gtkaml_ast_markup_tag_get_source_reference ((GtkamlAstMarkupTag*) self);
		_tmp9_ = _tmp8_;
		_tmp10_ = self->priv->_parent_tag;
		_tmp11_ = gtkaml_ast_markup_tag_get_tag_name (_tmp10_);
		_tmp12_ = _tmp11_;
		_tmp13_ = g_strdup_printf ("Could not resolve parent type for %s", _tmp12_);
		_tmp14_ = _tmp13_;
		vala_report_error (_tmp9_, "%s", _tmp14_);
		_g_free0 (_tmp14_);
		_vala_code_node_unref0 (parent_type_symbol);
		return;
	}
	_tmp15_ = parent_type_symbol;
	_tmp16_ = gtkaml_markup_resolver_get_composition_method_candidates (resolver, _tmp15_);
	candidates = _tmp16_;
	{
		ValaList* _candidate_list = NULL;
		ValaList* _tmp17_;
		gint _candidate_size = 0;
		ValaList* _tmp18_;
		gint _tmp19_;
		gint _tmp20_;
		gint _candidate_index = 0;
		_tmp17_ = candidates;
		_candidate_list = _tmp17_;
		_tmp18_ = _candidate_list;
		_tmp19_ = vala_collection_get_size ((ValaCollection*) _tmp18_);
		_tmp20_ = _tmp19_;
		_candidate_size = _tmp20_;
		_candidate_index = -1;
		while (TRUE) {
			gint _tmp21_;
			gint _tmp22_;
			GtkamlCallable* candidate = NULL;
			ValaList* _tmp23_;
			gpointer _tmp24_;
			GtkamlAstMarkupAttribute* explicit = NULL;
			GtkamlCallable* _tmp25_;
			const gchar* _tmp26_;
			const gchar* _tmp27_;
			GtkamlAstMarkupAttribute* _tmp28_;
			gboolean _tmp29_ = FALSE;
			GtkamlAstMarkupAttribute* _tmp30_;
			_candidate_index = _candidate_index + 1;
			_tmp21_ = _candidate_index;
			_tmp22_ = _candidate_size;
			if (!(_tmp21_ < _tmp22_)) {
				break;
			}
			_tmp23_ = _candidate_list;
			_tmp24_ = vala_list_get (_tmp23_, _candidate_index);
			candidate = (GtkamlCallable*) _tmp24_;
			_tmp25_ = candidate;
			_tmp26_ = gtkaml_callable_get_name (_tmp25_);
			_tmp27_ = _tmp26_;
			_tmp28_ = gtkaml_ast_markup_tag_get_attribute ((GtkamlAstMarkupTag*) self, _tmp27_);
			explicit = _tmp28_;
			_tmp30_ = explicit;
			if (GTKAML_AST_IS_MARKUP_ATTRIBUTE (_tmp30_)) {
				GtkamlAstMarkupAttribute* _tmp31_;
				const gchar* _tmp32_;
				const gchar* _tmp33_;
				_tmp31_ = explicit;
				_tmp32_ = gtkaml_ast_markup_attribute_get_attribute_value (G_TYPE_CHECK_INSTANCE_CAST (_tmp31_, GTKAML_AST_TYPE_MARKUP_ATTRIBUTE, GtkamlAstMarkupAttribute));
				_tmp33_ = _tmp32_;
				_tmp29_ = g_strcmp0 (_tmp33_, "true") == 0;
			} else {
				_tmp29_ = FALSE;
			}
			if (_tmp29_) {
				GtkamlAstMarkupAttribute* _tmp34_;
				GEqualFunc _tmp35_;
				ValaArrayList* _tmp36_;
				ValaList* _tmp37_;
				GtkamlCallable* _tmp38_;
				_tmp34_ = explicit;
				gtkaml_ast_markup_tag_remove_attribute ((GtkamlAstMarkupTag*) self, _tmp34_);
				_tmp35_ = g_direct_equal;
				_tmp36_ = vala_array_list_new (GTKAML_TYPE_CALLABLE, (GBoxedCopyFunc) gtkaml_callable_ref, (GDestroyNotify) gtkaml_callable_unref, _tmp35_);
				_vala_iterable_unref0 (candidates);
				candidates = (ValaList*) _tmp36_;
				_tmp37_ = candidates;
				_tmp38_ = candidate;
				vala_collection_add ((ValaCollection*) _tmp37_, _tmp38_);
				_gtkaml_ast_markup_attribute_unref0 (explicit);
				_gtkaml_callable_unref0 (candidate);
				break;
			}
			_gtkaml_ast_markup_attribute_unref0 (explicit);
			_gtkaml_callable_unref0 (candidate);
		}
	}
	_tmp39_ = candidates;
	_tmp40_ = vala_collection_get_size ((ValaCollection*) _tmp39_);
	_tmp41_ = _tmp40_;
	if (_tmp41_ == 0) {
		ValaSourceReference* _tmp42_;
		ValaSourceReference* _tmp43_;
		const gchar* _tmp44_;
		const gchar* _tmp45_;
		GtkamlAstMarkupTag* _tmp46_;
		const gchar* _tmp47_;
		const gchar* _tmp48_;
		gchar* _tmp49_;
		gchar* _tmp50_;
		_tmp42_ = gtkaml_ast_markup_tag_get_source_reference ((GtkamlAstMarkupTag*) self);
		_tmp43_ = _tmp42_;
		_tmp44_ = gtkaml_ast_markup_tag_get_full_name ((GtkamlAstMarkupTag*) self);
		_tmp45_ = _tmp44_;
		_tmp46_ = self->priv->_parent_tag;
		_tmp47_ = gtkaml_ast_markup_tag_get_full_name (_tmp46_);
		_tmp48_ = _tmp47_;
		_tmp49_ = g_strdup_printf ("No composition methods found for adding %s to a %s", _tmp45_, _tmp48_);
		_tmp50_ = _tmp49_;
		vala_report_error (_tmp43_, "%s", _tmp50_);
		_g_free0 (_tmp50_);
		_vala_iterable_unref0 (candidates);
		_vala_code_node_unref0 (parent_type_symbol);
		return;
	}
	min = 100;
	_tmp51_ = candidates;
	_tmp52_ = vala_list_get (_tmp51_, 0);
	min_match_method = (GtkamlCallable*) _tmp52_;
	max = -1;
	_tmp53_ = candidates;
	_tmp54_ = vala_list_get (_tmp53_, 0);
	max_match_method = (GtkamlCallable*) _tmp54_;
	_tmp55_ = gtkaml_ast_markup_attribute_new ("not-intialized-warning-was-true", NULL, NULL);
	max_self = _tmp55_;
	_tmp56_ = g_direct_equal;
	_tmp57_ = vala_array_list_new (GTKAML_AST_TYPE_MARKUP_ATTRIBUTE, (GBoxedCopyFunc) gtkaml_ast_markup_attribute_ref, (GDestroyNotify) gtkaml_ast_markup_attribute_unref, _tmp56_);
	matched_method_parameters = (ValaList*) _tmp57_;
	i = 0;
	{
		gboolean _tmp58_ = FALSE;
		_tmp58_ = TRUE;
		while (TRUE) {
			GtkamlCallable* current_candidate = NULL;
			ValaList* _tmp62_;
			gpointer _tmp63_;
			GtkamlAstMarkupAttribute* _self_ = NULL;
			GtkamlCallable* _tmp64_;
			ValaList* _tmp65_;
			ValaList* _tmp66_;
			gint _tmp67_;
			gint _tmp68_;
			gboolean _tmp69_;
			ValaList* parameters = NULL;
			GtkamlCallable* _tmp75_;
			ValaSymbol* _tmp76_;
			ValaSymbol* _tmp77_;
			gchar* _tmp78_;
			gchar* _tmp79_;
			GtkamlCallable* _tmp80_;
			ValaSourceReference* _tmp81_;
			ValaSourceReference* _tmp82_;
			ValaList* _tmp83_;
			ValaList* _tmp84_;
			gint matches = 0;
			ValaList* _tmp85_;
			gpointer _tmp86_;
			GtkamlAstMarkupAttribute* _tmp87_;
			const gchar* _tmp88_;
			const gchar* _tmp89_;
			const gchar* _tmp90_;
			const gchar* _tmp91_;
			gchar* _tmp92_;
			gchar* _tmp93_;
			gchar* _tmp94_;
			gchar* _tmp95_;
			ValaSourceReference* _tmp96_;
			ValaSourceReference* _tmp97_;
			GtkamlAstMarkupAttribute* _tmp98_;
			GtkamlAstMarkupAttribute* _tmp99_;
			ValaList* _tmp119_;
			gint _tmp120_;
			gint _tmp121_;
			gint _tmp145_;
			GtkamlAstMarkupAttribute* _tmp146_;
			if (!_tmp58_) {
				ValaList* _tmp59_;
				gint _tmp60_;
				gint _tmp61_;
				_tmp59_ = candidates;
				_tmp60_ = vala_collection_get_size ((ValaCollection*) _tmp59_);
				_tmp61_ = _tmp60_;
				if (!(i < _tmp61_)) {
					break;
				}
			}
			_tmp58_ = FALSE;
			_tmp62_ = candidates;
			_tmp63_ = vala_list_get (_tmp62_, i);
			current_candidate = (GtkamlCallable*) _tmp63_;
			_tmp64_ = current_candidate;
			_tmp65_ = gtkaml_callable_get_parameters (_tmp64_);
			_tmp66_ = _tmp65_;
			_tmp67_ = vala_collection_get_size ((ValaCollection*) _tmp66_);
			_tmp68_ = _tmp67_;
			_tmp69_ = _tmp68_ == 0;
			_vala_iterable_unref0 (_tmp66_);
			if (_tmp69_) {
				GtkamlCallable* _tmp70_;
				const gchar* _tmp71_;
				const gchar* _tmp72_;
				gchar* _tmp73_;
				gchar* _tmp74_;
				_tmp70_ = current_candidate;
				_tmp71_ = gtkaml_callable_get_name (_tmp70_);
				_tmp72_ = _tmp71_;
				_tmp73_ = g_strdup_printf ("%s composition method has no parameters", _tmp72_);
				_tmp74_ = _tmp73_;
				vala_report_warning (NULL, "%s", _tmp74_);
				_g_free0 (_tmp74_);
				_gtkaml_ast_markup_attribute_unref0 (_self_);
				_gtkaml_callable_unref0 (current_candidate);
				continue;
			}
			_tmp75_ = current_candidate;
			_tmp76_ = gtkaml_callable_get_parent_symbol (_tmp75_);
			_tmp77_ = _tmp76_;
			_tmp78_ = vala_symbol_get_full_name (_tmp77_);
			_tmp79_ = _tmp78_;
			_tmp80_ = current_candidate;
			_tmp81_ = gtkaml_ast_markup_tag_get_source_reference ((GtkamlAstMarkupTag*) self);
			_tmp82_ = _tmp81_;
			_tmp83_ = gtkaml_markup_resolver_get_default_parameters (resolver, _tmp79_, _tmp80_, _tmp82_);
			_tmp84_ = _tmp83_;
			_g_free0 (_tmp79_);
			parameters = _tmp84_;
			matches = 0;
			_tmp85_ = parameters;
			_tmp86_ = vala_list_get (_tmp85_, 0);
			_tmp87_ = (GtkamlAstMarkupAttribute*) _tmp86_;
			_tmp88_ = gtkaml_ast_markup_attribute_get_attribute_name (_tmp87_);
			_tmp89_ = _tmp88_;
			_tmp90_ = gtkaml_ast_markup_tag_get_me ((GtkamlAstMarkupTag*) self);
			_tmp91_ = _tmp90_;
			_tmp92_ = g_strconcat ("{", _tmp91_, NULL);
			_tmp93_ = _tmp92_;
			_tmp94_ = g_strconcat (_tmp93_, "}", NULL);
			_tmp95_ = _tmp94_;
			_tmp96_ = gtkaml_ast_markup_tag_get_source_reference ((GtkamlAstMarkupTag*) self);
			_tmp97_ = _tmp96_;
			_tmp98_ = gtkaml_ast_markup_attribute_new (_tmp89_, _tmp95_, _tmp97_);
			_gtkaml_ast_markup_attribute_unref0 (_self_);
			_self_ = _tmp98_;
			_g_free0 (_tmp95_);
			_g_free0 (_tmp93_);
			_gtkaml_ast_markup_attribute_unref0 (_tmp87_);
			_tmp99_ = _self_;
			gtkaml_ast_markup_tag_add_markup_attribute ((GtkamlAstMarkupTag*) self, _tmp99_);
			{
				ValaList* _parameter_list = NULL;
				ValaList* _tmp100_;
				gint _parameter_size = 0;
				ValaList* _tmp101_;
				gint _tmp102_;
				gint _tmp103_;
				gint _parameter_index = 0;
				_tmp100_ = parameters;
				_parameter_list = _tmp100_;
				_tmp101_ = _parameter_list;
				_tmp102_ = vala_collection_get_size ((ValaCollection*) _tmp101_);
				_tmp103_ = _tmp102_;
				_parameter_size = _tmp103_;
				_parameter_index = -1;
				while (TRUE) {
					gint _tmp104_;
					gint _tmp105_;
					GtkamlAstMarkupAttribute* parameter = NULL;
					ValaList* _tmp106_;
					gpointer _tmp107_;
					gboolean _tmp108_ = FALSE;
					GtkamlAstMarkupAttribute* _tmp109_;
					const gchar* _tmp110_;
					const gchar* _tmp111_;
					GtkamlAstMarkupAttribute* _tmp112_;
					GtkamlAstMarkupAttribute* _tmp113_;
					gboolean _tmp114_;
					_parameter_index = _parameter_index + 1;
					_tmp104_ = _parameter_index;
					_tmp105_ = _parameter_size;
					if (!(_tmp104_ < _tmp105_)) {
						break;
					}
					_tmp106_ = _parameter_list;
					_tmp107_ = vala_list_get (_tmp106_, _parameter_index);
					parameter = (GtkamlAstMarkupAttribute*) _tmp107_;
					_tmp109_ = parameter;
					_tmp110_ = gtkaml_ast_markup_attribute_get_attribute_name (_tmp109_);
					_tmp111_ = _tmp110_;
					_tmp112_ = gtkaml_ast_markup_tag_get_attribute ((GtkamlAstMarkupTag*) self, _tmp111_);
					_tmp113_ = _tmp112_;
					_tmp114_ = NULL != _tmp113_;
					_gtkaml_ast_markup_attribute_unref0 (_tmp113_);
					if (_tmp114_) {
						_tmp108_ = TRUE;
					} else {
						GtkamlAstMarkupAttribute* _tmp115_;
						const gchar* _tmp116_;
						const gchar* _tmp117_;
						_tmp115_ = parameter;
						_tmp116_ = gtkaml_ast_markup_attribute_get_attribute_value (_tmp115_);
						_tmp117_ = _tmp116_;
						_tmp108_ = _tmp117_ != NULL;
					}
					if (_tmp108_) {
						gint _tmp118_;
						_tmp118_ = matches;
						matches = _tmp118_ + 1;
					}
					_gtkaml_ast_markup_attribute_unref0 (parameter);
				}
			}
			_tmp119_ = parameters;
			_tmp120_ = vala_collection_get_size ((ValaCollection*) _tmp119_);
			_tmp121_ = _tmp120_;
			if (matches < _tmp121_) {
				ValaList* _tmp122_;
				gint _tmp123_;
				gint _tmp124_;
				_tmp122_ = parameters;
				_tmp123_ = vala_collection_get_size ((ValaCollection*) _tmp122_);
				_tmp124_ = _tmp123_;
				if (_tmp124_ < min) {
					ValaList* _tmp125_;
					gint _tmp126_;
					gint _tmp127_;
					GtkamlCallable* _tmp128_;
					GtkamlCallable* _tmp129_;
					_tmp125_ = parameters;
					_tmp126_ = vala_collection_get_size ((ValaCollection*) _tmp125_);
					_tmp127_ = _tmp126_;
					min = _tmp127_;
					_tmp128_ = current_candidate;
					_tmp129_ = _gtkaml_callable_ref0 (_tmp128_);
					_gtkaml_callable_unref0 (min_match_method);
					min_match_method = _tmp129_;
				}
			} else {
				ValaList* _tmp130_;
				gint _tmp131_;
				gint _tmp132_;
				ValaList* _tmp133_;
				gint _tmp134_;
				gint _tmp135_;
				_tmp130_ = parameters;
				_tmp131_ = vala_collection_get_size ((ValaCollection*) _tmp130_);
				_tmp132_ = _tmp131_;
				_vala_assert (matches == _tmp132_, "matches == parameters.size");
				_tmp133_ = parameters;
				_tmp134_ = vala_collection_get_size ((ValaCollection*) _tmp133_);
				_tmp135_ = _tmp134_;
				if (_tmp135_ > max) {
					ValaList* _tmp136_;
					gint _tmp137_;
					gint _tmp138_;
					GtkamlAstMarkupAttribute* _tmp139_;
					GtkamlAstMarkupAttribute* _tmp140_;
					GtkamlCallable* _tmp141_;
					GtkamlCallable* _tmp142_;
					ValaList* _tmp143_;
					ValaList* _tmp144_;
					_tmp136_ = parameters;
					_tmp137_ = vala_collection_get_size ((ValaCollection*) _tmp136_);
					_tmp138_ = _tmp137_;
					max = _tmp138_;
					_tmp139_ = _self_;
					_tmp140_ = _gtkaml_ast_markup_attribute_ref0 (_tmp139_);
					_gtkaml_ast_markup_attribute_unref0 (max_self);
					max_self = _tmp140_;
					_tmp141_ = current_candidate;
					_tmp142_ = _gtkaml_callable_ref0 (_tmp141_);
					_gtkaml_callable_unref0 (max_match_method);
					max_match_method = _tmp142_;
					_tmp143_ = parameters;
					_tmp144_ = _vala_iterable_ref0 (_tmp143_);
					_vala_iterable_unref0 (matched_method_parameters);
					matched_method_parameters = _tmp144_;
				}
			}
			_tmp145_ = i;
			i = _tmp145_ + 1;
			_tmp146_ = _self_;
			gtkaml_ast_markup_tag_remove_attribute ((GtkamlAstMarkupTag*) self, _tmp146_);
			_vala_iterable_unref0 (parameters);
			_gtkaml_ast_markup_attribute_unref0 (_self_);
			_gtkaml_callable_unref0 (current_candidate);
		}
	}
	_tmp147_ = max_match_method;
	_tmp148_ = gtkaml_callable_get_parameters (_tmp147_);
	_tmp149_ = _tmp148_;
	_tmp150_ = vala_collection_get_size ((ValaCollection*) _tmp149_);
	_tmp151_ = _tmp150_;
	_tmp152_ = _tmp151_ == max;
	_vala_iterable_unref0 (_tmp149_);
	if (_tmp152_) {
		GtkamlCallable* _tmp153_;
		GtkamlCallable* _tmp154_;
		GtkamlAstMarkupAttribute* _tmp155_;
		_tmp153_ = max_match_method;
		_tmp154_ = _gtkaml_callable_ref0 (_tmp153_);
		_gtkaml_callable_unref0 (self->composition_method);
		self->composition_method = _tmp154_;
		_tmp155_ = max_self;
		gtkaml_ast_markup_tag_add_markup_attribute ((GtkamlAstMarkupTag*) self, _tmp155_);
		{
			ValaList* _parameter_list = NULL;
			ValaList* _tmp156_;
			gint _parameter_size = 0;
			ValaList* _tmp157_;
			gint _tmp158_;
			gint _tmp159_;
			gint _parameter_index = 0;
			_tmp156_ = matched_method_parameters;
			_parameter_list = _tmp156_;
			_tmp157_ = _parameter_list;
			_tmp158_ = vala_collection_get_size ((ValaCollection*) _tmp157_);
			_tmp159_ = _tmp158_;
			_parameter_size = _tmp159_;
			_parameter_index = -1;
			while (TRUE) {
				gint _tmp160_;
				gint _tmp161_;
				GtkamlAstMarkupAttribute* parameter = NULL;
				ValaList* _tmp162_;
				gpointer _tmp163_;
				GtkamlAstMarkupAttribute* explicit_attribute = NULL;
				GtkamlAstMarkupAttribute* _tmp164_;
				const gchar* _tmp165_;
				const gchar* _tmp166_;
				GtkamlAstMarkupAttribute* _tmp167_;
				GtkamlAstMarkupAttribute* _tmp168_;
				_parameter_index = _parameter_index + 1;
				_tmp160_ = _parameter_index;
				_tmp161_ = _parameter_size;
				if (!(_tmp160_ < _tmp161_)) {
					break;
				}
				_tmp162_ = _parameter_list;
				_tmp163_ = vala_list_get (_tmp162_, _parameter_index);
				parameter = (GtkamlAstMarkupAttribute*) _tmp163_;
				explicit_attribute = NULL;
				_tmp164_ = parameter;
				_tmp165_ = gtkaml_ast_markup_attribute_get_attribute_name (_tmp164_);
				_tmp166_ = _tmp165_;
				_tmp167_ = gtkaml_ast_markup_tag_get_attribute ((GtkamlAstMarkupTag*) self, _tmp166_);
				_gtkaml_ast_markup_attribute_unref0 (explicit_attribute);
				explicit_attribute = _tmp167_;
				_tmp168_ = explicit_attribute;
				if (NULL != _tmp168_) {
					GtkamlAstMarkupAttribute* _tmp169_;
					GtkamlAstMarkupAttribute* _tmp170_;
					ValaDataType* _tmp171_;
					ValaDataType* _tmp172_;
					ValaList* _tmp173_;
					GtkamlAstMarkupAttribute* _tmp174_;
					GtkamlAstMarkupAttribute* _tmp175_;
					_tmp169_ = explicit_attribute;
					_tmp170_ = parameter;
					_tmp171_ = gtkaml_ast_markup_attribute_get_target_type (_tmp170_);
					_tmp172_ = _tmp171_;
					gtkaml_ast_markup_attribute_set_target_type (_tmp169_, _tmp172_);
					_tmp173_ = self->composition_parameters;
					_tmp174_ = explicit_attribute;
					vala_collection_add ((ValaCollection*) _tmp173_, _tmp174_);
					_tmp175_ = explicit_attribute;
					gtkaml_ast_markup_tag_remove_attribute ((GtkamlAstMarkupTag*) self, _tmp175_);
				} else {
					ValaList* _tmp176_;
					GtkamlAstMarkupAttribute* _tmp177_;
					_tmp176_ = self->composition_parameters;
					_tmp177_ = parameter;
					vala_collection_add ((ValaCollection*) _tmp176_, _tmp177_);
				}
				_gtkaml_ast_markup_attribute_unref0 (explicit_attribute);
				_gtkaml_ast_markup_attribute_unref0 (parameter);
			}
		}
	} else {
		gchar* required = NULL;
		gchar* _tmp178_;
		ValaList* parameters = NULL;
		GtkamlCallable* _tmp179_;
		ValaList* _tmp180_;
		const gchar* _tmp197_;
		ValaList* _tmp198_;
		gpointer _tmp199_;
		ValaParameter* _tmp200_;
		const gchar* _tmp201_;
		const gchar* _tmp202_;
		gchar* _tmp203_;
		gchar* _tmp204_;
		gchar* _tmp205_;
		gchar* _tmp206_;
		gchar* _tmp207_;
		ValaSourceReference* _tmp208_;
		ValaSourceReference* _tmp209_;
		const gchar* _tmp210_;
		const gchar* _tmp211_;
		const gchar* _tmp212_;
		GtkamlAstMarkupTag* _tmp213_;
		const gchar* _tmp214_;
		const gchar* _tmp215_;
		GtkamlCallable* _tmp216_;
		const gchar* _tmp217_;
		const gchar* _tmp218_;
		gchar* _tmp219_;
		gchar* _tmp220_;
		_tmp178_ = g_strdup ("");
		required = _tmp178_;
		_tmp179_ = min_match_method;
		_tmp180_ = gtkaml_callable_get_parameters (_tmp179_);
		parameters = _tmp180_;
		i = 0;
		{
			gboolean _tmp181_ = FALSE;
			_tmp181_ = TRUE;
			while (TRUE) {
				ValaList* _tmp183_;
				gint _tmp184_;
				gint _tmp185_;
				const gchar* _tmp186_;
				ValaList* _tmp187_;
				gpointer _tmp188_;
				ValaParameter* _tmp189_;
				const gchar* _tmp190_;
				const gchar* _tmp191_;
				gchar* _tmp192_;
				gchar* _tmp193_;
				gchar* _tmp194_;
				gchar* _tmp195_;
				gchar* _tmp196_;
				if (!_tmp181_) {
					gint _tmp182_;
					_tmp182_ = i;
					i = _tmp182_ + 1;
				}
				_tmp181_ = FALSE;
				_tmp183_ = parameters;
				_tmp184_ = vala_collection_get_size ((ValaCollection*) _tmp183_);
				_tmp185_ = _tmp184_;
				if (!(i < (_tmp185_ - 1))) {
					break;
				}
				_tmp186_ = required;
				_tmp187_ = parameters;
				_tmp188_ = vala_list_get (_tmp187_, i);
				_tmp189_ = (ValaParameter*) _tmp188_;
				_tmp190_ = vala_symbol_get_name ((ValaSymbol*) _tmp189_);
				_tmp191_ = _tmp190_;
				_tmp192_ = g_strconcat ("'", _tmp191_, NULL);
				_tmp193_ = _tmp192_;
				_tmp194_ = g_strconcat (_tmp193_, "',", NULL);
				_tmp195_ = _tmp194_;
				_tmp196_ = g_strconcat (_tmp186_, _tmp195_, NULL);
				_g_free0 (required);
				required = _tmp196_;
				_g_free0 (_tmp195_);
				_g_free0 (_tmp193_);
				_vala_code_node_unref0 (_tmp189_);
			}
		}
		_tmp197_ = required;
		_tmp198_ = parameters;
		_tmp199_ = vala_list_get (_tmp198_, i);
		_tmp200_ = (ValaParameter*) _tmp199_;
		_tmp201_ = vala_symbol_get_name ((ValaSymbol*) _tmp200_);
		_tmp202_ = _tmp201_;
		_tmp203_ = g_strconcat ("'", _tmp202_, NULL);
		_tmp204_ = _tmp203_;
		_tmp205_ = g_strconcat (_tmp204_, "'", NULL);
		_tmp206_ = _tmp205_;
		_tmp207_ = g_strconcat (_tmp197_, _tmp206_, NULL);
		_g_free0 (required);
		required = _tmp207_;
		_g_free0 (_tmp206_);
		_g_free0 (_tmp204_);
		_vala_code_node_unref0 (_tmp200_);
		_tmp208_ = gtkaml_ast_markup_tag_get_source_reference ((GtkamlAstMarkupTag*) self);
		_tmp209_ = _tmp208_;
		_tmp210_ = required;
		_tmp211_ = gtkaml_ast_markup_tag_get_full_name ((GtkamlAstMarkupTag*) self);
		_tmp212_ = _tmp211_;
		_tmp213_ = self->priv->_parent_tag;
		_tmp214_ = gtkaml_ast_markup_tag_get_full_name (_tmp213_);
		_tmp215_ = _tmp214_;
		_tmp216_ = min_match_method;
		_tmp217_ = gtkaml_callable_get_name (_tmp216_);
		_tmp218_ = _tmp217_;
		_tmp219_ = g_strdup_printf ("at least %s required for composing %s into %s using %s () .", _tmp210_, _tmp212_, _tmp215_, _tmp218_);
		_tmp220_ = _tmp219_;
		vala_report_error (_tmp209_, "%s", _tmp220_);
		_g_free0 (_tmp220_);
		_vala_iterable_unref0 (parameters);
		_g_free0 (required);
	}
	_vala_iterable_unref0 (matched_method_parameters);
	_gtkaml_ast_markup_attribute_unref0 (max_self);
	_gtkaml_callable_unref0 (max_match_method);
	_gtkaml_callable_unref0 (min_match_method);
	_vala_iterable_unref0 (candidates);
	_vala_code_node_unref0 (parent_type_symbol);
}

/**
 * returns the list of possible creation methods, containing a single element if explicitly requested with `creationmethod='true'`
 */
static ValaList*
gtkaml_ast_markup_child_tag_real_get_creation_method_candidates (GtkamlAstMarkupTag* base)
{
	GtkamlAstMarkupChildTag * self;
	ValaList* candidates = NULL;
	ValaList* _tmp0_;
	ValaList* result;
	self = (GtkamlAstMarkupChildTag*) base;
	_tmp0_ = GTKAML_AST_MARKUP_TAG_CLASS (gtkaml_ast_markup_child_tag_parent_class)->get_creation_method_candidates (G_TYPE_CHECK_INSTANCE_CAST (self, GTKAML_AST_TYPE_MARKUP_TAG, GtkamlAstMarkupTag));
	candidates = _tmp0_;
	{
		ValaList* _candidate_list = NULL;
		ValaList* _tmp1_;
		gint _candidate_size = 0;
		ValaList* _tmp2_;
		gint _tmp3_;
		gint _tmp4_;
		gint _candidate_index = 0;
		_tmp1_ = candidates;
		_candidate_list = _tmp1_;
		_tmp2_ = _candidate_list;
		_tmp3_ = vala_collection_get_size ((ValaCollection*) _tmp2_);
		_tmp4_ = _tmp3_;
		_candidate_size = _tmp4_;
		_candidate_index = -1;
		while (TRUE) {
			gint _tmp5_;
			gint _tmp6_;
			ValaCreationMethod* candidate = NULL;
			ValaList* _tmp7_;
			gpointer _tmp8_;
			GtkamlAstMarkupAttribute* explicit = NULL;
			ValaCreationMethod* _tmp9_;
			const gchar* _tmp10_;
			const gchar* _tmp11_;
			GtkamlAstMarkupAttribute* _tmp12_;
			gboolean _tmp13_ = FALSE;
			GtkamlAstMarkupAttribute* _tmp14_;
			_candidate_index = _candidate_index + 1;
			_tmp5_ = _candidate_index;
			_tmp6_ = _candidate_size;
			if (!(_tmp5_ < _tmp6_)) {
				break;
			}
			_tmp7_ = _candidate_list;
			_tmp8_ = vala_list_get (_tmp7_, _candidate_index);
			candidate = (ValaCreationMethod*) _tmp8_;
			_tmp9_ = candidate;
			_tmp10_ = vala_symbol_get_name ((ValaSymbol*) _tmp9_);
			_tmp11_ = _tmp10_;
			_tmp12_ = gtkaml_ast_markup_tag_get_attribute ((GtkamlAstMarkupTag*) self, _tmp11_);
			explicit = _tmp12_;
			_tmp14_ = explicit;
			if (GTKAML_AST_IS_MARKUP_ATTRIBUTE (_tmp14_)) {
				GtkamlAstMarkupAttribute* _tmp15_;
				const gchar* _tmp16_;
				const gchar* _tmp17_;
				_tmp15_ = explicit;
				_tmp16_ = gtkaml_ast_markup_attribute_get_attribute_value (G_TYPE_CHECK_INSTANCE_CAST (_tmp15_, GTKAML_AST_TYPE_MARKUP_ATTRIBUTE, GtkamlAstMarkupAttribute));
				_tmp17_ = _tmp16_;
				_tmp13_ = g_strcmp0 (_tmp17_, "true") == 0;
			} else {
				_tmp13_ = FALSE;
			}
			if (_tmp13_) {
				GtkamlAstMarkupAttribute* _tmp18_;
				GEqualFunc _tmp19_;
				ValaArrayList* _tmp20_;
				ValaList* _tmp21_;
				ValaCreationMethod* _tmp22_;
				_tmp18_ = explicit;
				gtkaml_ast_markup_tag_remove_attribute ((GtkamlAstMarkupTag*) self, _tmp18_);
				_tmp19_ = g_direct_equal;
				_tmp20_ = vala_array_list_new (VALA_TYPE_CREATION_METHOD, (GBoxedCopyFunc) vala_code_node_ref, (GDestroyNotify) vala_code_node_unref, _tmp19_);
				_vala_iterable_unref0 (candidates);
				candidates = (ValaList*) _tmp20_;
				_tmp21_ = candidates;
				_tmp22_ = candidate;
				vala_collection_add ((ValaCollection*) _tmp21_, _tmp22_);
				_gtkaml_ast_markup_attribute_unref0 (explicit);
				_vala_code_node_unref0 (candidate);
				break;
			}
			_gtkaml_ast_markup_attribute_unref0 (explicit);
			_vala_code_node_unref0 (candidate);
		}
	}
	result = candidates;
	return result;
}

/**
 * creates the rvalue for the initializer expression
 */
ValaObjectCreationExpression*
gtkaml_ast_markup_child_tag_get_initializer (GtkamlAstMarkupChildTag* self,
                                             GtkamlMarkupResolver* resolver)
{
	gboolean is_struct = FALSE;
	ValaDataType* _tmp0_;
	ValaDataType* _tmp1_;
	ValaMemberAccess* creation_method_access = NULL;
	ValaMemberAccess* _tmp8_;
	gboolean _tmp9_ = FALSE;
	ValaObjectCreationExpression* initializer = NULL;
	ValaMemberAccess* _tmp20_;
	ValaSourceReference* _tmp21_;
	ValaSourceReference* _tmp22_;
	ValaObjectCreationExpression* _tmp23_;
	ValaObjectCreationExpression* _tmp24_;
	ValaDataType* variable_type = NULL;
	ValaDataType* _tmp37_;
	ValaDataType* _tmp38_;
	ValaDataType* _tmp39_;
	ValaObjectCreationExpression* _tmp40_;
	ValaObjectCreationExpression* result;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (resolver != NULL, NULL);
	_tmp0_ = gtkaml_ast_markup_tag_get_resolved_type ((GtkamlAstMarkupTag*) self);
	_tmp1_ = _tmp0_;
	is_struct = G_TYPE_CHECK_INSTANCE_TYPE (_tmp1_, VALA_TYPE_STRUCT_VALUE_TYPE);
	if (is_struct) {
		FILE* _tmp2_;
		const gchar* _tmp3_;
		const gchar* _tmp4_;
		ValaCreationMethod* _tmp5_;
		const gchar* _tmp6_;
		const gchar* _tmp7_;
		_tmp2_ = stderr;
		_tmp3_ = gtkaml_ast_markup_tag_get_me ((GtkamlAstMarkupTag*) self);
		_tmp4_ = _tmp3_;
		_tmp5_ = ((GtkamlAstMarkupTag*) self)->creation_method;
		_tmp6_ = vala_symbol_get_name ((ValaSymbol*) _tmp5_);
		_tmp7_ = _tmp6_;
		fprintf (_tmp2_, "This is struct %s and is created with %s\n", _tmp4_, _tmp7_);
	}
	_tmp8_ = gtkaml_ast_markup_tag_get_class_expression ((GtkamlAstMarkupTag*) self);
	creation_method_access = _tmp8_;
	if (!is_struct) {
		_tmp9_ = TRUE;
	} else {
		ValaCreationMethod* _tmp10_;
		const gchar* _tmp11_;
		const gchar* _tmp12_;
		_tmp10_ = ((GtkamlAstMarkupTag*) self)->creation_method;
		_tmp11_ = vala_symbol_get_name ((ValaSymbol*) _tmp10_);
		_tmp12_ = _tmp11_;
		_tmp9_ = g_strcmp0 (_tmp12_, ".new") != 0;
	}
	if (_tmp9_) {
		ValaMemberAccess* _tmp13_;
		ValaCreationMethod* _tmp14_;
		const gchar* _tmp15_;
		const gchar* _tmp16_;
		ValaSourceReference* _tmp17_;
		ValaSourceReference* _tmp18_;
		ValaMemberAccess* _tmp19_;
		_tmp13_ = creation_method_access;
		_tmp14_ = ((GtkamlAstMarkupTag*) self)->creation_method;
		_tmp15_ = vala_symbol_get_name ((ValaSymbol*) _tmp14_);
		_tmp16_ = _tmp15_;
		_tmp17_ = gtkaml_ast_markup_tag_get_source_reference ((GtkamlAstMarkupTag*) self);
		_tmp18_ = _tmp17_;
		_tmp19_ = vala_member_access_new ((ValaExpression*) _tmp13_, _tmp16_, _tmp18_);
		_vala_code_node_unref0 (creation_method_access);
		creation_method_access = _tmp19_;
	}
	_tmp20_ = creation_method_access;
	_tmp21_ = gtkaml_ast_markup_tag_get_source_reference ((GtkamlAstMarkupTag*) self);
	_tmp22_ = _tmp21_;
	_tmp23_ = vala_object_creation_expression_new (_tmp20_, _tmp22_);
	initializer = _tmp23_;
	_tmp24_ = initializer;
	vala_object_creation_expression_set_struct_creation (_tmp24_, is_struct);
	{
		ValaList* _parameter_list = NULL;
		ValaList* _tmp25_;
		gint _parameter_size = 0;
		ValaList* _tmp26_;
		gint _tmp27_;
		gint _tmp28_;
		gint _parameter_index = 0;
		_tmp25_ = ((GtkamlAstMarkupTag*) self)->creation_parameters;
		_parameter_list = _tmp25_;
		_tmp26_ = _parameter_list;
		_tmp27_ = vala_collection_get_size ((ValaCollection*) _tmp26_);
		_tmp28_ = _tmp27_;
		_parameter_size = _tmp28_;
		_parameter_index = -1;
		while (TRUE) {
			gint _tmp29_;
			gint _tmp30_;
			GtkamlAstMarkupAttribute* parameter = NULL;
			ValaList* _tmp31_;
			gpointer _tmp32_;
			ValaObjectCreationExpression* _tmp33_;
			GtkamlAstMarkupAttribute* _tmp34_;
			ValaExpression* _tmp35_;
			ValaExpression* _tmp36_;
			_parameter_index = _parameter_index + 1;
			_tmp29_ = _parameter_index;
			_tmp30_ = _parameter_size;
			if (!(_tmp29_ < _tmp30_)) {
				break;
			}
			_tmp31_ = _parameter_list;
			_tmp32_ = vala_list_get (_tmp31_, _parameter_index);
			parameter = (GtkamlAstMarkupAttribute*) _tmp32_;
			_tmp33_ = initializer;
			_tmp34_ = parameter;
			_tmp35_ = gtkaml_ast_markup_attribute_get_expression (_tmp34_, resolver, (GtkamlAstMarkupTag*) self);
			_tmp36_ = _tmp35_;
			vala_callable_expression_add_argument ((ValaCallableExpression*) _tmp33_, _tmp36_);
			_vala_code_node_unref0 (_tmp36_);
			_gtkaml_ast_markup_attribute_unref0 (parameter);
		}
	}
	_tmp37_ = gtkaml_ast_markup_tag_get_resolved_type ((GtkamlAstMarkupTag*) self);
	_tmp38_ = _tmp37_;
	_tmp39_ = vala_data_type_copy (_tmp38_);
	variable_type = _tmp39_;
	vala_data_type_set_value_owned (variable_type, TRUE);
	vala_data_type_set_nullable (variable_type, FALSE);
	vala_data_type_set_is_dynamic (variable_type, FALSE);
	_tmp40_ = initializer;
	vala_expression_set_target_type ((ValaExpression*) _tmp40_, variable_type);
	result = initializer;
	_vala_code_node_unref0 (variable_type);
	_vala_code_node_unref0 (creation_method_access);
	return result;
}

/**
 * generates the composition method call, unless standalone
 */
void
gtkaml_ast_markup_child_tag_generate_add (GtkamlAstMarkupChildTag* self,
                                          GtkamlMarkupResolver* resolver)
{
	gboolean _tmp0_;
	ValaMemberAccess* parent_member = NULL;
	GtkamlAstMarkupTag* _tmp1_;
	const gchar* _tmp2_;
	const gchar* _tmp3_;
	GtkamlAstMarkupTag* _tmp4_;
	ValaSourceReference* _tmp5_;
	ValaSourceReference* _tmp6_;
	ValaMemberAccess* _tmp7_;
	ValaMethodCall* method_call = NULL;
	ValaMemberAccess* _tmp8_;
	GtkamlCallable* _tmp9_;
	const gchar* _tmp10_;
	const gchar* _tmp11_;
	ValaSourceReference* _tmp12_;
	ValaSourceReference* _tmp13_;
	ValaMemberAccess* _tmp14_;
	ValaMemberAccess* _tmp15_;
	ValaMethodCall* _tmp16_;
	ValaMethodCall* _tmp17_;
	GtkamlMarkupClass* _tmp30_;
	GtkamlMarkupClass* _tmp31_;
	ValaConstructor* _tmp32_;
	ValaConstructor* _tmp33_;
	ValaBlock* _tmp34_;
	ValaBlock* _tmp35_;
	ValaMethodCall* _tmp36_;
	ValaSourceReference* _tmp37_;
	ValaSourceReference* _tmp38_;
	ValaExpressionStatement* _tmp39_;
	ValaExpressionStatement* _tmp40_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (resolver != NULL);
	_tmp0_ = self->priv->_standalone;
	if (_tmp0_) {
		return;
	}
	_tmp1_ = self->priv->_parent_tag;
	_tmp2_ = gtkaml_ast_markup_tag_get_me (_tmp1_);
	_tmp3_ = _tmp2_;
	_tmp4_ = self->priv->_parent_tag;
	_tmp5_ = gtkaml_ast_markup_tag_get_source_reference (_tmp4_);
	_tmp6_ = _tmp5_;
	_tmp7_ = vala_member_access_new_simple (_tmp3_, _tmp6_);
	parent_member = _tmp7_;
	_tmp8_ = parent_member;
	_tmp9_ = self->composition_method;
	_tmp10_ = gtkaml_callable_get_name (_tmp9_);
	_tmp11_ = _tmp10_;
	_tmp12_ = gtkaml_ast_markup_tag_get_source_reference ((GtkamlAstMarkupTag*) self);
	_tmp13_ = _tmp12_;
	_tmp14_ = vala_member_access_new ((ValaExpression*) _tmp8_, _tmp11_, _tmp13_);
	_tmp15_ = _tmp14_;
	_tmp16_ = vala_method_call_new ((ValaExpression*) _tmp15_, NULL);
	_tmp17_ = _tmp16_;
	_vala_code_node_unref0 (_tmp15_);
	method_call = _tmp17_;
	{
		ValaList* _attr_list = NULL;
		ValaList* _tmp18_;
		gint _attr_size = 0;
		ValaList* _tmp19_;
		gint _tmp20_;
		gint _tmp21_;
		gint _attr_index = 0;
		_tmp18_ = self->composition_parameters;
		_attr_list = _tmp18_;
		_tmp19_ = _attr_list;
		_tmp20_ = vala_collection_get_size ((ValaCollection*) _tmp19_);
		_tmp21_ = _tmp20_;
		_attr_size = _tmp21_;
		_attr_index = -1;
		while (TRUE) {
			gint _tmp22_;
			gint _tmp23_;
			GtkamlAstMarkupAttribute* attr = NULL;
			ValaList* _tmp24_;
			gpointer _tmp25_;
			ValaMethodCall* _tmp26_;
			GtkamlAstMarkupAttribute* _tmp27_;
			ValaExpression* _tmp28_;
			ValaExpression* _tmp29_;
			_attr_index = _attr_index + 1;
			_tmp22_ = _attr_index;
			_tmp23_ = _attr_size;
			if (!(_tmp22_ < _tmp23_)) {
				break;
			}
			_tmp24_ = _attr_list;
			_tmp25_ = vala_list_get (_tmp24_, _attr_index);
			attr = (GtkamlAstMarkupAttribute*) _tmp25_;
			_tmp26_ = method_call;
			_tmp27_ = attr;
			_tmp28_ = gtkaml_ast_markup_attribute_get_expression (_tmp27_, resolver, (GtkamlAstMarkupTag*) self);
			_tmp29_ = _tmp28_;
			vala_callable_expression_add_argument ((ValaCallableExpression*) _tmp26_, _tmp29_);
			_vala_code_node_unref0 (_tmp29_);
			_gtkaml_ast_markup_attribute_unref0 (attr);
		}
	}
	_tmp30_ = gtkaml_ast_markup_tag_get_markup_class ((GtkamlAstMarkupTag*) self);
	_tmp31_ = _tmp30_;
	_tmp32_ = vala_class_get_constructor ((ValaClass*) _tmp31_);
	_tmp33_ = _tmp32_;
	_tmp34_ = vala_subroutine_get_body ((ValaSubroutine*) _tmp33_);
	_tmp35_ = _tmp34_;
	_tmp36_ = method_call;
	_tmp37_ = gtkaml_ast_markup_tag_get_source_reference ((GtkamlAstMarkupTag*) self);
	_tmp38_ = _tmp37_;
	_tmp39_ = vala_expression_statement_new ((ValaExpression*) _tmp36_, _tmp38_);
	_tmp40_ = _tmp39_;
	vala_block_add_statement (_tmp35_, (ValaStatement*) _tmp40_);
	_vala_code_node_unref0 (_tmp40_);
	_vala_code_node_unref0 (method_call);
	_vala_code_node_unref0 (parent_member);
}

gboolean
gtkaml_ast_markup_child_tag_get_standalone (GtkamlAstMarkupChildTag* self)
{
	gboolean result;
	g_return_val_if_fail (self != NULL, FALSE);
	result = self->priv->_standalone;
	return result;
}

void
gtkaml_ast_markup_child_tag_set_standalone (GtkamlAstMarkupChildTag* self,
                                            gboolean value)
{
	gboolean old_value;
	g_return_if_fail (self != NULL);
	old_value = gtkaml_ast_markup_child_tag_get_standalone (self);
	if (old_value != value) {
		self->priv->_standalone = value;
		g_object_notify_by_pspec ((GObject *) self, gtkaml_ast_markup_child_tag_properties[GTKAML_AST_MARKUP_CHILD_TAG_STANDALONE_PROPERTY]);
	}
}

GtkamlAstMarkupTag*
gtkaml_ast_markup_child_tag_get_parent_tag (GtkamlAstMarkupChildTag* self)
{
	GtkamlAstMarkupTag* result;
	GtkamlAstMarkupTag* _tmp0_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_parent_tag;
	result = _tmp0_;
	return result;
}

void
gtkaml_ast_markup_child_tag_set_parent_tag (GtkamlAstMarkupChildTag* self,
                                            GtkamlAstMarkupTag* value)
{
	GtkamlAstMarkupTag* old_value;
	g_return_if_fail (self != NULL);
	old_value = gtkaml_ast_markup_child_tag_get_parent_tag (self);
	if (old_value != value) {
		self->priv->_parent_tag = value;
		g_object_notify_by_pspec ((GObject *) self, gtkaml_ast_markup_child_tag_properties[GTKAML_AST_MARKUP_CHILD_TAG_PARENT_TAG_PROPERTY]);
	}
}

static void
gtkaml_ast_markup_child_tag_class_init (GtkamlAstMarkupChildTagClass * klass,
                                        gpointer klass_data)
{
	gtkaml_ast_markup_child_tag_parent_class = g_type_class_peek_parent (klass);
	g_type_class_adjust_private_offset (klass, &GtkamlAstMarkupChildTag_private_offset);
	((GtkamlAstMarkupTagClass *) klass)->resolve_attributes = (void (*) (GtkamlAstMarkupTag*, GtkamlMarkupResolver*)) gtkaml_ast_markup_child_tag_real_resolve_attributes;
	((GtkamlAstMarkupTagClass *) klass)->generate_attributes = (void (*) (GtkamlAstMarkupTag*, GtkamlMarkupResolver*)) gtkaml_ast_markup_child_tag_real_generate_attributes;
	((GtkamlAstMarkupTagClass *) klass)->generate_construct = (void (*) (GtkamlAstMarkupTag*, GtkamlMarkupResolver*)) gtkaml_ast_markup_child_tag_real_generate_construct;
	((GtkamlAstMarkupTagClass *) klass)->get_creation_method_candidates = (ValaList* (*) (GtkamlAstMarkupTag*)) gtkaml_ast_markup_child_tag_real_get_creation_method_candidates;
	G_OBJECT_CLASS (klass)->get_property = _vala_gtkaml_ast_markup_child_tag_get_property;
	G_OBJECT_CLASS (klass)->set_property = _vala_gtkaml_ast_markup_child_tag_set_property;
	G_OBJECT_CLASS (klass)->finalize = gtkaml_ast_markup_child_tag_finalize;
	/**
	 * Means it won't be added to the parent tag
	 */
	g_object_class_install_property (G_OBJECT_CLASS (klass), GTKAML_AST_MARKUP_CHILD_TAG_STANDALONE_PROPERTY, gtkaml_ast_markup_child_tag_properties[GTKAML_AST_MARKUP_CHILD_TAG_STANDALONE_PROPERTY] = g_param_spec_boolean ("standalone", "standalone", "standalone", FALSE, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE));
	/** 
	 * Parent tag 
	 */
	g_object_class_install_property (G_OBJECT_CLASS (klass), GTKAML_AST_MARKUP_CHILD_TAG_PARENT_TAG_PROPERTY, gtkaml_ast_markup_child_tag_properties[GTKAML_AST_MARKUP_CHILD_TAG_PARENT_TAG_PROPERTY] = g_param_spec_object ("parent-tag", "parent-tag", "parent-tag", GTKAML_AST_TYPE_MARKUP_TAG, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE));
}

static void
gtkaml_ast_markup_child_tag_instance_init (GtkamlAstMarkupChildTag * self,
                                           gpointer klass)
{
	GEqualFunc _tmp0_;
	ValaArrayList* _tmp1_;
	self->priv = gtkaml_ast_markup_child_tag_get_instance_private (self);
	_tmp0_ = g_direct_equal;
	_tmp1_ = vala_array_list_new (GTKAML_AST_TYPE_MARKUP_ATTRIBUTE, (GBoxedCopyFunc) gtkaml_ast_markup_attribute_ref, (GDestroyNotify) gtkaml_ast_markup_attribute_unref, _tmp0_);
	self->composition_parameters = (ValaList*) _tmp1_;
}

static void
gtkaml_ast_markup_child_tag_finalize (GObject * obj)
{
	GtkamlAstMarkupChildTag * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, GTKAML_AST_TYPE_MARKUP_CHILD_TAG, GtkamlAstMarkupChildTag);
	_vala_iterable_unref0 (self->composition_parameters);
	_gtkaml_callable_unref0 (self->composition_method);
	G_OBJECT_CLASS (gtkaml_ast_markup_child_tag_parent_class)->finalize (obj);
}

/**
 * MarkupChildTag is a MarkupTag that has itself a parent: parent_tag, 
 */
static GType
gtkaml_ast_markup_child_tag_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (GtkamlAstMarkupChildTagClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) gtkaml_ast_markup_child_tag_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (GtkamlAstMarkupChildTag), 0, (GInstanceInitFunc) gtkaml_ast_markup_child_tag_instance_init, NULL };
	GType gtkaml_ast_markup_child_tag_type_id;
	gtkaml_ast_markup_child_tag_type_id = g_type_register_static (GTKAML_AST_TYPE_MARKUP_TAG, "GtkamlAstMarkupChildTag", &g_define_type_info, G_TYPE_FLAG_ABSTRACT);
	GtkamlAstMarkupChildTag_private_offset = g_type_add_instance_private (gtkaml_ast_markup_child_tag_type_id, sizeof (GtkamlAstMarkupChildTagPrivate));
	return gtkaml_ast_markup_child_tag_type_id;
}

GType
gtkaml_ast_markup_child_tag_get_type (void)
{
	static volatile gsize gtkaml_ast_markup_child_tag_type_id__once = 0;
	if (g_once_init_enter (&gtkaml_ast_markup_child_tag_type_id__once)) {
		GType gtkaml_ast_markup_child_tag_type_id;
		gtkaml_ast_markup_child_tag_type_id = gtkaml_ast_markup_child_tag_get_type_once ();
		g_once_init_leave (&gtkaml_ast_markup_child_tag_type_id__once, gtkaml_ast_markup_child_tag_type_id);
	}
	return gtkaml_ast_markup_child_tag_type_id__once;
}

static void
_vala_gtkaml_ast_markup_child_tag_get_property (GObject * object,
                                                guint property_id,
                                                GValue * value,
                                                GParamSpec * pspec)
{
	GtkamlAstMarkupChildTag * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, GTKAML_AST_TYPE_MARKUP_CHILD_TAG, GtkamlAstMarkupChildTag);
	switch (property_id) {
		case GTKAML_AST_MARKUP_CHILD_TAG_STANDALONE_PROPERTY:
		g_value_set_boolean (value, gtkaml_ast_markup_child_tag_get_standalone (self));
		break;
		case GTKAML_AST_MARKUP_CHILD_TAG_PARENT_TAG_PROPERTY:
		g_value_set_object (value, gtkaml_ast_markup_child_tag_get_parent_tag (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}

static void
_vala_gtkaml_ast_markup_child_tag_set_property (GObject * object,
                                                guint property_id,
                                                const GValue * value,
                                                GParamSpec * pspec)
{
	GtkamlAstMarkupChildTag * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, GTKAML_AST_TYPE_MARKUP_CHILD_TAG, GtkamlAstMarkupChildTag);
	switch (property_id) {
		case GTKAML_AST_MARKUP_CHILD_TAG_STANDALONE_PROPERTY:
		gtkaml_ast_markup_child_tag_set_standalone (self, g_value_get_boolean (value));
		break;
		case GTKAML_AST_MARKUP_CHILD_TAG_PARENT_TAG_PROPERTY:
		gtkaml_ast_markup_child_tag_set_parent_tag (self, g_value_get_object (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}

