/* gtkamlmarkupmember.c generated by valac 0.56.16, the Vala compiler
 * generated from gtkamlmarkupmember.vala, do not modify */

/* gtkamlmarkupmember.vala
 *
 * Copyright (C) 2011 Vlad Grecescu
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public
 * License along with main.c; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor Boston, MA 02110-1301,  USA
 *
 * Author:
 *        Vlad Grecescu (b100dian@gmail.com)
 */

#include "gtkaml.h"
#include <stdlib.h>
#include <string.h>
#include <glib.h>
#include <vala.h>
#include <glib-object.h>

#if !defined(VALA_STRICT_C)
#if !defined(__clang__) && defined(__GNUC__) && (__GNUC__ >= 14)
#pragma GCC diagnostic warning "-Wincompatible-pointer-types"
#elif defined(__clang__) && (__clang_major__ >= 16)
#pragma clang diagnostic ignored "-Wincompatible-function-pointer-types"
#pragma clang diagnostic ignored "-Wincompatible-pointer-types"
#endif
#endif

enum  {
	GTKAML_AST_MARKUP_MEMBER_0_PROPERTY,
	GTKAML_AST_MARKUP_MEMBER_MEMBER_NAME_PROPERTY,
	GTKAML_AST_MARKUP_MEMBER_ACCESS_PROPERTY,
	GTKAML_AST_MARKUP_MEMBER_PROPERTY_SPEC_PROPERTY,
	GTKAML_AST_MARKUP_MEMBER_ME_PROPERTY,
	GTKAML_AST_MARKUP_MEMBER_NUM_PROPERTIES
};
static GParamSpec* gtkaml_ast_markup_member_properties[GTKAML_AST_MARKUP_MEMBER_NUM_PROPERTIES];
#define _g_free0(var) (var = (g_free (var), NULL))
#define _gtkaml_property_spec_unref0(var) ((var == NULL) ? NULL : (var = (gtkaml_property_spec_unref (var), NULL)))
#define _vala_code_node_unref0(var) ((var == NULL) ? NULL : (var = (vala_code_node_unref (var), NULL)))

struct _GtkamlAstMarkupMemberPrivate {
	gchar* _member_name;
	ValaSymbolAccessibility _access;
	GtkamlPropertySpec* _property_spec;
};

static gint GtkamlAstMarkupMember_private_offset;
static gpointer gtkaml_ast_markup_member_parent_class = NULL;

static void gtkaml_ast_markup_member_set_member_name (GtkamlAstMarkupMember* self,
                                               const gchar* value);
static void gtkaml_ast_markup_member_set_access (GtkamlAstMarkupMember* self,
                                          ValaSymbolAccessibility value);
static void gtkaml_ast_markup_member_set_property_spec (GtkamlAstMarkupMember* self,
                                                 GtkamlPropertySpec* value);
static void gtkaml_ast_markup_member_real_generate_public_ast (GtkamlAstMarkupTag* base,
                                                        GtkamlCodeParserProvider* parser);
static void gtkaml_ast_markup_member_generate_property (GtkamlAstMarkupMember* self);
static void gtkaml_ast_markup_member_real_generate (GtkamlAstMarkupTag* base,
                                             GtkamlMarkupResolver* resolver);
static void gtkaml_ast_markup_member_generate_construct_member (GtkamlAstMarkupMember* self,
                                                         GtkamlMarkupResolver* resolver);
static void gtkaml_ast_markup_member_finalize (GObject * obj);
static GType gtkaml_ast_markup_member_get_type_once (void);
static void _vala_gtkaml_ast_markup_member_get_property (GObject * object,
                                                  guint property_id,
                                                  GValue * value,
                                                  GParamSpec * pspec);
static void _vala_gtkaml_ast_markup_member_set_property (GObject * object,
                                                  guint property_id,
                                                  const GValue * value,
                                                  GParamSpec * pspec);

static inline gpointer
gtkaml_ast_markup_member_get_instance_private (GtkamlAstMarkupMember* self)
{
	return G_STRUCT_MEMBER_P (self, GtkamlAstMarkupMember_private_offset);
}

GtkamlAstMarkupMember*
gtkaml_ast_markup_member_construct (GType object_type,
                                    GtkamlAstMarkupTag* parent_tag,
                                    const gchar* tag_name,
                                    GtkamlMarkupNamespace* tag_namespace,
                                    const gchar* member_name,
                                    ValaSymbolAccessibility access,
                                    GtkamlPropertySpec* property_spec,
                                    ValaSourceReference* source_reference)
{
	GtkamlAstMarkupMember * self = NULL;
	g_return_val_if_fail (parent_tag != NULL, NULL);
	g_return_val_if_fail (tag_name != NULL, NULL);
	g_return_val_if_fail (tag_namespace != NULL, NULL);
	g_return_val_if_fail (member_name != NULL, NULL);
	self = (GtkamlAstMarkupMember*) gtkaml_ast_markup_child_tag_construct (object_type, parent_tag, tag_name, tag_namespace, source_reference);
	gtkaml_ast_markup_member_set_member_name (self, member_name);
	gtkaml_ast_markup_member_set_access (self, access);
	gtkaml_ast_markup_member_set_property_spec (self, property_spec);
	return self;
}

GtkamlAstMarkupMember*
gtkaml_ast_markup_member_new (GtkamlAstMarkupTag* parent_tag,
                              const gchar* tag_name,
                              GtkamlMarkupNamespace* tag_namespace,
                              const gchar* member_name,
                              ValaSymbolAccessibility access,
                              GtkamlPropertySpec* property_spec,
                              ValaSourceReference* source_reference)
{
	return gtkaml_ast_markup_member_construct (GTKAML_AST_TYPE_MARKUP_MEMBER, parent_tag, tag_name, tag_namespace, member_name, access, property_spec, source_reference);
}

static void
gtkaml_ast_markup_member_real_generate_public_ast (GtkamlAstMarkupTag* base,
                                                   GtkamlCodeParserProvider* parser)
{
	GtkamlAstMarkupMember * self;
	self = (GtkamlAstMarkupMember*) base;
	g_return_if_fail (parser != NULL);
	gtkaml_ast_markup_member_generate_property (self);
}

static void
gtkaml_ast_markup_member_real_generate (GtkamlAstMarkupTag* base,
                                        GtkamlMarkupResolver* resolver)
{
	GtkamlAstMarkupMember * self;
	self = (GtkamlAstMarkupMember*) base;
	g_return_if_fail (resolver != NULL);
	gtkaml_ast_markup_member_generate_construct_member (self, resolver);
}

static void
gtkaml_ast_markup_member_generate_property (GtkamlAstMarkupMember* self)
{
	ValaDataType* variable_type = NULL;
	ValaDataType* _tmp0_;
	ValaDataType* _tmp1_;
	ValaDataType* _tmp2_;
	ValaDataType* _tmp3_;
	ValaPropertyAccessor* getter = NULL;
	ValaDataType* _tmp4_;
	ValaSourceReference* _tmp5_;
	ValaSourceReference* _tmp6_;
	ValaPropertyAccessor* _tmp7_;
	gboolean _tmp8_ = FALSE;
	GtkamlPropertySpec* _tmp9_;
	ValaDataType* _tmp15_;
	ValaDataType* _tmp16_;
	ValaDataType* _tmp17_;
	ValaDataType* _tmp18_;
	ValaPropertyAccessor* setter = NULL;
	ValaDataType* _tmp19_;
	ValaSourceReference* _tmp20_;
	ValaSourceReference* _tmp21_;
	ValaPropertyAccessor* _tmp22_;
	gboolean _tmp23_ = FALSE;
	GtkamlPropertySpec* _tmp24_;
	ValaDataType* _tmp30_;
	ValaDataType* _tmp31_;
	ValaDataType* _tmp32_;
	ValaDataType* _tmp33_;
	ValaProperty* p = NULL;
	const gchar* _tmp34_;
	ValaDataType* _tmp35_;
	ValaPropertyAccessor* _tmp36_;
	ValaPropertyAccessor* _tmp37_;
	ValaSourceReference* _tmp38_;
	ValaSourceReference* _tmp39_;
	ValaProperty* _tmp40_;
	ValaSymbolAccessibility _tmp41_;
	GtkamlMarkupClass* _tmp42_;
	GtkamlMarkupClass* _tmp43_;
	g_return_if_fail (self != NULL);
	_tmp0_ = gtkaml_ast_markup_tag_get_data_type ((GtkamlAstMarkupTag*) self);
	_tmp1_ = _tmp0_;
	_tmp2_ = vala_data_type_copy (_tmp1_);
	variable_type = _tmp2_;
	_tmp3_ = variable_type;
	vala_data_type_set_value_owned (_tmp3_, FALSE);
	_tmp4_ = variable_type;
	_tmp5_ = gtkaml_ast_markup_tag_get_source_reference ((GtkamlAstMarkupTag*) self);
	_tmp6_ = _tmp5_;
	_tmp7_ = vala_property_accessor_new (TRUE, FALSE, FALSE, _tmp4_, NULL, _tmp6_, NULL);
	getter = _tmp7_;
	_tmp9_ = self->priv->_property_spec;
	if (_tmp9_ != NULL) {
		GtkamlPropertySpec* _tmp10_;
		ValaSymbolAccessibility* _tmp11_;
		_tmp10_ = self->priv->_property_spec;
		_tmp11_ = _tmp10_->getter_accessibility;
		_tmp8_ = _tmp11_ != NULL;
	} else {
		_tmp8_ = FALSE;
	}
	if (_tmp8_) {
		ValaPropertyAccessor* _tmp12_;
		GtkamlPropertySpec* _tmp13_;
		ValaSymbolAccessibility* _tmp14_;
		_tmp12_ = getter;
		_tmp13_ = self->priv->_property_spec;
		_tmp14_ = _tmp13_->getter_accessibility;
		vala_symbol_set_access ((ValaSymbol*) _tmp12_, *_tmp14_);
	}
	_tmp15_ = gtkaml_ast_markup_tag_get_data_type ((GtkamlAstMarkupTag*) self);
	_tmp16_ = _tmp15_;
	_tmp17_ = vala_data_type_copy (_tmp16_);
	_vala_code_node_unref0 (variable_type);
	variable_type = _tmp17_;
	_tmp18_ = variable_type;
	vala_data_type_set_value_owned (_tmp18_, FALSE);
	_tmp19_ = variable_type;
	_tmp20_ = gtkaml_ast_markup_tag_get_source_reference ((GtkamlAstMarkupTag*) self);
	_tmp21_ = _tmp20_;
	_tmp22_ = vala_property_accessor_new (FALSE, TRUE, FALSE, _tmp19_, NULL, _tmp21_, NULL);
	setter = _tmp22_;
	_tmp24_ = self->priv->_property_spec;
	if (_tmp24_ != NULL) {
		GtkamlPropertySpec* _tmp25_;
		ValaSymbolAccessibility* _tmp26_;
		_tmp25_ = self->priv->_property_spec;
		_tmp26_ = _tmp25_->setter_accessibility;
		_tmp23_ = _tmp26_ != NULL;
	} else {
		_tmp23_ = FALSE;
	}
	if (_tmp23_) {
		ValaPropertyAccessor* _tmp27_;
		GtkamlPropertySpec* _tmp28_;
		ValaSymbolAccessibility* _tmp29_;
		_tmp27_ = setter;
		_tmp28_ = self->priv->_property_spec;
		_tmp29_ = _tmp28_->setter_accessibility;
		vala_symbol_set_access ((ValaSymbol*) _tmp27_, *_tmp29_);
	}
	_tmp30_ = gtkaml_ast_markup_tag_get_data_type ((GtkamlAstMarkupTag*) self);
	_tmp31_ = _tmp30_;
	_tmp32_ = vala_data_type_copy (_tmp31_);
	_vala_code_node_unref0 (variable_type);
	variable_type = _tmp32_;
	_tmp33_ = variable_type;
	vala_data_type_set_value_owned (_tmp33_, TRUE);
	_tmp34_ = self->priv->_member_name;
	_tmp35_ = variable_type;
	_tmp36_ = getter;
	_tmp37_ = setter;
	_tmp38_ = gtkaml_ast_markup_tag_get_source_reference ((GtkamlAstMarkupTag*) self);
	_tmp39_ = _tmp38_;
	_tmp40_ = vala_property_new (_tmp34_, _tmp35_, _tmp36_, _tmp37_, _tmp39_, NULL);
	p = _tmp40_;
	_tmp41_ = self->priv->_access;
	vala_symbol_set_access ((ValaSymbol*) p, _tmp41_);
	_tmp42_ = gtkaml_ast_markup_tag_get_markup_class ((GtkamlAstMarkupTag*) self);
	_tmp43_ = _tmp42_;
	vala_symbol_add_property ((ValaSymbol*) _tmp43_, p);
	_vala_code_node_unref0 (p);
	_vala_code_node_unref0 (setter);
	_vala_code_node_unref0 (getter);
	_vala_code_node_unref0 (variable_type);
}

static void
gtkaml_ast_markup_member_generate_construct_member (GtkamlAstMarkupMember* self,
                                                    GtkamlMarkupResolver* resolver)
{
	ValaObjectCreationExpression* initializer = NULL;
	ValaObjectCreationExpression* _tmp0_;
	ValaAssignment* assignment = NULL;
	const gchar* _tmp1_;
	const gchar* _tmp2_;
	ValaSourceReference* _tmp3_;
	ValaSourceReference* _tmp4_;
	ValaMemberAccess* _tmp5_;
	ValaMemberAccess* _tmp6_;
	ValaSourceReference* _tmp7_;
	ValaSourceReference* _tmp8_;
	ValaAssignment* _tmp9_;
	ValaAssignment* _tmp10_;
	GtkamlMarkupClass* _tmp11_;
	GtkamlMarkupClass* _tmp12_;
	ValaConstructor* _tmp13_;
	ValaConstructor* _tmp14_;
	ValaBlock* _tmp15_;
	ValaBlock* _tmp16_;
	ValaSourceReference* _tmp17_;
	ValaSourceReference* _tmp18_;
	ValaExpressionStatement* _tmp19_;
	ValaExpressionStatement* _tmp20_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (resolver != NULL);
	_tmp0_ = gtkaml_ast_markup_child_tag_get_initializer ((GtkamlAstMarkupChildTag*) self, resolver);
	initializer = _tmp0_;
	_tmp1_ = gtkaml_ast_markup_tag_get_me ((GtkamlAstMarkupTag*) self);
	_tmp2_ = _tmp1_;
	_tmp3_ = gtkaml_ast_markup_tag_get_source_reference ((GtkamlAstMarkupTag*) self);
	_tmp4_ = _tmp3_;
	_tmp5_ = vala_member_access_new_simple (_tmp2_, _tmp4_);
	_tmp6_ = _tmp5_;
	_tmp7_ = gtkaml_ast_markup_tag_get_source_reference ((GtkamlAstMarkupTag*) self);
	_tmp8_ = _tmp7_;
	_tmp9_ = vala_assignment_new ((ValaExpression*) _tmp6_, (ValaExpression*) initializer, VALA_ASSIGNMENT_OPERATOR_SIMPLE, _tmp8_);
	_tmp10_ = _tmp9_;
	_vala_code_node_unref0 (_tmp6_);
	assignment = _tmp10_;
	_tmp11_ = gtkaml_ast_markup_tag_get_markup_class ((GtkamlAstMarkupTag*) self);
	_tmp12_ = _tmp11_;
	_tmp13_ = vala_class_get_constructor ((ValaClass*) _tmp12_);
	_tmp14_ = _tmp13_;
	_tmp15_ = vala_subroutine_get_body ((ValaSubroutine*) _tmp14_);
	_tmp16_ = _tmp15_;
	_tmp17_ = gtkaml_ast_markup_tag_get_source_reference ((GtkamlAstMarkupTag*) self);
	_tmp18_ = _tmp17_;
	_tmp19_ = vala_expression_statement_new ((ValaExpression*) assignment, _tmp18_);
	_tmp20_ = _tmp19_;
	vala_block_add_statement (_tmp16_, (ValaStatement*) _tmp20_);
	_vala_code_node_unref0 (_tmp20_);
	_vala_code_node_unref0 (assignment);
	_vala_code_node_unref0 (initializer);
}

const gchar*
gtkaml_ast_markup_member_get_member_name (GtkamlAstMarkupMember* self)
{
	const gchar* result;
	const gchar* _tmp0_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_member_name;
	result = _tmp0_;
	return result;
}

static void
gtkaml_ast_markup_member_set_member_name (GtkamlAstMarkupMember* self,
                                          const gchar* value)
{
	gchar* old_value;
	g_return_if_fail (self != NULL);
	old_value = gtkaml_ast_markup_member_get_member_name (self);
	if (g_strcmp0 (value, old_value) != 0) {
		gchar* _tmp0_;
		_tmp0_ = g_strdup (value);
		_g_free0 (self->priv->_member_name);
		self->priv->_member_name = _tmp0_;
		g_object_notify_by_pspec ((GObject *) self, gtkaml_ast_markup_member_properties[GTKAML_AST_MARKUP_MEMBER_MEMBER_NAME_PROPERTY]);
	}
}

ValaSymbolAccessibility
gtkaml_ast_markup_member_get_access (GtkamlAstMarkupMember* self)
{
	ValaSymbolAccessibility result;
	g_return_val_if_fail (self != NULL, 0);
	result = self->priv->_access;
	return result;
}

static void
gtkaml_ast_markup_member_set_access (GtkamlAstMarkupMember* self,
                                     ValaSymbolAccessibility value)
{
	ValaSymbolAccessibility old_value;
	g_return_if_fail (self != NULL);
	old_value = gtkaml_ast_markup_member_get_access (self);
	if (old_value != value) {
		self->priv->_access = value;
		g_object_notify_by_pspec ((GObject *) self, gtkaml_ast_markup_member_properties[GTKAML_AST_MARKUP_MEMBER_ACCESS_PROPERTY]);
	}
}

GtkamlPropertySpec*
gtkaml_ast_markup_member_get_property_spec (GtkamlAstMarkupMember* self)
{
	GtkamlPropertySpec* result;
	GtkamlPropertySpec* _tmp0_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_property_spec;
	result = _tmp0_;
	return result;
}

static gpointer
_gtkaml_property_spec_ref0 (gpointer self)
{
	return self ? gtkaml_property_spec_ref (self) : NULL;
}

static void
gtkaml_ast_markup_member_set_property_spec (GtkamlAstMarkupMember* self,
                                            GtkamlPropertySpec* value)
{
	GtkamlPropertySpec* old_value;
	g_return_if_fail (self != NULL);
	old_value = gtkaml_ast_markup_member_get_property_spec (self);
	if (old_value != value) {
		GtkamlPropertySpec* _tmp0_;
		_tmp0_ = _gtkaml_property_spec_ref0 (value);
		_gtkaml_property_spec_unref0 (self->priv->_property_spec);
		self->priv->_property_spec = _tmp0_;
		g_object_notify_by_pspec ((GObject *) self, gtkaml_ast_markup_member_properties[GTKAML_AST_MARKUP_MEMBER_PROPERTY_SPEC_PROPERTY]);
	}
}

static const gchar*
gtkaml_ast_markup_member_real_get_me (GtkamlAstMarkupTag* base)
{
	const gchar* result;
	GtkamlAstMarkupMember* self;
	const gchar* _tmp0_;
	self = (GtkamlAstMarkupMember*) base;
	_tmp0_ = self->priv->_member_name;
	result = _tmp0_;
	return result;
}

static void
gtkaml_ast_markup_member_class_init (GtkamlAstMarkupMemberClass * klass,
                                     gpointer klass_data)
{
	gtkaml_ast_markup_member_parent_class = g_type_class_peek_parent (klass);
	g_type_class_adjust_private_offset (klass, &GtkamlAstMarkupMember_private_offset);
	((GtkamlAstMarkupTagClass *) klass)->generate_public_ast = (void (*) (GtkamlAstMarkupTag*, GtkamlCodeParserProvider*)) gtkaml_ast_markup_member_real_generate_public_ast;
	((GtkamlAstMarkupTagClass *) klass)->generate = (void (*) (GtkamlAstMarkupTag*, GtkamlMarkupResolver*)) gtkaml_ast_markup_member_real_generate;
	GTKAML_AST_MARKUP_TAG_CLASS (klass)->get_me = (const gchar* (*) (GtkamlAstMarkupTag*)) gtkaml_ast_markup_member_real_get_me;
	G_OBJECT_CLASS (klass)->get_property = _vala_gtkaml_ast_markup_member_get_property;
	G_OBJECT_CLASS (klass)->set_property = _vala_gtkaml_ast_markup_member_set_property;
	G_OBJECT_CLASS (klass)->finalize = gtkaml_ast_markup_member_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), GTKAML_AST_MARKUP_MEMBER_MEMBER_NAME_PROPERTY, gtkaml_ast_markup_member_properties[GTKAML_AST_MARKUP_MEMBER_MEMBER_NAME_PROPERTY] = g_param_spec_string ("member-name", "member-name", "member-name", NULL, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), GTKAML_AST_MARKUP_MEMBER_ACCESS_PROPERTY, gtkaml_ast_markup_member_properties[GTKAML_AST_MARKUP_MEMBER_ACCESS_PROPERTY] = g_param_spec_enum ("access", "access", "access", VALA_TYPE_SYMBOL_ACCESSIBILITY, 0, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), GTKAML_AST_MARKUP_MEMBER_PROPERTY_SPEC_PROPERTY, gtkaml_ast_markup_member_properties[GTKAML_AST_MARKUP_MEMBER_PROPERTY_SPEC_PROPERTY] = gtkaml_param_spec_property_spec ("property-spec", "property-spec", "property-spec", GTKAML_TYPE_PROPERTY_SPEC, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), GTKAML_AST_MARKUP_MEMBER_ME_PROPERTY, gtkaml_ast_markup_member_properties[GTKAML_AST_MARKUP_MEMBER_ME_PROPERTY] = g_param_spec_string ("me", "me", "me", NULL, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE));
}

static void
gtkaml_ast_markup_member_instance_init (GtkamlAstMarkupMember * self,
                                        gpointer klass)
{
	self->priv = gtkaml_ast_markup_member_get_instance_private (self);
}

static void
gtkaml_ast_markup_member_finalize (GObject * obj)
{
	GtkamlAstMarkupMember * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, GTKAML_AST_TYPE_MARKUP_MEMBER, GtkamlAstMarkupMember);
	_g_free0 (self->priv->_member_name);
	_gtkaml_property_spec_unref0 (self->priv->_property_spec);
	G_OBJECT_CLASS (gtkaml_ast_markup_member_parent_class)->finalize (obj);
}

/**
 * Represents a tag with g:private or g:public which will be declared as an instance member
 */
static GType
gtkaml_ast_markup_member_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (GtkamlAstMarkupMemberClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) gtkaml_ast_markup_member_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (GtkamlAstMarkupMember), 0, (GInstanceInitFunc) gtkaml_ast_markup_member_instance_init, NULL };
	GType gtkaml_ast_markup_member_type_id;
	gtkaml_ast_markup_member_type_id = g_type_register_static (GTKAML_AST_TYPE_MARKUP_CHILD_TAG, "GtkamlAstMarkupMember", &g_define_type_info, 0);
	GtkamlAstMarkupMember_private_offset = g_type_add_instance_private (gtkaml_ast_markup_member_type_id, sizeof (GtkamlAstMarkupMemberPrivate));
	return gtkaml_ast_markup_member_type_id;
}

GType
gtkaml_ast_markup_member_get_type (void)
{
	static volatile gsize gtkaml_ast_markup_member_type_id__once = 0;
	if (g_once_init_enter (&gtkaml_ast_markup_member_type_id__once)) {
		GType gtkaml_ast_markup_member_type_id;
		gtkaml_ast_markup_member_type_id = gtkaml_ast_markup_member_get_type_once ();
		g_once_init_leave (&gtkaml_ast_markup_member_type_id__once, gtkaml_ast_markup_member_type_id);
	}
	return gtkaml_ast_markup_member_type_id__once;
}

static void
_vala_gtkaml_ast_markup_member_get_property (GObject * object,
                                             guint property_id,
                                             GValue * value,
                                             GParamSpec * pspec)
{
	GtkamlAstMarkupMember * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, GTKAML_AST_TYPE_MARKUP_MEMBER, GtkamlAstMarkupMember);
	switch (property_id) {
		case GTKAML_AST_MARKUP_MEMBER_MEMBER_NAME_PROPERTY:
		g_value_set_string (value, gtkaml_ast_markup_member_get_member_name (self));
		break;
		case GTKAML_AST_MARKUP_MEMBER_ACCESS_PROPERTY:
		g_value_set_enum (value, gtkaml_ast_markup_member_get_access (self));
		break;
		case GTKAML_AST_MARKUP_MEMBER_PROPERTY_SPEC_PROPERTY:
		gtkaml_value_set_property_spec (value, gtkaml_ast_markup_member_get_property_spec (self));
		break;
		case GTKAML_AST_MARKUP_MEMBER_ME_PROPERTY:
		g_value_set_string (value, gtkaml_ast_markup_tag_get_me ((GtkamlAstMarkupTag*) self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}

static void
_vala_gtkaml_ast_markup_member_set_property (GObject * object,
                                             guint property_id,
                                             const GValue * value,
                                             GParamSpec * pspec)
{
	GtkamlAstMarkupMember * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, GTKAML_AST_TYPE_MARKUP_MEMBER, GtkamlAstMarkupMember);
	switch (property_id) {
		case GTKAML_AST_MARKUP_MEMBER_MEMBER_NAME_PROPERTY:
		gtkaml_ast_markup_member_set_member_name (self, g_value_get_string (value));
		break;
		case GTKAML_AST_MARKUP_MEMBER_ACCESS_PROPERTY:
		gtkaml_ast_markup_member_set_access (self, g_value_get_enum (value));
		break;
		case GTKAML_AST_MARKUP_MEMBER_PROPERTY_SPEC_PROPERTY:
		gtkaml_ast_markup_member_set_property_spec (self, gtkaml_value_get_property_spec (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}

