/* gtkamlmarkupattribute.c generated by valac 0.56.16, the Vala compiler
 * generated from gtkamlmarkupattribute.vala, do not modify */

/* gtkamlmarkupattribute.vala
 *
 * Copyright (C) 2011 Vlad Grecescu
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public
 * License along with main.c; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor Boston, MA 02110-1301,  USA
 *
 * Author:
 *        Vlad Grecescu (b100dian@gmail.com)
 */

#include "gtkaml.h"
#include <vala.h>
#include <stdlib.h>
#include <string.h>
#include <glib.h>
#include <glib-object.h>
#include <valagee.h>
#include <gobject/gvaluecollector.h>

#if !defined(VALA_STRICT_C)
#if !defined(__clang__) && defined(__GNUC__) && (__GNUC__ >= 14)
#pragma GCC diagnostic warning "-Wincompatible-pointer-types"
#elif defined(__clang__) && (__clang_major__ >= 16)
#pragma clang diagnostic ignored "-Wincompatible-function-pointer-types"
#pragma clang diagnostic ignored "-Wincompatible-pointer-types"
#endif
#endif

#define _vala_code_node_unref0(var) ((var == NULL) ? NULL : (var = (vala_code_node_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
#define _vala_source_reference_unref0(var) ((var == NULL) ? NULL : (var = (vala_source_reference_unref (var), NULL)))
#define _g_regex_unref0(var) ((var == NULL) ? NULL : (var = (g_regex_unref (var), NULL)))
typedef struct _GtkamlAstParamSpecMarkupAttribute GtkamlAstParamSpecMarkupAttribute;
#define _vala_assert(expr, msg) if G_LIKELY (expr) ; else g_assertion_message_expr (G_LOG_DOMAIN, __FILE__, __LINE__, G_STRFUNC, msg);
#define _vala_return_if_fail(expr, msg) if G_LIKELY (expr) ; else { g_return_if_fail_warning (G_LOG_DOMAIN, G_STRFUNC, msg); return; }
#define _vala_return_val_if_fail(expr, msg, val) if G_LIKELY (expr) ; else { g_return_if_fail_warning (G_LOG_DOMAIN, G_STRFUNC, msg); return val; }
#define _vala_warn_if_fail(expr, msg) if G_LIKELY (expr) ; else g_warn_message (G_LOG_DOMAIN, __FILE__, __LINE__, G_STRFUNC, msg);

struct _GtkamlAstMarkupAttributePrivate {
	ValaDataType* _target_type;
	gchar* _attribute_value;
};

struct _GtkamlAstParamSpecMarkupAttribute {
	GParamSpec parent_instance;
};

static gint GtkamlAstMarkupAttribute_private_offset;
static gpointer gtkaml_ast_markup_attribute_parent_class = NULL;

static void gtkaml_ast_markup_attribute_set_attribute_value (GtkamlAstMarkupAttribute* self,
                                                      const gchar* value);
static ValaExpression* gtkaml_ast_markup_attribute_real_get_expression (GtkamlAstMarkupAttribute* self,
                                                                 GtkamlMarkupResolver* resolver,
                                                                 GtkamlAstMarkupTag* markup_tag);
static ValaStatement* gtkaml_ast_markup_attribute_real_get_assignment (GtkamlAstMarkupAttribute* self,
                                                                GtkamlMarkupResolver* resolver,
                                                                GtkamlAstMarkupTag* markup_tag);
static void gtkaml_ast_markup_attribute_real_resolve (GtkamlAstMarkupAttribute* self,
                                               GtkamlMarkupResolver* resolver,
                                               GtkamlAstMarkupTag* markup_tag);
static void gtkaml_ast_markup_attribute_finalize (GtkamlAstMarkupAttribute * obj);
static GType gtkaml_ast_markup_attribute_get_type_once (void);

static inline gpointer
gtkaml_ast_markup_attribute_get_instance_private (GtkamlAstMarkupAttribute* self)
{
	return G_STRUCT_MEMBER_P (self, GtkamlAstMarkupAttribute_private_offset);
}

static gpointer
_vala_source_reference_ref0 (gpointer self)
{
	return self ? vala_source_reference_ref (self) : NULL;
}

GtkamlAstMarkupAttribute*
gtkaml_ast_markup_attribute_construct (GType object_type,
                                       const gchar* attribute_name,
                                       const gchar* attribute_value,
                                       ValaSourceReference* source_reference)
{
	GtkamlAstMarkupAttribute* self = NULL;
	gchar* _tmp0_;
	ValaSourceReference* _tmp1_;
	g_return_val_if_fail (attribute_name != NULL, NULL);
	self = (GtkamlAstMarkupAttribute*) g_type_create_instance (object_type);
	_tmp0_ = g_strdup (attribute_name);
	_g_free0 (self->_attribute_name);
	self->_attribute_name = _tmp0_;
	gtkaml_ast_markup_attribute_set_attribute_value (self, attribute_value);
	_tmp1_ = _vala_source_reference_ref0 (source_reference);
	_vala_source_reference_unref0 (self->source_reference);
	self->source_reference = _tmp1_;
	return self;
}

GtkamlAstMarkupAttribute*
gtkaml_ast_markup_attribute_new (const gchar* attribute_name,
                                 const gchar* attribute_value,
                                 ValaSourceReference* source_reference)
{
	return gtkaml_ast_markup_attribute_construct (GTKAML_AST_TYPE_MARKUP_ATTRIBUTE, attribute_name, attribute_value, source_reference);
}

GtkamlAstMarkupAttribute*
gtkaml_ast_markup_attribute_construct_with_type (GType object_type,
                                                 const gchar* attribute_name,
                                                 const gchar* attribute_value,
                                                 ValaDataType* target_type,
                                                 ValaSourceReference* source_reference)
{
	GtkamlAstMarkupAttribute* self = NULL;
	gchar* _tmp0_;
	ValaSourceReference* _tmp1_;
	g_return_val_if_fail (attribute_name != NULL, NULL);
	g_return_val_if_fail (target_type != NULL, NULL);
	self = (GtkamlAstMarkupAttribute*) g_type_create_instance (object_type);
	_tmp0_ = g_strdup (attribute_name);
	_g_free0 (self->_attribute_name);
	self->_attribute_name = _tmp0_;
	gtkaml_ast_markup_attribute_set_attribute_value (self, attribute_value);
	gtkaml_ast_markup_attribute_set_target_type (self, target_type);
	_tmp1_ = _vala_source_reference_ref0 (source_reference);
	_vala_source_reference_unref0 (self->source_reference);
	self->source_reference = _tmp1_;
	return self;
}

GtkamlAstMarkupAttribute*
gtkaml_ast_markup_attribute_new_with_type (const gchar* attribute_name,
                                           const gchar* attribute_value,
                                           ValaDataType* target_type,
                                           ValaSourceReference* source_reference)
{
	return gtkaml_ast_markup_attribute_construct_with_type (GTKAML_AST_TYPE_MARKUP_ATTRIBUTE, attribute_name, attribute_value, target_type, source_reference);
}

static gchar*
string_strip (const gchar* self)
{
	gchar* _result_ = NULL;
	gchar* _tmp0_;
	gchar* result;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = g_strdup (self);
	_result_ = _tmp0_;
	g_strstrip (_result_);
	result = _result_;
	return result;
}

static glong
string_strnlen (gchar* str,
                glong maxlen)
{
	gchar* end = NULL;
	gchar* _tmp0_;
	gchar* _tmp1_;
	glong result;
	_tmp0_ = memchr (str, 0, (gsize) maxlen);
	end = _tmp0_;
	_tmp1_ = end;
	if (_tmp1_ == NULL) {
		result = maxlen;
		return result;
	} else {
		gchar* _tmp2_;
		_tmp2_ = end;
		result = (glong) (_tmp2_ - str);
		return result;
	}
}

static gchar*
string_substring (const gchar* self,
                  glong offset,
                  glong len)
{
	glong string_length = 0L;
	gboolean _tmp0_ = FALSE;
	gchar* _tmp3_;
	gchar* result;
	g_return_val_if_fail (self != NULL, NULL);
	if (offset >= ((glong) 0)) {
		_tmp0_ = len >= ((glong) 0);
	} else {
		_tmp0_ = FALSE;
	}
	if (_tmp0_) {
		string_length = string_strnlen ((gchar*) self, offset + len);
	} else {
		gint _tmp1_;
		gint _tmp2_;
		_tmp1_ = strlen (self);
		_tmp2_ = _tmp1_;
		string_length = (glong) _tmp2_;
	}
	if (offset < ((glong) 0)) {
		offset = string_length + offset;
		g_return_val_if_fail (offset >= ((glong) 0), NULL);
	} else {
		g_return_val_if_fail (offset <= string_length, NULL);
	}
	if (len < ((glong) 0)) {
		len = string_length - offset;
	}
	g_return_val_if_fail ((offset + len) <= string_length, NULL);
	_tmp3_ = g_strndup (((gchar*) self) + offset, (gsize) len);
	result = _tmp3_;
	return result;
}

static ValaExpression*
gtkaml_ast_markup_attribute_real_get_expression (GtkamlAstMarkupAttribute* self,
                                                 GtkamlMarkupResolver* resolver,
                                                 GtkamlAstMarkupTag* markup_tag)
{
	gchar* stripped_value = NULL;
	const gchar* _tmp0_;
	gchar* _tmp1_;
	const gchar* _tmp2_;
	ValaExpression* result;
	g_return_val_if_fail (resolver != NULL, NULL);
	g_return_val_if_fail (markup_tag != NULL, NULL);
	gtkaml_ast_markup_attribute_resolve (self, resolver, markup_tag);
	_tmp0_ = self->priv->_attribute_value;
	_tmp1_ = string_strip (_tmp0_);
	stripped_value = _tmp1_;
	_tmp2_ = stripped_value;
	if (g_str_has_prefix (_tmp2_, "{")) {
		const gchar* _tmp3_;
		_tmp3_ = stripped_value;
		if (g_str_has_suffix (_tmp3_, "}")) {
			gchar* code_source = NULL;
			const gchar* _tmp4_;
			const gchar* _tmp5_;
			gint _tmp6_;
			gint _tmp7_;
			gchar* _tmp8_;
			ValaSignal* _tmp9_;
			_tmp4_ = stripped_value;
			_tmp5_ = stripped_value;
			_tmp6_ = strlen (_tmp5_);
			_tmp7_ = _tmp6_;
			_tmp8_ = string_substring (_tmp4_, (glong) 1, (glong) (_tmp7_ - 2));
			code_source = _tmp8_;
			_tmp9_ = self->signal;
			if (_tmp9_ != NULL) {
				ValaBlock* stmts = NULL;
				GtkamlValaParser* _tmp10_;
				GtkamlValaParser* _tmp11_;
				GtkamlMarkupClass* _tmp12_;
				GtkamlMarkupClass* _tmp13_;
				const gchar* _tmp14_;
				const gchar* _tmp15_;
				const gchar* _tmp16_;
				const gchar* _tmp17_;
				const gchar* _tmp18_;
				ValaBlock* _tmp19_;
				ValaLambdaExpression* lambda = NULL;
				ValaBlock* _tmp20_;
				ValaSourceReference* _tmp21_;
				ValaLambdaExpression* _tmp22_;
				ValaLambdaExpression* _tmp23_;
				ValaDataType* _tmp24_;
				ValaDataType* _tmp25_;
				ValaSourceReference* _tmp26_;
				ValaSourceReference* _tmp27_;
				ValaParameter* _tmp28_;
				ValaParameter* _tmp29_;
				_tmp10_ = gtkaml_code_parser_provider_get_code_parser ((GtkamlCodeParserProvider*) resolver);
				_tmp11_ = _tmp10_;
				_tmp12_ = gtkaml_ast_markup_tag_get_markup_class (markup_tag);
				_tmp13_ = _tmp12_;
				_tmp14_ = gtkaml_ast_markup_tag_get_me (markup_tag);
				_tmp15_ = _tmp14_;
				_tmp16_ = gtkaml_ast_markup_attribute_get_attribute_name (self);
				_tmp17_ = _tmp16_;
				_tmp18_ = code_source;
				_tmp19_ = gtkaml_vala_parser_parse_statements (_tmp11_, _tmp13_, _tmp15_, _tmp17_, _tmp18_);
				stmts = _tmp19_;
				_tmp20_ = stmts;
				_tmp21_ = self->source_reference;
				_tmp22_ = vala_lambda_expression_new_with_statement_body (_tmp20_, _tmp21_);
				lambda = _tmp22_;
				_tmp23_ = lambda;
				_tmp24_ = gtkaml_ast_markup_tag_get_data_type (markup_tag);
				_tmp25_ = _tmp24_;
				_tmp26_ = gtkaml_ast_markup_tag_get_source_reference (markup_tag);
				_tmp27_ = _tmp26_;
				_tmp28_ = vala_parameter_new ("target", _tmp25_, _tmp27_);
				_tmp29_ = _tmp28_;
				vala_lambda_expression_add_parameter (_tmp23_, _tmp29_);
				_vala_code_node_unref0 (_tmp29_);
				{
					ValaList* _parameter_list = NULL;
					ValaSignal* _tmp30_;
					ValaList* _tmp31_;
					gint _parameter_size = 0;
					ValaList* _tmp32_;
					gint _tmp33_;
					gint _tmp34_;
					gint _parameter_index = 0;
					_tmp30_ = self->signal;
					_tmp31_ = vala_callable_get_parameters ((ValaCallable*) _tmp30_);
					_parameter_list = _tmp31_;
					_tmp32_ = _parameter_list;
					_tmp33_ = vala_collection_get_size ((ValaCollection*) _tmp32_);
					_tmp34_ = _tmp33_;
					_parameter_size = _tmp34_;
					_parameter_index = -1;
					while (TRUE) {
						gint _tmp35_;
						gint _tmp36_;
						ValaParameter* parameter = NULL;
						ValaList* _tmp37_;
						gpointer _tmp38_;
						ValaLambdaExpression* _tmp39_;
						ValaParameter* _tmp40_;
						_parameter_index = _parameter_index + 1;
						_tmp35_ = _parameter_index;
						_tmp36_ = _parameter_size;
						if (!(_tmp35_ < _tmp36_)) {
							break;
						}
						_tmp37_ = _parameter_list;
						_tmp38_ = vala_list_get (_tmp37_, _parameter_index);
						parameter = (ValaParameter*) _tmp38_;
						_tmp39_ = lambda;
						_tmp40_ = parameter;
						vala_lambda_expression_add_parameter (_tmp39_, _tmp40_);
						_vala_code_node_unref0 (parameter);
					}
				}
				result = (ValaExpression*) lambda;
				_vala_code_node_unref0 (stmts);
				_g_free0 (code_source);
				_g_free0 (stripped_value);
				return result;
			} else {
				GtkamlValaParser* _tmp41_;
				GtkamlValaParser* _tmp42_;
				GtkamlMarkupClass* _tmp43_;
				GtkamlMarkupClass* _tmp44_;
				const gchar* _tmp45_;
				const gchar* _tmp46_;
				const gchar* _tmp47_;
				const gchar* _tmp48_;
				const gchar* _tmp49_;
				ValaExpression* _tmp50_;
				_tmp41_ = gtkaml_code_parser_provider_get_code_parser ((GtkamlCodeParserProvider*) resolver);
				_tmp42_ = _tmp41_;
				_tmp43_ = gtkaml_ast_markup_tag_get_markup_class (markup_tag);
				_tmp44_ = _tmp43_;
				_tmp45_ = gtkaml_ast_markup_tag_get_me (markup_tag);
				_tmp46_ = _tmp45_;
				_tmp47_ = gtkaml_ast_markup_attribute_get_attribute_name (self);
				_tmp48_ = _tmp47_;
				_tmp49_ = code_source;
				_tmp50_ = gtkaml_vala_parser_parse_expression (_tmp42_, _tmp44_, _tmp46_, _tmp48_, _tmp49_);
				result = _tmp50_;
				_g_free0 (code_source);
				_g_free0 (stripped_value);
				return result;
			}
			_g_free0 (code_source);
		} else {
			ValaSourceReference* _tmp51_;
			const gchar* _tmp52_;
			const gchar* _tmp53_;
			gchar* _tmp54_;
			gchar* _tmp55_;
			_tmp51_ = self->source_reference;
			_tmp52_ = gtkaml_ast_markup_attribute_get_attribute_name (self);
			_tmp53_ = _tmp52_;
			_tmp54_ = g_strdup_printf ("Unmatched closing brace in %'s value.", _tmp53_);
			_tmp55_ = _tmp54_;
			vala_report_error (_tmp51_, "%s", _tmp55_);
			_g_free0 (_tmp55_);
		}
	} else {
		ValaSignal* _tmp56_;
		_tmp56_ = self->signal;
		if (_tmp56_ != NULL) {
			GtkamlValaParser* _tmp57_;
			GtkamlValaParser* _tmp58_;
			GtkamlMarkupClass* _tmp59_;
			GtkamlMarkupClass* _tmp60_;
			const gchar* _tmp61_;
			const gchar* _tmp62_;
			const gchar* _tmp63_;
			const gchar* _tmp64_;
			const gchar* _tmp65_;
			ValaExpression* _tmp66_;
			_tmp57_ = gtkaml_code_parser_provider_get_code_parser ((GtkamlCodeParserProvider*) resolver);
			_tmp58_ = _tmp57_;
			_tmp59_ = gtkaml_ast_markup_tag_get_markup_class (markup_tag);
			_tmp60_ = _tmp59_;
			_tmp61_ = gtkaml_ast_markup_tag_get_me (markup_tag);
			_tmp62_ = _tmp61_;
			_tmp63_ = gtkaml_ast_markup_attribute_get_attribute_name (self);
			_tmp64_ = _tmp63_;
			_tmp65_ = stripped_value;
			_tmp66_ = gtkaml_vala_parser_parse_expression (_tmp58_, _tmp60_, _tmp62_, _tmp64_, _tmp65_);
			result = _tmp66_;
			_g_free0 (stripped_value);
			return result;
		} else {
			const gchar* _tmp67_;
			ValaExpression* _tmp68_;
			_tmp67_ = stripped_value;
			_tmp68_ = gtkaml_ast_markup_attribute_generate_literal (self, _tmp67_);
			result = _tmp68_;
			_g_free0 (stripped_value);
			return result;
		}
	}
	result = NULL;
	_g_free0 (stripped_value);
	return result;
}

ValaExpression*
gtkaml_ast_markup_attribute_get_expression (GtkamlAstMarkupAttribute* self,
                                            GtkamlMarkupResolver* resolver,
                                            GtkamlAstMarkupTag* markup_tag)
{
	GtkamlAstMarkupAttributeClass* _klass_;
	g_return_val_if_fail (self != NULL, NULL);
	_klass_ = GTKAML_AST_MARKUP_ATTRIBUTE_GET_CLASS (self);
	if (_klass_->get_expression) {
		return _klass_->get_expression (self, resolver, markup_tag);
	}
	return NULL;
}

static gpointer
_vala_code_node_ref0 (gpointer self)
{
	return self ? vala_code_node_ref (self) : NULL;
}

static ValaStatement*
gtkaml_ast_markup_attribute_real_get_assignment (GtkamlAstMarkupAttribute* self,
                                                 GtkamlMarkupResolver* resolver,
                                                 GtkamlAstMarkupTag* markup_tag)
{
	ValaExpression* assignment = NULL;
	ValaExpression* right_hand = NULL;
	ValaExpression* _tmp0_;
	ValaExpression* _tmp1_;
	ValaMemberAccess* parent_access = NULL;
	const gchar* _tmp2_;
	const gchar* _tmp3_;
	ValaSourceReference* _tmp4_;
	ValaMemberAccess* _tmp5_;
	ValaMemberAccess* attribute_access = NULL;
	ValaMemberAccess* _tmp6_;
	const gchar* _tmp7_;
	const gchar* _tmp8_;
	ValaSourceReference* _tmp9_;
	ValaMemberAccess* _tmp10_;
	ValaSignal* _tmp11_;
	ValaExpression* _tmp27_;
	ValaExpressionStatement* _tmp28_;
	ValaStatement* result;
	g_return_val_if_fail (resolver != NULL, NULL);
	g_return_val_if_fail (markup_tag != NULL, NULL);
	gtkaml_ast_markup_attribute_resolve (self, resolver, markup_tag);
	_tmp0_ = gtkaml_ast_markup_attribute_get_expression (self, resolver, markup_tag);
	right_hand = _tmp0_;
	_tmp1_ = right_hand;
	if (_tmp1_ == NULL) {
		result = NULL;
		_vala_code_node_unref0 (right_hand);
		_vala_code_node_unref0 (assignment);
		return result;
	}
	_tmp2_ = gtkaml_ast_markup_tag_get_me (markup_tag);
	_tmp3_ = _tmp2_;
	_tmp4_ = self->source_reference;
	_tmp5_ = vala_member_access_new_simple (_tmp3_, _tmp4_);
	parent_access = _tmp5_;
	_tmp6_ = parent_access;
	_tmp7_ = gtkaml_ast_markup_attribute_get_attribute_name (self);
	_tmp8_ = _tmp7_;
	_tmp9_ = self->source_reference;
	_tmp10_ = vala_member_access_new ((ValaExpression*) _tmp6_, _tmp8_, _tmp9_);
	attribute_access = _tmp10_;
	_tmp11_ = self->signal;
	if (_tmp11_ != NULL) {
		ValaMethodCall* connect_call = NULL;
		ValaMemberAccess* _tmp12_;
		ValaSourceReference* _tmp13_;
		ValaMemberAccess* _tmp14_;
		ValaMemberAccess* _tmp15_;
		ValaSourceReference* _tmp16_;
		ValaMethodCall* _tmp17_;
		ValaMethodCall* _tmp18_;
		ValaMethodCall* _tmp19_;
		ValaExpression* _tmp20_;
		ValaMethodCall* _tmp21_;
		ValaExpression* _tmp22_;
		_tmp12_ = attribute_access;
		_tmp13_ = self->source_reference;
		_tmp14_ = vala_member_access_new ((ValaExpression*) _tmp12_, "connect", _tmp13_);
		_tmp15_ = _tmp14_;
		_tmp16_ = self->source_reference;
		_tmp17_ = vala_method_call_new ((ValaExpression*) _tmp15_, _tmp16_);
		_tmp18_ = _tmp17_;
		_vala_code_node_unref0 (_tmp15_);
		connect_call = _tmp18_;
		_tmp19_ = connect_call;
		_tmp20_ = right_hand;
		vala_callable_expression_add_argument ((ValaCallableExpression*) _tmp19_, _tmp20_);
		_tmp21_ = connect_call;
		_tmp22_ = _vala_code_node_ref0 ((ValaExpression*) _tmp21_);
		_vala_code_node_unref0 (assignment);
		assignment = _tmp22_;
		_vala_code_node_unref0 (connect_call);
	} else {
		ValaMemberAccess* _tmp23_;
		ValaExpression* _tmp24_;
		ValaSourceReference* _tmp25_;
		ValaAssignment* _tmp26_;
		_tmp23_ = attribute_access;
		_tmp24_ = right_hand;
		_tmp25_ = self->source_reference;
		_tmp26_ = vala_assignment_new ((ValaExpression*) _tmp23_, _tmp24_, VALA_ASSIGNMENT_OPERATOR_SIMPLE, _tmp25_);
		_vala_code_node_unref0 (assignment);
		assignment = (ValaExpression*) _tmp26_;
	}
	_tmp27_ = assignment;
	_tmp28_ = vala_expression_statement_new (_tmp27_, NULL);
	result = (ValaStatement*) _tmp28_;
	_vala_code_node_unref0 (attribute_access);
	_vala_code_node_unref0 (parent_access);
	_vala_code_node_unref0 (right_hand);
	_vala_code_node_unref0 (assignment);
	return result;
}

ValaStatement*
gtkaml_ast_markup_attribute_get_assignment (GtkamlAstMarkupAttribute* self,
                                            GtkamlMarkupResolver* resolver,
                                            GtkamlAstMarkupTag* markup_tag)
{
	GtkamlAstMarkupAttributeClass* _klass_;
	g_return_val_if_fail (self != NULL, NULL);
	_klass_ = GTKAML_AST_MARKUP_ATTRIBUTE_GET_CLASS (self);
	if (_klass_->get_assignment) {
		return _klass_->get_assignment (self, resolver, markup_tag);
	}
	return NULL;
}

static void
gtkaml_ast_markup_attribute_real_resolve (GtkamlAstMarkupAttribute* self,
                                          GtkamlMarkupResolver* resolver,
                                          GtkamlAstMarkupTag* markup_tag)
{
	ValaDataType* _tmp0_;
	gboolean _tmp1_ = FALSE;
	ValaDataType* _tmp2_;
	ValaDataType* _tmp3_;
	ValaTypeSymbol* type_symbol = NULL;
	ValaDataType* _tmp6_;
	ValaDataType* _tmp7_;
	ValaSymbol* resolved_attribute = NULL;
	ValaTypeSymbol* _tmp20_;
	const gchar* _tmp21_;
	const gchar* _tmp22_;
	ValaSymbol* _tmp23_;
	ValaSymbol* _tmp24_;
	g_return_if_fail (resolver != NULL);
	g_return_if_fail (markup_tag != NULL);
	_tmp0_ = self->priv->_target_type;
	if (_tmp0_ != NULL) {
		return;
	}
	_tmp2_ = gtkaml_ast_markup_tag_get_resolved_type (markup_tag);
	_tmp3_ = _tmp2_;
	if (G_TYPE_CHECK_INSTANCE_TYPE (_tmp3_, VALA_TYPE_OBJECT_TYPE)) {
		_tmp1_ = TRUE;
	} else {
		ValaDataType* _tmp4_;
		ValaDataType* _tmp5_;
		_tmp4_ = gtkaml_ast_markup_tag_get_resolved_type (markup_tag);
		_tmp5_ = _tmp4_;
		_tmp1_ = G_TYPE_CHECK_INSTANCE_TYPE (_tmp5_, VALA_TYPE_STRUCT_VALUE_TYPE);
	}
	_vala_assert (_tmp1_, "markup_tag.resolved_type is ObjectType || markup_tag.resolved_type is StructValueType");
	type_symbol = NULL;
	_tmp6_ = gtkaml_ast_markup_tag_get_resolved_type (markup_tag);
	_tmp7_ = _tmp6_;
	if (G_TYPE_CHECK_INSTANCE_TYPE (_tmp7_, VALA_TYPE_OBJECT_TYPE)) {
		ValaDataType* _tmp8_;
		ValaDataType* _tmp9_;
		ValaTypeSymbol* _tmp10_;
		ValaTypeSymbol* _tmp11_;
		ValaTypeSymbol* _tmp12_;
		_tmp8_ = gtkaml_ast_markup_tag_get_resolved_type (markup_tag);
		_tmp9_ = _tmp8_;
		_tmp10_ = vala_data_type_get_type_symbol ((ValaDataType*) G_TYPE_CHECK_INSTANCE_CAST (_tmp9_, VALA_TYPE_OBJECT_TYPE, ValaObjectType));
		_tmp11_ = _tmp10_;
		_tmp12_ = _vala_code_node_ref0 (_tmp11_);
		_vala_code_node_unref0 (type_symbol);
		type_symbol = _tmp12_;
	} else {
		ValaDataType* _tmp13_;
		ValaDataType* _tmp14_;
		_tmp13_ = gtkaml_ast_markup_tag_get_resolved_type (markup_tag);
		_tmp14_ = _tmp13_;
		if (G_TYPE_CHECK_INSTANCE_TYPE (_tmp14_, VALA_TYPE_STRUCT_VALUE_TYPE)) {
			ValaDataType* _tmp15_;
			ValaDataType* _tmp16_;
			ValaTypeSymbol* _tmp17_;
			ValaTypeSymbol* _tmp18_;
			ValaTypeSymbol* _tmp19_;
			_tmp15_ = gtkaml_ast_markup_tag_get_resolved_type (markup_tag);
			_tmp16_ = _tmp15_;
			_tmp17_ = vala_data_type_get_type_symbol ((ValaDataType*) G_TYPE_CHECK_INSTANCE_CAST (_tmp16_, VALA_TYPE_STRUCT_VALUE_TYPE, ValaStructValueType));
			_tmp18_ = _tmp17_;
			_tmp19_ = _vala_code_node_ref0 (_tmp18_);
			_vala_code_node_unref0 (type_symbol);
			type_symbol = _tmp19_;
		}
	}
	_tmp20_ = type_symbol;
	_tmp21_ = gtkaml_ast_markup_attribute_get_attribute_name (self);
	_tmp22_ = _tmp21_;
	_tmp23_ = gtkaml_markup_resolver_search_symbol (resolver, _tmp20_, _tmp22_);
	resolved_attribute = _tmp23_;
	_tmp24_ = resolved_attribute;
	if (G_TYPE_CHECK_INSTANCE_TYPE (_tmp24_, VALA_TYPE_PROPERTY)) {
		ValaSymbol* _tmp25_;
		ValaDataType* _tmp26_;
		ValaDataType* _tmp27_;
		ValaDataType* _tmp28_;
		ValaDataType* _tmp29_;
		_tmp25_ = resolved_attribute;
		_tmp26_ = vala_property_get_property_type (G_TYPE_CHECK_INSTANCE_CAST (_tmp25_, VALA_TYPE_PROPERTY, ValaProperty));
		_tmp27_ = _tmp26_;
		_tmp28_ = vala_data_type_copy (_tmp27_);
		_tmp29_ = _tmp28_;
		gtkaml_ast_markup_attribute_set_target_type (self, _tmp29_);
		_vala_code_node_unref0 (_tmp29_);
	} else {
		ValaSymbol* _tmp30_;
		_tmp30_ = resolved_attribute;
		if (G_TYPE_CHECK_INSTANCE_TYPE (_tmp30_, VALA_TYPE_FIELD)) {
			ValaSymbol* _tmp31_;
			ValaDataType* _tmp32_;
			ValaDataType* _tmp33_;
			ValaDataType* _tmp34_;
			ValaDataType* _tmp35_;
			_tmp31_ = resolved_attribute;
			_tmp32_ = vala_variable_get_variable_type ((ValaVariable*) G_TYPE_CHECK_INSTANCE_CAST (_tmp31_, VALA_TYPE_FIELD, ValaField));
			_tmp33_ = _tmp32_;
			_tmp34_ = vala_data_type_copy (_tmp33_);
			_tmp35_ = _tmp34_;
			gtkaml_ast_markup_attribute_set_target_type (self, _tmp35_);
			_vala_code_node_unref0 (_tmp35_);
		} else {
			ValaSymbol* _tmp36_;
			_tmp36_ = resolved_attribute;
			if (G_TYPE_CHECK_INSTANCE_TYPE (_tmp36_, VALA_TYPE_SIGNAL)) {
				ValaSymbol* _tmp37_;
				ValaSignal* _tmp38_;
				_tmp37_ = resolved_attribute;
				_tmp38_ = _vala_code_node_ref0 (G_TYPE_CHECK_INSTANCE_CAST (_tmp37_, VALA_TYPE_SIGNAL, ValaSignal));
				_vala_code_node_unref0 (self->signal);
				self->signal = _tmp38_;
			} else {
			}
		}
	}
	_vala_code_node_unref0 (resolved_attribute);
	_vala_code_node_unref0 (type_symbol);
}

void
gtkaml_ast_markup_attribute_resolve (GtkamlAstMarkupAttribute* self,
                                     GtkamlMarkupResolver* resolver,
                                     GtkamlAstMarkupTag* markup_tag)
{
	GtkamlAstMarkupAttributeClass* _klass_;
	g_return_if_fail (self != NULL);
	_klass_ = GTKAML_AST_MARKUP_ATTRIBUTE_GET_CLASS (self);
	if (_klass_->resolve) {
		_klass_->resolve (self, resolver, markup_tag);
	}
}

static gchar*
string_replace (const gchar* self,
                const gchar* old,
                const gchar* replacement)
{
	gboolean _tmp0_ = FALSE;
	gboolean _tmp1_ = FALSE;
	GError* _inner_error0_ = NULL;
	gchar* result;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (old != NULL, NULL);
	g_return_val_if_fail (replacement != NULL, NULL);
	if ((*((gchar*) self)) == '\0') {
		_tmp1_ = TRUE;
	} else {
		_tmp1_ = (*((gchar*) old)) == '\0';
	}
	if (_tmp1_) {
		_tmp0_ = TRUE;
	} else {
		_tmp0_ = g_strcmp0 (old, replacement) == 0;
	}
	if (_tmp0_) {
		gchar* _tmp2_;
		_tmp2_ = g_strdup (self);
		result = _tmp2_;
		return result;
	}
	{
		GRegex* regex = NULL;
		gchar* _tmp3_;
		gchar* _tmp4_;
		GRegex* _tmp5_;
		GRegex* _tmp6_;
		gchar* _tmp7_ = NULL;
		GRegex* _tmp8_;
		gchar* _tmp9_;
		gchar* _tmp10_;
		_tmp3_ = g_regex_escape_string (old, -1);
		_tmp4_ = _tmp3_;
		_tmp5_ = g_regex_new (_tmp4_, 0, 0, &_inner_error0_);
		_tmp6_ = _tmp5_;
		_g_free0 (_tmp4_);
		regex = _tmp6_;
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
			if (_inner_error0_->domain == G_REGEX_ERROR) {
				goto __catch0_g_regex_error;
			}
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
			g_clear_error (&_inner_error0_);
			return NULL;
		}
		_tmp8_ = regex;
		_tmp9_ = g_regex_replace_literal (_tmp8_, self, (gssize) -1, 0, replacement, 0, &_inner_error0_);
		_tmp7_ = _tmp9_;
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
			_g_regex_unref0 (regex);
			if (_inner_error0_->domain == G_REGEX_ERROR) {
				goto __catch0_g_regex_error;
			}
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
			g_clear_error (&_inner_error0_);
			return NULL;
		}
		_tmp10_ = _tmp7_;
		_tmp7_ = NULL;
		result = _tmp10_;
		_g_free0 (_tmp7_);
		_g_regex_unref0 (regex);
		return result;
	}
	goto __finally0;
	__catch0_g_regex_error:
	{
		g_clear_error (&_inner_error0_);
		g_assert_not_reached ();
	}
	__finally0:
	g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
	g_clear_error (&_inner_error0_);
	return NULL;
}

ValaExpression*
gtkaml_ast_markup_attribute_generate_literal (GtkamlAstMarkupAttribute* self,
                                              const gchar* stripped_value)
{
	ValaDataType* _tmp0_;
	ValaTypeSymbol* type_symbol = NULL;
	ValaDataType* _tmp6_;
	ValaTypeSymbol* _tmp7_;
	ValaTypeSymbol* _tmp8_;
	ValaTypeSymbol* _tmp9_;
	gchar* _tmp10_ = NULL;
	ValaTypeSymbol* _tmp11_;
	gchar* type_name = NULL;
	gchar* _tmp16_;
	const gchar* _tmp17_;
	ValaExpression* result;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (stripped_value != NULL, NULL);
	_tmp0_ = self->priv->_target_type;
	if (_tmp0_ == NULL) {
		ValaSourceReference* _tmp1_;
		const gchar* _tmp2_;
		const gchar* _tmp3_;
		gchar* _tmp4_;
		gchar* _tmp5_;
		_tmp1_ = self->source_reference;
		_tmp2_ = gtkaml_ast_markup_attribute_get_attribute_name (self);
		_tmp3_ = _tmp2_;
		_tmp4_ = g_strdup_printf ("Unknown attribute `%s' on `%s'", _tmp3_, stripped_value);
		_tmp5_ = _tmp4_;
		vala_report_error (_tmp1_, "%s", _tmp5_);
		_g_free0 (_tmp5_);
		result = NULL;
		return result;
	}
	_tmp6_ = self->priv->_target_type;
	_tmp7_ = vala_data_type_get_type_symbol (_tmp6_);
	_tmp8_ = _tmp7_;
	_tmp9_ = _vala_code_node_ref0 (_tmp8_);
	type_symbol = _tmp9_;
	_tmp11_ = type_symbol;
	if (_tmp11_ != NULL) {
		ValaTypeSymbol* _tmp12_;
		gchar* _tmp13_;
		_tmp12_ = type_symbol;
		_tmp13_ = vala_symbol_get_full_name ((ValaSymbol*) _tmp12_);
		_g_free0 (_tmp10_);
		_tmp10_ = _tmp13_;
	} else {
		ValaDataType* _tmp14_;
		gchar* _tmp15_;
		_tmp14_ = self->priv->_target_type;
		_tmp15_ = vala_data_type_to_qualified_string (_tmp14_, NULL);
		_g_free0 (_tmp10_);
		_tmp10_ = _tmp15_;
	}
	_tmp16_ = g_strdup (_tmp10_);
	type_name = _tmp16_;
	_tmp17_ = type_name;
	if (g_strcmp0 (_tmp17_, "string") == 0) {
		const gchar* _tmp18_;
		gchar* _tmp19_;
		gchar* _tmp20_;
		gchar* _tmp21_;
		gchar* _tmp22_;
		gchar* _tmp23_;
		gchar* _tmp24_;
		ValaSourceReference* _tmp25_;
		ValaStringLiteral* _tmp26_;
		ValaExpression* _tmp27_;
		_tmp18_ = self->priv->_attribute_value;
		_tmp19_ = string_replace (_tmp18_, "\"", "\\\"");
		_tmp20_ = _tmp19_;
		_tmp21_ = g_strconcat ("\"", _tmp20_, NULL);
		_tmp22_ = _tmp21_;
		_tmp23_ = g_strconcat (_tmp22_, "\"", NULL);
		_tmp24_ = _tmp23_;
		_tmp25_ = self->source_reference;
		_tmp26_ = vala_string_literal_new (_tmp24_, _tmp25_);
		_tmp27_ = (ValaExpression*) _tmp26_;
		_g_free0 (_tmp24_);
		_g_free0 (_tmp22_);
		_g_free0 (_tmp20_);
		result = _tmp27_;
		_g_free0 (type_name);
		_g_free0 (_tmp10_);
		_vala_code_node_unref0 (type_symbol);
		return result;
	} else {
		const gchar* _tmp28_;
		_tmp28_ = type_name;
		if (g_strcmp0 (_tmp28_, "bool") == 0) {
			const gchar* _tmp29_;
			ValaSourceReference* _tmp30_;
			ValaBooleanLiteral* _tmp31_;
			_tmp29_ = self->priv->_attribute_value;
			_tmp30_ = self->source_reference;
			_tmp31_ = vala_boolean_literal_new (g_strcmp0 (_tmp29_, "true") == 0, _tmp30_);
			result = (ValaExpression*) _tmp31_;
			_g_free0 (type_name);
			_g_free0 (_tmp10_);
			_vala_code_node_unref0 (type_symbol);
			return result;
		} else {
			ValaDataType* _tmp32_;
			_tmp32_ = self->priv->_target_type;
			if (G_TYPE_CHECK_INSTANCE_TYPE (_tmp32_, VALA_TYPE_INTEGER_TYPE)) {
				const gchar* _tmp33_;
				ValaSourceReference* _tmp34_;
				ValaIntegerLiteral* _tmp35_;
				_tmp33_ = self->priv->_attribute_value;
				_tmp34_ = self->source_reference;
				_tmp35_ = vala_integer_literal_new (_tmp33_, _tmp34_);
				result = (ValaExpression*) _tmp35_;
				_g_free0 (type_name);
				_g_free0 (_tmp10_);
				_vala_code_node_unref0 (type_symbol);
				return result;
			} else {
				ValaDataType* _tmp36_;
				_tmp36_ = self->priv->_target_type;
				if (G_TYPE_CHECK_INSTANCE_TYPE (_tmp36_, VALA_TYPE_FLOATING_TYPE)) {
					const gchar* _tmp37_;
					ValaSourceReference* _tmp38_;
					ValaRealLiteral* _tmp39_;
					_tmp37_ = self->priv->_attribute_value;
					_tmp38_ = self->source_reference;
					_tmp39_ = vala_real_literal_new (_tmp37_, _tmp38_);
					result = (ValaExpression*) _tmp39_;
					_g_free0 (type_name);
					_g_free0 (_tmp10_);
					_vala_code_node_unref0 (type_symbol);
					return result;
				} else {
					gboolean _tmp40_ = FALSE;
					ValaDataType* _tmp41_;
					_tmp41_ = self->priv->_target_type;
					if (G_TYPE_CHECK_INSTANCE_TYPE (_tmp41_, VALA_TYPE_REFERENCE_TYPE)) {
						_tmp40_ = g_strcmp0 (stripped_value, "null") == 0;
					} else {
						_tmp40_ = FALSE;
					}
					if (_tmp40_) {
						ValaSourceReference* _tmp42_;
						ValaNullLiteral* _tmp43_;
						_tmp42_ = self->source_reference;
						_tmp43_ = vala_null_literal_new (_tmp42_);
						result = (ValaExpression*) _tmp43_;
						_g_free0 (type_name);
						_g_free0 (_tmp10_);
						_vala_code_node_unref0 (type_symbol);
						return result;
					} else {
						ValaDataType* _tmp44_;
						_tmp44_ = self->priv->_target_type;
						if (G_TYPE_CHECK_INSTANCE_TYPE (_tmp44_, VALA_TYPE_ENUM_VALUE_TYPE)) {
							ValaSymbol* enum_value = NULL;
							ValaDataType* _tmp45_;
							const gchar* _tmp46_;
							ValaSymbol* _tmp47_;
							ValaSymbol* _tmp48_;
							ValaSymbol* _tmp54_;
							_tmp45_ = self->priv->_target_type;
							_tmp46_ = self->priv->_attribute_value;
							_tmp47_ = vala_data_type_get_member ((ValaDataType*) G_TYPE_CHECK_INSTANCE_CAST (_tmp45_, VALA_TYPE_ENUM_VALUE_TYPE, ValaEnumValueType), _tmp46_);
							enum_value = _tmp47_;
							_tmp48_ = enum_value;
							if (_tmp48_ == NULL) {
								ValaDataType* _tmp49_;
								const gchar* _tmp50_;
								gchar* _tmp51_;
								gchar* _tmp52_;
								ValaSymbol* _tmp53_;
								_tmp49_ = self->priv->_target_type;
								_tmp50_ = self->priv->_attribute_value;
								_tmp51_ = g_utf8_strup (_tmp50_, (gssize) -1);
								_tmp52_ = _tmp51_;
								_tmp53_ = vala_data_type_get_member ((ValaDataType*) G_TYPE_CHECK_INSTANCE_CAST (_tmp49_, VALA_TYPE_ENUM_VALUE_TYPE, ValaEnumValueType), _tmp52_);
								_vala_code_node_unref0 (enum_value);
								enum_value = _tmp53_;
								_g_free0 (_tmp52_);
							}
							_tmp54_ = enum_value;
							if (G_TYPE_CHECK_INSTANCE_TYPE (_tmp54_, VALA_TYPE_ENUM_VALUE)) {
								ValaTypeSymbol* _tmp55_;
								ValaMemberAccess* enum_access = NULL;
								ValaTypeSymbol* _tmp61_;
								const gchar* _tmp62_;
								const gchar* _tmp63_;
								ValaSourceReference* _tmp64_;
								ValaMemberAccess* _tmp65_;
								ValaMemberAccess* _tmp66_;
								ValaSymbol* _tmp67_;
								const gchar* _tmp68_;
								const gchar* _tmp69_;
								ValaSourceReference* _tmp70_;
								ValaMemberAccess* _tmp71_;
								_tmp55_ = type_symbol;
								if (_tmp55_ == NULL) {
									ValaSourceReference* _tmp56_;
									const gchar* _tmp57_;
									const gchar* _tmp58_;
									gchar* _tmp59_;
									gchar* _tmp60_;
									_tmp56_ = self->source_reference;
									_tmp57_ = gtkaml_ast_markup_attribute_get_attribute_name (self);
									_tmp58_ = _tmp57_;
									_tmp59_ = g_strdup_printf ("Error: enum type for '%s' could not be resolved\n", _tmp58_);
									_tmp60_ = _tmp59_;
									vala_report_error (_tmp56_, "%s", _tmp60_);
									_g_free0 (_tmp60_);
									result = NULL;
									_vala_code_node_unref0 (enum_value);
									_g_free0 (type_name);
									_g_free0 (_tmp10_);
									_vala_code_node_unref0 (type_symbol);
									return result;
								}
								_tmp61_ = type_symbol;
								_tmp62_ = vala_symbol_get_name ((ValaSymbol*) _tmp61_);
								_tmp63_ = _tmp62_;
								_tmp64_ = self->source_reference;
								_tmp65_ = vala_member_access_new_simple (_tmp63_, _tmp64_);
								enum_access = _tmp65_;
								_tmp66_ = enum_access;
								_tmp67_ = enum_value;
								_tmp68_ = vala_symbol_get_name (_tmp67_);
								_tmp69_ = _tmp68_;
								_tmp70_ = self->source_reference;
								_tmp71_ = vala_member_access_new ((ValaExpression*) _tmp66_, _tmp69_, _tmp70_);
								result = (ValaExpression*) _tmp71_;
								_vala_code_node_unref0 (enum_access);
								_vala_code_node_unref0 (enum_value);
								_g_free0 (type_name);
								_g_free0 (_tmp10_);
								_vala_code_node_unref0 (type_symbol);
								return result;
							} else {
								ValaSourceReference* _tmp72_;
								const gchar* _tmp73_;
								const gchar* _tmp74_;
								gchar* _tmp75_;
								gchar* _tmp76_;
								_tmp72_ = self->source_reference;
								_tmp73_ = type_name;
								_tmp74_ = self->priv->_attribute_value;
								_tmp75_ = g_strdup_printf ("Error: enum literal of '%s' not found: %s\n", _tmp73_, _tmp74_);
								_tmp76_ = _tmp75_;
								vala_report_error (_tmp72_, "%s", _tmp76_);
								_g_free0 (_tmp76_);
								result = NULL;
								_vala_code_node_unref0 (enum_value);
								_g_free0 (type_name);
								_g_free0 (_tmp10_);
								_vala_code_node_unref0 (type_symbol);
								return result;
							}
							_vala_code_node_unref0 (enum_value);
						} else {
							ValaSourceReference* _tmp77_;
							const gchar* _tmp78_;
							gchar* _tmp79_;
							gchar* _tmp80_;
							_tmp77_ = self->source_reference;
							_tmp78_ = type_name;
							_tmp79_ = g_strdup_printf ("Error: attribute literal of '%s' type found\n", _tmp78_);
							_tmp80_ = _tmp79_;
							vala_report_error (_tmp77_, "%s", _tmp80_);
							_g_free0 (_tmp80_);
							result = NULL;
							_g_free0 (type_name);
							_g_free0 (_tmp10_);
							_vala_code_node_unref0 (type_symbol);
							return result;
						}
					}
				}
			}
		}
	}
}

ValaDataType*
gtkaml_ast_markup_attribute_get_target_type (GtkamlAstMarkupAttribute* self)
{
	ValaDataType* result;
	ValaDataType* _tmp0_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_target_type;
	result = _tmp0_;
	return result;
}

void
gtkaml_ast_markup_attribute_set_target_type (GtkamlAstMarkupAttribute* self,
                                             ValaDataType* value)
{
	ValaDataType* _tmp0_;
	g_return_if_fail (self != NULL);
	_tmp0_ = _vala_code_node_ref0 (value);
	_vala_code_node_unref0 (self->priv->_target_type);
	self->priv->_target_type = _tmp0_;
}

const gchar*
gtkaml_ast_markup_attribute_get_attribute_name (GtkamlAstMarkupAttribute* self)
{
	const gchar* result;
	const gchar* _tmp0_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->_attribute_name;
	result = _tmp0_;
	return result;
}

const gchar*
gtkaml_ast_markup_attribute_get_attribute_value (GtkamlAstMarkupAttribute* self)
{
	const gchar* result;
	const gchar* _tmp0_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_attribute_value;
	result = _tmp0_;
	return result;
}

static void
gtkaml_ast_markup_attribute_set_attribute_value (GtkamlAstMarkupAttribute* self,
                                                 const gchar* value)
{
	gchar* _tmp0_;
	g_return_if_fail (self != NULL);
	_tmp0_ = g_strdup (value);
	_g_free0 (self->priv->_attribute_value);
	self->priv->_attribute_value = _tmp0_;
}

static void
gtkaml_ast_value_markup_attribute_init (GValue* value)
{
	value->data[0].v_pointer = NULL;
}

static void
gtkaml_ast_value_markup_attribute_free_value (GValue* value)
{
	if (value->data[0].v_pointer) {
		gtkaml_ast_markup_attribute_unref (value->data[0].v_pointer);
	}
}

static void
gtkaml_ast_value_markup_attribute_copy_value (const GValue* src_value,
                                              GValue* dest_value)
{
	if (src_value->data[0].v_pointer) {
		dest_value->data[0].v_pointer = gtkaml_ast_markup_attribute_ref (src_value->data[0].v_pointer);
	} else {
		dest_value->data[0].v_pointer = NULL;
	}
}

static gpointer
gtkaml_ast_value_markup_attribute_peek_pointer (const GValue* value)
{
	return value->data[0].v_pointer;
}

static gchar*
gtkaml_ast_value_markup_attribute_collect_value (GValue* value,
                                                 guint n_collect_values,
                                                 GTypeCValue* collect_values,
                                                 guint collect_flags)
{
	if (collect_values[0].v_pointer) {
		GtkamlAstMarkupAttribute * object;
		object = collect_values[0].v_pointer;
		if (object->parent_instance.g_class == NULL) {
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		}
		value->data[0].v_pointer = gtkaml_ast_markup_attribute_ref (object);
	} else {
		value->data[0].v_pointer = NULL;
	}
	return NULL;
}

static gchar*
gtkaml_ast_value_markup_attribute_lcopy_value (const GValue* value,
                                               guint n_collect_values,
                                               GTypeCValue* collect_values,
                                               guint collect_flags)
{
	GtkamlAstMarkupAttribute ** object_p;
	object_p = collect_values[0].v_pointer;
	if (!object_p) {
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
	}
	if (!value->data[0].v_pointer) {
		*object_p = NULL;
	} else if (collect_flags & G_VALUE_NOCOPY_CONTENTS) {
		*object_p = value->data[0].v_pointer;
	} else {
		*object_p = gtkaml_ast_markup_attribute_ref (value->data[0].v_pointer);
	}
	return NULL;
}

GParamSpec*
gtkaml_ast_param_spec_markup_attribute (const gchar* name,
                                        const gchar* nick,
                                        const gchar* blurb,
                                        GType object_type,
                                        GParamFlags flags)
{
	GtkamlAstParamSpecMarkupAttribute* spec;
	g_return_val_if_fail (g_type_is_a (object_type, GTKAML_AST_TYPE_MARKUP_ATTRIBUTE), NULL);
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
	G_PARAM_SPEC (spec)->value_type = object_type;
	return G_PARAM_SPEC (spec);
}

gpointer
gtkaml_ast_value_get_markup_attribute (const GValue* value)
{
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, GTKAML_AST_TYPE_MARKUP_ATTRIBUTE), NULL);
	return value->data[0].v_pointer;
}

void
gtkaml_ast_value_set_markup_attribute (GValue* value,
                                       gpointer v_object)
{
	GtkamlAstMarkupAttribute * old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, GTKAML_AST_TYPE_MARKUP_ATTRIBUTE));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, GTKAML_AST_TYPE_MARKUP_ATTRIBUTE));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
		gtkaml_ast_markup_attribute_ref (value->data[0].v_pointer);
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		gtkaml_ast_markup_attribute_unref (old);
	}
}

void
gtkaml_ast_value_take_markup_attribute (GValue* value,
                                        gpointer v_object)
{
	GtkamlAstMarkupAttribute * old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, GTKAML_AST_TYPE_MARKUP_ATTRIBUTE));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, GTKAML_AST_TYPE_MARKUP_ATTRIBUTE));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		gtkaml_ast_markup_attribute_unref (old);
	}
}

static void
gtkaml_ast_markup_attribute_class_init (GtkamlAstMarkupAttributeClass * klass,
                                        gpointer klass_data)
{
	gtkaml_ast_markup_attribute_parent_class = g_type_class_peek_parent (klass);
	((GtkamlAstMarkupAttributeClass *) klass)->finalize = gtkaml_ast_markup_attribute_finalize;
	g_type_class_adjust_private_offset (klass, &GtkamlAstMarkupAttribute_private_offset);
	((GtkamlAstMarkupAttributeClass *) klass)->get_expression = (ValaExpression* (*) (GtkamlAstMarkupAttribute*, GtkamlMarkupResolver*, GtkamlAstMarkupTag*)) gtkaml_ast_markup_attribute_real_get_expression;
	((GtkamlAstMarkupAttributeClass *) klass)->get_assignment = (ValaStatement* (*) (GtkamlAstMarkupAttribute*, GtkamlMarkupResolver*, GtkamlAstMarkupTag*)) gtkaml_ast_markup_attribute_real_get_assignment;
	((GtkamlAstMarkupAttributeClass *) klass)->resolve = (void (*) (GtkamlAstMarkupAttribute*, GtkamlMarkupResolver*, GtkamlAstMarkupTag*)) gtkaml_ast_markup_attribute_real_resolve;
}

static void
gtkaml_ast_markup_attribute_instance_init (GtkamlAstMarkupAttribute * self,
                                           gpointer klass)
{
	self->priv = gtkaml_ast_markup_attribute_get_instance_private (self);
	self->signal = NULL;
	self->ref_count = 1;
}

static void
gtkaml_ast_markup_attribute_finalize (GtkamlAstMarkupAttribute * obj)
{
	GtkamlAstMarkupAttribute * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, GTKAML_AST_TYPE_MARKUP_ATTRIBUTE, GtkamlAstMarkupAttribute);
	g_signal_handlers_destroy (self);
	_vala_code_node_unref0 (self->priv->_target_type);
	_g_free0 (self->priv->_attribute_value);
	_vala_source_reference_unref0 (self->source_reference);
	_g_free0 (self->_attribute_name);
	_vala_code_node_unref0 (self->signal);
}

/**
 * Represents an attribute of a MarkupTag
 */
static GType
gtkaml_ast_markup_attribute_get_type_once (void)
{
	static const GTypeValueTable g_define_type_value_table = { gtkaml_ast_value_markup_attribute_init, gtkaml_ast_value_markup_attribute_free_value, gtkaml_ast_value_markup_attribute_copy_value, gtkaml_ast_value_markup_attribute_peek_pointer, "p", gtkaml_ast_value_markup_attribute_collect_value, "p", gtkaml_ast_value_markup_attribute_lcopy_value };
	static const GTypeInfo g_define_type_info = { sizeof (GtkamlAstMarkupAttributeClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) gtkaml_ast_markup_attribute_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (GtkamlAstMarkupAttribute), 0, (GInstanceInitFunc) gtkaml_ast_markup_attribute_instance_init, &g_define_type_value_table };
	static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
	GType gtkaml_ast_markup_attribute_type_id;
	gtkaml_ast_markup_attribute_type_id = g_type_register_fundamental (g_type_fundamental_next (), "GtkamlAstMarkupAttribute", &g_define_type_info, &g_define_type_fundamental_info, 0);
	GtkamlAstMarkupAttribute_private_offset = g_type_add_instance_private (gtkaml_ast_markup_attribute_type_id, sizeof (GtkamlAstMarkupAttributePrivate));
	return gtkaml_ast_markup_attribute_type_id;
}

GType
gtkaml_ast_markup_attribute_get_type (void)
{
	static volatile gsize gtkaml_ast_markup_attribute_type_id__once = 0;
	if (g_once_init_enter (&gtkaml_ast_markup_attribute_type_id__once)) {
		GType gtkaml_ast_markup_attribute_type_id;
		gtkaml_ast_markup_attribute_type_id = gtkaml_ast_markup_attribute_get_type_once ();
		g_once_init_leave (&gtkaml_ast_markup_attribute_type_id__once, gtkaml_ast_markup_attribute_type_id);
	}
	return gtkaml_ast_markup_attribute_type_id__once;
}

gpointer
gtkaml_ast_markup_attribute_ref (gpointer instance)
{
	GtkamlAstMarkupAttribute * self;
	self = instance;
	g_atomic_int_inc (&self->ref_count);
	return instance;
}

void
gtkaml_ast_markup_attribute_unref (gpointer instance)
{
	GtkamlAstMarkupAttribute * self;
	self = instance;
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
		GTKAML_AST_MARKUP_ATTRIBUTE_GET_CLASS (self)->finalize (self);
		g_type_free_instance ((GTypeInstance *) self);
	}
}

