/* gtkamlmarkupcomplexattribute.c generated by valac 0.56.16, the Vala compiler
 * generated from gtkamlmarkupcomplexattribute.vala, do not modify */

/* gtkamlmarkupcomplexattribute.vala
 *
 * Copyright (C) 2011 Vlad Grecescu
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public
 * License along with main.c; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor Boston, MA 02110-1301,  USA
 *
 * Author:
 *        Vlad Grecescu (b100dian@gmail.com)
 */

#include "gtkaml.h"
#include <vala.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <glib.h>

#if !defined(VALA_STRICT_C)
#if !defined(__clang__) && defined(__GNUC__) && (__GNUC__ >= 14)
#pragma GCC diagnostic warning "-Wincompatible-pointer-types"
#elif defined(__clang__) && (__clang_major__ >= 16)
#pragma clang diagnostic ignored "-Wincompatible-function-pointer-types"
#pragma clang diagnostic ignored "-Wincompatible-pointer-types"
#endif
#endif

#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

static gpointer gtkaml_ast_markup_complex_attribute_parent_class = NULL;

static ValaExpression* gtkaml_ast_markup_complex_attribute_real_get_expression (GtkamlAstMarkupAttribute* base,
                                                                         GtkamlMarkupResolver* resolver,
                                                                         GtkamlAstMarkupTag* markup_tag);
static void gtkaml_ast_markup_complex_attribute_finalize (GtkamlAstMarkupAttribute * obj);
static GType gtkaml_ast_markup_complex_attribute_get_type_once (void);

static gpointer
_g_object_ref0 (gpointer self)
{
	return self ? g_object_ref (self) : NULL;
}

GtkamlAstMarkupComplexAttribute*
gtkaml_ast_markup_complex_attribute_construct (GType object_type,
                                               const gchar* attribute_name,
                                               GtkamlAstMarkupTag* parent_tag,
                                               GtkamlAstMarkupTag* value_tag,
                                               ValaSourceReference* source_reference)
{
	GtkamlAstMarkupComplexAttribute* self = NULL;
	const gchar* _tmp0_;
	const gchar* _tmp1_;
	GtkamlAstMarkupTag* _tmp2_;
	g_return_val_if_fail (attribute_name != NULL, NULL);
	g_return_val_if_fail (parent_tag != NULL, NULL);
	g_return_val_if_fail (value_tag != NULL, NULL);
	_tmp0_ = gtkaml_ast_markup_tag_get_me (parent_tag);
	_tmp1_ = _tmp0_;
	self = (GtkamlAstMarkupComplexAttribute*) gtkaml_ast_markup_attribute_construct (object_type, attribute_name, _tmp1_, source_reference);
	_tmp2_ = _g_object_ref0 (value_tag);
	_g_object_unref0 (self->value_tag);
	self->value_tag = _tmp2_;
	return self;
}

GtkamlAstMarkupComplexAttribute*
gtkaml_ast_markup_complex_attribute_new (const gchar* attribute_name,
                                         GtkamlAstMarkupTag* parent_tag,
                                         GtkamlAstMarkupTag* value_tag,
                                         ValaSourceReference* source_reference)
{
	return gtkaml_ast_markup_complex_attribute_construct (GTKAML_AST_TYPE_MARKUP_COMPLEX_ATTRIBUTE, attribute_name, parent_tag, value_tag, source_reference);
}

static ValaExpression*
gtkaml_ast_markup_complex_attribute_real_get_expression (GtkamlAstMarkupAttribute* base,
                                                         GtkamlMarkupResolver* resolver,
                                                         GtkamlAstMarkupTag* markup_tag)
{
	GtkamlAstMarkupComplexAttribute * self;
	ValaSignal* _tmp0_;
	ValaExpression* result;
	self = (GtkamlAstMarkupComplexAttribute*) base;
	g_return_val_if_fail (resolver != NULL, NULL);
	g_return_val_if_fail (markup_tag != NULL, NULL);
	gtkaml_ast_markup_attribute_resolve ((GtkamlAstMarkupAttribute*) self, resolver, markup_tag);
	_tmp0_ = ((GtkamlAstMarkupAttribute*) self)->signal;
	if (_tmp0_ != NULL) {
		ValaSourceReference* _tmp1_;
		_tmp1_ = ((GtkamlAstMarkupAttribute*) self)->source_reference;
		vala_report_error (_tmp1_, "Signals cannot be defined as complex attributes");
		result = NULL;
		return result;
	} else {
		GtkamlAstMarkupTag* _tmp2_;
		const gchar* _tmp3_;
		const gchar* _tmp4_;
		ValaSourceReference* _tmp5_;
		ValaMemberAccess* _tmp6_;
		_tmp2_ = self->value_tag;
		_tmp3_ = gtkaml_ast_markup_tag_get_me (_tmp2_);
		_tmp4_ = _tmp3_;
		_tmp5_ = ((GtkamlAstMarkupAttribute*) self)->source_reference;
		_tmp6_ = vala_member_access_new_simple (_tmp4_, _tmp5_);
		result = (ValaExpression*) _tmp6_;
		return result;
	}
}

static void
gtkaml_ast_markup_complex_attribute_class_init (GtkamlAstMarkupComplexAttributeClass * klass,
                                                gpointer klass_data)
{
	gtkaml_ast_markup_complex_attribute_parent_class = g_type_class_peek_parent (klass);
	((GtkamlAstMarkupAttributeClass *) klass)->finalize = gtkaml_ast_markup_complex_attribute_finalize;
	((GtkamlAstMarkupAttributeClass *) klass)->get_expression = (ValaExpression* (*) (GtkamlAstMarkupAttribute*, GtkamlMarkupResolver*, GtkamlAstMarkupTag*)) gtkaml_ast_markup_complex_attribute_real_get_expression;
}

static void
gtkaml_ast_markup_complex_attribute_instance_init (GtkamlAstMarkupComplexAttribute * self,
                                                   gpointer klass)
{
}

static void
gtkaml_ast_markup_complex_attribute_finalize (GtkamlAstMarkupAttribute * obj)
{
	GtkamlAstMarkupComplexAttribute * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, GTKAML_AST_TYPE_MARKUP_COMPLEX_ATTRIBUTE, GtkamlAstMarkupComplexAttribute);
	_g_object_unref0 (self->value_tag);
	GTKAML_AST_MARKUP_ATTRIBUTE_CLASS (gtkaml_ast_markup_complex_attribute_parent_class)->finalize (obj);
}

/**
 * An attribute whose value is represented as another MarkupTag
 */
static GType
gtkaml_ast_markup_complex_attribute_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (GtkamlAstMarkupComplexAttributeClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) gtkaml_ast_markup_complex_attribute_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (GtkamlAstMarkupComplexAttribute), 0, (GInstanceInitFunc) gtkaml_ast_markup_complex_attribute_instance_init, NULL };
	GType gtkaml_ast_markup_complex_attribute_type_id;
	gtkaml_ast_markup_complex_attribute_type_id = g_type_register_static (GTKAML_AST_TYPE_MARKUP_ATTRIBUTE, "GtkamlAstMarkupComplexAttribute", &g_define_type_info, 0);
	return gtkaml_ast_markup_complex_attribute_type_id;
}

GType
gtkaml_ast_markup_complex_attribute_get_type (void)
{
	static volatile gsize gtkaml_ast_markup_complex_attribute_type_id__once = 0;
	if (g_once_init_enter (&gtkaml_ast_markup_complex_attribute_type_id__once)) {
		GType gtkaml_ast_markup_complex_attribute_type_id;
		gtkaml_ast_markup_complex_attribute_type_id = gtkaml_ast_markup_complex_attribute_get_type_once ();
		g_once_init_leave (&gtkaml_ast_markup_complex_attribute_type_id__once, gtkaml_ast_markup_complex_attribute_type_id);
	}
	return gtkaml_ast_markup_complex_attribute_type_id__once;
}

