/* gtkamlmarkupunresolvedtag.c generated by valac 0.56.16, the Vala compiler
 * generated from gtkamlmarkupunresolvedtag.vala, do not modify */

/* gtkamlmarkupunresolvedtag.vala
 *
 * Copyright (C) 2011 Vlad Grecescu
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public
 * License along with main.c; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor Boston, MA 02110-1301,  USA
 *
 * Author:
 *        Vlad Grecescu (b100dian@gmail.com)
 */

#include "gtkaml.h"
#include <stdlib.h>
#include <string.h>
#include <glib.h>
#include <glib-object.h>
#include <vala.h>
#include <valagee.h>

#if !defined(VALA_STRICT_C)
#if !defined(__clang__) && defined(__GNUC__) && (__GNUC__ >= 14)
#pragma GCC diagnostic warning "-Wincompatible-pointer-types"
#elif defined(__clang__) && (__clang_major__ >= 16)
#pragma clang diagnostic ignored "-Wincompatible-function-pointer-types"
#pragma clang diagnostic ignored "-Wincompatible-pointer-types"
#endif
#endif

enum  {
	GTKAML_AST_MARKUP_UNRESOLVED_TAG_0_PROPERTY,
	GTKAML_AST_MARKUP_UNRESOLVED_TAG_ME_PROPERTY,
	GTKAML_AST_MARKUP_UNRESOLVED_TAG_NUM_PROPERTIES
};
static GParamSpec* gtkaml_ast_markup_unresolved_tag_properties[GTKAML_AST_MARKUP_UNRESOLVED_TAG_NUM_PROPERTIES];
#define _gtkaml_ast_markup_attribute_unref0(var) ((var == NULL) ? NULL : (var = (gtkaml_ast_markup_attribute_unref (var), NULL)))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))

static gpointer gtkaml_ast_markup_unresolved_tag_parent_class = NULL;

static void gtkaml_ast_markup_unresolved_tag_real_generate_public_ast (GtkamlAstMarkupTag* base,
                                                                GtkamlCodeParserProvider* parser);
static GtkamlAstMarkupTag* gtkaml_ast_markup_unresolved_tag_real_resolve (GtkamlAstMarkupTag* base,
                                                                   GtkamlMarkupResolver* resolver);
static void gtkaml_ast_markup_unresolved_tag_resolve_silently (GtkamlAstMarkupUnresolvedTag* self,
                                                        GtkamlMarkupResolver* resolver);
static GtkamlAstMarkupComplexAttribute* gtkaml_ast_markup_unresolved_tag_mutate_into_complex_attribute (GtkamlAstMarkupUnresolvedTag* self,
                                                                                                 GtkamlAstMarkupChildTag* child_tag,
                                                                                                 GtkamlMarkupResolver* resolver);
static void gtkaml_ast_markup_unresolved_tag_real_generate (GtkamlAstMarkupTag* base,
                                                     GtkamlMarkupResolver* resolver);
static GType gtkaml_ast_markup_unresolved_tag_get_type_once (void);
static void _vala_gtkaml_ast_markup_unresolved_tag_get_property (GObject * object,
                                                          guint property_id,
                                                          GValue * value,
                                                          GParamSpec * pspec);

GtkamlAstMarkupUnresolvedTag*
gtkaml_ast_markup_unresolved_tag_construct (GType object_type,
                                            GtkamlAstMarkupTag* parent_tag,
                                            const gchar* tag_name,
                                            GtkamlMarkupNamespace* tag_namespace,
                                            ValaSourceReference* source_reference)
{
	GtkamlAstMarkupUnresolvedTag * self = NULL;
	g_return_val_if_fail (parent_tag != NULL, NULL);
	g_return_val_if_fail (tag_name != NULL, NULL);
	g_return_val_if_fail (tag_namespace != NULL, NULL);
	self = (GtkamlAstMarkupUnresolvedTag*) gtkaml_ast_markup_child_tag_construct (object_type, parent_tag, tag_name, tag_namespace, source_reference);
	return self;
}

GtkamlAstMarkupUnresolvedTag*
gtkaml_ast_markup_unresolved_tag_new (GtkamlAstMarkupTag* parent_tag,
                                      const gchar* tag_name,
                                      GtkamlMarkupNamespace* tag_namespace,
                                      ValaSourceReference* source_reference)
{
	return gtkaml_ast_markup_unresolved_tag_construct (GTKAML_AST_TYPE_MARKUP_UNRESOLVED_TAG, parent_tag, tag_name, tag_namespace, source_reference);
}

static void
gtkaml_ast_markup_unresolved_tag_real_generate_public_ast (GtkamlAstMarkupTag* base,
                                                           GtkamlCodeParserProvider* parser)
{
	GtkamlAstMarkupUnresolvedTag * self;
	self = (GtkamlAstMarkupUnresolvedTag*) base;
	g_return_if_fail (parser != NULL);
}

static GtkamlAstMarkupTag*
gtkaml_ast_markup_unresolved_tag_real_resolve (GtkamlAstMarkupTag* base,
                                               GtkamlMarkupResolver* resolver)
{
	GtkamlAstMarkupUnresolvedTag * self;
	gboolean _tmp0_ = FALSE;
	GtkamlMarkupNamespace* _tmp1_;
	GtkamlMarkupNamespace* _tmp2_;
	gboolean _tmp3_;
	gboolean _tmp4_;
	GtkamlAstMarkupTemp* markup_temp = NULL;
	GtkamlAstMarkupTag* _tmp39_;
	GtkamlAstMarkupTag* _tmp40_;
	const gchar* _tmp41_;
	const gchar* _tmp42_;
	GtkamlMarkupNamespace* _tmp43_;
	GtkamlMarkupNamespace* _tmp44_;
	ValaSourceReference* _tmp45_;
	ValaSourceReference* _tmp46_;
	GtkamlAstMarkupTemp* _tmp47_;
	GtkamlAstMarkupTemp* _tmp48_;
	GtkamlAstMarkupTag* _tmp49_;
	GtkamlAstMarkupTag* _tmp50_;
	GtkamlAstMarkupTag* _tmp51_;
	GtkamlAstMarkupTag* _tmp52_;
	GtkamlAstMarkupTemp* _tmp53_;
	GtkamlAstMarkupTag* result;
	self = (GtkamlAstMarkupUnresolvedTag*) base;
	g_return_val_if_fail (resolver != NULL, NULL);
	gtkaml_ast_markup_unresolved_tag_resolve_silently (self, resolver);
	_tmp1_ = gtkaml_ast_markup_tag_get_tag_namespace ((GtkamlAstMarkupTag*) self);
	_tmp2_ = _tmp1_;
	_tmp3_ = gtkaml_markup_namespace_get_explicit_prefix (_tmp2_);
	_tmp4_ = _tmp3_;
	if (!_tmp4_) {
		ValaList* _tmp5_;
		gint _tmp6_;
		gint _tmp7_;
		_tmp5_ = ((GtkamlAstMarkupTag*) self)->markup_attributes;
		_tmp6_ = vala_collection_get_size ((ValaCollection*) _tmp5_);
		_tmp7_ = _tmp6_;
		_tmp0_ = _tmp7_ == 0;
	} else {
		_tmp0_ = FALSE;
	}
	if (_tmp0_) {
		ValaDataType* _tmp8_;
		ValaDataType* _tmp9_;
		ValaTypeSymbol* _tmp10_;
		ValaTypeSymbol* _tmp11_;
		_tmp8_ = gtkaml_ast_markup_tag_get_resolved_type ((GtkamlAstMarkupTag*) self);
		_tmp9_ = _tmp8_;
		_tmp10_ = vala_data_type_get_type_symbol (_tmp9_);
		_tmp11_ = _tmp10_;
		if (_tmp11_ == NULL) {
			ValaList* _tmp12_;
			gint _tmp13_;
			gint _tmp14_;
			_tmp12_ = ((GtkamlAstMarkupTag*) self)->child_tags;
			_tmp13_ = vala_collection_get_size ((ValaCollection*) _tmp12_);
			_tmp14_ = _tmp13_;
			switch (_tmp14_) {
				case 0:
				{
					GtkamlAstMarkupTag* _tmp15_;
					GtkamlAstMarkupTag* _tmp16_;
					const gchar* _tmp17_;
					const gchar* _tmp18_;
					const gchar* _tmp19_;
					const gchar* _tmp20_;
					ValaSourceReference* _tmp21_;
					ValaSourceReference* _tmp22_;
					GtkamlAstMarkupAttribute* _tmp23_;
					GtkamlAstMarkupAttribute* _tmp24_;
					_tmp15_ = gtkaml_ast_markup_child_tag_get_parent_tag ((GtkamlAstMarkupChildTag*) self);
					_tmp16_ = _tmp15_;
					_tmp17_ = gtkaml_ast_markup_tag_get_tag_name ((GtkamlAstMarkupTag*) self);
					_tmp18_ = _tmp17_;
					_tmp19_ = gtkaml_ast_markup_tag_get_text ((GtkamlAstMarkupTag*) self);
					_tmp20_ = _tmp19_;
					_tmp21_ = gtkaml_ast_markup_tag_get_source_reference ((GtkamlAstMarkupTag*) self);
					_tmp22_ = _tmp21_;
					_tmp23_ = gtkaml_ast_markup_attribute_new (_tmp18_, _tmp20_, _tmp22_);
					_tmp24_ = _tmp23_;
					gtkaml_ast_markup_tag_add_markup_attribute (_tmp16_, _tmp24_);
					_gtkaml_ast_markup_attribute_unref0 (_tmp24_);
					result = NULL;
					return result;
				}
				case 1:
				{
					GtkamlAstMarkupComplexAttribute* complex_attribute = NULL;
					ValaList* _tmp25_;
					gpointer _tmp26_;
					GtkamlAstMarkupChildTag* _tmp27_;
					GtkamlAstMarkupComplexAttribute* _tmp28_;
					GtkamlAstMarkupComplexAttribute* _tmp29_;
					GtkamlAstMarkupTag* _tmp30_;
					GtkamlAstMarkupTag* _tmp31_;
					GtkamlAstMarkupComplexAttribute* _tmp32_;
					_tmp25_ = ((GtkamlAstMarkupTag*) self)->child_tags;
					_tmp26_ = vala_list_get (_tmp25_, 0);
					_tmp27_ = (GtkamlAstMarkupChildTag*) _tmp26_;
					_tmp28_ = gtkaml_ast_markup_unresolved_tag_mutate_into_complex_attribute (self, _tmp27_, resolver);
					_tmp29_ = _tmp28_;
					_g_object_unref0 (_tmp27_);
					complex_attribute = _tmp29_;
					_tmp30_ = gtkaml_ast_markup_child_tag_get_parent_tag ((GtkamlAstMarkupChildTag*) self);
					_tmp31_ = _tmp30_;
					_tmp32_ = complex_attribute;
					gtkaml_ast_markup_tag_add_markup_attribute (_tmp31_, (GtkamlAstMarkupAttribute*) _tmp32_);
					result = NULL;
					_gtkaml_ast_markup_attribute_unref0 (complex_attribute);
					return result;
				}
				default:
				{
					ValaSourceReference* _tmp33_;
					ValaSourceReference* _tmp34_;
					const gchar* _tmp35_;
					const gchar* _tmp36_;
					gchar* _tmp37_;
					gchar* _tmp38_;
					_tmp33_ = gtkaml_ast_markup_tag_get_source_reference ((GtkamlAstMarkupTag*) self);
					_tmp34_ = _tmp33_;
					_tmp35_ = gtkaml_ast_markup_tag_get_tag_name ((GtkamlAstMarkupTag*) self);
					_tmp36_ = _tmp35_;
					_tmp37_ = g_strdup_printf ("Don't know how to handle `%s's children", _tmp36_);
					_tmp38_ = _tmp37_;
					vala_report_error (_tmp34_, "%s", _tmp38_);
					_g_free0 (_tmp38_);
					result = NULL;
					return result;
				}
			}
		}
	}
	_tmp39_ = gtkaml_ast_markup_child_tag_get_parent_tag ((GtkamlAstMarkupChildTag*) self);
	_tmp40_ = _tmp39_;
	_tmp41_ = gtkaml_ast_markup_tag_get_tag_name ((GtkamlAstMarkupTag*) self);
	_tmp42_ = _tmp41_;
	_tmp43_ = gtkaml_ast_markup_tag_get_tag_namespace ((GtkamlAstMarkupTag*) self);
	_tmp44_ = _tmp43_;
	_tmp45_ = gtkaml_ast_markup_tag_get_source_reference ((GtkamlAstMarkupTag*) self);
	_tmp46_ = _tmp45_;
	_tmp47_ = gtkaml_ast_markup_temp_new (_tmp40_, _tmp42_, _tmp44_, _tmp46_);
	markup_temp = _tmp47_;
	_tmp48_ = markup_temp;
	_tmp49_ = gtkaml_ast_markup_tag_resolve ((GtkamlAstMarkupTag*) _tmp48_, resolver);
	_tmp50_ = _tmp49_;
	_g_object_unref0 (_tmp50_);
	_tmp51_ = gtkaml_ast_markup_child_tag_get_parent_tag ((GtkamlAstMarkupChildTag*) self);
	_tmp52_ = _tmp51_;
	_tmp53_ = markup_temp;
	gtkaml_ast_markup_tag_replace_child_tag (_tmp52_, (GtkamlAstMarkupChildTag*) self, (GtkamlAstMarkupChildTag*) _tmp53_);
	result = (GtkamlAstMarkupTag*) markup_temp;
	return result;
}

static void
gtkaml_ast_markup_unresolved_tag_real_generate (GtkamlAstMarkupTag* base,
                                                GtkamlMarkupResolver* resolver)
{
	GtkamlAstMarkupUnresolvedTag * self;
	self = (GtkamlAstMarkupUnresolvedTag*) base;
	g_return_if_fail (resolver != NULL);
	g_assert_not_reached ();
}

static GtkamlAstMarkupComplexAttribute*
gtkaml_ast_markup_unresolved_tag_mutate_into_complex_attribute (GtkamlAstMarkupUnresolvedTag* self,
                                                                GtkamlAstMarkupChildTag* child_tag,
                                                                GtkamlMarkupResolver* resolver)
{
	GtkamlAstMarkupChildTag* resolved_child = NULL;
	GtkamlAstMarkupTag* _tmp0_;
	GtkamlAstMarkupChildTag* _tmp1_;
	const gchar* _tmp2_;
	const gchar* _tmp3_;
	GtkamlAstMarkupTag* _tmp4_;
	GtkamlAstMarkupTag* _tmp5_;
	ValaSourceReference* _tmp6_;
	ValaSourceReference* _tmp7_;
	GtkamlAstMarkupComplexAttribute* _tmp8_;
	GtkamlAstMarkupComplexAttribute* result;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (child_tag != NULL, NULL);
	g_return_val_if_fail (resolver != NULL, NULL);
	_tmp0_ = gtkaml_ast_markup_tag_resolve ((GtkamlAstMarkupTag*) child_tag, resolver);
	_tmp1_ = GTKAML_AST_IS_MARKUP_CHILD_TAG (_tmp0_) ? ((GtkamlAstMarkupChildTag*) _tmp0_) : NULL;
	if (_tmp1_ == NULL) {
		_g_object_unref0 (_tmp0_);
	}
	resolved_child = _tmp1_;
	gtkaml_ast_markup_child_tag_set_standalone (resolved_child, TRUE);
	gtkaml_ast_markup_tag_resolve_attributes ((GtkamlAstMarkupTag*) resolved_child, resolver);
	_tmp2_ = gtkaml_ast_markup_tag_get_tag_name ((GtkamlAstMarkupTag*) self);
	_tmp3_ = _tmp2_;
	_tmp4_ = gtkaml_ast_markup_child_tag_get_parent_tag ((GtkamlAstMarkupChildTag*) self);
	_tmp5_ = _tmp4_;
	_tmp6_ = gtkaml_ast_markup_tag_get_source_reference ((GtkamlAstMarkupTag*) self);
	_tmp7_ = _tmp6_;
	_tmp8_ = gtkaml_ast_markup_complex_attribute_new (_tmp3_, _tmp5_, (GtkamlAstMarkupTag*) resolved_child, _tmp7_);
	result = _tmp8_;
	_g_object_unref0 (resolved_child);
	return result;
}

static void
gtkaml_ast_markup_unresolved_tag_resolve_silently (GtkamlAstMarkupUnresolvedTag* self,
                                                   GtkamlMarkupResolver* resolver)
{
	ValaDataType* _tmp0_;
	ValaDataType* _tmp1_;
	ValaDataType* _tmp2_;
	ValaDataType* _tmp3_;
	ValaUnresolvedSymbol* _tmp4_;
	ValaUnresolvedSymbol* _tmp5_;
	ValaDataType* _tmp6_;
	ValaDataType* _tmp7_;
	ValaDataType* _tmp8_;
	ValaDataType* _tmp9_;
	ValaUnresolvedSymbol* _tmp10_;
	ValaUnresolvedSymbol* _tmp11_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (resolver != NULL);
	_tmp0_ = gtkaml_ast_markup_tag_get_data_type ((GtkamlAstMarkupTag*) self);
	_tmp1_ = _tmp0_;
	if (!G_TYPE_CHECK_INSTANCE_TYPE (_tmp1_, VALA_TYPE_UNRESOLVED_TYPE)) {
		return;
	}
	_tmp2_ = gtkaml_ast_markup_tag_get_data_type ((GtkamlAstMarkupTag*) self);
	_tmp3_ = _tmp2_;
	_tmp4_ = vala_unresolved_type_get_unresolved_symbol (G_TYPE_CHECK_INSTANCE_CAST (_tmp3_, VALA_TYPE_UNRESOLVED_TYPE, ValaUnresolvedType));
	_tmp5_ = _tmp4_;
	vala_code_node_set_error ((ValaCodeNode*) _tmp5_, TRUE);
	_tmp6_ = gtkaml_ast_markup_tag_get_data_type ((GtkamlAstMarkupTag*) self);
	_tmp7_ = _tmp6_;
	vala_code_node_accept ((ValaCodeNode*) _tmp7_, (ValaCodeVisitor*) resolver);
	_tmp8_ = gtkaml_ast_markup_tag_get_data_type ((GtkamlAstMarkupTag*) self);
	_tmp9_ = _tmp8_;
	_tmp10_ = vala_unresolved_type_get_unresolved_symbol (G_TYPE_CHECK_INSTANCE_CAST (_tmp9_, VALA_TYPE_UNRESOLVED_TYPE, ValaUnresolvedType));
	_tmp11_ = _tmp10_;
	vala_code_node_set_error ((ValaCodeNode*) _tmp11_, FALSE);
}

static const gchar*
gtkaml_ast_markup_unresolved_tag_real_get_me (GtkamlAstMarkupTag* base)
{
	GtkamlAstMarkupUnresolvedTag* self;
	self = (GtkamlAstMarkupUnresolvedTag*) base;
	g_assert_not_reached ();
}

static void
gtkaml_ast_markup_unresolved_tag_class_init (GtkamlAstMarkupUnresolvedTagClass * klass,
                                             gpointer klass_data)
{
	gtkaml_ast_markup_unresolved_tag_parent_class = g_type_class_peek_parent (klass);
	((GtkamlAstMarkupTagClass *) klass)->generate_public_ast = (void (*) (GtkamlAstMarkupTag*, GtkamlCodeParserProvider*)) gtkaml_ast_markup_unresolved_tag_real_generate_public_ast;
	((GtkamlAstMarkupTagClass *) klass)->resolve = (GtkamlAstMarkupTag* (*) (GtkamlAstMarkupTag*, GtkamlMarkupResolver*)) gtkaml_ast_markup_unresolved_tag_real_resolve;
	((GtkamlAstMarkupTagClass *) klass)->generate = (void (*) (GtkamlAstMarkupTag*, GtkamlMarkupResolver*)) gtkaml_ast_markup_unresolved_tag_real_generate;
	GTKAML_AST_MARKUP_TAG_CLASS (klass)->get_me = (const gchar* (*) (GtkamlAstMarkupTag*)) gtkaml_ast_markup_unresolved_tag_real_get_me;
	G_OBJECT_CLASS (klass)->get_property = _vala_gtkaml_ast_markup_unresolved_tag_get_property;
	g_object_class_install_property (G_OBJECT_CLASS (klass), GTKAML_AST_MARKUP_UNRESOLVED_TAG_ME_PROPERTY, gtkaml_ast_markup_unresolved_tag_properties[GTKAML_AST_MARKUP_UNRESOLVED_TAG_ME_PROPERTY] = g_param_spec_string ("me", "me", "me", NULL, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE));
}

static void
gtkaml_ast_markup_unresolved_tag_instance_init (GtkamlAstMarkupUnresolvedTag * self,
                                                gpointer klass)
{
}

/**
 * Any markup tag encountered in XML that is not the root, nor has g:public/g:private identifier.
 * Can later morph into a complex attribute or into a temp
 */
static GType
gtkaml_ast_markup_unresolved_tag_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (GtkamlAstMarkupUnresolvedTagClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) gtkaml_ast_markup_unresolved_tag_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (GtkamlAstMarkupUnresolvedTag), 0, (GInstanceInitFunc) gtkaml_ast_markup_unresolved_tag_instance_init, NULL };
	GType gtkaml_ast_markup_unresolved_tag_type_id;
	gtkaml_ast_markup_unresolved_tag_type_id = g_type_register_static (GTKAML_AST_TYPE_MARKUP_CHILD_TAG, "GtkamlAstMarkupUnresolvedTag", &g_define_type_info, 0);
	return gtkaml_ast_markup_unresolved_tag_type_id;
}

GType
gtkaml_ast_markup_unresolved_tag_get_type (void)
{
	static volatile gsize gtkaml_ast_markup_unresolved_tag_type_id__once = 0;
	if (g_once_init_enter (&gtkaml_ast_markup_unresolved_tag_type_id__once)) {
		GType gtkaml_ast_markup_unresolved_tag_type_id;
		gtkaml_ast_markup_unresolved_tag_type_id = gtkaml_ast_markup_unresolved_tag_get_type_once ();
		g_once_init_leave (&gtkaml_ast_markup_unresolved_tag_type_id__once, gtkaml_ast_markup_unresolved_tag_type_id);
	}
	return gtkaml_ast_markup_unresolved_tag_type_id__once;
}

static void
_vala_gtkaml_ast_markup_unresolved_tag_get_property (GObject * object,
                                                     guint property_id,
                                                     GValue * value,
                                                     GParamSpec * pspec)
{
	GtkamlAstMarkupUnresolvedTag * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, GTKAML_AST_TYPE_MARKUP_UNRESOLVED_TAG, GtkamlAstMarkupUnresolvedTag);
	switch (property_id) {
		case GTKAML_AST_MARKUP_UNRESOLVED_TAG_ME_PROPERTY:
		g_value_set_string (value, gtkaml_ast_markup_tag_get_me ((GtkamlAstMarkupTag*) self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}

