/* gtkamlmarkupclass.c generated by valac 0.56.16, the Vala compiler
 * generated from gtkamlmarkupclass.vala, do not modify */

/* gtkamlmarkupclass.vala
 *
 * Copyright (C) 2011 Vlad Grecescu
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public
 * License along with main.c; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor Boston, MA 02110-1301,  USA
 *
 * Author:
 *        Vlad Grecescu (b100dian@gmail.com)
 */

#include "gtkaml.h"
#include <vala.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <glib.h>

#if !defined(VALA_STRICT_C)
#if !defined(__clang__) && defined(__GNUC__) && (__GNUC__ >= 14)
#pragma GCC diagnostic warning "-Wincompatible-pointer-types"
#elif defined(__clang__) && (__clang_major__ >= 16)
#pragma clang diagnostic ignored "-Wincompatible-function-pointer-types"
#pragma clang diagnostic ignored "-Wincompatible-pointer-types"
#endif
#endif

#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

struct _GtkamlMarkupClassPrivate {
	GtkamlAstMarkupTag* _markup_root;
};

static gint GtkamlMarkupClass_private_offset;
static gpointer gtkaml_markupclass_parent_class = NULL;

static void gtkaml_markupclass_real_accept_children (ValaCodeNode* base,
                                              ValaCodeVisitor* visitor);
static void gtkaml_markupclass_finalize (ValaCodeNode * obj);
static GType gtkaml_markupclass_get_type_once (void);

static inline gpointer
gtkaml_markupclass_get_instance_private (GtkamlMarkupClass* self)
{
	return G_STRUCT_MEMBER_P (self, GtkamlMarkupClass_private_offset);
}

GtkamlMarkupClass*
gtkaml_markupclass_construct (GType object_type,
                              const gchar* tag_name,
                              GtkamlMarkupNamespace* tag_namespace,
                              const gchar* class_name,
                              ValaSourceReference* source_reference)
{
	GtkamlMarkupClass* self = NULL;
	GtkamlAstMarkupRoot* _tmp0_;
	GtkamlAstMarkupRoot* _tmp1_;
	g_return_val_if_fail (tag_name != NULL, NULL);
	g_return_val_if_fail (tag_namespace != NULL, NULL);
	g_return_val_if_fail (class_name != NULL, NULL);
	self = (GtkamlMarkupClass*) vala_class_construct (object_type, class_name, source_reference, NULL);
	_tmp0_ = gtkaml_ast_markup_root_new (self, tag_name, tag_namespace, source_reference);
	_tmp1_ = _tmp0_;
	gtkaml_markupclass_set_markup_root (self, (GtkamlAstMarkupTag*) _tmp1_);
	_g_object_unref0 (_tmp1_);
	return self;
}

GtkamlMarkupClass*
gtkaml_markupclass_new (const gchar* tag_name,
                        GtkamlMarkupNamespace* tag_namespace,
                        const gchar* class_name,
                        ValaSourceReference* source_reference)
{
	return gtkaml_markupclass_construct (GTKAML_TYPE_MARKUPCLASS, tag_name, tag_namespace, class_name, source_reference);
}

static void
gtkaml_markupclass_real_accept_children (ValaCodeNode* base,
                                         ValaCodeVisitor* visitor)
{
	GtkamlMarkupClass * self;
	self = (GtkamlMarkupClass*) base;
	g_return_if_fail (visitor != NULL);
	if (GTKAML_IS_MARKUP_RESOLVER (visitor)) {
		gtkaml_markup_resolver_visit_markup_class (G_TYPE_CHECK_INSTANCE_CAST (visitor, GTKAML_TYPE_MARKUP_RESOLVER, GtkamlMarkupResolver), self);
	}
	VALA_CODE_NODE_CLASS (gtkaml_markupclass_parent_class)->accept_children ((ValaCodeNode*) G_TYPE_CHECK_INSTANCE_CAST (self, VALA_TYPE_CLASS, ValaClass), visitor);
}

GtkamlAstMarkupTag*
gtkaml_markupclass_get_markup_root (GtkamlMarkupClass* self)
{
	GtkamlAstMarkupTag* result;
	GtkamlAstMarkupTag* _tmp0_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_markup_root;
	result = _tmp0_;
	return result;
}

static gpointer
_g_object_ref0 (gpointer self)
{
	return self ? g_object_ref (self) : NULL;
}

void
gtkaml_markupclass_set_markup_root (GtkamlMarkupClass* self,
                                    GtkamlAstMarkupTag* value)
{
	GtkamlAstMarkupTag* _tmp0_;
	g_return_if_fail (self != NULL);
	_tmp0_ = _g_object_ref0 (value);
	_g_object_unref0 (self->priv->_markup_root);
	self->priv->_markup_root = _tmp0_;
}

static void
gtkaml_markupclass_class_init (GtkamlMarkupClassClass * klass,
                               gpointer klass_data)
{
	gtkaml_markupclass_parent_class = g_type_class_peek_parent (klass);
	((ValaCodeNodeClass *) klass)->finalize = gtkaml_markupclass_finalize;
	g_type_class_adjust_private_offset (klass, &GtkamlMarkupClass_private_offset);
	((ValaCodeNodeClass *) klass)->accept_children = (void (*) (ValaCodeNode*, ValaCodeVisitor*)) gtkaml_markupclass_real_accept_children;
}

static void
gtkaml_markupclass_instance_init (GtkamlMarkupClass * self,
                                  gpointer klass)
{
	self->priv = gtkaml_markupclass_get_instance_private (self);
}

static void
gtkaml_markupclass_finalize (ValaCodeNode * obj)
{
	GtkamlMarkupClass * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, GTKAML_TYPE_MARKUPCLASS, GtkamlMarkupClass);
	_g_object_unref0 (self->priv->_markup_root);
	VALA_CODE_NODE_CLASS (gtkaml_markupclass_parent_class)->finalize (obj);
}

/**
 * Represents a Class as declared by a Gtkaml root node. 
 * This is mainly used to identify that after parsing, a Gtkaml markup resolver needs to be used on this specific class
 */
static GType
gtkaml_markupclass_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (GtkamlMarkupClassClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) gtkaml_markupclass_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (GtkamlMarkupClass), 0, (GInstanceInitFunc) gtkaml_markupclass_instance_init, NULL };
	GType gtkaml_markupclass_type_id;
	gtkaml_markupclass_type_id = g_type_register_static (VALA_TYPE_CLASS, "GtkamlMarkupClass", &g_define_type_info, 0);
	GtkamlMarkupClass_private_offset = g_type_add_instance_private (gtkaml_markupclass_type_id, sizeof (GtkamlMarkupClassPrivate));
	return gtkaml_markupclass_type_id;
}

GType
gtkaml_markupclass_get_type (void)
{
	static volatile gsize gtkaml_markupclass_type_id__once = 0;
	if (g_once_init_enter (&gtkaml_markupclass_type_id__once)) {
		GType gtkaml_markupclass_type_id;
		gtkaml_markupclass_type_id = gtkaml_markupclass_get_type_once ();
		g_once_init_leave (&gtkaml_markupclass_type_id__once, gtkaml_markupclass_type_id);
	}
	return gtkaml_markupclass_type_id__once;
}

