/* gtkamlmarkupnamespace.c generated by valac 0.56.16, the Vala compiler
 * generated from gtkamlmarkupnamespace.vala, do not modify */

/* gtkamlmarkupnamespace.vala
 *
 * Copyright (C) 2011 Vlad Grecescu
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public
 * License along with main.c; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor Boston, MA 02110-1301,  USA
 *
 * Author:
 *        Vlad Grecescu (b100dian@gmail.com)
 */

#include "gtkaml.h"
#include <glib.h>
#include <glib-object.h>
#include <vala.h>
#include <stdlib.h>
#include <string.h>

#if !defined(VALA_STRICT_C)
#if !defined(__clang__) && defined(__GNUC__) && (__GNUC__ >= 14)
#pragma GCC diagnostic warning "-Wincompatible-pointer-types"
#elif defined(__clang__) && (__clang_major__ >= 16)
#pragma clang diagnostic ignored "-Wincompatible-function-pointer-types"
#pragma clang diagnostic ignored "-Wincompatible-pointer-types"
#endif
#endif

struct _GtkamlMarkupNamespacePrivate {
	gboolean _explicit_prefix;
};

static gint GtkamlMarkupNamespace_private_offset;
static gpointer gtkaml_markup_namespace_parent_class = NULL;

static void gtkaml_markup_namespace_finalize (ValaCodeNode * obj);
static GType gtkaml_markup_namespace_get_type_once (void);

static inline gpointer
gtkaml_markup_namespace_get_instance_private (GtkamlMarkupNamespace* self)
{
	return G_STRUCT_MEMBER_P (self, GtkamlMarkupNamespace_private_offset);
}

GtkamlMarkupNamespace*
gtkaml_markup_namespace_construct (GType object_type,
                                   ValaUnresolvedSymbol* inner,
                                   const gchar* name,
                                   ValaSourceReference* source_reference)
{
	GtkamlMarkupNamespace* self = NULL;
	g_return_val_if_fail (name != NULL, NULL);
	self = (GtkamlMarkupNamespace*) vala_unresolved_symbol_construct (object_type, inner, name, source_reference);
	return self;
}

GtkamlMarkupNamespace*
gtkaml_markup_namespace_new (ValaUnresolvedSymbol* inner,
                             const gchar* name,
                             ValaSourceReference* source_reference)
{
	return gtkaml_markup_namespace_construct (GTKAML_TYPE_MARKUP_NAMESPACE, inner, name, source_reference);
}

gboolean
gtkaml_markup_namespace_get_explicit_prefix (GtkamlMarkupNamespace* self)
{
	gboolean result;
	g_return_val_if_fail (self != NULL, FALSE);
	result = self->priv->_explicit_prefix;
	return result;
}

void
gtkaml_markup_namespace_set_explicit_prefix (GtkamlMarkupNamespace* self,
                                             gboolean value)
{
	g_return_if_fail (self != NULL);
	self->priv->_explicit_prefix = value;
}

static void
gtkaml_markup_namespace_class_init (GtkamlMarkupNamespaceClass * klass,
                                    gpointer klass_data)
{
	gtkaml_markup_namespace_parent_class = g_type_class_peek_parent (klass);
	((ValaCodeNodeClass *) klass)->finalize = gtkaml_markup_namespace_finalize;
	g_type_class_adjust_private_offset (klass, &GtkamlMarkupNamespace_private_offset);
}

static void
gtkaml_markup_namespace_instance_init (GtkamlMarkupNamespace * self,
                                       gpointer klass)
{
	self->priv = gtkaml_markup_namespace_get_instance_private (self);
}

static void
gtkaml_markup_namespace_finalize (ValaCodeNode * obj)
{
	GtkamlMarkupNamespace * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, GTKAML_TYPE_MARKUP_NAMESPACE, GtkamlMarkupNamespace);
	VALA_CODE_NODE_CLASS (gtkaml_markup_namespace_parent_class)->finalize (obj);
}

/**
 * A Vala unresolved symbol that will be parsed as a namespace. 
 */
static GType
gtkaml_markup_namespace_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (GtkamlMarkupNamespaceClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) gtkaml_markup_namespace_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (GtkamlMarkupNamespace), 0, (GInstanceInitFunc) gtkaml_markup_namespace_instance_init, NULL };
	GType gtkaml_markup_namespace_type_id;
	gtkaml_markup_namespace_type_id = g_type_register_static (VALA_TYPE_UNRESOLVED_SYMBOL, "GtkamlMarkupNamespace", &g_define_type_info, 0);
	GtkamlMarkupNamespace_private_offset = g_type_add_instance_private (gtkaml_markup_namespace_type_id, sizeof (GtkamlMarkupNamespacePrivate));
	return gtkaml_markup_namespace_type_id;
}

GType
gtkaml_markup_namespace_get_type (void)
{
	static volatile gsize gtkaml_markup_namespace_type_id__once = 0;
	if (g_once_init_enter (&gtkaml_markup_namespace_type_id__once)) {
		GType gtkaml_markup_namespace_type_id;
		gtkaml_markup_namespace_type_id = gtkaml_markup_namespace_get_type_once ();
		g_once_init_leave (&gtkaml_markup_namespace_type_id__once, gtkaml_markup_namespace_type_id);
	}
	return gtkaml_markup_namespace_type_id__once;
}

