/* gtkamlcodecontext.c generated by valac 0.56.16, the Vala compiler
 * generated from gtkamlcodecontext.vala, do not modify */

/* gtkamlcodecontext.vala
 *
 * Copyright (C) 2011 Vlad Grecescu
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public
 * License along with main.c; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor Boston, MA 02110-1301,  USA
 *
 * Author:
 *        Vlad Grecescu (b100dian@gmail.com)
 */

#include "gtkaml.h"
#include <glib.h>
#include <stdlib.h>
#include <string.h>
#include <valagee.h>
#include <glib-object.h>
#include <vala.h>
#include <glib/gstdio.h>

#if !defined(VALA_STRICT_C)
#if !defined(__clang__) && defined(__GNUC__) && (__GNUC__ >= 14)
#pragma GCC diagnostic warning "-Wincompatible-pointer-types"
#elif defined(__clang__) && (__clang_major__ >= 16)
#pragma clang diagnostic ignored "-Wincompatible-function-pointer-types"
#pragma clang diagnostic ignored "-Wincompatible-pointer-types"
#endif
#endif

#define _vala_code_visitor_unref0(var) ((var == NULL) ? NULL : (var = (vala_code_visitor_unref (var), NULL)))
#define _vala_iterable_unref0(var) ((var == NULL) ? NULL : (var = (vala_iterable_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))

struct _GtkamlCodeContextPrivate {
	GtkamlMarkupResolver* _markup_resolver;
};

static gint GtkamlCodeContext_private_offset;
static gpointer gtkaml_code_context_parent_class = NULL;

static void gtkaml_code_context_set_markup_resolver (GtkamlCodeContext* self,
                                              GtkamlMarkupResolver* value);
static gchar* gtkaml_code_context_get_file_path (GtkamlCodeContext* self,
                                          const gchar* basename,
                                          const gchar* versioned_data_dir,
                                          const gchar* data_dir,
                                          gchar** directories,
                                          gint directories_length1);
static void gtkaml_code_context_finalize (ValaCodeContext * obj);
static GType gtkaml_code_context_get_type_once (void);
static gssize _vala_array_length (gpointer array);

static inline gpointer
gtkaml_code_context_get_instance_private (GtkamlCodeContext* self)
{
	return G_STRUCT_MEMBER_P (self, GtkamlCodeContext_private_offset);
}

GtkamlCodeContext*
gtkaml_code_context_construct (GType object_type)
{
	GtkamlCodeContext* self = NULL;
	GtkamlMarkupResolver* _tmp0_;
	GtkamlMarkupResolver* _tmp1_;
	self = (GtkamlCodeContext*) vala_code_context_construct (object_type);
	_tmp0_ = gtkaml_markup_resolver_new ();
	_tmp1_ = _tmp0_;
	gtkaml_code_context_set_markup_resolver (self, _tmp1_);
	_vala_code_visitor_unref0 (_tmp1_);
	return self;
}

GtkamlCodeContext*
gtkaml_code_context_new (void)
{
	return gtkaml_code_context_construct (GTKAML_TYPE_CODE_CONTEXT);
}

void
gtkaml_code_context_check (GtkamlCodeContext* self)
{
	GtkamlMarkupResolver* _tmp0_;
	ValaReport* _tmp1_;
	ValaReport* _tmp2_;
	ValaSemanticAnalyzer* _tmp3_;
	ValaSemanticAnalyzer* _tmp4_;
	ValaReport* _tmp5_;
	ValaReport* _tmp6_;
	ValaFlowAnalyzer* _tmp7_;
	ValaFlowAnalyzer* _tmp8_;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->_markup_resolver;
	gtkaml_markup_resolver_resolve (_tmp0_, self);
	_tmp1_ = vala_code_context_get_report ((ValaCodeContext*) self);
	_tmp2_ = _tmp1_;
	if (vala_report_get_errors (_tmp2_) > 0) {
		return;
	}
	_tmp3_ = vala_code_context_get_analyzer ((ValaCodeContext*) self);
	_tmp4_ = _tmp3_;
	vala_semantic_analyzer_analyze (_tmp4_, (ValaCodeContext*) self);
	_tmp5_ = vala_code_context_get_report ((ValaCodeContext*) self);
	_tmp6_ = _tmp5_;
	if (vala_report_get_errors (_tmp6_) > 0) {
		return;
	}
	_tmp7_ = vala_code_context_get_flow_analyzer ((ValaCodeContext*) self);
	_tmp8_ = _tmp7_;
	vala_flow_analyzer_analyze (_tmp8_, (ValaCodeContext*) self);
}

void
gtkaml_code_context_add_define (GtkamlCodeContext* self,
                                const gchar* define)
{
	ValaSet* _tmp0_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (define != NULL);
	_tmp0_ = self->defines;
	vala_collection_add ((ValaCollection*) _tmp0_, define);
	vala_code_context_add_define (G_TYPE_CHECK_INSTANCE_CAST (self, VALA_TYPE_CODE_CONTEXT, ValaCodeContext), define);
}

gchar*
gtkaml_code_context_get_markuphints_path (GtkamlCodeContext* self,
                                          const gchar* pkg)
{
	gchar* vapi_hint = NULL;
	gchar* _tmp0_;
	gchar* _tmp1_;
	gchar** _tmp2_;
	gint _tmp2__length1;
	gint _tmp3_ = 0;
	gchar** _tmp4_;
	gint _tmp4__length1;
	gchar* _tmp5_;
	gchar* _tmp6_;
	gchar* result;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (pkg != NULL, NULL);
	_tmp0_ = g_strconcat (pkg, ".markuphints", NULL);
	_tmp1_ = _tmp0_;
	_tmp2_ = vala_code_context_get_vapi_directories ((ValaCodeContext*) self, &_tmp3_);
	_tmp2__length1 = _tmp3_;
	_tmp4_ = _tmp2_;
	_tmp4__length1 = _tmp2__length1;
	_tmp5_ = gtkaml_code_context_get_file_path (self, _tmp1_, NULL, "gtkaml/markuphints", _tmp4_, (gint) _tmp4__length1);
	_tmp6_ = _tmp5_;
	_g_free0 (_tmp1_);
	vapi_hint = _tmp6_;
	result = vapi_hint;
	return result;
}

static gchar*
gtkaml_code_context_get_file_path (GtkamlCodeContext* self,
                                   const gchar* basename,
                                   const gchar* versioned_data_dir,
                                   const gchar* data_dir,
                                   gchar** directories,
                                   gint directories_length1)
{
	gchar* filename = NULL;
	gchar* result;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (basename != NULL, NULL);
	filename = NULL;
	if (directories != NULL) {
		{
			gchar** dir_collection = NULL;
			gint dir_collection_length1 = 0;
			gint _dir_collection_size_ = 0;
			gint dir_it = 0;
			dir_collection = directories;
			dir_collection_length1 = directories_length1;
			for (dir_it = 0; dir_it < dir_collection_length1; dir_it = dir_it + 1) {
				gchar* _tmp0_;
				gchar* dir = NULL;
				_tmp0_ = g_strdup (dir_collection[dir_it]);
				dir = _tmp0_;
				{
					const gchar* _tmp1_;
					gchar* _tmp2_;
					const gchar* _tmp3_;
					_tmp1_ = dir;
					_tmp2_ = g_build_path ("/", _tmp1_, basename, NULL);
					_g_free0 (filename);
					filename = _tmp2_;
					_tmp3_ = filename;
					if (g_file_test (_tmp3_, G_FILE_TEST_EXISTS)) {
						result = filename;
						_g_free0 (dir);
						return result;
					}
					_g_free0 (dir);
				}
			}
		}
	}
	if (versioned_data_dir != NULL) {
		gchar** _tmp4_;
		gchar** _tmp5_;
		_tmp5_ = _tmp4_ = g_get_system_data_dirs ();
		{
			gchar** dir_collection = NULL;
			gint dir_collection_length1 = 0;
			gint _dir_collection_size_ = 0;
			gint dir_it = 0;
			dir_collection = _tmp5_;
			dir_collection_length1 = _vala_array_length (_tmp4_);
			for (dir_it = 0; dir_it < dir_collection_length1; dir_it = dir_it + 1) {
				gchar* _tmp6_;
				gchar* dir = NULL;
				_tmp6_ = g_strdup (dir_collection[dir_it]);
				dir = _tmp6_;
				{
					const gchar* _tmp7_;
					gchar* _tmp8_;
					const gchar* _tmp9_;
					_tmp7_ = dir;
					_tmp8_ = g_build_path ("/", _tmp7_, versioned_data_dir, basename, NULL);
					_g_free0 (filename);
					filename = _tmp8_;
					_tmp9_ = filename;
					if (g_file_test (_tmp9_, G_FILE_TEST_EXISTS)) {
						result = filename;
						_g_free0 (dir);
						return result;
					}
					_g_free0 (dir);
				}
			}
		}
	}
	if (data_dir != NULL) {
		gchar** _tmp10_;
		gchar** _tmp11_;
		_tmp11_ = _tmp10_ = g_get_system_data_dirs ();
		{
			gchar** dir_collection = NULL;
			gint dir_collection_length1 = 0;
			gint _dir_collection_size_ = 0;
			gint dir_it = 0;
			dir_collection = _tmp11_;
			dir_collection_length1 = _vala_array_length (_tmp10_);
			for (dir_it = 0; dir_it < dir_collection_length1; dir_it = dir_it + 1) {
				gchar* _tmp12_;
				gchar* dir = NULL;
				_tmp12_ = g_strdup (dir_collection[dir_it]);
				dir = _tmp12_;
				{
					const gchar* _tmp13_;
					gchar* _tmp14_;
					const gchar* _tmp15_;
					_tmp13_ = dir;
					_tmp14_ = g_build_path ("/", _tmp13_, data_dir, basename, NULL);
					_g_free0 (filename);
					filename = _tmp14_;
					_tmp15_ = filename;
					if (g_file_test (_tmp15_, G_FILE_TEST_EXISTS)) {
						result = filename;
						_g_free0 (dir);
						return result;
					}
					_g_free0 (dir);
				}
			}
		}
	}
	result = NULL;
	_g_free0 (filename);
	return result;
}

GtkamlMarkupResolver*
gtkaml_code_context_get_markup_resolver (GtkamlCodeContext* self)
{
	GtkamlMarkupResolver* result;
	GtkamlMarkupResolver* _tmp0_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_markup_resolver;
	result = _tmp0_;
	return result;
}

static gpointer
_vala_code_visitor_ref0 (gpointer self)
{
	return self ? vala_code_visitor_ref (self) : NULL;
}

static void
gtkaml_code_context_set_markup_resolver (GtkamlCodeContext* self,
                                         GtkamlMarkupResolver* value)
{
	GtkamlMarkupResolver* _tmp0_;
	g_return_if_fail (self != NULL);
	_tmp0_ = _vala_code_visitor_ref0 (value);
	_vala_code_visitor_unref0 (self->priv->_markup_resolver);
	self->priv->_markup_resolver = _tmp0_;
}

ValaSymbolResolver*
gtkaml_code_context_get_resolver (GtkamlCodeContext* self)
{
	ValaSymbolResolver* result;
	GtkamlMarkupResolver* _tmp0_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_markup_resolver;
	result = (ValaSymbolResolver*) _tmp0_;
	return result;
}

static void
gtkaml_code_context_class_init (GtkamlCodeContextClass * klass,
                                gpointer klass_data)
{
	gtkaml_code_context_parent_class = g_type_class_peek_parent (klass);
	((ValaCodeContextClass *) klass)->finalize = gtkaml_code_context_finalize;
	g_type_class_adjust_private_offset (klass, &GtkamlCodeContext_private_offset);
}

static void
gtkaml_code_context_instance_init (GtkamlCodeContext * self,
                                   gpointer klass)
{
	GHashFunc _tmp0_;
	GEqualFunc _tmp1_;
	ValaHashSet* _tmp2_;
	self->priv = gtkaml_code_context_get_instance_private (self);
	_tmp0_ = g_str_hash;
	_tmp1_ = g_str_equal;
	_tmp2_ = vala_hash_set_new (G_TYPE_STRING, (GBoxedCopyFunc) g_strdup, (GDestroyNotify) g_free, _tmp0_, _tmp1_);
	self->defines = (ValaSet*) _tmp2_;
}

static void
gtkaml_code_context_finalize (ValaCodeContext * obj)
{
	GtkamlCodeContext * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, GTKAML_TYPE_CODE_CONTEXT, GtkamlCodeContext);
	_vala_code_visitor_unref0 (self->priv->_markup_resolver);
	_vala_iterable_unref0 (self->defines);
	VALA_CODE_CONTEXT_CLASS (gtkaml_code_context_parent_class)->finalize (obj);
}

/**
 * Hides some methods from Vala.CodeContext with our implementation
 * This is useful only if the methods are called from vala/gtkaml compiler driver where
 * Gtkaml.CodeContext is explicitly used
 */
static GType
gtkaml_code_context_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (GtkamlCodeContextClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) gtkaml_code_context_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (GtkamlCodeContext), 0, (GInstanceInitFunc) gtkaml_code_context_instance_init, NULL };
	GType gtkaml_code_context_type_id;
	gtkaml_code_context_type_id = g_type_register_static (VALA_TYPE_CODE_CONTEXT, "GtkamlCodeContext", &g_define_type_info, 0);
	GtkamlCodeContext_private_offset = g_type_add_instance_private (gtkaml_code_context_type_id, sizeof (GtkamlCodeContextPrivate));
	return gtkaml_code_context_type_id;
}

GType
gtkaml_code_context_get_type (void)
{
	static volatile gsize gtkaml_code_context_type_id__once = 0;
	if (g_once_init_enter (&gtkaml_code_context_type_id__once)) {
		GType gtkaml_code_context_type_id;
		gtkaml_code_context_type_id = gtkaml_code_context_get_type_once ();
		g_once_init_leave (&gtkaml_code_context_type_id__once, gtkaml_code_context_type_id);
	}
	return gtkaml_code_context_type_id__once;
}

static gssize
_vala_array_length (gpointer array)
{
	gssize length;
	length = 0;
	if (array) {
		while (((gpointer*) array)[length]) {
			length++;
		}
	}
	return length;
}

