/* gtkamlpropertyspec.c generated by valac 0.56.16, the Vala compiler
 * generated from gtkamlpropertyspec.vala, do not modify */

/* gtkamlmarkupscanner.vala
 *
 * Copyright (C) 2011 Vlad Grecescu
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public
 * License along with main.c; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor Boston, MA 02110-1301,  USA
 *
 * Author:
 *        Vlad Grecescu (b100dian@gmail.com)
 */

#include "gtkaml.h"
#include <glib.h>
#include <glib-object.h>
#include <gobject/gvaluecollector.h>

#if !defined(VALA_STRICT_C)
#if !defined(__clang__) && defined(__GNUC__) && (__GNUC__ >= 14)
#pragma GCC diagnostic warning "-Wincompatible-pointer-types"
#elif defined(__clang__) && (__clang_major__ >= 16)
#pragma clang diagnostic ignored "-Wincompatible-function-pointer-types"
#pragma clang diagnostic ignored "-Wincompatible-pointer-types"
#endif
#endif

#define _g_free0(var) ((var == NULL) ? NULL : (var = (g_free (var), NULL)))
typedef struct _GtkamlParamSpecPropertySpec GtkamlParamSpecPropertySpec;

struct _GtkamlParamSpecPropertySpec {
	GParamSpec parent_instance;
};

static gpointer gtkaml_property_spec_parent_class = NULL;

static void gtkaml_property_spec_finalize (GtkamlPropertySpec * obj);
static GType gtkaml_property_spec_get_type_once (void);

GtkamlPropertySpec*
gtkaml_property_spec_construct (GType object_type)
{
	GtkamlPropertySpec* self = NULL;
	self = (GtkamlPropertySpec*) g_type_create_instance (object_type);
	return self;
}

GtkamlPropertySpec*
gtkaml_property_spec_new (void)
{
	return gtkaml_property_spec_construct (GTKAML_TYPE_PROPERTY_SPEC);
}

static void
gtkaml_value_property_spec_init (GValue* value)
{
	value->data[0].v_pointer = NULL;
}

static void
gtkaml_value_property_spec_free_value (GValue* value)
{
	if (value->data[0].v_pointer) {
		gtkaml_property_spec_unref (value->data[0].v_pointer);
	}
}

static void
gtkaml_value_property_spec_copy_value (const GValue* src_value,
                                       GValue* dest_value)
{
	if (src_value->data[0].v_pointer) {
		dest_value->data[0].v_pointer = gtkaml_property_spec_ref (src_value->data[0].v_pointer);
	} else {
		dest_value->data[0].v_pointer = NULL;
	}
}

static gpointer
gtkaml_value_property_spec_peek_pointer (const GValue* value)
{
	return value->data[0].v_pointer;
}

static gchar*
gtkaml_value_property_spec_collect_value (GValue* value,
                                          guint n_collect_values,
                                          GTypeCValue* collect_values,
                                          guint collect_flags)
{
	if (collect_values[0].v_pointer) {
		GtkamlPropertySpec * object;
		object = collect_values[0].v_pointer;
		if (object->parent_instance.g_class == NULL) {
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		}
		value->data[0].v_pointer = gtkaml_property_spec_ref (object);
	} else {
		value->data[0].v_pointer = NULL;
	}
	return NULL;
}

static gchar*
gtkaml_value_property_spec_lcopy_value (const GValue* value,
                                        guint n_collect_values,
                                        GTypeCValue* collect_values,
                                        guint collect_flags)
{
	GtkamlPropertySpec ** object_p;
	object_p = collect_values[0].v_pointer;
	if (!object_p) {
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
	}
	if (!value->data[0].v_pointer) {
		*object_p = NULL;
	} else if (collect_flags & G_VALUE_NOCOPY_CONTENTS) {
		*object_p = value->data[0].v_pointer;
	} else {
		*object_p = gtkaml_property_spec_ref (value->data[0].v_pointer);
	}
	return NULL;
}

GParamSpec*
gtkaml_param_spec_property_spec (const gchar* name,
                                 const gchar* nick,
                                 const gchar* blurb,
                                 GType object_type,
                                 GParamFlags flags)
{
	GtkamlParamSpecPropertySpec* spec;
	g_return_val_if_fail (g_type_is_a (object_type, GTKAML_TYPE_PROPERTY_SPEC), NULL);
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
	G_PARAM_SPEC (spec)->value_type = object_type;
	return G_PARAM_SPEC (spec);
}

gpointer
gtkaml_value_get_property_spec (const GValue* value)
{
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, GTKAML_TYPE_PROPERTY_SPEC), NULL);
	return value->data[0].v_pointer;
}

void
gtkaml_value_set_property_spec (GValue* value,
                                gpointer v_object)
{
	GtkamlPropertySpec * old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, GTKAML_TYPE_PROPERTY_SPEC));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, GTKAML_TYPE_PROPERTY_SPEC));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
		gtkaml_property_spec_ref (value->data[0].v_pointer);
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		gtkaml_property_spec_unref (old);
	}
}

void
gtkaml_value_take_property_spec (GValue* value,
                                 gpointer v_object)
{
	GtkamlPropertySpec * old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, GTKAML_TYPE_PROPERTY_SPEC));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, GTKAML_TYPE_PROPERTY_SPEC));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		gtkaml_property_spec_unref (old);
	}
}

static void
gtkaml_property_spec_class_init (GtkamlPropertySpecClass * klass,
                                 gpointer klass_data)
{
	gtkaml_property_spec_parent_class = g_type_class_peek_parent (klass);
	((GtkamlPropertySpecClass *) klass)->finalize = gtkaml_property_spec_finalize;
}

static void
gtkaml_property_spec_instance_init (GtkamlPropertySpec * self,
                                    gpointer klass)
{
	self->ref_count = 1;
}

static void
gtkaml_property_spec_finalize (GtkamlPropertySpec * obj)
{
	GtkamlPropertySpec * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, GTKAML_TYPE_PROPERTY_SPEC, GtkamlPropertySpec);
	g_signal_handlers_destroy (self);
	_g_free0 (self->getter_accessibility);
	_g_free0 (self->setter_accessibility);
}

/** 
 * Indicates a property's has both accessors and their accessibility
 */
static GType
gtkaml_property_spec_get_type_once (void)
{
	static const GTypeValueTable g_define_type_value_table = { gtkaml_value_property_spec_init, gtkaml_value_property_spec_free_value, gtkaml_value_property_spec_copy_value, gtkaml_value_property_spec_peek_pointer, "p", gtkaml_value_property_spec_collect_value, "p", gtkaml_value_property_spec_lcopy_value };
	static const GTypeInfo g_define_type_info = { sizeof (GtkamlPropertySpecClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) gtkaml_property_spec_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (GtkamlPropertySpec), 0, (GInstanceInitFunc) gtkaml_property_spec_instance_init, &g_define_type_value_table };
	static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
	GType gtkaml_property_spec_type_id;
	gtkaml_property_spec_type_id = g_type_register_fundamental (g_type_fundamental_next (), "GtkamlPropertySpec", &g_define_type_info, &g_define_type_fundamental_info, 0);
	return gtkaml_property_spec_type_id;
}

GType
gtkaml_property_spec_get_type (void)
{
	static volatile gsize gtkaml_property_spec_type_id__once = 0;
	if (g_once_init_enter (&gtkaml_property_spec_type_id__once)) {
		GType gtkaml_property_spec_type_id;
		gtkaml_property_spec_type_id = gtkaml_property_spec_get_type_once ();
		g_once_init_leave (&gtkaml_property_spec_type_id__once, gtkaml_property_spec_type_id);
	}
	return gtkaml_property_spec_type_id__once;
}

gpointer
gtkaml_property_spec_ref (gpointer instance)
{
	GtkamlPropertySpec * self;
	self = instance;
	g_atomic_int_inc (&self->ref_count);
	return instance;
}

void
gtkaml_property_spec_unref (gpointer instance)
{
	GtkamlPropertySpec * self;
	self = instance;
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
		GTKAML_PROPERTY_SPEC_GET_CLASS (self)->finalize (self);
		g_type_free_instance ((GTypeInstance *) self);
	}
}

