/* gtkamlmarkupresolver.c generated by valac 0.56.16, the Vala compiler
 * generated from gtkamlmarkupresolver.vala, do not modify */

/* gtkamlmarkupresolver.vala
 *
 * Copyright (C) 2011 Vlad Grecescu
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public
 * License along with main.c; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor Boston, MA 02110-1301,  USA
 *
 * Author:
 *        Vlad Grecescu (b100dian@gmail.com)
 */

#include "gtkaml.h"
#include <glib.h>
#include <vala.h>
#include <stdlib.h>
#include <string.h>
#include <valagee.h>
#include <glib-object.h>

#if !defined(VALA_STRICT_C)
#if !defined(__clang__) && defined(__GNUC__) && (__GNUC__ >= 14)
#pragma GCC diagnostic warning "-Wincompatible-pointer-types"
#elif defined(__clang__) && (__clang_major__ >= 16)
#pragma clang diagnostic ignored "-Wincompatible-function-pointer-types"
#pragma clang diagnostic ignored "-Wincompatible-pointer-types"
#endif
#endif

#define _gtkaml_markup_hints_store_unref0(var) ((var == NULL) ? NULL : (var = (gtkaml_markup_hints_store_unref (var), NULL)))
#define _gtkaml_vala_parser_unref0(var) ((var == NULL) ? NULL : (var = (gtkaml_vala_parser_unref (var), NULL)))
#define _vala_code_context_unref0(var) ((var == NULL) ? NULL : (var = (vala_code_context_unref (var), NULL)))
#define _vala_iterable_unref0(var) ((var == NULL) ? NULL : (var = (vala_iterable_unref (var), NULL)))
#define _vala_code_node_unref0(var) ((var == NULL) ? NULL : (var = (vala_code_node_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _gtkaml_pair_unref0(var) ((var == NULL) ? NULL : (var = (gtkaml_pair_unref (var), NULL)))
#define _gtkaml_ast_markup_attribute_unref0(var) ((var == NULL) ? NULL : (var = (gtkaml_ast_markup_attribute_unref (var), NULL)))
#define _gtkaml_markup_hint_unref0(var) ((var == NULL) ? NULL : (var = (gtkaml_markup_hint_unref (var), NULL)))
#define _gtkaml_callable_unref0(var) ((var == NULL) ? NULL : (var = (gtkaml_callable_unref (var), NULL)))
#define _vala_assert(expr, msg) if G_LIKELY (expr) ; else g_assertion_message_expr (G_LOG_DOMAIN, __FILE__, __LINE__, G_STRFUNC, msg);
#define _vala_return_if_fail(expr, msg) if G_LIKELY (expr) ; else { g_return_if_fail_warning (G_LOG_DOMAIN, G_STRFUNC, msg); return; }
#define _vala_return_val_if_fail(expr, msg, val) if G_LIKELY (expr) ; else { g_return_if_fail_warning (G_LOG_DOMAIN, G_STRFUNC, msg); return val; }
#define _vala_warn_if_fail(expr, msg) if G_LIKELY (expr) ; else g_warn_message (G_LOG_DOMAIN, __FILE__, __LINE__, G_STRFUNC, msg);

struct _GtkamlMarkupResolverPrivate {
	GtkamlValaParser* _code_parser;
	GtkamlCodeContext* _context;
};

static gint GtkamlMarkupResolver_private_offset;
static gpointer gtkaml_markup_resolver_parent_class = NULL;
static GtkamlCodeParserProviderIface * gtkaml_markup_resolver_gtkaml_code_parser_provider_parent_iface = NULL;

static void gtkaml_markup_resolver_set_context (GtkamlMarkupResolver* self,
                                         GtkamlCodeContext* value);
static GtkamlCodeContext* gtkaml_markup_resolver_get_context (GtkamlMarkupResolver* self);
static void gtkaml_markup_resolver_finalize (ValaCodeVisitor * obj);
static GType gtkaml_markup_resolver_get_type_once (void);

static inline gpointer
gtkaml_markup_resolver_get_instance_private (GtkamlMarkupResolver* self)
{
	return G_STRUCT_MEMBER_P (self, GtkamlMarkupResolver_private_offset);
}

void
gtkaml_markup_resolver_resolve (GtkamlMarkupResolver* self,
                                GtkamlCodeContext* context)
{
	GtkamlMarkupHintsStore* _tmp0_;
	GtkamlValaParser* _tmp1_;
	GtkamlValaParser* _tmp2_;
	GtkamlMarkupHintsStore* _tmp3_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (context != NULL);
	_tmp0_ = gtkaml_markup_hints_store_new (context);
	_gtkaml_markup_hints_store_unref0 (self->markup_hints);
	self->markup_hints = _tmp0_;
	_tmp1_ = gtkaml_vala_parser_new (context);
	_tmp2_ = _tmp1_;
	gtkaml_code_parser_provider_set_code_parser ((GtkamlCodeParserProvider*) self, _tmp2_);
	_gtkaml_vala_parser_unref0 (_tmp2_);
	_tmp3_ = self->markup_hints;
	gtkaml_markup_hints_store_parse (_tmp3_);
	gtkaml_markup_resolver_set_context (self, context);
	vala_symbol_resolver_resolve (G_TYPE_CHECK_INSTANCE_CAST (self, VALA_TYPE_SYMBOL_RESOLVER, ValaSymbolResolver), (ValaCodeContext*) context);
}

/**
 * executes before base.visit_class, triggers resolving and generating of tags
 */
void
gtkaml_markup_resolver_visit_markup_class (GtkamlMarkupResolver* self,
                                           GtkamlMarkupClass* mcl)
{
	GtkamlAstMarkupTag* _tmp0_;
	GtkamlAstMarkupTag* _tmp1_;
	gboolean _tmp2_;
	gboolean _tmp3_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (mcl != NULL);
	_tmp0_ = gtkaml_markupclass_get_markup_root (mcl);
	_tmp1_ = _tmp0_;
	_tmp2_ = gtkaml_ast_markup_tag_get_is_resolved (_tmp1_);
	_tmp3_ = _tmp2_;
	if (!_tmp3_) {
		GtkamlAstMarkupTag* _tmp4_;
		GtkamlAstMarkupTag* _tmp5_;
		GtkamlAstMarkupTag* _tmp6_;
		GtkamlAstMarkupTag* _tmp7_;
		_tmp4_ = gtkaml_markupclass_get_markup_root (mcl);
		_tmp5_ = _tmp4_;
		gtkaml_markup_resolver_resolve_markup_tag (self, _tmp5_);
		_tmp6_ = gtkaml_markupclass_get_markup_root (mcl);
		_tmp7_ = _tmp6_;
		gtkaml_markup_resolver_generate_markup_tag (self, _tmp7_);
	}
}

/**
 * looks up a memeber in the type hierarchy and returns its symbol
 */
static gpointer
_vala_iterable_ref0 (gpointer self)
{
	return self ? vala_iterable_ref (self) : NULL;
}

ValaSymbol*
gtkaml_markup_resolver_search_symbol (GtkamlMarkupResolver* self,
                                      ValaTypeSymbol* type,
                                      const gchar* sym_name)
{
	ValaSymbol* sym = NULL;
	ValaScope* _tmp0_;
	ValaScope* _tmp1_;
	ValaSymbol* _tmp2_;
	ValaSymbol* _tmp3_;
	ValaSymbol* result;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (type != NULL, NULL);
	g_return_val_if_fail (sym_name != NULL, NULL);
	_tmp0_ = vala_symbol_get_scope ((ValaSymbol*) type);
	_tmp1_ = _tmp0_;
	_tmp2_ = vala_scope_lookup (_tmp1_, sym_name);
	sym = _tmp2_;
	_tmp3_ = sym;
	if (_tmp3_ == NULL) {
		ValaList* base_types = NULL;
		if (G_TYPE_CHECK_INSTANCE_TYPE (type, VALA_TYPE_CLASS)) {
			ValaList* _tmp4_;
			ValaList* _tmp5_;
			_tmp4_ = vala_class_get_base_types (G_TYPE_CHECK_INSTANCE_CAST (type, VALA_TYPE_CLASS, ValaClass));
			_tmp5_ = _vala_iterable_ref0 (_tmp4_);
			_vala_iterable_unref0 (base_types);
			base_types = _tmp5_;
		} else {
			result = NULL;
			_vala_iterable_unref0 (base_types);
			_vala_code_node_unref0 (sym);
			return result;
		}
		{
			ValaList* _base_type_list = NULL;
			ValaList* _tmp6_;
			gint _base_type_size = 0;
			ValaList* _tmp7_;
			gint _tmp8_;
			gint _tmp9_;
			gint _base_type_index = 0;
			_tmp6_ = base_types;
			_base_type_list = _tmp6_;
			_tmp7_ = _base_type_list;
			_tmp8_ = vala_collection_get_size ((ValaCollection*) _tmp7_);
			_tmp9_ = _tmp8_;
			_base_type_size = _tmp9_;
			_base_type_index = -1;
			while (TRUE) {
				gint _tmp10_;
				gint _tmp11_;
				ValaDataType* base_type = NULL;
				ValaList* _tmp12_;
				gpointer _tmp13_;
				ValaDataType* _tmp14_;
				ValaSymbol* _tmp29_;
				_base_type_index = _base_type_index + 1;
				_tmp10_ = _base_type_index;
				_tmp11_ = _base_type_size;
				if (!(_tmp10_ < _tmp11_)) {
					break;
				}
				_tmp12_ = _base_type_list;
				_tmp13_ = vala_list_get (_tmp12_, _base_type_index);
				base_type = (ValaDataType*) _tmp13_;
				_tmp14_ = base_type;
				if (G_TYPE_CHECK_INSTANCE_TYPE (_tmp14_, VALA_TYPE_CLASS_TYPE)) {
					ValaDataType* _tmp15_;
					ValaClass* _tmp16_;
					ValaClass* _tmp17_;
					ValaSymbol* _tmp18_;
					_tmp15_ = base_type;
					_tmp16_ = vala_class_type_get_class_symbol (G_TYPE_CHECK_INSTANCE_CAST (_tmp15_, VALA_TYPE_CLASS_TYPE, ValaClassType));
					_tmp17_ = _tmp16_;
					_tmp18_ = gtkaml_markup_resolver_search_symbol (self, (ValaTypeSymbol*) _tmp17_, sym_name);
					_vala_code_node_unref0 (sym);
					sym = _tmp18_;
				} else {
					ValaDataType* _tmp19_;
					_tmp19_ = base_type;
					if (G_TYPE_CHECK_INSTANCE_TYPE (_tmp19_, VALA_TYPE_INTERFACE_TYPE)) {
						ValaDataType* _tmp20_;
						ValaInterface* _tmp21_;
						ValaInterface* _tmp22_;
						ValaSymbol* _tmp23_;
						_tmp20_ = base_type;
						_tmp21_ = vala_interface_type_get_interface_symbol (G_TYPE_CHECK_INSTANCE_CAST (_tmp20_, VALA_TYPE_INTERFACE_TYPE, ValaInterfaceType));
						_tmp22_ = _tmp21_;
						_tmp23_ = gtkaml_markup_resolver_search_symbol (self, (ValaTypeSymbol*) _tmp22_, sym_name);
						_vala_code_node_unref0 (sym);
						sym = _tmp23_;
					} else {
						ValaDataType* _tmp24_;
						_tmp24_ = base_type;
						if (G_TYPE_CHECK_INSTANCE_TYPE (_tmp24_, VALA_TYPE_OBJECT_TYPE)) {
							ValaDataType* _tmp25_;
							ValaTypeSymbol* _tmp26_;
							ValaTypeSymbol* _tmp27_;
							ValaSymbol* _tmp28_;
							_tmp25_ = base_type;
							_tmp26_ = vala_data_type_get_type_symbol ((ValaDataType*) G_TYPE_CHECK_INSTANCE_CAST (_tmp25_, VALA_TYPE_OBJECT_TYPE, ValaObjectType));
							_tmp27_ = _tmp26_;
							_tmp28_ = gtkaml_markup_resolver_search_symbol (self, _tmp27_, sym_name);
							_vala_code_node_unref0 (sym);
							sym = _tmp28_;
						}
					}
				}
				_tmp29_ = sym;
				if (_tmp29_ != NULL) {
					_vala_code_node_unref0 (base_type);
					break;
				}
				_vala_code_node_unref0 (base_type);
			}
		}
		_vala_iterable_unref0 (base_types);
	}
	result = sym;
	return result;
}

/**
 * processes tag hierarchy. Unresolved tags are removed after this step
 */
gboolean
gtkaml_markup_resolver_resolve_markup_tag (GtkamlMarkupResolver* self,
                                           GtkamlAstMarkupTag* markup_tag)
{
	GtkamlAstMarkupTag* resolved_tag = NULL;
	GtkamlAstMarkupTag* _tmp0_;
	GtkamlAstMarkupTag* _tmp1_;
	GtkamlAstMarkupTag* _tmp48_;
	gboolean result;
	g_return_val_if_fail (self != NULL, FALSE);
	g_return_val_if_fail (markup_tag != NULL, FALSE);
	_tmp0_ = gtkaml_ast_markup_tag_resolve (markup_tag, self);
	resolved_tag = _tmp0_;
	_tmp1_ = resolved_tag;
	if (_tmp1_ != NULL) {
		GtkamlAstMarkupTag* _tmp2_;
		gboolean _tmp3_;
		gboolean _tmp4_;
		GtkamlAstMarkupTag* _tmp11_;
		ValaDataType* _tmp12_;
		ValaDataType* _tmp13_;
		ValaTypeSymbol* _tmp14_;
		ValaTypeSymbol* _tmp15_;
		ValaList* to_remove = NULL;
		GEqualFunc _tmp23_;
		ValaArrayList* _tmp24_;
		GtkamlAstMarkupTag* _tmp47_;
		_tmp2_ = resolved_tag;
		_tmp3_ = gtkaml_ast_markup_tag_get_is_resolved (_tmp2_);
		_tmp4_ = _tmp3_;
		if (!_tmp4_) {
			ValaSourceReference* _tmp5_;
			ValaSourceReference* _tmp6_;
			const gchar* _tmp7_;
			const gchar* _tmp8_;
			gchar* _tmp9_;
			gchar* _tmp10_;
			_tmp5_ = gtkaml_ast_markup_tag_get_source_reference (markup_tag);
			_tmp6_ = _tmp5_;
			_tmp7_ = gtkaml_ast_markup_tag_get_tag_name (markup_tag);
			_tmp8_ = _tmp7_;
			_tmp9_ = g_strdup_printf ("Unknown type %s", _tmp8_);
			_tmp10_ = _tmp9_;
			vala_report_error (_tmp6_, "%s", _tmp10_);
			_g_free0 (_tmp10_);
			result = FALSE;
			_g_object_unref0 (resolved_tag);
			return result;
		}
		_tmp11_ = resolved_tag;
		_tmp12_ = gtkaml_ast_markup_tag_get_resolved_type (_tmp11_);
		_tmp13_ = _tmp12_;
		_tmp14_ = vala_data_type_get_type_symbol (_tmp13_);
		_tmp15_ = _tmp14_;
		if (_tmp15_ == NULL) {
			ValaSourceReference* _tmp16_;
			ValaSourceReference* _tmp17_;
			GtkamlAstMarkupTag* _tmp18_;
			const gchar* _tmp19_;
			const gchar* _tmp20_;
			gchar* _tmp21_;
			gchar* _tmp22_;
			_tmp16_ = gtkaml_ast_markup_tag_get_source_reference (markup_tag);
			_tmp17_ = _tmp16_;
			_tmp18_ = resolved_tag;
			_tmp19_ = gtkaml_ast_markup_tag_get_tag_name (_tmp18_);
			_tmp20_ = _tmp19_;
			_tmp21_ = g_strdup_printf ("Unknown type %s", _tmp20_);
			_tmp22_ = _tmp21_;
			vala_report_error (_tmp17_, "%s", _tmp22_);
			_g_free0 (_tmp22_);
			result = FALSE;
			_g_object_unref0 (resolved_tag);
			return result;
		}
		_tmp23_ = g_direct_equal;
		_tmp24_ = vala_array_list_new (GTKAML_AST_TYPE_MARKUP_CHILD_TAG, (GBoxedCopyFunc) g_object_ref, (GDestroyNotify) g_object_unref, _tmp23_);
		to_remove = (ValaList*) _tmp24_;
		{
			ValaList* _child_tag_list = NULL;
			GtkamlAstMarkupTag* _tmp25_;
			ValaList* _tmp26_;
			gint _child_tag_size = 0;
			ValaList* _tmp27_;
			gint _tmp28_;
			gint _tmp29_;
			gint _child_tag_index = 0;
			_tmp25_ = resolved_tag;
			_tmp26_ = gtkaml_ast_markup_tag_get_child_tags (_tmp25_);
			_child_tag_list = _tmp26_;
			_tmp27_ = _child_tag_list;
			_tmp28_ = vala_collection_get_size ((ValaCollection*) _tmp27_);
			_tmp29_ = _tmp28_;
			_child_tag_size = _tmp29_;
			_child_tag_index = -1;
			while (TRUE) {
				gint _tmp30_;
				gint _tmp31_;
				GtkamlAstMarkupChildTag* child_tag = NULL;
				ValaList* _tmp32_;
				gpointer _tmp33_;
				GtkamlAstMarkupChildTag* _tmp34_;
				_child_tag_index = _child_tag_index + 1;
				_tmp30_ = _child_tag_index;
				_tmp31_ = _child_tag_size;
				if (!(_tmp30_ < _tmp31_)) {
					break;
				}
				_tmp32_ = _child_tag_list;
				_tmp33_ = vala_list_get (_tmp32_, _child_tag_index);
				child_tag = (GtkamlAstMarkupChildTag*) _tmp33_;
				_tmp34_ = child_tag;
				if (FALSE == gtkaml_markup_resolver_resolve_markup_tag (self, (GtkamlAstMarkupTag*) _tmp34_)) {
					ValaList* _tmp35_;
					GtkamlAstMarkupChildTag* _tmp36_;
					_tmp35_ = to_remove;
					_tmp36_ = child_tag;
					vala_collection_add ((ValaCollection*) _tmp35_, _tmp36_);
				}
				_g_object_unref0 (child_tag);
			}
			_vala_iterable_unref0 (_child_tag_list);
		}
		{
			ValaList* _remove_list = NULL;
			ValaList* _tmp37_;
			gint _remove_size = 0;
			ValaList* _tmp38_;
			gint _tmp39_;
			gint _tmp40_;
			gint _remove_index = 0;
			_tmp37_ = to_remove;
			_remove_list = _tmp37_;
			_tmp38_ = _remove_list;
			_tmp39_ = vala_collection_get_size ((ValaCollection*) _tmp38_);
			_tmp40_ = _tmp39_;
			_remove_size = _tmp40_;
			_remove_index = -1;
			while (TRUE) {
				gint _tmp41_;
				gint _tmp42_;
				GtkamlAstMarkupChildTag* remove = NULL;
				ValaList* _tmp43_;
				gpointer _tmp44_;
				GtkamlAstMarkupTag* _tmp45_;
				GtkamlAstMarkupChildTag* _tmp46_;
				_remove_index = _remove_index + 1;
				_tmp41_ = _remove_index;
				_tmp42_ = _remove_size;
				if (!(_tmp41_ < _tmp42_)) {
					break;
				}
				_tmp43_ = _remove_list;
				_tmp44_ = vala_list_get (_tmp43_, _remove_index);
				remove = (GtkamlAstMarkupChildTag*) _tmp44_;
				_tmp45_ = resolved_tag;
				_tmp46_ = remove;
				gtkaml_ast_markup_tag_remove_child_tag (_tmp45_, _tmp46_);
				_g_object_unref0 (remove);
			}
		}
		_tmp47_ = resolved_tag;
		gtkaml_ast_markup_tag_resolve_attributes (_tmp47_, self);
		_vala_iterable_unref0 (to_remove);
	}
	_tmp48_ = resolved_tag;
	result = _tmp48_ != NULL;
	_g_object_unref0 (resolved_tag);
	return result;
}

/**
 * processes tag hierarchy, calling generate () on each, then recurses, then generate_attributes () 
 */
void
gtkaml_markup_resolver_generate_markup_tag (GtkamlMarkupResolver* self,
                                            GtkamlAstMarkupTag* markup_tag)
{
	g_return_if_fail (self != NULL);
	g_return_if_fail (markup_tag != NULL);
	gtkaml_ast_markup_tag_generate (markup_tag, self);
	gtkaml_ast_markup_tag_generate_preconstruct (markup_tag, self);
	gtkaml_ast_markup_tag_generate_attributes (markup_tag, self);
	{
		ValaList* _child_tag_list = NULL;
		ValaList* _tmp0_;
		gint _child_tag_size = 0;
		ValaList* _tmp1_;
		gint _tmp2_;
		gint _tmp3_;
		gint _child_tag_index = 0;
		_tmp0_ = gtkaml_ast_markup_tag_get_child_tags (markup_tag);
		_child_tag_list = _tmp0_;
		_tmp1_ = _child_tag_list;
		_tmp2_ = vala_collection_get_size ((ValaCollection*) _tmp1_);
		_tmp3_ = _tmp2_;
		_child_tag_size = _tmp3_;
		_child_tag_index = -1;
		while (TRUE) {
			gint _tmp4_;
			gint _tmp5_;
			GtkamlAstMarkupTag* child_tag = NULL;
			ValaList* _tmp6_;
			gpointer _tmp7_;
			GtkamlAstMarkupTag* _tmp8_;
			_child_tag_index = _child_tag_index + 1;
			_tmp4_ = _child_tag_index;
			_tmp5_ = _child_tag_size;
			if (!(_tmp4_ < _tmp5_)) {
				break;
			}
			_tmp6_ = _child_tag_list;
			_tmp7_ = vala_list_get (_tmp6_, _child_tag_index);
			child_tag = (GtkamlAstMarkupTag*) ((GtkamlAstMarkupChildTag*) _tmp7_);
			_tmp8_ = child_tag;
			gtkaml_markup_resolver_generate_markup_tag (self, _tmp8_);
			_g_object_unref0 (child_tag);
		}
		_vala_iterable_unref0 (_child_tag_list);
	}
	gtkaml_ast_markup_tag_generate_construct (markup_tag, self);
}

/** 
 * returns parameters of a Callable as a list of MarkupAttributes with name, type and default value if one exists as markup hints
 */
ValaList*
gtkaml_markup_resolver_get_default_parameters (GtkamlMarkupResolver* self,
                                               const gchar* full_type_name,
                                               GtkamlCallable* m,
                                               ValaSourceReference* source_reference)
{
	ValaArrayList* parameters = NULL;
	GEqualFunc _tmp0_;
	ValaArrayList* _tmp1_;
	GtkamlMarkupHint* hint = NULL;
	GtkamlMarkupHintsStore* _tmp2_;
	ValaMap* _tmp3_;
	gpointer _tmp4_;
	GtkamlMarkupHint* _tmp5_;
	ValaList* result;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (full_type_name != NULL, NULL);
	g_return_val_if_fail (m != NULL, NULL);
	_tmp0_ = g_direct_equal;
	_tmp1_ = vala_array_list_new (GTKAML_AST_TYPE_MARKUP_ATTRIBUTE, (GBoxedCopyFunc) gtkaml_ast_markup_attribute_ref, (GDestroyNotify) gtkaml_ast_markup_attribute_unref, _tmp0_);
	parameters = _tmp1_;
	_tmp2_ = self->markup_hints;
	_tmp3_ = _tmp2_->markup_hints;
	_tmp4_ = vala_map_get (_tmp3_, full_type_name);
	hint = (GtkamlMarkupHint*) _tmp4_;
	_tmp5_ = hint;
	if (_tmp5_ != NULL) {
		ValaList* parameter_hints = NULL;
		GtkamlMarkupHint* _tmp6_;
		const gchar* _tmp7_;
		const gchar* _tmp8_;
		ValaList* _tmp9_;
		ValaList* _tmp10_;
		gboolean _tmp15_ = FALSE;
		ValaList* _tmp16_;
		gboolean _tmp35_ = FALSE;
		ValaList* _tmp36_;
		_tmp6_ = hint;
		_tmp7_ = gtkaml_callable_get_name (m);
		_tmp8_ = _tmp7_;
		_tmp9_ = gtkaml_markup_hint_get_creation_method_parameters (_tmp6_, _tmp8_);
		parameter_hints = _tmp9_;
		_tmp10_ = parameter_hints;
		if (_tmp10_ == NULL) {
			GtkamlMarkupHint* _tmp11_;
			const gchar* _tmp12_;
			const gchar* _tmp13_;
			ValaList* _tmp14_;
			_tmp11_ = hint;
			_tmp12_ = gtkaml_callable_get_name (m);
			_tmp13_ = _tmp12_;
			_tmp14_ = gtkaml_markup_hint_get_composition_method_parameters (_tmp11_, _tmp13_);
			_vala_iterable_unref0 (parameter_hints);
			parameter_hints = _tmp14_;
		}
		_tmp16_ = parameter_hints;
		if (_tmp16_ != NULL) {
			ValaList* _tmp17_;
			gint _tmp18_;
			gint _tmp19_;
			_tmp17_ = parameter_hints;
			_tmp18_ = vala_collection_get_size ((ValaCollection*) _tmp17_);
			_tmp19_ = _tmp18_;
			_tmp15_ = _tmp19_ != 0;
		} else {
			_tmp15_ = FALSE;
		}
		if (_tmp15_) {
			ValaList* _tmp20_;
			gint _tmp21_;
			gint _tmp22_;
			ValaList* _tmp23_;
			ValaList* _tmp24_;
			gint _tmp25_;
			gint _tmp26_;
			gboolean _tmp27_;
			_tmp20_ = parameter_hints;
			_tmp21_ = vala_collection_get_size ((ValaCollection*) _tmp20_);
			_tmp22_ = _tmp21_;
			_tmp23_ = gtkaml_callable_get_parameters (m);
			_tmp24_ = _tmp23_;
			_tmp25_ = vala_collection_get_size ((ValaCollection*) _tmp24_);
			_tmp26_ = _tmp25_;
			_tmp27_ = _tmp22_ != _tmp26_;
			_vala_iterable_unref0 (_tmp24_);
			if (_tmp27_) {
				GtkamlCodeContext* _tmp28_;
				ValaReport* _tmp29_;
				ValaReport* _tmp30_;
				const gchar* _tmp31_;
				const gchar* _tmp32_;
				gchar* _tmp33_;
				gchar* _tmp34_;
				_tmp28_ = self->priv->_context;
				_tmp29_ = vala_code_context_get_report ((ValaCodeContext*) _tmp28_);
				_tmp30_ = _tmp29_;
				_tmp31_ = gtkaml_callable_get_name (m);
				_tmp32_ = _tmp31_;
				_tmp33_ = g_strdup_printf ("Ignoring outdated markuphints for %s#%s", full_type_name, _tmp32_);
				_tmp34_ = _tmp33_;
				vala_report_warn (_tmp30_, source_reference, _tmp34_);
				_g_free0 (_tmp34_);
				_vala_iterable_unref0 (parameter_hints);
				parameter_hints = NULL;
			}
		}
		_tmp36_ = parameter_hints;
		if (_tmp36_ != NULL) {
			ValaList* _tmp37_;
			gint _tmp38_;
			gint _tmp39_;
			_tmp37_ = parameter_hints;
			_tmp38_ = vala_collection_get_size ((ValaCollection*) _tmp37_);
			_tmp39_ = _tmp38_;
			_tmp35_ = _tmp39_ != 0;
		} else {
			_tmp35_ = FALSE;
		}
		if (_tmp35_) {
			gint i = 0;
			i = 0;
			{
				ValaList* _formal_parameter_list = NULL;
				ValaList* _tmp40_;
				gint _formal_parameter_size = 0;
				ValaList* _tmp41_;
				gint _tmp42_;
				gint _tmp43_;
				gint _formal_parameter_index = 0;
				_tmp40_ = gtkaml_callable_get_parameters (m);
				_formal_parameter_list = _tmp40_;
				_tmp41_ = _formal_parameter_list;
				_tmp42_ = vala_collection_get_size ((ValaCollection*) _tmp41_);
				_tmp43_ = _tmp42_;
				_formal_parameter_size = _tmp43_;
				_formal_parameter_index = -1;
				while (TRUE) {
					gint _tmp44_;
					gint _tmp45_;
					ValaParameter* formal_parameter = NULL;
					ValaList* _tmp46_;
					gpointer _tmp47_;
					ValaList* _tmp48_;
					gint _tmp49_;
					gint _tmp50_;
					GtkamlAstMarkupAttribute* parameter = NULL;
					ValaList* _tmp51_;
					gpointer _tmp52_;
					GtkamlPair* _tmp53_;
					gconstpointer _tmp54_;
					ValaList* _tmp55_;
					gpointer _tmp56_;
					GtkamlPair* _tmp57_;
					gconstpointer _tmp58_;
					ValaParameter* _tmp59_;
					ValaDataType* _tmp60_;
					ValaDataType* _tmp61_;
					GtkamlAstMarkupAttribute* _tmp62_;
					GtkamlAstMarkupAttribute* _tmp63_;
					ValaArrayList* _tmp64_;
					GtkamlAstMarkupAttribute* _tmp65_;
					gint _tmp66_;
					_formal_parameter_index = _formal_parameter_index + 1;
					_tmp44_ = _formal_parameter_index;
					_tmp45_ = _formal_parameter_size;
					if (!(_tmp44_ < _tmp45_)) {
						break;
					}
					_tmp46_ = _formal_parameter_list;
					_tmp47_ = vala_list_get (_tmp46_, _formal_parameter_index);
					formal_parameter = (ValaParameter*) _tmp47_;
					_tmp48_ = parameter_hints;
					_tmp49_ = vala_collection_get_size ((ValaCollection*) _tmp48_);
					_tmp50_ = _tmp49_;
					_vala_assert (i < _tmp50_, "i < parameter_hints.size");
					_tmp51_ = parameter_hints;
					_tmp52_ = vala_list_get (_tmp51_, i);
					_tmp53_ = (GtkamlPair*) _tmp52_;
					_tmp54_ = _tmp53_->name;
					_tmp55_ = parameter_hints;
					_tmp56_ = vala_list_get (_tmp55_, i);
					_tmp57_ = (GtkamlPair*) _tmp56_;
					_tmp58_ = _tmp57_->value;
					_tmp59_ = formal_parameter;
					_tmp60_ = vala_variable_get_variable_type ((ValaVariable*) _tmp59_);
					_tmp61_ = _tmp60_;
					_tmp62_ = gtkaml_ast_markup_attribute_new_with_type ((const gchar*) _tmp54_, (const gchar*) _tmp58_, _tmp61_, source_reference);
					_tmp63_ = _tmp62_;
					_gtkaml_pair_unref0 (_tmp57_);
					_gtkaml_pair_unref0 (_tmp53_);
					parameter = _tmp63_;
					_tmp64_ = parameters;
					_tmp65_ = parameter;
					vala_collection_add ((ValaCollection*) _tmp64_, _tmp65_);
					_tmp66_ = i;
					i = _tmp66_ + 1;
					_gtkaml_ast_markup_attribute_unref0 (parameter);
					_vala_code_node_unref0 (formal_parameter);
				}
				_vala_iterable_unref0 (_formal_parameter_list);
			}
			result = (ValaList*) parameters;
			_vala_iterable_unref0 (parameter_hints);
			_gtkaml_markup_hint_unref0 (hint);
			return result;
		}
		_vala_iterable_unref0 (parameter_hints);
	}
	{
		ValaList* _formal_parameter_list = NULL;
		ValaList* _tmp67_;
		gint _formal_parameter_size = 0;
		ValaList* _tmp68_;
		gint _tmp69_;
		gint _tmp70_;
		gint _formal_parameter_index = 0;
		_tmp67_ = gtkaml_callable_get_parameters (m);
		_formal_parameter_list = _tmp67_;
		_tmp68_ = _formal_parameter_list;
		_tmp69_ = vala_collection_get_size ((ValaCollection*) _tmp68_);
		_tmp70_ = _tmp69_;
		_formal_parameter_size = _tmp70_;
		_formal_parameter_index = -1;
		while (TRUE) {
			gint _tmp71_;
			gint _tmp72_;
			ValaParameter* formal_parameter = NULL;
			ValaList* _tmp73_;
			gpointer _tmp74_;
			ValaParameter* _tmp75_;
			gboolean _tmp76_;
			gboolean _tmp77_;
			GtkamlAstMarkupAttribute* parameter = NULL;
			ValaParameter* _tmp83_;
			const gchar* _tmp84_;
			const gchar* _tmp85_;
			ValaParameter* _tmp86_;
			ValaDataType* _tmp87_;
			ValaDataType* _tmp88_;
			GtkamlAstMarkupAttribute* _tmp89_;
			ValaArrayList* _tmp90_;
			GtkamlAstMarkupAttribute* _tmp91_;
			_formal_parameter_index = _formal_parameter_index + 1;
			_tmp71_ = _formal_parameter_index;
			_tmp72_ = _formal_parameter_size;
			if (!(_tmp71_ < _tmp72_)) {
				break;
			}
			_tmp73_ = _formal_parameter_list;
			_tmp74_ = vala_list_get (_tmp73_, _formal_parameter_index);
			formal_parameter = (ValaParameter*) _tmp74_;
			_tmp75_ = formal_parameter;
			_tmp76_ = vala_parameter_get_ellipsis (_tmp75_);
			_tmp77_ = _tmp76_;
			if (_tmp77_) {
				ValaArrayList* _tmp78_;
				ValaNullType* _tmp79_;
				ValaNullType* _tmp80_;
				GtkamlAstMarkupAttribute* _tmp81_;
				GtkamlAstMarkupAttribute* _tmp82_;
				_tmp78_ = parameters;
				_tmp79_ = vala_null_type_new (source_reference);
				_tmp80_ = _tmp79_;
				_tmp81_ = gtkaml_ast_markup_attribute_new_with_type ("...", "null", (ValaDataType*) _tmp80_, NULL);
				_tmp82_ = _tmp81_;
				vala_collection_add ((ValaCollection*) _tmp78_, _tmp82_);
				_gtkaml_ast_markup_attribute_unref0 (_tmp82_);
				_vala_code_node_unref0 (_tmp80_);
				_vala_code_node_unref0 (formal_parameter);
				break;
			}
			_tmp83_ = formal_parameter;
			_tmp84_ = vala_symbol_get_name ((ValaSymbol*) _tmp83_);
			_tmp85_ = _tmp84_;
			_tmp86_ = formal_parameter;
			_tmp87_ = vala_variable_get_variable_type ((ValaVariable*) _tmp86_);
			_tmp88_ = _tmp87_;
			_tmp89_ = gtkaml_ast_markup_attribute_new_with_type (_tmp85_, NULL, _tmp88_, NULL);
			parameter = _tmp89_;
			_tmp90_ = parameters;
			_tmp91_ = parameter;
			vala_collection_add ((ValaCollection*) _tmp90_, _tmp91_);
			_gtkaml_ast_markup_attribute_unref0 (parameter);
			_vala_code_node_unref0 (formal_parameter);
		}
		_vala_iterable_unref0 (_formal_parameter_list);
	}
	result = (ValaList*) parameters;
	_gtkaml_markup_hint_unref0 (hint);
	return result;
}

/**
 * returns the list of methods that can be used to add child tags for the current type, and its base types
 */
ValaList*
gtkaml_markup_resolver_get_composition_method_candidates (GtkamlMarkupResolver* self,
                                                          ValaTypeSymbol* parent_tag_symbol)
{
	ValaSet* visited = NULL;
	GHashFunc _tmp0_;
	GEqualFunc _tmp1_;
	ValaHashSet* _tmp2_;
	ValaList* _tmp3_;
	ValaList* result;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (parent_tag_symbol != NULL, NULL);
	_tmp0_ = g_str_hash;
	_tmp1_ = g_str_equal;
	_tmp2_ = vala_hash_set_new (G_TYPE_STRING, (GBoxedCopyFunc) g_strdup, (GDestroyNotify) g_free, _tmp0_, _tmp1_);
	visited = (ValaSet*) _tmp2_;
	_tmp3_ = gtkaml_markup_resolver_get_composition_methods_cached (self, parent_tag_symbol, visited);
	result = _tmp3_;
	_vala_iterable_unref0 (visited);
	return result;
}

static gpointer
_vala_code_node_ref0 (gpointer self)
{
	return self ? vala_code_node_ref (self) : NULL;
}

ValaList*
gtkaml_markup_resolver_get_composition_methods_cached (GtkamlMarkupResolver* self,
                                                       ValaTypeSymbol* parent_tag_symbol,
                                                       ValaSet* visited)
{
	ValaList* candidates = NULL;
	GEqualFunc _tmp0_;
	ValaArrayList* _tmp1_;
	GtkamlMarkupHint* hint = NULL;
	GtkamlMarkupHintsStore* _tmp2_;
	ValaMap* _tmp3_;
	gchar* _tmp4_;
	gchar* _tmp5_;
	gpointer _tmp6_;
	GtkamlMarkupHint* _tmp7_;
	GtkamlMarkupHint* _tmp8_;
	gchar* _tmp83_;
	gchar* _tmp84_;
	ValaList* result;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (parent_tag_symbol != NULL, NULL);
	g_return_val_if_fail (visited != NULL, NULL);
	_tmp0_ = g_direct_equal;
	_tmp1_ = vala_array_list_new (GTKAML_TYPE_CALLABLE, (GBoxedCopyFunc) gtkaml_callable_ref, (GDestroyNotify) gtkaml_callable_unref, _tmp0_);
	candidates = (ValaList*) _tmp1_;
	_tmp2_ = self->markup_hints;
	_tmp3_ = _tmp2_->markup_hints;
	_tmp4_ = vala_symbol_get_full_name ((ValaSymbol*) parent_tag_symbol);
	_tmp5_ = _tmp4_;
	_tmp6_ = vala_map_get (_tmp3_, _tmp5_);
	_tmp7_ = (GtkamlMarkupHint*) _tmp6_;
	_g_free0 (_tmp5_);
	hint = _tmp7_;
	_tmp8_ = hint;
	if (_tmp8_ != NULL) {
		ValaList* names = NULL;
		GtkamlMarkupHint* _tmp9_;
		ValaList* _tmp10_;
		_tmp9_ = hint;
		_tmp10_ = gtkaml_markup_hint_get_composition_method_names (_tmp9_);
		names = _tmp10_;
		{
			ValaList* _name_list = NULL;
			ValaList* _tmp11_;
			gint _name_size = 0;
			ValaList* _tmp12_;
			gint _tmp13_;
			gint _tmp14_;
			gint _name_index = 0;
			_tmp11_ = names;
			_name_list = _tmp11_;
			_tmp12_ = _name_list;
			_tmp13_ = vala_collection_get_size ((ValaCollection*) _tmp12_);
			_tmp14_ = _tmp13_;
			_name_size = _tmp14_;
			_name_index = -1;
			while (TRUE) {
				gint _tmp15_;
				gint _tmp16_;
				gchar* name = NULL;
				ValaList* _tmp17_;
				gpointer _tmp18_;
				ValaSymbol* m = NULL;
				const gchar* _tmp19_;
				ValaSymbol* _tmp20_;
				ValaSymbol* _tmp21_;
				_name_index = _name_index + 1;
				_tmp15_ = _name_index;
				_tmp16_ = _name_size;
				if (!(_tmp15_ < _tmp16_)) {
					break;
				}
				_tmp17_ = _name_list;
				_tmp18_ = vala_list_get (_tmp17_, _name_index);
				name = (gchar*) _tmp18_;
				_tmp19_ = name;
				_tmp20_ = gtkaml_markup_resolver_search_method_or_signal (self, parent_tag_symbol, _tmp19_);
				m = _tmp20_;
				_tmp21_ = m;
				if (_tmp21_ == NULL) {
					const gchar* _tmp22_;
					gchar* _tmp23_;
					gchar* _tmp24_;
					gchar* _tmp25_;
					gchar* _tmp26_;
					_tmp22_ = name;
					_tmp23_ = vala_symbol_get_full_name ((ValaSymbol*) parent_tag_symbol);
					_tmp24_ = _tmp23_;
					_tmp25_ = g_strdup_printf ("Invalid composition method hint: %s does not belong to %s", _tmp22_, _tmp24_);
					_tmp26_ = _tmp25_;
					vala_report_error (NULL, "%s", _tmp26_);
					_g_free0 (_tmp26_);
					_g_free0 (_tmp24_);
				} else {
					ValaList* _tmp27_;
					ValaSymbol* _tmp28_;
					GtkamlCallable* _tmp29_;
					GtkamlCallable* _tmp30_;
					_tmp27_ = candidates;
					_tmp28_ = m;
					_tmp29_ = gtkaml_callable_new (_tmp28_);
					_tmp30_ = _tmp29_;
					vala_collection_add ((ValaCollection*) _tmp27_, _tmp30_);
					_gtkaml_callable_unref0 (_tmp30_);
				}
				_vala_code_node_unref0 (m);
				_g_free0 (name);
			}
		}
		_vala_iterable_unref0 (names);
	}
	if (G_TYPE_CHECK_INSTANCE_TYPE (parent_tag_symbol, VALA_TYPE_CLASS)) {
		ValaClass* parent_class = NULL;
		ValaClass* _tmp31_;
		gboolean _tmp32_ = FALSE;
		ValaClass* _tmp33_;
		ValaClass* _tmp34_;
		ValaClass* _tmp35_;
		_tmp31_ = _vala_code_node_ref0 (G_TYPE_CHECK_INSTANCE_CAST (parent_tag_symbol, VALA_TYPE_CLASS, ValaClass));
		parent_class = _tmp31_;
		_tmp33_ = parent_class;
		_tmp34_ = vala_class_get_base_class (_tmp33_);
		_tmp35_ = _tmp34_;
		if (_tmp35_ != NULL) {
			ValaClass* _tmp36_;
			ValaClass* _tmp37_;
			ValaClass* _tmp38_;
			gchar* _tmp39_;
			gchar* _tmp40_;
			_tmp36_ = parent_class;
			_tmp37_ = vala_class_get_base_class (_tmp36_);
			_tmp38_ = _tmp37_;
			_tmp39_ = vala_symbol_get_full_name ((ValaSymbol*) _tmp38_);
			_tmp40_ = _tmp39_;
			_tmp32_ = !vala_collection_contains ((ValaCollection*) visited, _tmp40_);
			_g_free0 (_tmp40_);
		} else {
			_tmp32_ = FALSE;
		}
		if (_tmp32_) {
			{
				ValaList* _m_list = NULL;
				ValaClass* _tmp41_;
				ValaClass* _tmp42_;
				ValaClass* _tmp43_;
				ValaList* _tmp44_;
				gint _m_size = 0;
				ValaList* _tmp45_;
				gint _tmp46_;
				gint _tmp47_;
				gint _m_index = 0;
				_tmp41_ = parent_class;
				_tmp42_ = vala_class_get_base_class (_tmp41_);
				_tmp43_ = _tmp42_;
				_tmp44_ = gtkaml_markup_resolver_get_composition_methods_cached (self, (ValaTypeSymbol*) _tmp43_, visited);
				_m_list = _tmp44_;
				_tmp45_ = _m_list;
				_tmp46_ = vala_collection_get_size ((ValaCollection*) _tmp45_);
				_tmp47_ = _tmp46_;
				_m_size = _tmp47_;
				_m_index = -1;
				while (TRUE) {
					gint _tmp48_;
					gint _tmp49_;
					GtkamlCallable* m = NULL;
					ValaList* _tmp50_;
					gpointer _tmp51_;
					ValaList* _tmp52_;
					GtkamlCallable* _tmp53_;
					_m_index = _m_index + 1;
					_tmp48_ = _m_index;
					_tmp49_ = _m_size;
					if (!(_tmp48_ < _tmp49_)) {
						break;
					}
					_tmp50_ = _m_list;
					_tmp51_ = vala_list_get (_tmp50_, _m_index);
					m = (GtkamlCallable*) _tmp51_;
					_tmp52_ = candidates;
					_tmp53_ = m;
					vala_collection_add ((ValaCollection*) _tmp52_, _tmp53_);
					_gtkaml_callable_unref0 (m);
				}
				_vala_iterable_unref0 (_m_list);
			}
		}
		{
			ValaList* _base_type_list = NULL;
			ValaClass* _tmp54_;
			ValaList* _tmp55_;
			gint _base_type_size = 0;
			ValaList* _tmp56_;
			gint _tmp57_;
			gint _tmp58_;
			gint _base_type_index = 0;
			_tmp54_ = parent_class;
			_tmp55_ = vala_class_get_base_types (_tmp54_);
			_base_type_list = _tmp55_;
			_tmp56_ = _base_type_list;
			_tmp57_ = vala_collection_get_size ((ValaCollection*) _tmp56_);
			_tmp58_ = _tmp57_;
			_base_type_size = _tmp58_;
			_base_type_index = -1;
			while (TRUE) {
				gint _tmp59_;
				gint _tmp60_;
				ValaDataType* base_type = NULL;
				ValaList* _tmp61_;
				gpointer _tmp62_;
				ValaDataType* _tmp63_;
				gchar* _tmp64_;
				gchar* _tmp65_;
				gboolean _tmp66_;
				_base_type_index = _base_type_index + 1;
				_tmp59_ = _base_type_index;
				_tmp60_ = _base_type_size;
				if (!(_tmp59_ < _tmp60_)) {
					break;
				}
				_tmp61_ = _base_type_list;
				_tmp62_ = vala_list_get (_tmp61_, _base_type_index);
				base_type = (ValaDataType*) _tmp62_;
				_tmp63_ = base_type;
				_tmp64_ = vala_data_type_to_qualified_string (_tmp63_, NULL);
				_tmp65_ = _tmp64_;
				_tmp66_ = !vala_collection_contains ((ValaCollection*) visited, _tmp65_);
				_g_free0 (_tmp65_);
				if (_tmp66_) {
					ValaDataType* _tmp67_;
					ValaTypeSymbol* _tmp68_;
					ValaTypeSymbol* _tmp69_;
					_tmp67_ = base_type;
					_tmp68_ = vala_data_type_get_type_symbol (_tmp67_);
					_tmp69_ = _tmp68_;
					if (_tmp69_ == NULL) {
						_vala_code_node_unref0 (base_type);
						continue;
					}
					{
						ValaList* _m_list = NULL;
						ValaDataType* _tmp70_;
						ValaTypeSymbol* _tmp71_;
						ValaTypeSymbol* _tmp72_;
						ValaList* _tmp73_;
						gint _m_size = 0;
						ValaList* _tmp74_;
						gint _tmp75_;
						gint _tmp76_;
						gint _m_index = 0;
						_tmp70_ = base_type;
						_tmp71_ = vala_data_type_get_type_symbol (_tmp70_);
						_tmp72_ = _tmp71_;
						_tmp73_ = gtkaml_markup_resolver_get_composition_methods_cached (self, _tmp72_, visited);
						_m_list = _tmp73_;
						_tmp74_ = _m_list;
						_tmp75_ = vala_collection_get_size ((ValaCollection*) _tmp74_);
						_tmp76_ = _tmp75_;
						_m_size = _tmp76_;
						_m_index = -1;
						while (TRUE) {
							gint _tmp77_;
							gint _tmp78_;
							GtkamlCallable* m = NULL;
							ValaList* _tmp79_;
							gpointer _tmp80_;
							ValaList* _tmp81_;
							GtkamlCallable* _tmp82_;
							_m_index = _m_index + 1;
							_tmp77_ = _m_index;
							_tmp78_ = _m_size;
							if (!(_tmp77_ < _tmp78_)) {
								break;
							}
							_tmp79_ = _m_list;
							_tmp80_ = vala_list_get (_tmp79_, _m_index);
							m = (GtkamlCallable*) _tmp80_;
							_tmp81_ = candidates;
							_tmp82_ = m;
							vala_collection_add ((ValaCollection*) _tmp81_, _tmp82_);
							_gtkaml_callable_unref0 (m);
						}
						_vala_iterable_unref0 (_m_list);
					}
				}
				_vala_code_node_unref0 (base_type);
			}
		}
		_vala_code_node_unref0 (parent_class);
	}
	_tmp83_ = vala_symbol_get_full_name ((ValaSymbol*) parent_tag_symbol);
	_tmp84_ = _tmp83_;
	vala_collection_add ((ValaCollection*) visited, _tmp84_);
	_g_free0 (_tmp84_);
	result = candidates;
	_gtkaml_markup_hint_unref0 (hint);
	return result;
}

/** 
 * returns method or signal 
 */
ValaSymbol*
gtkaml_markup_resolver_search_method_or_signal (GtkamlMarkupResolver* self,
                                                ValaTypeSymbol* type,
                                                const gchar* name)
{
	ValaSymbol* result;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (type != NULL, NULL);
	g_return_val_if_fail (name != NULL, NULL);
	if (G_TYPE_CHECK_INSTANCE_TYPE (type, VALA_TYPE_CLASS)) {
		ValaClass* class_type = NULL;
		ValaClass* _tmp0_;
		ValaClass* _tmp25_;
		ValaClass* _tmp26_;
		ValaClass* _tmp27_;
		_tmp0_ = _vala_code_node_ref0 (G_TYPE_CHECK_INSTANCE_CAST (type, VALA_TYPE_CLASS, ValaClass));
		class_type = _tmp0_;
		{
			ValaList* _m_list = NULL;
			ValaClass* _tmp1_;
			ValaList* _tmp2_;
			gint _m_size = 0;
			ValaList* _tmp3_;
			gint _tmp4_;
			gint _tmp5_;
			gint _m_index = 0;
			_tmp1_ = class_type;
			_tmp2_ = vala_object_type_symbol_get_methods ((ValaObjectTypeSymbol*) _tmp1_);
			_m_list = _tmp2_;
			_tmp3_ = _m_list;
			_tmp4_ = vala_collection_get_size ((ValaCollection*) _tmp3_);
			_tmp5_ = _tmp4_;
			_m_size = _tmp5_;
			_m_index = -1;
			while (TRUE) {
				gint _tmp6_;
				gint _tmp7_;
				ValaMethod* m = NULL;
				ValaList* _tmp8_;
				gpointer _tmp9_;
				ValaMethod* _tmp10_;
				const gchar* _tmp11_;
				const gchar* _tmp12_;
				_m_index = _m_index + 1;
				_tmp6_ = _m_index;
				_tmp7_ = _m_size;
				if (!(_tmp6_ < _tmp7_)) {
					break;
				}
				_tmp8_ = _m_list;
				_tmp9_ = vala_list_get (_tmp8_, _m_index);
				m = (ValaMethod*) _tmp9_;
				_tmp10_ = m;
				_tmp11_ = vala_symbol_get_name ((ValaSymbol*) _tmp10_);
				_tmp12_ = _tmp11_;
				if (g_strcmp0 (_tmp12_, name) == 0) {
					result = (ValaSymbol*) m;
					_vala_code_node_unref0 (class_type);
					return result;
				}
				_vala_code_node_unref0 (m);
			}
		}
		{
			ValaList* _s_list = NULL;
			ValaClass* _tmp13_;
			ValaList* _tmp14_;
			gint _s_size = 0;
			ValaList* _tmp15_;
			gint _tmp16_;
			gint _tmp17_;
			gint _s_index = 0;
			_tmp13_ = class_type;
			_tmp14_ = vala_object_type_symbol_get_signals ((ValaObjectTypeSymbol*) _tmp13_);
			_s_list = _tmp14_;
			_tmp15_ = _s_list;
			_tmp16_ = vala_collection_get_size ((ValaCollection*) _tmp15_);
			_tmp17_ = _tmp16_;
			_s_size = _tmp17_;
			_s_index = -1;
			while (TRUE) {
				gint _tmp18_;
				gint _tmp19_;
				ValaSignal* s = NULL;
				ValaList* _tmp20_;
				gpointer _tmp21_;
				ValaSignal* _tmp22_;
				const gchar* _tmp23_;
				const gchar* _tmp24_;
				_s_index = _s_index + 1;
				_tmp18_ = _s_index;
				_tmp19_ = _s_size;
				if (!(_tmp18_ < _tmp19_)) {
					break;
				}
				_tmp20_ = _s_list;
				_tmp21_ = vala_list_get (_tmp20_, _s_index);
				s = (ValaSignal*) _tmp21_;
				_tmp22_ = s;
				_tmp23_ = vala_symbol_get_name ((ValaSymbol*) _tmp22_);
				_tmp24_ = _tmp23_;
				if (g_strcmp0 (_tmp24_, name) == 0) {
					result = (ValaSymbol*) s;
					_vala_code_node_unref0 (class_type);
					return result;
				}
				_vala_code_node_unref0 (s);
			}
		}
		_tmp25_ = class_type;
		_tmp26_ = vala_class_get_base_class (_tmp25_);
		_tmp27_ = _tmp26_;
		if (_tmp27_ != NULL) {
			ValaSymbol* m = NULL;
			ValaClass* _tmp28_;
			ValaClass* _tmp29_;
			ValaClass* _tmp30_;
			ValaSymbol* _tmp31_;
			ValaSymbol* _tmp32_;
			_tmp28_ = class_type;
			_tmp29_ = vala_class_get_base_class (_tmp28_);
			_tmp30_ = _tmp29_;
			_tmp31_ = gtkaml_markup_resolver_search_method_or_signal (self, (ValaTypeSymbol*) _tmp30_, name);
			m = _tmp31_;
			_tmp32_ = m;
			if (_tmp32_ != NULL) {
				result = m;
				_vala_code_node_unref0 (class_type);
				return result;
			}
			_vala_code_node_unref0 (m);
		}
		{
			ValaList* _base_type_list = NULL;
			ValaClass* _tmp33_;
			ValaList* _tmp34_;
			gint _base_type_size = 0;
			ValaList* _tmp35_;
			gint _tmp36_;
			gint _tmp37_;
			gint _base_type_index = 0;
			_tmp33_ = class_type;
			_tmp34_ = vala_class_get_base_types (_tmp33_);
			_base_type_list = _tmp34_;
			_tmp35_ = _base_type_list;
			_tmp36_ = vala_collection_get_size ((ValaCollection*) _tmp35_);
			_tmp37_ = _tmp36_;
			_base_type_size = _tmp37_;
			_base_type_index = -1;
			while (TRUE) {
				gint _tmp38_;
				gint _tmp39_;
				ValaDataType* base_type = NULL;
				ValaList* _tmp40_;
				gpointer _tmp41_;
				ValaDataType* _tmp42_;
				ValaTypeSymbol* _tmp43_;
				ValaTypeSymbol* _tmp44_;
				ValaSymbol* m = NULL;
				ValaDataType* _tmp45_;
				ValaTypeSymbol* _tmp46_;
				ValaTypeSymbol* _tmp47_;
				ValaSymbol* _tmp48_;
				ValaSymbol* _tmp49_;
				_base_type_index = _base_type_index + 1;
				_tmp38_ = _base_type_index;
				_tmp39_ = _base_type_size;
				if (!(_tmp38_ < _tmp39_)) {
					break;
				}
				_tmp40_ = _base_type_list;
				_tmp41_ = vala_list_get (_tmp40_, _base_type_index);
				base_type = (ValaDataType*) _tmp41_;
				_tmp42_ = base_type;
				_tmp43_ = vala_data_type_get_type_symbol (_tmp42_);
				_tmp44_ = _tmp43_;
				if (_tmp44_ == NULL) {
					_vala_code_node_unref0 (base_type);
					continue;
				}
				_tmp45_ = base_type;
				_tmp46_ = vala_data_type_get_type_symbol (_tmp45_);
				_tmp47_ = _tmp46_;
				_tmp48_ = gtkaml_markup_resolver_search_method_or_signal (self, _tmp47_, name);
				m = _tmp48_;
				_tmp49_ = m;
				if (_tmp49_ != NULL) {
					result = m;
					_vala_code_node_unref0 (base_type);
					_vala_code_node_unref0 (class_type);
					return result;
				}
				_vala_code_node_unref0 (m);
				_vala_code_node_unref0 (base_type);
			}
		}
		_vala_code_node_unref0 (class_type);
	} else {
		if (G_TYPE_CHECK_INSTANCE_TYPE (type, VALA_TYPE_INTERFACE)) {
			ValaInterface* interface_type = NULL;
			ValaInterface* _tmp50_;
			_tmp50_ = _vala_code_node_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (type, VALA_TYPE_INTERFACE) ? ((ValaInterface*) type) : NULL);
			interface_type = _tmp50_;
			{
				ValaList* _m_list = NULL;
				ValaInterface* _tmp51_;
				ValaList* _tmp52_;
				gint _m_size = 0;
				ValaList* _tmp53_;
				gint _tmp54_;
				gint _tmp55_;
				gint _m_index = 0;
				_tmp51_ = interface_type;
				_tmp52_ = vala_object_type_symbol_get_methods ((ValaObjectTypeSymbol*) _tmp51_);
				_m_list = _tmp52_;
				_tmp53_ = _m_list;
				_tmp54_ = vala_collection_get_size ((ValaCollection*) _tmp53_);
				_tmp55_ = _tmp54_;
				_m_size = _tmp55_;
				_m_index = -1;
				while (TRUE) {
					gint _tmp56_;
					gint _tmp57_;
					ValaMethod* m = NULL;
					ValaList* _tmp58_;
					gpointer _tmp59_;
					ValaMethod* _tmp60_;
					const gchar* _tmp61_;
					const gchar* _tmp62_;
					_m_index = _m_index + 1;
					_tmp56_ = _m_index;
					_tmp57_ = _m_size;
					if (!(_tmp56_ < _tmp57_)) {
						break;
					}
					_tmp58_ = _m_list;
					_tmp59_ = vala_list_get (_tmp58_, _m_index);
					m = (ValaMethod*) _tmp59_;
					_tmp60_ = m;
					_tmp61_ = vala_symbol_get_name ((ValaSymbol*) _tmp60_);
					_tmp62_ = _tmp61_;
					if (g_strcmp0 (_tmp62_, name) == 0) {
						result = (ValaSymbol*) m;
						_vala_code_node_unref0 (interface_type);
						return result;
					}
					_vala_code_node_unref0 (m);
				}
			}
			{
				ValaList* _s_list = NULL;
				ValaInterface* _tmp63_;
				ValaList* _tmp64_;
				gint _s_size = 0;
				ValaList* _tmp65_;
				gint _tmp66_;
				gint _tmp67_;
				gint _s_index = 0;
				_tmp63_ = interface_type;
				_tmp64_ = vala_object_type_symbol_get_signals ((ValaObjectTypeSymbol*) _tmp63_);
				_s_list = _tmp64_;
				_tmp65_ = _s_list;
				_tmp66_ = vala_collection_get_size ((ValaCollection*) _tmp65_);
				_tmp67_ = _tmp66_;
				_s_size = _tmp67_;
				_s_index = -1;
				while (TRUE) {
					gint _tmp68_;
					gint _tmp69_;
					ValaSignal* s = NULL;
					ValaList* _tmp70_;
					gpointer _tmp71_;
					ValaSignal* _tmp72_;
					const gchar* _tmp73_;
					const gchar* _tmp74_;
					_s_index = _s_index + 1;
					_tmp68_ = _s_index;
					_tmp69_ = _s_size;
					if (!(_tmp68_ < _tmp69_)) {
						break;
					}
					_tmp70_ = _s_list;
					_tmp71_ = vala_list_get (_tmp70_, _s_index);
					s = (ValaSignal*) _tmp71_;
					_tmp72_ = s;
					_tmp73_ = vala_symbol_get_name ((ValaSymbol*) _tmp72_);
					_tmp74_ = _tmp73_;
					if (g_strcmp0 (_tmp74_, name) == 0) {
						result = (ValaSymbol*) s;
						_vala_code_node_unref0 (interface_type);
						return result;
					}
					_vala_code_node_unref0 (s);
				}
			}
			_vala_code_node_unref0 (interface_type);
		} else {
			g_assert_not_reached ();
		}
	}
	result = NULL;
	return result;
}

GtkamlMarkupResolver*
gtkaml_markup_resolver_construct (GType object_type)
{
	GtkamlMarkupResolver* self = NULL;
	self = (GtkamlMarkupResolver*) vala_symbol_resolver_construct (object_type);
	return self;
}

GtkamlMarkupResolver*
gtkaml_markup_resolver_new (void)
{
	return gtkaml_markup_resolver_construct (GTKAML_TYPE_MARKUP_RESOLVER);
}

static GtkamlValaParser*
gtkaml_markup_resolver_real_get_code_parser (GtkamlCodeParserProvider* base)
{
	GtkamlValaParser* result;
	GtkamlMarkupResolver* self;
	GtkamlValaParser* _tmp0_;
	self = (GtkamlMarkupResolver*) base;
	_tmp0_ = self->priv->_code_parser;
	result = _tmp0_;
	return result;
}

static gpointer
_gtkaml_vala_parser_ref0 (gpointer self)
{
	return self ? gtkaml_vala_parser_ref (self) : NULL;
}

static void
gtkaml_markup_resolver_real_set_code_parser (GtkamlCodeParserProvider* base,
                                             GtkamlValaParser* value)
{
	GtkamlMarkupResolver* self;
	GtkamlValaParser* _tmp0_;
	self = (GtkamlMarkupResolver*) base;
	_tmp0_ = _gtkaml_vala_parser_ref0 (value);
	_gtkaml_vala_parser_unref0 (self->priv->_code_parser);
	self->priv->_code_parser = _tmp0_;
}

static GtkamlCodeContext*
gtkaml_markup_resolver_get_context (GtkamlMarkupResolver* self)
{
	GtkamlCodeContext* result;
	GtkamlCodeContext* _tmp0_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_context;
	result = _tmp0_;
	return result;
}

static gpointer
_vala_code_context_ref0 (gpointer self)
{
	return self ? vala_code_context_ref (self) : NULL;
}

static void
gtkaml_markup_resolver_set_context (GtkamlMarkupResolver* self,
                                    GtkamlCodeContext* value)
{
	GtkamlCodeContext* _tmp0_;
	g_return_if_fail (self != NULL);
	_tmp0_ = _vala_code_context_ref0 (value);
	_vala_code_context_unref0 (self->priv->_context);
	self->priv->_context = _tmp0_;
}

static void
gtkaml_markup_resolver_class_init (GtkamlMarkupResolverClass * klass,
                                   gpointer klass_data)
{
	gtkaml_markup_resolver_parent_class = g_type_class_peek_parent (klass);
	((ValaCodeVisitorClass *) klass)->finalize = gtkaml_markup_resolver_finalize;
	g_type_class_adjust_private_offset (klass, &GtkamlMarkupResolver_private_offset);
}

static void
gtkaml_markup_resolver_gtkaml_code_parser_provider_interface_init (GtkamlCodeParserProviderIface * iface,
                                                                   gpointer iface_data)
{
	gtkaml_markup_resolver_gtkaml_code_parser_provider_parent_iface = g_type_interface_peek_parent (iface);
	iface->get_code_parser = gtkaml_markup_resolver_real_get_code_parser;
	iface->set_code_parser = gtkaml_markup_resolver_real_set_code_parser;
}

static void
gtkaml_markup_resolver_instance_init (GtkamlMarkupResolver * self,
                                      gpointer klass)
{
	self->priv = gtkaml_markup_resolver_get_instance_private (self);
}

static void
gtkaml_markup_resolver_finalize (ValaCodeVisitor * obj)
{
	GtkamlMarkupResolver * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, GTKAML_TYPE_MARKUP_RESOLVER, GtkamlMarkupResolver);
	_gtkaml_markup_hints_store_unref0 (self->markup_hints);
	_gtkaml_vala_parser_unref0 (self->priv->_code_parser);
	_vala_code_context_unref0 (self->priv->_context);
	VALA_CODE_VISITOR_CLASS (gtkaml_markup_resolver_parent_class)->finalize (obj);
}

/**
 * Gtkaml SymbolResolver
 */
static GType
gtkaml_markup_resolver_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (GtkamlMarkupResolverClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) gtkaml_markup_resolver_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (GtkamlMarkupResolver), 0, (GInstanceInitFunc) gtkaml_markup_resolver_instance_init, NULL };
	static const GInterfaceInfo gtkaml_code_parser_provider_info = { (GInterfaceInitFunc) gtkaml_markup_resolver_gtkaml_code_parser_provider_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
	GType gtkaml_markup_resolver_type_id;
	gtkaml_markup_resolver_type_id = g_type_register_static (VALA_TYPE_SYMBOL_RESOLVER, "GtkamlMarkupResolver", &g_define_type_info, 0);
	g_type_add_interface_static (gtkaml_markup_resolver_type_id, GTKAML_TYPE_CODE_PARSER_PROVIDER, &gtkaml_code_parser_provider_info);
	GtkamlMarkupResolver_private_offset = g_type_add_instance_private (gtkaml_markup_resolver_type_id, sizeof (GtkamlMarkupResolverPrivate));
	return gtkaml_markup_resolver_type_id;
}

GType
gtkaml_markup_resolver_get_type (void)
{
	static volatile gsize gtkaml_markup_resolver_type_id__once = 0;
	if (g_once_init_enter (&gtkaml_markup_resolver_type_id__once)) {
		GType gtkaml_markup_resolver_type_id;
		gtkaml_markup_resolver_type_id = gtkaml_markup_resolver_get_type_once ();
		g_once_init_leave (&gtkaml_markup_resolver_type_id__once, gtkaml_markup_resolver_type_id);
	}
	return gtkaml_markup_resolver_type_id__once;
}

