/* gtkamlcodeparserprovider.c generated by valac 0.56.16, the Vala compiler
 * generated from gtkamlcodeparserprovider.vala, do not modify */

/* gtkamlcodeparserprovider.vala
 *
 * Copyright (C) 2011 Vlad Grecescu
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public
 * License along with main.c; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor Boston, MA 02110-1301,  USA
 *
 * Author:
 *        Vlad Grecescu (b100dian@gmail.com)
 */

#include "gtkaml.h"
#include <glib.h>

#if !defined(VALA_STRICT_C)
#if !defined(__clang__) && defined(__GNUC__) && (__GNUC__ >= 14)
#pragma GCC diagnostic warning "-Wincompatible-pointer-types"
#elif defined(__clang__) && (__clang_major__ >= 16)
#pragma clang diagnostic ignored "-Wincompatible-function-pointer-types"
#pragma clang diagnostic ignored "-Wincompatible-pointer-types"
#endif
#endif

static GType gtkaml_code_parser_provider_get_type_once (void);

GtkamlValaParser*
gtkaml_code_parser_provider_get_code_parser (GtkamlCodeParserProvider* self)
{
	GtkamlCodeParserProviderIface* _iface_;
	g_return_val_if_fail (self != NULL, NULL);
	_iface_ = GTKAML_CODE_PARSER_PROVIDER_GET_INTERFACE (self);
	if (_iface_->get_code_parser) {
		return _iface_->get_code_parser (self);
	}
	return NULL;
}

void
gtkaml_code_parser_provider_set_code_parser (GtkamlCodeParserProvider* self,
                                             GtkamlValaParser* value)
{
	GtkamlCodeParserProviderIface* _iface_;
	g_return_if_fail (self != NULL);
	_iface_ = GTKAML_CODE_PARSER_PROVIDER_GET_INTERFACE (self);
	if (_iface_->set_code_parser) {
		_iface_->set_code_parser (self, value);
	}
}

static void
gtkaml_code_parser_provider_default_init (GtkamlCodeParserProviderIface * iface,
                                          gpointer iface_data)
{
}

/**
 * common interface between resolver and parser: to provide a parser of Vala code
 */
static GType
gtkaml_code_parser_provider_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (GtkamlCodeParserProviderIface), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) gtkaml_code_parser_provider_default_init, (GClassFinalizeFunc) NULL, NULL, 0, 0, (GInstanceInitFunc) NULL, NULL };
	GType gtkaml_code_parser_provider_type_id;
	gtkaml_code_parser_provider_type_id = g_type_register_static (G_TYPE_INTERFACE, "GtkamlCodeParserProvider", &g_define_type_info, 0);
	g_type_interface_add_prerequisite (gtkaml_code_parser_provider_type_id, VALA_TYPE_CODE_VISITOR);
	return gtkaml_code_parser_provider_type_id;
}

GType
gtkaml_code_parser_provider_get_type (void)
{
	static volatile gsize gtkaml_code_parser_provider_type_id__once = 0;
	if (g_once_init_enter (&gtkaml_code_parser_provider_type_id__once)) {
		GType gtkaml_code_parser_provider_type_id;
		gtkaml_code_parser_provider_type_id = gtkaml_code_parser_provider_get_type_once ();
		g_once_init_leave (&gtkaml_code_parser_provider_type_id__once, gtkaml_code_parser_provider_type_id);
	}
	return gtkaml_code_parser_provider_type_id__once;
}

