/* gtkonparser.c generated by valac 0.56.16, the Vala compiler
 * generated from gtkonparser.vala, do not modify */

/* gtkon parser -- Copyleft 2010-2011 -- author: pancake<nopcode.org> */

#include "gtkaml.h"
#include <glib.h>
#include <stdlib.h>
#include <string.h>
#include <gio/gio.h>
#include <config.h>
#include <glib-object.h>
#include <gobject/gvaluecollector.h>

#if !defined(VALA_STRICT_C)
#if !defined(__clang__) && defined(__GNUC__) && (__GNUC__ >= 14)
#pragma GCC diagnostic warning "-Wincompatible-pointer-types"
#elif defined(__clang__) && (__clang_major__ >= 16)
#pragma clang diagnostic ignored "-Wincompatible-function-pointer-types"
#pragma clang diagnostic ignored "-Wincompatible-pointer-types"
#endif
#endif

#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _gtkon_token_free0(var) ((var == NULL) ? NULL : (var = (gtkon_token_free (var), NULL)))
#define _g_regex_unref0(var) ((var == NULL) ? NULL : (var = (g_regex_unref (var), NULL)))
#define _g_string_free0(var) ((var == NULL) ? NULL : (var = (g_string_free (var, TRUE), NULL)))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))
typedef struct _ParamSpecGtkonParser ParamSpecGtkonParser;

struct _GtkonParserPrivate {
	GString* xmlstr;
};

struct _ParamSpecGtkonParser {
	GParamSpec parent_instance;
};

VALA_EXTERN gint tok_idx;
gint tok_idx = 0;
VALA_EXTERN gint usingcount;
gint usingcount = 0;
VALA_EXTERN gchar* tokens[64];
gchar* tokens[64] = {0};
VALA_EXTERN gboolean mustclose;
gboolean mustclose = FALSE;
VALA_EXTERN GtkonTokenType last_type;
GtkonTokenType last_type = 0;
VALA_EXTERN gboolean first_class;
gboolean first_class = TRUE;
VALA_EXTERN gboolean has_version;
gboolean has_version = FALSE;
VALA_EXTERN gchar* rootclass;
gchar* rootclass = NULL;
VALA_EXTERN gchar nextchar;
gchar nextchar = (gchar) 0;
gboolean genie_mode = FALSE;
gint genie_indent = 1;
gboolean nextiscode = FALSE;
gint spaces = 0;
gboolean newkeyword = TRUE;
gint ospaces = 0;
gboolean checkforindent = FALSE;
VALA_EXTERN GtkonToken* next_token;
GtkonToken* next_token = NULL;
static gint GtkonParser_private_offset;
static gpointer gtkon_parser_parent_class = NULL;

VALA_EXTERN void pushtoken (const gchar* token);
VALA_EXTERN gchar* poptoken (void);
static void gtkon_token_instance_init (GtkonToken * self);
static gboolean gtkon_token_is_separator (GtkonToken* self,
                                   guchar ch);
static guchar gtkon_token_readchar (GtkonToken* self,
                             GError** error);
static gboolean gtkon_token_skip_spaces (GtkonToken* self,
                                  GError** error);
static gchar* gtkon_token_xmlfilteredchar (GtkonToken* self,
                                    guchar ch);
static void gtkon_parser_finalize (GtkonParser * obj);
static GType gtkon_parser_get_type_once (void);
static void _vala_array_destroy (gpointer array,
                          gssize array_length,
                          GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array,
                       gssize array_length,
                       GDestroyNotify destroy_func);
static gssize _vala_array_length (gpointer array);

static GType
gtkon_token_type_get_type_once (void)
{
	static const GEnumValue values[] = {{GTKON_TOKEN_TYPE_CODE, "GTKON_TOKEN_TYPE_CODE", "code"}, {GTKON_TOKEN_TYPE_CLASS, "GTKON_TOKEN_TYPE_CLASS", "class"}, {GTKON_TOKEN_TYPE_COMMENT_LINE, "GTKON_TOKEN_TYPE_COMMENT_LINE", "comment-line"}, {GTKON_TOKEN_TYPE_COMMENT_BLOCK, "GTKON_TOKEN_TYPE_COMMENT_BLOCK", "comment-block"}, {GTKON_TOKEN_TYPE_ATTRIBUTE, "GTKON_TOKEN_TYPE_ATTRIBUTE", "attribute"}, {GTKON_TOKEN_TYPE_BEGIN, "GTKON_TOKEN_TYPE_BEGIN", "begin"}, {GTKON_TOKEN_TYPE_END, "GTKON_TOKEN_TYPE_END", "end"}, {GTKON_TOKEN_TYPE_INVALID, "GTKON_TOKEN_TYPE_INVALID", "invalid"}, {0, NULL, NULL}};
	GType gtkon_token_type_type_id;
	gtkon_token_type_type_id = g_enum_register_static ("GtkonTokenType", values);
	return gtkon_token_type_type_id;
}

GType
gtkon_token_type_get_type (void)
{
	static volatile gsize gtkon_token_type_type_id__once = 0;
	if (g_once_init_enter (&gtkon_token_type_type_id__once)) {
		GType gtkon_token_type_type_id;
		gtkon_token_type_type_id = gtkon_token_type_get_type_once ();
		g_once_init_leave (&gtkon_token_type_type_id__once, gtkon_token_type_type_id);
	}
	return gtkon_token_type_type_id__once;
}

void
pushtoken (const gchar* token)
{
	gint _tmp0_;
	const gchar* _tmp1_;
	gchar* _tmp2_;
	g_return_if_fail (token != NULL);
	if (tok_idx >= 64) {
		g_error ("gtkonparser.vala:27: Cannot push more tokens");
	}
	_tmp0_ = tok_idx;
	tok_idx = _tmp0_ + 1;
	_tmp1_ = token;
	_tmp2_ = g_strdup (_tmp1_);
	_g_free0 (tokens[_tmp0_]);
	tokens[_tmp0_] = _tmp2_;
}

gchar*
poptoken (void)
{
	gint _tmp1_;
	const gchar* _tmp2_;
	gchar* _tmp3_;
	gchar* result;
	if (tok_idx == 0) {
		gchar* _tmp0_;
		_tmp0_ = g_strdup ("");
		result = _tmp0_;
		return result;
	}
	tok_idx = tok_idx - 1;
	_tmp1_ = tok_idx;
	_tmp2_ = tokens[_tmp1_];
	_tmp3_ = g_strdup (_tmp2_);
	result = _tmp3_;
	return result;
}

static gboolean
gtkon_token_is_separator (GtkonToken* self,
                          guchar ch)
{
	gboolean result;
	g_return_val_if_fail (self != NULL, FALSE);
	if (genie_mode) {
		if (nextiscode) {
			self->type = GTKON_TOKEN_TYPE_CODE;
			result = FALSE;
			return result;
		}
		switch (ch) {
			case ' ':
			case '\t':
			{
				g_print ("is_space\n");
				if (newkeyword) {
					gint _tmp0_;
					_tmp0_ = spaces;
					spaces = _tmp0_ + 1;
				}
				result = TRUE;
				return result;
			}
			case '\r':
			case '\n':
			{
				g_print ("-------> is_newline and new keyword\n");
				newkeyword = TRUE;
				ospaces = spaces;
				spaces = 0;
				result = TRUE;
				return result;
			}
			case ',':
			case '\0':
			{
				result = TRUE;
				return result;
			}
			default:
			break;
		}
		if (newkeyword) {
			if (ospaces >= spaces) {
				newkeyword = TRUE;
				ospaces = spaces;
				g_print ("==== CLOSE TAG\n");
			}
		}
		g_print ("  %d %d is_char (%c)\n", (gint) newkeyword, spaces, (gint) ch);
		newkeyword = FALSE;
		result = FALSE;
		return result;
	} else {
		switch (ch) {
			case ' ':
			case '\t':
			case '\r':
			case '\n':
			case ',':
			case '\0':
			{
				result = TRUE;
				return result;
			}
			default:
			break;
		}
		result = FALSE;
		return result;
	}
}

static guchar
gtkon_token_readchar (GtkonToken* self,
                      GError** error)
{
	guchar ch = '\0';
	GError* _inner_error0_ = NULL;
	guchar result;
	g_return_val_if_fail (self != NULL, '\0');
	ch = (guchar) nextchar;
	if (((gint) ch) != 0) {
		nextchar = (gchar) 0;
	} else {
		guint8 _tmp0_ = 0U;
		GDataInputStream* _tmp1_;
		_tmp1_ = self->dis;
		_tmp0_ = g_data_input_stream_read_byte (_tmp1_, NULL, &_inner_error0_);
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
			guchar _tmp2_ = '\0';
			g_propagate_error (error, _inner_error0_);
			return _tmp2_;
		}
		ch = (guchar) _tmp0_;
	}
	result = ch;
	return result;
}

static gboolean
gtkon_token_skip_spaces (GtkonToken* self,
                         GError** error)
{
	gint ch = 0;
	GError* _inner_error0_ = NULL;
	gboolean result;
	g_return_val_if_fail (self != NULL, FALSE);
	ch = 0;
	{
		gboolean _tmp0_ = FALSE;
		_tmp0_ = TRUE;
		while (TRUE) {
			guchar _tmp1_ = '\0';
			if (!_tmp0_) {
				if (!gtkon_token_is_separator (self, (guchar) ch)) {
					break;
				}
			}
			_tmp0_ = FALSE;
			_tmp1_ = gtkon_token_readchar (self, &_inner_error0_);
			if (G_UNLIKELY (_inner_error0_ != NULL)) {
				gboolean _tmp2_ = FALSE;
				g_propagate_error (error, _inner_error0_);
				return _tmp2_;
			}
			ch = (gint) _tmp1_;
		}
	}
	result = gtkon_token_update (self, (guchar) ch);
	return result;
}

static gpointer
_g_object_ref0 (gpointer self)
{
	return self ? g_object_ref (self) : NULL;
}

GtkonToken*
gtkon_token_new_copy (GtkonToken* src)
{
	GtkonToken* self;
	const gchar* _tmp0_;
	gchar* _tmp1_;
	GDataInputStream* _tmp2_;
	GDataInputStream* _tmp3_;
	g_return_val_if_fail (src != NULL, NULL);
	self = g_slice_new0 (GtkonToken);
	gtkon_token_instance_init (self);
	_tmp0_ = src->str;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->str);
	self->str = _tmp1_;
	self->type = src->type;
	self->quoted = src->quoted;
	_tmp2_ = src->dis;
	_tmp3_ = _g_object_ref0 (_tmp2_);
	_g_object_unref0 (self->dis);
	self->dis = _tmp3_;
	return self;
}

GtkonToken*
gtkon_token_new (GDataInputStream* dis,
                 GError** error)
{
	GtkonToken* self;
	GtkonToken* _tmp0_;
	GError* _inner_error0_ = NULL;
	g_return_val_if_fail (dis != NULL, NULL);
	self = g_slice_new0 (GtkonToken);
	gtkon_token_instance_init (self);
	_tmp0_ = next_token;
	if (_tmp0_ != NULL) {
		GtkonToken* _tmp1_;
		const gchar* _tmp2_;
		gchar* _tmp3_;
		GtkonToken* _tmp4_;
		GtkonToken* _tmp5_;
		_tmp1_ = next_token;
		_tmp2_ = _tmp1_->str;
		_tmp3_ = g_strdup (_tmp2_);
		_g_free0 (self->str);
		self->str = _tmp3_;
		_tmp4_ = next_token;
		self->type = _tmp4_->type;
		_tmp5_ = next_token;
		self->quoted = _tmp5_->quoted;
		_gtkon_token_free0 (next_token);
		next_token = NULL;
	} else {
		gchar* _tmp6_;
		GDataInputStream* _tmp7_;
		_tmp6_ = g_strdup ("");
		_g_free0 (self->str);
		self->str = _tmp6_;
		self->quoted = (guchar) 0;
		self->bracket = 0;
		_tmp7_ = _g_object_ref0 (dis);
		_g_object_unref0 (self->dis);
		self->dis = _tmp7_;
		self->type = GTKON_TOKEN_TYPE_CLASS;
		gtkon_token_skip_spaces (self, &_inner_error0_);
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
			g_propagate_error (error, _inner_error0_);
			_gtkon_token_free0 (self);
			return NULL;
		}
		if (genie_mode) {
			const gchar* _tmp8_;
			_tmp8_ = self->str;
			g_print ("TOKEN IS (%s)\n", _tmp8_);
			if (self->type == GTKON_TOKEN_TYPE_CLASS) {
				if (checkforindent) {
					g_print ("============ SPACES ==== %d %d\n", spaces, ospaces);
					if (ospaces > spaces) {
						GtkonToken* _tmp9_;
						_tmp9_ = gtkon_token_new_copy (self);
						_gtkon_token_free0 (next_token);
						next_token = _tmp9_;
						self->type = GTKON_TOKEN_TYPE_END;
						return self;
					}
					checkforindent = FALSE;
				}
			}
			{
				while (TRUE) {
					guchar _tmp10_ = '\0';
					_tmp10_ = gtkon_token_readchar (self, &_inner_error0_);
					if (G_UNLIKELY (_inner_error0_ != NULL)) {
						goto __catch0_g_error;
					}
					if (!gtkon_token_update (self, _tmp10_)) {
						break;
					}
				}
			}
			goto __finally0;
			__catch0_g_error:
			{
				g_clear_error (&_inner_error0_);
			}
			__finally0:
			if (G_UNLIKELY (_inner_error0_ != NULL)) {
				g_propagate_error (error, _inner_error0_);
				_gtkon_token_free0 (self);
				return NULL;
			}
		} else {
			while (TRUE) {
				guchar _tmp11_ = '\0';
				_tmp11_ = gtkon_token_readchar (self, &_inner_error0_);
				if (G_UNLIKELY (_inner_error0_ != NULL)) {
					g_propagate_error (error, _inner_error0_);
					_gtkon_token_free0 (self);
					return NULL;
				}
				if (!gtkon_token_update (self, _tmp11_)) {
					break;
				}
			}
		}
	}
	return self;
}

static gchar*
gtkon_token_xmlfilteredchar (GtkonToken* self,
                             guchar ch)
{
	gchar* _tmp3_;
	gchar* result;
	g_return_val_if_fail (self != NULL, NULL);
	switch (ch) {
		case '<':
		{
			gchar* _tmp0_;
			_tmp0_ = g_strdup ("&lt;");
			result = _tmp0_;
			return result;
		}
		case '>':
		{
			gchar* _tmp1_;
			_tmp1_ = g_strdup ("&gt;");
			result = _tmp1_;
			return result;
		}
		case '&':
		{
			gchar* _tmp2_;
			_tmp2_ = g_strdup ("&amp;");
			result = _tmp2_;
			return result;
		}
		default:
		break;
	}
	_tmp3_ = g_strdup_printf ("%c", (gint) ch);
	result = _tmp3_;
	return result;
}

static gchar*
string_slice (const gchar* self,
              glong start,
              glong end)
{
	glong string_length = 0L;
	gint _tmp0_;
	gint _tmp1_;
	gboolean _tmp2_ = FALSE;
	gboolean _tmp3_ = FALSE;
	gchar* _tmp4_;
	gchar* result;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = strlen (self);
	_tmp1_ = _tmp0_;
	string_length = (glong) _tmp1_;
	if (start < ((glong) 0)) {
		start = string_length + start;
	}
	if (end < ((glong) 0)) {
		end = string_length + end;
	}
	if (start >= ((glong) 0)) {
		_tmp2_ = start <= string_length;
	} else {
		_tmp2_ = FALSE;
	}
	g_return_val_if_fail (_tmp2_, NULL);
	if (end >= ((glong) 0)) {
		_tmp3_ = end <= string_length;
	} else {
		_tmp3_ = FALSE;
	}
	g_return_val_if_fail (_tmp3_, NULL);
	g_return_val_if_fail (start <= end, NULL);
	_tmp4_ = g_strndup (((gchar*) self) + start, (gsize) (end - start));
	result = _tmp4_;
	return result;
}

static gchar
string_get (const gchar* self,
            glong index)
{
	gchar _tmp0_;
	gchar result;
	g_return_val_if_fail (self != NULL, '\0');
	_tmp0_ = ((gchar*) self)[index];
	result = _tmp0_;
	return result;
}

static gint
string_index_of (const gchar* self,
                 const gchar* needle,
                 gint start_index)
{
	gchar* _result_ = NULL;
	gchar* _tmp0_;
	gchar* _tmp1_;
	gint result;
	g_return_val_if_fail (self != NULL, 0);
	g_return_val_if_fail (needle != NULL, 0);
	_tmp0_ = strstr (((gchar*) self) + start_index, (gchar*) needle);
	_result_ = _tmp0_;
	_tmp1_ = _result_;
	if (_tmp1_ != NULL) {
		gchar* _tmp2_;
		_tmp2_ = _result_;
		result = (gint) (_tmp2_ - ((gchar*) self));
		return result;
	} else {
		result = -1;
		return result;
	}
}

gboolean
gtkon_token_update (GtkonToken* self,
                    guchar ch)
{
	const gchar* _tmp63_;
	gchar* _tmp64_;
	gchar* _tmp65_;
	gchar* _tmp66_;
	gboolean _tmp67_ = FALSE;
	const gchar* _tmp68_;
	gboolean result;
	g_return_val_if_fail (self != NULL, FALSE);
	if (((gint) self->quoted) != 0) {
		const gchar* _tmp0_;
		gchar* _tmp1_;
		gchar* _tmp2_;
		gchar* _tmp3_;
		self->type = GTKON_TOKEN_TYPE_ATTRIBUTE;
		_tmp0_ = self->str;
		_tmp1_ = gtkon_token_xmlfilteredchar (self, ch);
		_tmp2_ = _tmp1_;
		_tmp3_ = g_strconcat (_tmp0_, _tmp2_, NULL);
		_g_free0 (self->str);
		self->str = _tmp3_;
		_g_free0 (_tmp2_);
		if (self->quoted == ((guchar) '{')) {
			gboolean _tmp6_ = FALSE;
			if (ch == ((guchar) '{')) {
				gint _tmp4_;
				_tmp4_ = self->bracket;
				self->bracket = _tmp4_ + 1;
			}
			if (ch == ((guchar) '}')) {
				gint _tmp5_;
				_tmp5_ = self->bracket;
				self->bracket = _tmp5_ - 1;
			}
			if (self->bracket < 0) {
				_tmp6_ = ch == ((guchar) '}');
			} else {
				_tmp6_ = FALSE;
			}
			if (_tmp6_) {
				const gchar* _tmp7_;
				gchar* _tmp8_;
				_tmp7_ = self->str;
				_tmp8_ = g_strconcat (_tmp7_, "'", NULL);
				_g_free0 (self->str);
				self->str = _tmp8_;
				result = FALSE;
				return result;
			}
		} else {
			if (self->quoted == ((guchar) '\'')) {
				if (ch == ((guchar) '\'')) {
					result = FALSE;
					return result;
				}
			} else {
				gboolean _tmp9_ = FALSE;
				const gchar* _tmp10_;
				_tmp10_ = self->str;
				if (g_str_has_suffix (_tmp10_, "\"")) {
					const gchar* _tmp11_;
					_tmp11_ = self->str;
					_tmp9_ = !g_str_has_suffix (_tmp11_, "\\\"");
				} else {
					_tmp9_ = FALSE;
				}
				if (_tmp9_) {
					result = FALSE;
					return result;
				}
			}
		}
		result = TRUE;
		return result;
	}
	switch (self->type) {
		case GTKON_TOKEN_TYPE_COMMENT_LINE:
		{
			gboolean _tmp12_ = FALSE;
			const gchar* _tmp13_;
			gchar* _tmp14_;
			gchar* _tmp15_;
			gchar* _tmp16_;
			if (ch == ((guchar) '\n')) {
				_tmp12_ = TRUE;
			} else {
				_tmp12_ = ch == ((guchar) '\r');
			}
			if (_tmp12_) {
				result = FALSE;
				return result;
			}
			_tmp13_ = self->str;
			_tmp14_ = g_strdup_printf ("%c", (gint) ch);
			_tmp15_ = _tmp14_;
			_tmp16_ = g_strconcat (_tmp13_, _tmp15_, NULL);
			_g_free0 (self->str);
			self->str = _tmp16_;
			_g_free0 (_tmp15_);
			result = TRUE;
			return result;
		}
		case GTKON_TOKEN_TYPE_COMMENT_BLOCK:
		{
			const gchar* _tmp17_;
			gchar* _tmp18_;
			gchar* _tmp19_;
			gchar* _tmp20_;
			const gchar* _tmp21_;
			_tmp17_ = self->str;
			_tmp18_ = g_strdup_printf ("%c", (gint) ch);
			_tmp19_ = _tmp18_;
			_tmp20_ = g_strconcat (_tmp17_, _tmp19_, NULL);
			_g_free0 (self->str);
			self->str = _tmp20_;
			_g_free0 (_tmp19_);
			_tmp21_ = self->str;
			if (g_str_has_suffix (_tmp21_, "*/")) {
				const gchar* _tmp22_;
				const gchar* _tmp23_;
				gint _tmp24_;
				gint _tmp25_;
				gchar* _tmp26_;
				_tmp22_ = self->str;
				_tmp23_ = self->str;
				_tmp24_ = strlen (_tmp23_);
				_tmp25_ = _tmp24_;
				_tmp26_ = string_slice (_tmp22_, (glong) 0, (glong) (_tmp25_ - 2));
				_g_free0 (self->str);
				self->str = _tmp26_;
				result = FALSE;
				return result;
			}
			result = TRUE;
			return result;
		}
		case GTKON_TOKEN_TYPE_CODE:
		{
			const gchar* _tmp27_;
			gchar* _tmp28_;
			gchar* _tmp29_;
			gchar* _tmp30_;
			const gchar* _tmp31_;
			_tmp27_ = self->str;
			_tmp28_ = g_strdup_printf ("%c", (gint) ch);
			_tmp29_ = _tmp28_;
			_tmp30_ = g_strconcat (_tmp27_, _tmp29_, NULL);
			_g_free0 (self->str);
			self->str = _tmp30_;
			_g_free0 (_tmp29_);
			_tmp31_ = self->str;
			if (g_str_has_suffix (_tmp31_, "}-")) {
				const gchar* _tmp32_;
				const gchar* _tmp33_;
				gint _tmp34_;
				gint _tmp35_;
				gchar* _tmp36_;
				_tmp32_ = self->str;
				_tmp33_ = self->str;
				_tmp34_ = strlen (_tmp33_);
				_tmp35_ = _tmp34_;
				_tmp36_ = string_slice (_tmp32_, (glong) 0, (glong) (_tmp35_ - 2));
				_g_free0 (self->str);
				self->str = _tmp36_;
				result = FALSE;
				return result;
			}
			result = TRUE;
			return result;
		}
		default:
		{
			break;
		}
	}
	if (gtkon_token_is_separator (self, ch)) {
		gboolean _tmp45_ = FALSE;
		if (genie_mode) {
			const gchar* _tmp37_;
			gboolean _tmp38_ = FALSE;
			gboolean _tmp39_ = FALSE;
			_tmp37_ = self->str;
			g_print ("type=NEW %s %d \n", _tmp37_, (gint) self->type);
			if (!nextiscode) {
				const gchar* _tmp40_;
				_tmp40_ = self->str;
				_tmp39_ = string_get (_tmp40_, (glong) 0) > 'A';
			} else {
				_tmp39_ = FALSE;
			}
			if (_tmp39_) {
				_tmp38_ = self->type == GTKON_TOKEN_TYPE_CLASS;
			} else {
				_tmp38_ = FALSE;
			}
			if (_tmp38_) {
				const gchar* _tmp41_;
				GtkonToken* _tmp42_;
				gchar* _tmp44_;
				checkforindent = TRUE;
				mustclose = TRUE;
				_tmp41_ = self->str;
				g_print ("NEWKEYWORLD (%s) (%d %d)\n", _tmp41_, ospaces, spaces);
				_tmp42_ = gtkon_token_new_copy (self);
				_gtkon_token_free0 (next_token);
				next_token = _tmp42_;
				if (ospaces >= spaces) {
					const gchar* _tmp43_;
					self->type = GTKON_TOKEN_TYPE_END;
					_tmp43_ = self->str;
					g_print ("NEW -- END ((%s))\n", _tmp43_);
				} else {
					self->type = GTKON_TOKEN_TYPE_BEGIN;
				}
				_tmp44_ = g_strdup ("");
				_g_free0 (self->str);
				self->str = _tmp44_;
				result = FALSE;
				return result;
			}
		}
		if (self->type == GTKON_TOKEN_TYPE_ATTRIBUTE) {
			const gchar* _tmp46_;
			gchar* _tmp47_;
			gchar* _tmp48_;
			_tmp46_ = self->str;
			_tmp47_ = g_strdup_printf ("=%c", (gint) ch);
			_tmp48_ = _tmp47_;
			_tmp45_ = string_index_of (_tmp46_, _tmp48_, 0) != -1;
			_g_free0 (_tmp48_);
		} else {
			_tmp45_ = FALSE;
		}
		if (_tmp45_) {
			gboolean _tmp49_ = FALSE;
			const gchar* _tmp50_;
			gchar* _tmp51_;
			gchar* _tmp52_;
			gboolean _tmp53_;
			_tmp50_ = self->str;
			_tmp51_ = g_strdup_printf ("%c", (gint) ch);
			_tmp52_ = _tmp51_;
			_tmp53_ = g_str_has_suffix (_tmp50_, _tmp52_);
			_g_free0 (_tmp52_);
			if (_tmp53_) {
				const gchar* _tmp54_;
				_tmp54_ = self->str;
				_tmp49_ = !g_str_has_suffix (_tmp54_, "\\\"");
			} else {
				_tmp49_ = FALSE;
			}
			if (_tmp49_) {
				result = FALSE;
				return result;
			}
		} else {
			result = FALSE;
			return result;
		}
	}
	switch (ch) {
		case '"':
		case '\'':
		{
			self->quoted = ch;
			break;
		}
		case '$':
		{
			self->type = GTKON_TOKEN_TYPE_ATTRIBUTE;
			break;
		}
		case ':':
		{
			const gchar* _tmp55_;
			_tmp55_ = self->str;
			if (string_index_of (_tmp55_, "=", 0) == -1) {
				self->type = GTKON_TOKEN_TYPE_CLASS;
			}
			if (last_type == GTKON_TOKEN_TYPE_CLASS) {
				self->type = GTKON_TOKEN_TYPE_ATTRIBUTE;
			}
			break;
		}
		case '=':
		{
			self->type = GTKON_TOKEN_TYPE_ATTRIBUTE;
			break;
		}
		case '{':
		{
			const gchar* _tmp56_;
			const gchar* _tmp59_;
			const gchar* _tmp61_;
			_tmp56_ = self->str;
			if (g_str_has_suffix (_tmp56_, "=")) {
				const gchar* _tmp57_;
				gchar* _tmp58_;
				_tmp57_ = self->str;
				_tmp58_ = g_strconcat (_tmp57_, "'{", NULL);
				_g_free0 (self->str);
				self->str = _tmp58_;
				self->quoted = ch;
				result = TRUE;
				return result;
			}
			_tmp59_ = self->str;
			if (g_strcmp0 (_tmp59_, "-") == 0) {
				gchar* _tmp60_;
				self->type = GTKON_TOKEN_TYPE_CODE;
				_tmp60_ = g_strdup ("");
				_g_free0 (self->str);
				self->str = _tmp60_;
				result = TRUE;
				return result;
			}
			_tmp61_ = self->str;
			if (g_strcmp0 (_tmp61_, "") == 0) {
				mustclose = TRUE;
				self->type = GTKON_TOKEN_TYPE_BEGIN;
				result = FALSE;
				return result;
			}
			nextchar = '{';
			result = FALSE;
			return result;
		}
		case ';':
		{
			const gchar* _tmp62_;
			_tmp62_ = self->str;
			if (g_strcmp0 (_tmp62_, "") == 0) {
				self->type = GTKON_TOKEN_TYPE_END;
				mustclose = TRUE;
				result = FALSE;
				return result;
			}
			nextchar = ';';
			result = FALSE;
			return result;
		}
		case '}':
		{
			self->type = GTKON_TOKEN_TYPE_END;
			result = FALSE;
			return result;
		}
		default:
		break;
	}
	_tmp63_ = self->str;
	_tmp64_ = g_strdup_printf ("%c", (gint) ch);
	_tmp65_ = _tmp64_;
	_tmp66_ = g_strconcat (_tmp63_, _tmp65_, NULL);
	_g_free0 (self->str);
	self->str = _tmp66_;
	_g_free0 (_tmp65_);
	_tmp68_ = self->str;
	if (g_strcmp0 (_tmp68_, "//") == 0) {
		_tmp67_ = TRUE;
	} else {
		const gchar* _tmp69_;
		_tmp69_ = self->str;
		_tmp67_ = g_strcmp0 (_tmp69_, "#") == 0;
	}
	if (_tmp67_) {
		gchar* _tmp70_;
		self->type = GTKON_TOKEN_TYPE_COMMENT_LINE;
		_tmp70_ = g_strdup ("");
		_g_free0 (self->str);
		self->str = _tmp70_;
	} else {
		const gchar* _tmp71_;
		_tmp71_ = self->str;
		if (g_strcmp0 (_tmp71_, "/*") == 0) {
			gchar* _tmp72_;
			self->type = GTKON_TOKEN_TYPE_COMMENT_BLOCK;
			_tmp72_ = g_strdup ("");
			_g_free0 (self->str);
			self->str = _tmp72_;
		}
	}
	result = TRUE;
	return result;
}

static gchar*
string_replace (const gchar* self,
                const gchar* old,
                const gchar* replacement)
{
	gboolean _tmp0_ = FALSE;
	gboolean _tmp1_ = FALSE;
	GError* _inner_error0_ = NULL;
	gchar* result;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (old != NULL, NULL);
	g_return_val_if_fail (replacement != NULL, NULL);
	if ((*((gchar*) self)) == '\0') {
		_tmp1_ = TRUE;
	} else {
		_tmp1_ = (*((gchar*) old)) == '\0';
	}
	if (_tmp1_) {
		_tmp0_ = TRUE;
	} else {
		_tmp0_ = g_strcmp0 (old, replacement) == 0;
	}
	if (_tmp0_) {
		gchar* _tmp2_;
		_tmp2_ = g_strdup (self);
		result = _tmp2_;
		return result;
	}
	{
		GRegex* regex = NULL;
		gchar* _tmp3_;
		gchar* _tmp4_;
		GRegex* _tmp5_;
		GRegex* _tmp6_;
		gchar* _tmp7_ = NULL;
		GRegex* _tmp8_;
		gchar* _tmp9_;
		gchar* _tmp10_;
		_tmp3_ = g_regex_escape_string (old, -1);
		_tmp4_ = _tmp3_;
		_tmp5_ = g_regex_new (_tmp4_, 0, 0, &_inner_error0_);
		_tmp6_ = _tmp5_;
		_g_free0 (_tmp4_);
		regex = _tmp6_;
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
			if (_inner_error0_->domain == G_REGEX_ERROR) {
				goto __catch0_g_regex_error;
			}
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
			g_clear_error (&_inner_error0_);
			return NULL;
		}
		_tmp8_ = regex;
		_tmp9_ = g_regex_replace_literal (_tmp8_, self, (gssize) -1, 0, replacement, 0, &_inner_error0_);
		_tmp7_ = _tmp9_;
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
			_g_regex_unref0 (regex);
			if (_inner_error0_->domain == G_REGEX_ERROR) {
				goto __catch0_g_regex_error;
			}
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
			g_clear_error (&_inner_error0_);
			return NULL;
		}
		_tmp10_ = _tmp7_;
		_tmp7_ = NULL;
		result = _tmp10_;
		_g_free0 (_tmp7_);
		_g_regex_unref0 (regex);
		return result;
	}
	goto __finally0;
	__catch0_g_regex_error:
	{
		g_clear_error (&_inner_error0_);
		g_assert_not_reached ();
	}
	__finally0:
	g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
	g_clear_error (&_inner_error0_);
	return NULL;
}

gchar*
gtkon_token_to_xml (GtkonToken* self)
{
	gchar* eos = NULL;
	gchar* _tmp0_;
	gchar* bos = NULL;
	gchar* _tmp1_;
	gint max = 0;
	const gchar* _tmp270_;
	gchar* _tmp271_;
	gchar* result;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = g_strdup ("");
	eos = _tmp0_;
	_tmp1_ = g_strdup ("");
	bos = _tmp1_;
	if (self->type == GTKON_TOKEN_TYPE_CLASS) {
		gboolean _tmp2_ = FALSE;
		if (last_type == GTKON_TOKEN_TYPE_CLASS) {
			_tmp2_ = TRUE;
		} else {
			_tmp2_ = last_type == GTKON_TOKEN_TYPE_ATTRIBUTE;
		}
		if (_tmp2_) {
			self->type = GTKON_TOKEN_TYPE_ATTRIBUTE;
		}
	}
	if (mustclose) {
		gchar* _tmp3_;
		_tmp3_ = g_strdup (">");
		_g_free0 (eos);
		eos = _tmp3_;
		mustclose = FALSE;
	}
	max = tok_idx;
	if (self->type == GTKON_TOKEN_TYPE_END) {
		gint _tmp4_;
		_tmp4_ = max;
		max = _tmp4_ - 1;
	}
	{
		gint i = 0;
		i = 0;
		{
			gboolean _tmp5_ = FALSE;
			_tmp5_ = TRUE;
			while (TRUE) {
				const gchar* _tmp7_;
				gchar* _tmp8_;
				if (!_tmp5_) {
					gint _tmp6_;
					_tmp6_ = i;
					i = _tmp6_ + 1;
				}
				_tmp5_ = FALSE;
				if (!(i < max)) {
					break;
				}
				_tmp7_ = bos;
				_tmp8_ = g_strconcat (_tmp7_, "  ", NULL);
				_g_free0 (bos);
				bos = _tmp8_;
			}
		}
	}
	switch (self->type) {
		case GTKON_TOKEN_TYPE_CLASS:
		{
			const gchar* _tmp9_;
			gchar* _tmp10_;
			const gchar* _tmp11_;
			const gchar* _tmp15_;
			const gchar* _tmp16_;
			gchar* _tmp17_;
			gchar* _tmp18_;
			const gchar* _tmp19_;
			gchar* _tmp20_;
			gchar* _tmp21_;
			_tmp9_ = self->str;
			_tmp10_ = string_replace (_tmp9_, ".", ":");
			_g_free0 (self->str);
			self->str = _tmp10_;
			_tmp11_ = self->str;
			if (g_strcmp0 (_tmp11_, "") != 0) {
				const gchar* _tmp12_;
				const gchar* _tmp13_;
				gchar* _tmp14_;
				_tmp12_ = self->str;
				pushtoken (_tmp12_);
				_tmp13_ = bos;
				_tmp14_ = g_strconcat (_tmp13_, "<", NULL);
				_g_free0 (bos);
				bos = _tmp14_;
			}
			_tmp15_ = bos;
			_tmp16_ = self->str;
			_tmp17_ = g_strconcat (_tmp15_, _tmp16_, NULL);
			_tmp18_ = _tmp17_;
			_tmp19_ = eos;
			_tmp20_ = g_strconcat (_tmp18_, _tmp19_, NULL);
			_tmp21_ = _tmp20_;
			_g_free0 (_tmp18_);
			result = _tmp21_;
			_g_free0 (bos);
			_g_free0 (eos);
			return result;
		}
		case GTKON_TOKEN_TYPE_COMMENT_BLOCK:
		case GTKON_TOKEN_TYPE_COMMENT_LINE:
		{
			result = eos;
			_g_free0 (bos);
			return result;
		}
		case GTKON_TOKEN_TYPE_BEGIN:
		{
			gboolean _tmp22_ = FALSE;
			gchar* _tmp24_;
			if (first_class) {
				_tmp22_ = !has_version;
			} else {
				_tmp22_ = FALSE;
			}
			if (_tmp22_) {
				gchar* _tmp23_;
				first_class = FALSE;
				_tmp23_ = g_strdup (" xmlns:gtkaml=\"http://gtkaml.org/" PACKAGE_VERSION "\">\n");
				result = _tmp23_;
				_g_free0 (bos);
				_g_free0 (eos);
				return result;
			}
			_tmp24_ = g_strdup (">\n");
			result = _tmp24_;
			_g_free0 (bos);
			_g_free0 (eos);
			return result;
		}
		case GTKON_TOKEN_TYPE_END:
		{
			gchar* _tmp37_;
			if (tok_idx > 0) {
				const gchar* _tmp25_;
				const gchar* _tmp26_;
				gchar* _tmp27_;
				gchar* _tmp28_;
				gchar* _tmp29_;
				gchar* _tmp30_;
				gchar* _tmp31_;
				gchar* _tmp32_;
				gchar* _tmp33_;
				gchar* _tmp34_;
				gchar* _tmp35_;
				gchar* _tmp36_;
				_tmp25_ = eos;
				_tmp26_ = bos;
				_tmp27_ = g_strconcat (_tmp25_, _tmp26_, NULL);
				_tmp28_ = _tmp27_;
				_tmp29_ = g_strconcat (_tmp28_, "</", NULL);
				_tmp30_ = _tmp29_;
				_tmp31_ = poptoken ();
				_tmp32_ = _tmp31_;
				_tmp33_ = g_strconcat (_tmp30_, _tmp32_, NULL);
				_tmp34_ = _tmp33_;
				_tmp35_ = g_strconcat (_tmp34_, ">\n", NULL);
				_tmp36_ = _tmp35_;
				_g_free0 (_tmp34_);
				_g_free0 (_tmp32_);
				_g_free0 (_tmp30_);
				_g_free0 (_tmp28_);
				result = _tmp36_;
				_g_free0 (bos);
				_g_free0 (eos);
				return result;
			}
			_tmp37_ = g_strdup ("");
			result = _tmp37_;
			_g_free0 (bos);
			_g_free0 (eos);
			return result;
		}
		case GTKON_TOKEN_TYPE_ATTRIBUTE:
		{
			const gchar* _tmp38_;
			const gchar* _tmp47_;
			const gchar* _tmp70_;
			gchar** foo = NULL;
			const gchar* _tmp81_;
			gchar** _tmp82_;
			gchar** _tmp83_;
			gint foo_length1;
			gint _foo_size_;
			gchar** _tmp84_;
			gint _tmp84__length1;
			const gchar* _tmp85_;
			gchar* val = NULL;
			gchar** _tmp188_;
			gint _tmp188__length1;
			const gchar* _tmp189_;
			gchar* _tmp190_;
			const gchar* _tmp191_;
			gchar** _tmp215_;
			gint _tmp215__length1;
			const gchar* _tmp216_;
			gchar* _tmp217_;
			gchar* _tmp218_;
			gchar* _tmp219_;
			gchar* _tmp220_;
			const gchar* _tmp221_;
			gchar* _tmp222_;
			gchar* _tmp223_;
			gchar* _tmp224_;
			gchar* _tmp225_;
			const gchar* _tmp226_;
			gchar* _tmp227_;
			gchar* _tmp228_;
			_tmp38_ = self->str;
			if (string_get (_tmp38_, (glong) 0) == '&') {
				const gchar* _tmp39_;
				const gchar* _tmp40_;
				gint _tmp41_;
				gint _tmp42_;
				gchar* _tmp43_;
				gchar* _tmp44_;
				gchar* _tmp45_;
				gchar* _tmp46_;
				_tmp39_ = self->str;
				_tmp40_ = self->str;
				_tmp41_ = strlen (_tmp40_);
				_tmp42_ = _tmp41_;
				_tmp43_ = string_slice (_tmp39_, (glong) 1, (glong) _tmp42_);
				_tmp44_ = _tmp43_;
				_tmp45_ = g_strdup_printf (" gtkaml:existing=\"%s\"", _tmp44_);
				_tmp46_ = _tmp45_;
				_g_free0 (_tmp44_);
				result = _tmp46_;
				_g_free0 (bos);
				_g_free0 (eos);
				return result;
			}
			_tmp47_ = self->str;
			if (string_get (_tmp47_, (glong) 0) == '$') {
				const gchar* _tmp53_;
				const gchar* _tmp62_;
				const gchar* _tmp63_;
				gint _tmp64_;
				gint _tmp65_;
				gchar* _tmp66_;
				gchar* _tmp67_;
				gchar* _tmp68_;
				gchar* _tmp69_;
				if (tok_idx == 1) {
					const gchar* _tmp48_;
					const gchar* _tmp49_;
					gint _tmp50_;
					gint _tmp51_;
					gchar* _tmp52_;
					_tmp48_ = self->str;
					_tmp49_ = self->str;
					_tmp50_ = strlen (_tmp49_);
					_tmp51_ = _tmp50_;
					_tmp52_ = string_slice (_tmp48_, (glong) 1, (glong) _tmp51_);
					_g_free0 (rootclass);
					rootclass = _tmp52_;
				}
				_tmp53_ = self->str;
				if (string_get (_tmp53_, (glong) 1) == '.') {
					const gchar* _tmp54_;
					const gchar* _tmp55_;
					gint _tmp56_;
					gint _tmp57_;
					gchar* _tmp58_;
					gchar* _tmp59_;
					gchar* _tmp60_;
					gchar* _tmp61_;
					_tmp54_ = self->str;
					_tmp55_ = self->str;
					_tmp56_ = strlen (_tmp55_);
					_tmp57_ = _tmp56_;
					_tmp58_ = string_slice (_tmp54_, (glong) 2, (glong) _tmp57_);
					_tmp59_ = _tmp58_;
					_tmp60_ = g_strdup_printf (" gtkaml:private=\"%s\"", _tmp59_);
					_tmp61_ = _tmp60_;
					_g_free0 (_tmp59_);
					result = _tmp61_;
					_g_free0 (bos);
					_g_free0 (eos);
					return result;
				}
				_tmp62_ = self->str;
				_tmp63_ = self->str;
				_tmp64_ = strlen (_tmp63_);
				_tmp65_ = _tmp64_;
				_tmp66_ = string_slice (_tmp62_, (glong) 1, (glong) _tmp65_);
				_tmp67_ = _tmp66_;
				_tmp68_ = g_strdup_printf (" gtkaml:public=\"%s\"", _tmp67_);
				_tmp69_ = _tmp68_;
				_g_free0 (_tmp67_);
				result = _tmp69_;
				_g_free0 (bos);
				_g_free0 (eos);
				return result;
			}
			_tmp70_ = self->str;
			if (string_index_of (_tmp70_, "=", 0) == -1) {
				const gchar* _tmp71_;
				_tmp71_ = self->str;
				if (string_get (_tmp71_, (glong) 0) == '!') {
					const gchar* _tmp72_;
					const gchar* _tmp73_;
					gint _tmp74_;
					gint _tmp75_;
					gchar* _tmp76_;
					gchar* _tmp77_;
					gchar* _tmp78_;
					_tmp72_ = self->str;
					_tmp73_ = self->str;
					_tmp74_ = strlen (_tmp73_);
					_tmp75_ = _tmp74_;
					_tmp76_ = string_slice (_tmp72_, (glong) 1, (glong) _tmp75_);
					_tmp77_ = _tmp76_;
					_tmp78_ = g_strconcat (_tmp77_, "=false", NULL);
					_g_free0 (self->str);
					self->str = _tmp78_;
					_g_free0 (_tmp77_);
				} else {
					const gchar* _tmp79_;
					gchar* _tmp80_;
					_tmp79_ = self->str;
					_tmp80_ = g_strconcat (_tmp79_, "=true", NULL);
					_g_free0 (self->str);
					self->str = _tmp80_;
				}
			}
			_tmp81_ = self->str;
			_tmp83_ = _tmp82_ = g_strsplit (_tmp81_, "=", 2);
			foo = _tmp83_;
			foo_length1 = _vala_array_length (_tmp82_);
			_foo_size_ = foo_length1;
			_tmp84_ = foo;
			_tmp84__length1 = foo_length1;
			_tmp85_ = _tmp84_[0];
			if (string_get (_tmp85_, (glong) 0) != '@') {
				gchar* arg = NULL;
				gchar** _tmp86_;
				gint _tmp86__length1;
				const gchar* _tmp87_;
				gchar* _tmp88_;
				gchar* _tmp89_;
				gchar* _tmp90_;
				gchar* _tmp91_;
				gchar** _tmp92_;
				gint _tmp92__length1;
				gchar** _tmp94_;
				gint _tmp94__length1;
				const gchar* _tmp95_;
				gchar** _tmp101_;
				gint _tmp101__length1;
				const gchar* _tmp102_;
				gchar** _tmp108_;
				gint _tmp108__length1;
				const gchar* _tmp109_;
				gchar** _tmp115_;
				gint _tmp115__length1;
				const gchar* _tmp116_;
				gchar** _tmp122_;
				gint _tmp122__length1;
				const gchar* _tmp123_;
				gchar** _tmp129_;
				gint _tmp129__length1;
				const gchar* _tmp130_;
				gchar** _tmp161_;
				gint _tmp161__length1;
				const gchar* _tmp162_;
				_tmp86_ = foo;
				_tmp86__length1 = foo_length1;
				_tmp87_ = _tmp86_[1];
				_tmp88_ = string_replace (_tmp87_, "\"", "");
				_tmp89_ = _tmp88_;
				_tmp90_ = string_replace (_tmp89_, "'", "");
				_tmp91_ = _tmp90_;
				_g_free0 (_tmp89_);
				arg = _tmp91_;
				_tmp92_ = foo;
				_tmp92__length1 = foo_length1;
				if (_tmp92__length1 != 2) {
					const gchar* _tmp93_;
					_tmp93_ = self->str;
					g_error ("gtkonparser.vala:370: Missing value in attribute '%s'", _tmp93_);
				}
				_tmp94_ = foo;
				_tmp94__length1 = foo_length1;
				_tmp95_ = _tmp94_[0];
				if (g_strcmp0 (_tmp95_, "gtkon:version") == 0) {
					const gchar* _tmp96_;
					gchar* _tmp97_;
					gchar* _tmp98_;
					gchar* _tmp99_;
					gchar* _tmp100_;
					has_version = TRUE;
					_tmp96_ = arg;
					_tmp97_ = g_strconcat (" xmlns:gtkaml=\"http://gtkaml.org/", _tmp96_, NULL);
					_tmp98_ = _tmp97_;
					_tmp99_ = g_strconcat (_tmp98_, "\"", NULL);
					_tmp100_ = _tmp99_;
					_g_free0 (_tmp98_);
					result = _tmp100_;
					_g_free0 (arg);
					foo = (_vala_array_free (foo, foo_length1, (GDestroyNotify) g_free), NULL);
					_g_free0 (bos);
					_g_free0 (eos);
					return result;
				}
				_tmp101_ = foo;
				_tmp101__length1 = foo_length1;
				_tmp102_ = _tmp101_[0];
				if (g_strcmp0 (_tmp102_, "standalone") == 0) {
					const gchar* _tmp103_;
					gchar* _tmp104_;
					gchar* _tmp105_;
					gchar* _tmp106_;
					gchar* _tmp107_;
					_tmp103_ = arg;
					_tmp104_ = g_strconcat (" gtkaml:standalone=\"", _tmp103_, NULL);
					_tmp105_ = _tmp104_;
					_tmp106_ = g_strconcat (_tmp105_, "\"", NULL);
					_tmp107_ = _tmp106_;
					_g_free0 (_tmp105_);
					result = _tmp107_;
					_g_free0 (arg);
					foo = (_vala_array_free (foo, foo_length1, (GDestroyNotify) g_free), NULL);
					_g_free0 (bos);
					_g_free0 (eos);
					return result;
				}
				_tmp108_ = foo;
				_tmp108__length1 = foo_length1;
				_tmp109_ = _tmp108_[0];
				if (g_strcmp0 (_tmp109_, "construct") == 0) {
					const gchar* _tmp110_;
					gchar* _tmp111_;
					gchar* _tmp112_;
					gchar* _tmp113_;
					gchar* _tmp114_;
					_tmp110_ = arg;
					_tmp111_ = g_strconcat (" gtkaml:construct=\"", _tmp110_, NULL);
					_tmp112_ = _tmp111_;
					_tmp113_ = g_strconcat (_tmp112_, "\"", NULL);
					_tmp114_ = _tmp113_;
					_g_free0 (_tmp112_);
					result = _tmp114_;
					_g_free0 (arg);
					foo = (_vala_array_free (foo, foo_length1, (GDestroyNotify) g_free), NULL);
					_g_free0 (bos);
					_g_free0 (eos);
					return result;
				}
				_tmp115_ = foo;
				_tmp115__length1 = foo_length1;
				_tmp116_ = _tmp115_[0];
				if (g_strcmp0 (_tmp116_, "property") == 0) {
					const gchar* _tmp117_;
					gchar* _tmp118_;
					gchar* _tmp119_;
					gchar* _tmp120_;
					gchar* _tmp121_;
					_tmp117_ = arg;
					_tmp118_ = g_strconcat (" gtkaml:property=\"", _tmp117_, NULL);
					_tmp119_ = _tmp118_;
					_tmp120_ = g_strconcat (_tmp119_, "\"", NULL);
					_tmp121_ = _tmp120_;
					_g_free0 (_tmp119_);
					result = _tmp121_;
					_g_free0 (arg);
					foo = (_vala_array_free (foo, foo_length1, (GDestroyNotify) g_free), NULL);
					_g_free0 (bos);
					_g_free0 (eos);
					return result;
				}
				_tmp122_ = foo;
				_tmp122__length1 = foo_length1;
				_tmp123_ = _tmp122_[0];
				if (g_strcmp0 (_tmp123_, "name") == 0) {
					const gchar* _tmp124_;
					gchar* _tmp125_;
					gchar* _tmp126_;
					gchar* _tmp127_;
					gchar* _tmp128_;
					g_warning ("gtkonparser.vala:382: name= attribute is deprecated. use '$' prefix");
					_tmp124_ = arg;
					_tmp125_ = g_strconcat (" gtkaml:name=\"", _tmp124_, NULL);
					_tmp126_ = _tmp125_;
					_tmp127_ = g_strconcat (_tmp126_, "\"", NULL);
					_tmp128_ = _tmp127_;
					_g_free0 (_tmp126_);
					result = _tmp128_;
					_g_free0 (arg);
					foo = (_vala_array_free (foo, foo_length1, (GDestroyNotify) g_free), NULL);
					_g_free0 (bos);
					_g_free0 (eos);
					return result;
				}
				_tmp129_ = foo;
				_tmp129__length1 = foo_length1;
				_tmp130_ = _tmp129_[0];
				if (g_strcmp0 (_tmp130_, "using") == 0) {
					gchar** ns = NULL;
					const gchar* _tmp131_;
					gchar** _tmp132_;
					gchar** _tmp133_;
					gint ns_length1;
					gint _ns_size_;
					gchar* s = NULL;
					gchar* _tmp134_;
					_tmp131_ = arg;
					_tmp133_ = _tmp132_ = g_strsplit (_tmp131_, ":", 0);
					ns = _tmp133_;
					ns_length1 = _vala_array_length (_tmp132_);
					_ns_size_ = ns_length1;
					_tmp134_ = g_strdup ("");
					s = _tmp134_;
					{
						gint i = 0;
						i = 0;
						{
							gboolean _tmp135_ = FALSE;
							_tmp135_ = TRUE;
							while (TRUE) {
								gchar** _tmp137_;
								gint _tmp137__length1;
								gint _tmp160_;
								if (!_tmp135_) {
									gint _tmp136_;
									_tmp136_ = i;
									i = _tmp136_ + 1;
								}
								_tmp135_ = FALSE;
								_tmp137_ = ns;
								_tmp137__length1 = ns_length1;
								if (!(i < _tmp137__length1)) {
									break;
								}
								if (usingcount == 0) {
									const gchar* _tmp138_;
									gchar** _tmp139_;
									gint _tmp139__length1;
									const gchar* _tmp140_;
									gchar* _tmp141_;
									gchar* _tmp142_;
									gchar* _tmp143_;
									gchar* _tmp144_;
									gchar* _tmp145_;
									_tmp138_ = s;
									_tmp139_ = ns;
									_tmp139__length1 = ns_length1;
									_tmp140_ = _tmp139_[i];
									_tmp141_ = g_strconcat (" xmlns=\"", _tmp140_, NULL);
									_tmp142_ = _tmp141_;
									_tmp143_ = g_strconcat (_tmp142_, "\"", NULL);
									_tmp144_ = _tmp143_;
									_tmp145_ = g_strconcat (_tmp138_, _tmp144_, NULL);
									_g_free0 (s);
									s = _tmp145_;
									_g_free0 (_tmp144_);
									_g_free0 (_tmp142_);
								} else {
									const gchar* _tmp146_;
									gchar** _tmp147_;
									gint _tmp147__length1;
									const gchar* _tmp148_;
									gchar* _tmp149_;
									gchar* _tmp150_;
									gchar* _tmp151_;
									gchar* _tmp152_;
									gchar** _tmp153_;
									gint _tmp153__length1;
									const gchar* _tmp154_;
									gchar* _tmp155_;
									gchar* _tmp156_;
									gchar* _tmp157_;
									gchar* _tmp158_;
									gchar* _tmp159_;
									_tmp146_ = s;
									_tmp147_ = ns;
									_tmp147__length1 = ns_length1;
									_tmp148_ = _tmp147_[i];
									_tmp149_ = g_strconcat (" xmlns:", _tmp148_, NULL);
									_tmp150_ = _tmp149_;
									_tmp151_ = g_strconcat (_tmp150_, "=\"", NULL);
									_tmp152_ = _tmp151_;
									_tmp153_ = ns;
									_tmp153__length1 = ns_length1;
									_tmp154_ = _tmp153_[i];
									_tmp155_ = g_strconcat (_tmp152_, _tmp154_, NULL);
									_tmp156_ = _tmp155_;
									_tmp157_ = g_strconcat (_tmp156_, "\"", NULL);
									_tmp158_ = _tmp157_;
									_tmp159_ = g_strconcat (_tmp146_, _tmp158_, NULL);
									_g_free0 (s);
									s = _tmp159_;
									_g_free0 (_tmp158_);
									_g_free0 (_tmp156_);
									_g_free0 (_tmp152_);
									_g_free0 (_tmp150_);
								}
								_tmp160_ = usingcount;
								usingcount = _tmp160_ + 1;
							}
						}
					}
					result = s;
					ns = (_vala_array_free (ns, ns_length1, (GDestroyNotify) g_free), NULL);
					_g_free0 (arg);
					foo = (_vala_array_free (foo, foo_length1, (GDestroyNotify) g_free), NULL);
					_g_free0 (bos);
					_g_free0 (eos);
					return result;
				}
				_tmp161_ = foo;
				_tmp161__length1 = foo_length1;
				_tmp162_ = _tmp161_[0];
				if (g_str_has_prefix (_tmp162_, "using:")) {
					gchar** _tmp163_;
					gint _tmp163__length1;
					const gchar* _tmp164_;
					gchar** _tmp165_;
					gint _tmp165__length1;
					const gchar* _tmp166_;
					gint _tmp167_;
					gint _tmp168_;
					gchar* _tmp169_;
					gchar* _tmp170_;
					gchar* _tmp171_;
					gchar* _tmp172_;
					gchar* _tmp173_;
					gchar* _tmp174_;
					const gchar* _tmp175_;
					gchar* _tmp176_;
					gchar* _tmp177_;
					gchar* _tmp178_;
					gchar* _tmp179_;
					_tmp163_ = foo;
					_tmp163__length1 = foo_length1;
					_tmp164_ = _tmp163_[0];
					_tmp165_ = foo;
					_tmp165__length1 = foo_length1;
					_tmp166_ = _tmp165_[0];
					_tmp167_ = strlen (_tmp166_);
					_tmp168_ = _tmp167_;
					_tmp169_ = string_slice (_tmp164_, (glong) 6, (glong) _tmp168_);
					_tmp170_ = _tmp169_;
					_tmp171_ = g_strconcat (" xmlns:", _tmp170_, NULL);
					_tmp172_ = _tmp171_;
					_tmp173_ = g_strconcat (_tmp172_, "=\"", NULL);
					_tmp174_ = _tmp173_;
					_tmp175_ = arg;
					_tmp176_ = g_strconcat (_tmp174_, _tmp175_, NULL);
					_tmp177_ = _tmp176_;
					_tmp178_ = g_strconcat (_tmp177_, "\"", NULL);
					_tmp179_ = _tmp178_;
					_g_free0 (_tmp177_);
					_g_free0 (_tmp174_);
					_g_free0 (_tmp172_);
					_g_free0 (_tmp170_);
					result = _tmp179_;
					_g_free0 (arg);
					foo = (_vala_array_free (foo, foo_length1, (GDestroyNotify) g_free), NULL);
					_g_free0 (bos);
					_g_free0 (eos);
					return result;
				}
				_g_free0 (arg);
			} else {
				gchar** _tmp180_;
				gint _tmp180__length1;
				gchar** _tmp181_;
				gint _tmp181__length1;
				const gchar* _tmp182_;
				gchar** _tmp183_;
				gint _tmp183__length1;
				const gchar* _tmp184_;
				gint _tmp185_;
				gint _tmp186_;
				gchar* _tmp187_;
				_tmp180_ = foo;
				_tmp180__length1 = foo_length1;
				_tmp181_ = foo;
				_tmp181__length1 = foo_length1;
				_tmp182_ = _tmp181_[0];
				_tmp183_ = foo;
				_tmp183__length1 = foo_length1;
				_tmp184_ = _tmp183_[0];
				_tmp185_ = strlen (_tmp184_);
				_tmp186_ = _tmp185_;
				_tmp187_ = string_slice (_tmp182_, (glong) 1, (glong) _tmp186_);
				_g_free0 (_tmp180_[0]);
				_tmp180_[0] = _tmp187_;
			}
			_tmp188_ = foo;
			_tmp188__length1 = foo_length1;
			_tmp189_ = _tmp188_[1];
			_tmp190_ = g_strdup (_tmp189_);
			val = _tmp190_;
			_tmp191_ = val;
			if (string_get (_tmp191_, (glong) 0) == '\'') {
				const gchar* _tmp192_;
				const gchar* _tmp193_;
				gint _tmp194_;
				gint _tmp195_;
				const gchar* _tmp197_;
				const gchar* _tmp198_;
				gint _tmp199_;
				gint _tmp200_;
				gchar* _tmp201_;
				_tmp192_ = val;
				_tmp193_ = val;
				_tmp194_ = strlen (_tmp193_);
				_tmp195_ = _tmp194_;
				if (string_get (_tmp192_, (glong) (_tmp195_ - 1)) != '\'') {
					const gchar* _tmp196_;
					_tmp196_ = self->str;
					g_error ("gtkonparser.vala:402: Missing '\'' in attribute '%s'", _tmp196_);
				}
				_tmp197_ = val;
				_tmp198_ = val;
				_tmp199_ = strlen (_tmp198_);
				_tmp200_ = _tmp199_;
				_tmp201_ = string_slice (_tmp197_, (glong) 1, (glong) (_tmp200_ - 1));
				_g_free0 (val);
				val = _tmp201_;
			} else {
				const gchar* _tmp202_;
				_tmp202_ = val;
				if (string_get (_tmp202_, (glong) 0) == '"') {
					const gchar* _tmp203_;
					const gchar* _tmp204_;
					gint _tmp205_;
					gint _tmp206_;
					const gchar* _tmp208_;
					const gchar* _tmp209_;
					gint _tmp210_;
					gint _tmp211_;
					gchar* _tmp212_;
					gchar* _tmp213_;
					gchar* _tmp214_;
					_tmp203_ = val;
					_tmp204_ = val;
					_tmp205_ = strlen (_tmp204_);
					_tmp206_ = _tmp205_;
					if (string_get (_tmp203_, (glong) (_tmp206_ - 1)) != '"') {
						const gchar* _tmp207_;
						_tmp207_ = self->str;
						g_error ("gtkonparser.vala:407: Missing '\"' in attribute '%s'", _tmp207_);
					}
					_tmp208_ = val;
					_tmp209_ = val;
					_tmp210_ = strlen (_tmp209_);
					_tmp211_ = _tmp210_;
					_tmp212_ = string_slice (_tmp208_, (glong) 1, (glong) (_tmp211_ - 1));
					_tmp213_ = _tmp212_;
					_tmp214_ = string_replace (_tmp213_, "\\\"", "\"");
					_g_free0 (val);
					val = _tmp214_;
					_g_free0 (_tmp213_);
				}
			}
			_tmp215_ = foo;
			_tmp215__length1 = foo_length1;
			_tmp216_ = _tmp215_[0];
			_tmp217_ = g_strconcat (" ", _tmp216_, NULL);
			_tmp218_ = _tmp217_;
			_tmp219_ = g_strconcat (_tmp218_, "='", NULL);
			_tmp220_ = _tmp219_;
			_tmp221_ = val;
			_tmp222_ = g_strconcat (_tmp220_, _tmp221_, NULL);
			_tmp223_ = _tmp222_;
			_tmp224_ = g_strconcat (_tmp223_, "'", NULL);
			_tmp225_ = _tmp224_;
			_tmp226_ = eos;
			_tmp227_ = g_strconcat (_tmp225_, _tmp226_, NULL);
			_tmp228_ = _tmp227_;
			_g_free0 (_tmp225_);
			_g_free0 (_tmp223_);
			_g_free0 (_tmp220_);
			_g_free0 (_tmp218_);
			result = _tmp228_;
			_g_free0 (val);
			foo = (_vala_array_free (foo, foo_length1, (GDestroyNotify) g_free), NULL);
			_g_free0 (bos);
			_g_free0 (eos);
			return result;
		}
		case GTKON_TOKEN_TYPE_CODE:
		{
			gchar* prestr = NULL;
			gchar* _tmp229_;
			const gchar* _tmp238_;
			const gchar* _tmp251_;
			const gchar* _tmp252_;
			gchar* _tmp253_;
			gchar* _tmp254_;
			gchar* _tmp255_;
			gchar* _tmp256_;
			const gchar* _tmp257_;
			gchar* _tmp258_;
			gchar* _tmp259_;
			gchar* _tmp260_;
			gchar* _tmp261_;
			const gchar* _tmp262_;
			gchar* _tmp263_;
			gchar* _tmp264_;
			gchar* _tmp265_;
			gchar* _tmp266_;
			const gchar* _tmp267_;
			gchar* _tmp268_;
			gchar* _tmp269_;
			_tmp229_ = g_strdup ("");
			prestr = _tmp229_;
			if (genie_mode) {
				g_print ("MUST FREE ALL THAT SHIT\n");
				while (TRUE) {
					const gchar* _tmp230_;
					gchar* _tmp231_;
					gchar* _tmp232_;
					gchar* _tmp233_;
					gchar* _tmp234_;
					gchar* _tmp235_;
					gchar* _tmp236_;
					gchar* _tmp237_;
					if (!(tok_idx > 1)) {
						break;
					}
					_tmp230_ = prestr;
					_tmp231_ = poptoken ();
					_tmp232_ = _tmp231_;
					_tmp233_ = g_strconcat ("</", _tmp232_, NULL);
					_tmp234_ = _tmp233_;
					_tmp235_ = g_strconcat (_tmp234_, ">\n", NULL);
					_tmp236_ = _tmp235_;
					_tmp237_ = g_strconcat (_tmp230_, _tmp236_, NULL);
					_g_free0 (prestr);
					prestr = _tmp237_;
					_g_free0 (_tmp236_);
					_g_free0 (_tmp234_);
					_g_free0 (_tmp232_);
				}
			}
			_tmp238_ = rootclass;
			if (_tmp238_ != NULL) {
				const gchar* _tmp239_;
				const gchar* _tmp240_;
				GQuark _tmp242_ = 0U;
				static GQuark _tmp241_label0 = 0;
				_tmp239_ = self->str;
				_tmp240_ = _tmp239_;
				_tmp242_ = (NULL == _tmp240_) ? 0 : g_quark_from_string (_tmp240_);
				if (_tmp242_ == ((0 != _tmp241_label0) ? _tmp241_label0 : (_tmp241_label0 = g_quark_from_static_string ("gtkaml::gtk::main")))) {
					switch (0) {
						default:
						{
							const gchar* _tmp243_;
							gchar* _tmp244_;
							gchar* _tmp245_;
							gchar* _tmp246_;
							gchar* _tmp247_;
							gchar* _tmp248_;
							gchar* _tmp249_;
							gchar* _tmp250_;
							_tmp243_ = rootclass;
							_tmp244_ = g_strdup_printf ("\t\t(new %s ()).show_all ();\n", _tmp243_);
							_tmp245_ = _tmp244_;
							_tmp246_ = g_strconcat ("\tpublic static void main(string[] args) {\n" "\t\tGtk.init (ref args);\n", _tmp245_, NULL);
							_tmp247_ = _tmp246_;
							_tmp248_ = g_strconcat (_tmp247_, "\t\tGtk.main ();\n", NULL);
							_tmp249_ = _tmp248_;
							_tmp250_ = g_strconcat (_tmp249_, "\t}\n", NULL);
							_g_free0 (self->str);
							self->str = _tmp250_;
							_g_free0 (_tmp249_);
							_g_free0 (_tmp247_);
							_g_free0 (_tmp245_);
							break;
						}
					}
				}
			}
			_tmp251_ = prestr;
			_tmp252_ = bos;
			_tmp253_ = g_strconcat (_tmp251_, _tmp252_, NULL);
			_tmp254_ = _tmp253_;
			_tmp255_ = g_strconcat (_tmp254_, "<![CDATA[\n", NULL);
			_tmp256_ = _tmp255_;
			_tmp257_ = self->str;
			_tmp258_ = g_strconcat (_tmp256_, _tmp257_, NULL);
			_tmp259_ = _tmp258_;
			_tmp260_ = g_strconcat (_tmp259_, "\n", NULL);
			_tmp261_ = _tmp260_;
			_tmp262_ = bos;
			_tmp263_ = g_strconcat (_tmp261_, _tmp262_, NULL);
			_tmp264_ = _tmp263_;
			_tmp265_ = g_strconcat (_tmp264_, "]]>\n", NULL);
			_tmp266_ = _tmp265_;
			_tmp267_ = eos;
			_tmp268_ = g_strconcat (_tmp266_, _tmp267_, NULL);
			_tmp269_ = _tmp268_;
			_g_free0 (_tmp266_);
			_g_free0 (_tmp264_);
			_g_free0 (_tmp261_);
			_g_free0 (_tmp259_);
			_g_free0 (_tmp256_);
			_g_free0 (_tmp254_);
			result = _tmp269_;
			_g_free0 (prestr);
			_g_free0 (bos);
			_g_free0 (eos);
			return result;
		}
		case GTKON_TOKEN_TYPE_INVALID:
		{
			g_error ("gtkonparser.vala:430: Invalid token!");
		}
		default:
		break;
	}
	_tmp270_ = eos;
	_tmp271_ = g_strconcat ("", _tmp270_, NULL);
	result = _tmp271_;
	_g_free0 (bos);
	_g_free0 (eos);
	return result;
}

static void
gtkon_token_instance_init (GtkonToken * self)
{
	self->bracket = 0;
}

void
gtkon_token_free (GtkonToken * self)
{
	_g_free0 (self->str);
	_g_object_unref0 (self->dis);
	g_slice_free (GtkonToken, self);
}

static inline gpointer
gtkon_parser_get_instance_private (GtkonParser* self)
{
	return G_STRUCT_MEMBER_P (self, GtkonParser_private_offset);
}

GtkonParser*
gtkon_parser_construct (GType object_type)
{
	GtkonParser* self = NULL;
	self = (GtkonParser*) g_type_create_instance (object_type);
	tok_idx = 0;
	usingcount = 0;
	mustclose = FALSE;
	first_class = TRUE;
	has_version = FALSE;
	last_type = GTKON_TOKEN_TYPE_INVALID;
	return self;
}

GtkonParser*
gtkon_parser_new (void)
{
	return gtkon_parser_construct (TYPE_GTKON_PARSER);
}

void
gtkon_parser_parse_format (GtkonParser* self,
                           const gchar* format)
{
	g_return_if_fail (self != NULL);
	g_return_if_fail (format != NULL);
	genie_mode = g_strcmp0 (format, "genie") == 0;
}

void
gtkon_parser_use_genie (GtkonParser* self,
                        gboolean use)
{
	g_return_if_fail (self != NULL);
	genie_mode = use;
}

void
gtkon_parser_parse_file (GtkonParser* self,
                         const gchar* filename)
{
	GString* _tmp0_;
	GFile* file = NULL;
	GFile* _tmp1_;
	GFile* _tmp2_;
	GtkonToken* token = NULL;
	GError* _inner_error0_ = NULL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (filename != NULL);
	_tmp0_ = g_string_new ("");
	_g_string_free0 (self->priv->xmlstr);
	self->priv->xmlstr = _tmp0_;
	_tmp1_ = g_file_new_for_path (filename);
	file = _tmp1_;
	_tmp2_ = file;
	if (!g_file_query_exists (_tmp2_, NULL)) {
		g_error ("gtkonparser.vala:462: File '%s' doesn't exist.", filename);
	}
	token = NULL;
	{
		GFileInputStream* _tmp3_ = NULL;
		GFile* _tmp4_;
		GFileInputStream* _tmp5_;
		GDataInputStream* dis = NULL;
		GDataInputStream* _tmp6_;
		_tmp4_ = file;
		_tmp5_ = g_file_read (_tmp4_, NULL, &_inner_error0_);
		_tmp3_ = _tmp5_;
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
			goto __catch0_g_error;
		}
		_tmp6_ = g_data_input_stream_new ((GInputStream*) _tmp3_);
		dis = _tmp6_;
		{
			gboolean _tmp7_ = FALSE;
			_tmp7_ = TRUE;
			while (TRUE) {
				GtkonToken* _tmp8_ = NULL;
				GDataInputStream* _tmp9_;
				GtkonToken* _tmp10_;
				GtkonToken* _tmp11_;
				GString* _tmp39_;
				GtkonToken* _tmp40_;
				gchar* _tmp41_;
				gchar* _tmp42_;
				GtkonToken* _tmp43_;
				if (!_tmp7_) {
				}
				_tmp7_ = FALSE;
				_tmp9_ = dis;
				_tmp10_ = gtkon_token_new (_tmp9_, &_inner_error0_);
				_tmp8_ = _tmp10_;
				if (G_UNLIKELY (_inner_error0_ != NULL)) {
					_g_object_unref0 (dis);
					_g_object_unref0 (_tmp3_);
					goto __catch0_g_error;
				}
				_tmp11_ = _tmp8_;
				_tmp8_ = NULL;
				_gtkon_token_free0 (token);
				token = _tmp11_;
				if (genie_mode) {
					if (nextiscode) {
						GString* _tmp12_;
						gchar* _tmp13_;
						gchar* _tmp14_;
						gchar* _tmp15_;
						gchar* _tmp16_;
						gchar* _tmp17_;
						gchar* _tmp18_;
						GtkonToken* _tmp19_;
						g_print ("-----------code---***********************************************\n");
						_tmp12_ = self->priv->xmlstr;
						_tmp13_ = poptoken ();
						_tmp14_ = _tmp13_;
						_tmp15_ = g_strconcat ("</", _tmp14_, NULL);
						_tmp16_ = _tmp15_;
						_tmp17_ = g_strconcat (_tmp16_, ">\n", NULL);
						_tmp18_ = _tmp17_;
						g_string_append (_tmp12_, _tmp18_);
						_g_free0 (_tmp18_);
						_g_free0 (_tmp16_);
						_g_free0 (_tmp14_);
						_tmp19_ = token;
						_tmp19_->type = GTKON_TOKEN_TYPE_CODE;
						last_type = _tmp19_->type;
					} else {
						GtkonToken* _tmp20_;
						const gchar* _tmp21_;
						_tmp20_ = token;
						_tmp21_ = _tmp20_->str;
						if (string_get (_tmp21_, (glong) 0) == '[') {
							GtkonToken* _tmp22_;
							const gchar* _tmp23_;
							gchar* _tmp24_;
							gchar* _tmp25_;
							gboolean _tmp26_;
							_tmp22_ = token;
							_tmp23_ = _tmp22_->str;
							_tmp24_ = string_slice (_tmp23_, (glong) 1, (glong) 8);
							_tmp25_ = _tmp24_;
							_tmp26_ = g_strcmp0 (_tmp25_, "indent=") == 0;
							_g_free0 (_tmp25_);
							if (_tmp26_) {
								GtkonToken* _tmp27_;
								const gchar* _tmp28_;
								GtkonToken* _tmp29_;
								const gchar* _tmp30_;
								gint _tmp31_;
								gint _tmp32_;
								gchar* _tmp33_;
								gchar* _tmp34_;
								_tmp27_ = token;
								_tmp28_ = _tmp27_->str;
								_tmp29_ = token;
								_tmp30_ = _tmp29_->str;
								_tmp31_ = strlen (_tmp30_);
								_tmp32_ = _tmp31_;
								_tmp33_ = string_slice (_tmp28_, (glong) 8, (glong) _tmp32_);
								_tmp34_ = _tmp33_;
								genie_indent = atoi (_tmp34_);
								_g_free0 (_tmp34_);
								g_print ("INDENT=%d\n", genie_indent);
								_gtkon_token_free0 (_tmp8_);
								continue;
							} else {
								GtkonToken* _tmp35_;
								const gchar* _tmp36_;
								_tmp35_ = token;
								_tmp36_ = _tmp35_->str;
								if (g_strcmp0 (_tmp36_, "[code]") == 0) {
									nextiscode = TRUE;
									_gtkon_token_free0 (_tmp8_);
									continue;
								} else {
									GtkonToken* _tmp37_;
									const gchar* _tmp38_;
									_tmp37_ = token;
									_tmp38_ = _tmp37_->str;
									g_print ("WARNING: Unkwnown preprocessing token (%s)\n", _tmp38_);
								}
							}
						}
					}
				}
				_tmp39_ = self->priv->xmlstr;
				_tmp40_ = token;
				_tmp41_ = gtkon_token_to_xml (_tmp40_);
				_tmp42_ = _tmp41_;
				g_string_append (_tmp39_, _tmp42_);
				_g_free0 (_tmp42_);
				_tmp43_ = token;
				last_type = _tmp43_->type;
				_gtkon_token_free0 (_tmp8_);
			}
		}
		_g_object_unref0 (dis);
		_g_object_unref0 (_tmp3_);
	}
	goto __finally0;
	__catch0_g_error:
	{
		GError* e = NULL;
		e = _inner_error0_;
		_inner_error0_ = NULL;
		if (e->code != 0) {
			const gchar* _tmp44_;
			_tmp44_ = e->message;
			g_error ("gtkonparser.vala:494: %s", _tmp44_);
		}
		_g_error_free0 (e);
	}
	__finally0:
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
		_gtkon_token_free0 (token);
		_g_object_unref0 (file);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
		g_clear_error (&_inner_error0_);
		return;
	}
	if (genie_mode) {
		g_print ("last type: %d\n", (gint) last_type);
		while (TRUE) {
			gchar* s = NULL;
			gchar* _tmp45_;
			gchar* _tmp46_;
			gchar* _tmp47_;
			gchar* _tmp48_;
			gchar* _tmp49_;
			gchar* _tmp50_;
			GString* _tmp51_;
			const gchar* _tmp52_;
			gint _tmp53_;
			if (!(tok_idx > 0)) {
				break;
			}
			g_print ("TOKID-----\n");
			_tmp45_ = poptoken ();
			_tmp46_ = _tmp45_;
			_tmp47_ = g_strconcat ("</", _tmp46_, NULL);
			_tmp48_ = _tmp47_;
			_tmp49_ = g_strconcat (_tmp48_, ">\n", NULL);
			_tmp50_ = _tmp49_;
			_g_free0 (_tmp48_);
			_g_free0 (_tmp46_);
			s = _tmp50_;
			_tmp51_ = self->priv->xmlstr;
			_tmp52_ = s;
			g_string_append (_tmp51_, _tmp52_);
			_tmp53_ = tok_idx;
			tok_idx = _tmp53_ - 1;
			_g_free0 (s);
		}
	}
	_gtkon_token_free0 (token);
	_g_object_unref0 (file);
}

void
gtkon_parser_to_file (GtkonParser* self,
                      const gchar* filename)
{
	GString* _tmp0_;
	GFile* file = NULL;
	GFile* _tmp1_;
	GError* _inner_error0_ = NULL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (filename != NULL);
	_tmp0_ = self->priv->xmlstr;
	if (_tmp0_ == NULL) {
		g_error ("gtkonparser.vala:512: no file parsed");
	}
	_tmp1_ = g_file_new_for_path (filename);
	file = _tmp1_;
	{
		GFileOutputStream* _tmp2_ = NULL;
		GFile* _tmp3_;
		GFileOutputStream* _tmp4_;
		GDataOutputStream* dos = NULL;
		GDataOutputStream* _tmp5_;
		GDataOutputStream* _tmp6_;
		GDataOutputStream* _tmp7_;
		GString* _tmp8_;
		const gchar* _tmp9_;
		_tmp3_ = file;
		_tmp4_ = g_file_create (_tmp3_, G_FILE_CREATE_NONE, NULL, &_inner_error0_);
		_tmp2_ = _tmp4_;
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
			goto __catch0_g_error;
		}
		_tmp5_ = g_data_output_stream_new ((GOutputStream*) _tmp2_);
		dos = _tmp5_;
		_tmp6_ = dos;
		g_data_output_stream_put_string (_tmp6_, "<!-- automatically generated by gtkon -->\n", NULL, &_inner_error0_);
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
			_g_object_unref0 (dos);
			_g_object_unref0 (_tmp2_);
			goto __catch0_g_error;
		}
		_tmp7_ = dos;
		_tmp8_ = self->priv->xmlstr;
		_tmp9_ = _tmp8_->str;
		g_data_output_stream_put_string (_tmp7_, _tmp9_, NULL, &_inner_error0_);
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
			_g_object_unref0 (dos);
			_g_object_unref0 (_tmp2_);
			goto __catch0_g_error;
		}
		_g_object_unref0 (dos);
		_g_object_unref0 (_tmp2_);
	}
	goto __finally0;
	__catch0_g_error:
	{
		GError* e = NULL;
		const gchar* _tmp10_;
		e = _inner_error0_;
		_inner_error0_ = NULL;
		_tmp10_ = e->message;
		g_error ("gtkonparser.vala:519: %s", _tmp10_);
		_g_error_free0 (e);
	}
	__finally0:
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
		_g_object_unref0 (file);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
		g_clear_error (&_inner_error0_);
		return;
	}
	_g_object_unref0 (file);
}

gchar*
gtkon_parser_to_string (GtkonParser* self)
{
	const gchar* _tmp0_ = NULL;
	GString* _tmp1_;
	gchar* _tmp4_;
	gchar* result;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp1_ = self->priv->xmlstr;
	if (_tmp1_ != NULL) {
		GString* _tmp2_;
		const gchar* _tmp3_;
		_tmp2_ = self->priv->xmlstr;
		_tmp3_ = _tmp2_->str;
		_tmp0_ = _tmp3_;
	} else {
		_tmp0_ = "";
	}
	_tmp4_ = g_strdup (_tmp0_);
	result = _tmp4_;
	return result;
}

static void
value_gtkon_parser_init (GValue* value)
{
	value->data[0].v_pointer = NULL;
}

static void
value_gtkon_parser_free_value (GValue* value)
{
	if (value->data[0].v_pointer) {
		gtkon_parser_unref (value->data[0].v_pointer);
	}
}

static void
value_gtkon_parser_copy_value (const GValue* src_value,
                               GValue* dest_value)
{
	if (src_value->data[0].v_pointer) {
		dest_value->data[0].v_pointer = gtkon_parser_ref (src_value->data[0].v_pointer);
	} else {
		dest_value->data[0].v_pointer = NULL;
	}
}

static gpointer
value_gtkon_parser_peek_pointer (const GValue* value)
{
	return value->data[0].v_pointer;
}

static gchar*
value_gtkon_parser_collect_value (GValue* value,
                                  guint n_collect_values,
                                  GTypeCValue* collect_values,
                                  guint collect_flags)
{
	if (collect_values[0].v_pointer) {
		GtkonParser * object;
		object = collect_values[0].v_pointer;
		if (object->parent_instance.g_class == NULL) {
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		}
		value->data[0].v_pointer = gtkon_parser_ref (object);
	} else {
		value->data[0].v_pointer = NULL;
	}
	return NULL;
}

static gchar*
value_gtkon_parser_lcopy_value (const GValue* value,
                                guint n_collect_values,
                                GTypeCValue* collect_values,
                                guint collect_flags)
{
	GtkonParser ** object_p;
	object_p = collect_values[0].v_pointer;
	if (!object_p) {
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
	}
	if (!value->data[0].v_pointer) {
		*object_p = NULL;
	} else if (collect_flags & G_VALUE_NOCOPY_CONTENTS) {
		*object_p = value->data[0].v_pointer;
	} else {
		*object_p = gtkon_parser_ref (value->data[0].v_pointer);
	}
	return NULL;
}

GParamSpec*
param_spec_gtkon_parser (const gchar* name,
                         const gchar* nick,
                         const gchar* blurb,
                         GType object_type,
                         GParamFlags flags)
{
	ParamSpecGtkonParser* spec;
	g_return_val_if_fail (g_type_is_a (object_type, TYPE_GTKON_PARSER), NULL);
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
	G_PARAM_SPEC (spec)->value_type = object_type;
	return G_PARAM_SPEC (spec);
}

gpointer
value_get_gtkon_parser (const GValue* value)
{
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_GTKON_PARSER), NULL);
	return value->data[0].v_pointer;
}

void
value_set_gtkon_parser (GValue* value,
                        gpointer v_object)
{
	GtkonParser * old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_GTKON_PARSER));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, TYPE_GTKON_PARSER));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
		gtkon_parser_ref (value->data[0].v_pointer);
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		gtkon_parser_unref (old);
	}
}

void
value_take_gtkon_parser (GValue* value,
                         gpointer v_object)
{
	GtkonParser * old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_GTKON_PARSER));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, TYPE_GTKON_PARSER));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		gtkon_parser_unref (old);
	}
}

static void
gtkon_parser_class_init (GtkonParserClass * klass,
                         gpointer klass_data)
{
	gtkon_parser_parent_class = g_type_class_peek_parent (klass);
	((GtkonParserClass *) klass)->finalize = gtkon_parser_finalize;
	g_type_class_adjust_private_offset (klass, &GtkonParser_private_offset);
}

static void
gtkon_parser_instance_init (GtkonParser * self,
                            gpointer klass)
{
	self->priv = gtkon_parser_get_instance_private (self);
	self->priv->xmlstr = NULL;
	self->ref_count = 1;
}

static void
gtkon_parser_finalize (GtkonParser * obj)
{
	GtkonParser * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_GTKON_PARSER, GtkonParser);
	g_signal_handlers_destroy (self);
	_g_string_free0 (self->priv->xmlstr);
}

static GType
gtkon_parser_get_type_once (void)
{
	static const GTypeValueTable g_define_type_value_table = { value_gtkon_parser_init, value_gtkon_parser_free_value, value_gtkon_parser_copy_value, value_gtkon_parser_peek_pointer, "p", value_gtkon_parser_collect_value, "p", value_gtkon_parser_lcopy_value };
	static const GTypeInfo g_define_type_info = { sizeof (GtkonParserClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) gtkon_parser_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (GtkonParser), 0, (GInstanceInitFunc) gtkon_parser_instance_init, &g_define_type_value_table };
	static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
	GType gtkon_parser_type_id;
	gtkon_parser_type_id = g_type_register_fundamental (g_type_fundamental_next (), "GtkonParser", &g_define_type_info, &g_define_type_fundamental_info, 0);
	GtkonParser_private_offset = g_type_add_instance_private (gtkon_parser_type_id, sizeof (GtkonParserPrivate));
	return gtkon_parser_type_id;
}

GType
gtkon_parser_get_type (void)
{
	static volatile gsize gtkon_parser_type_id__once = 0;
	if (g_once_init_enter (&gtkon_parser_type_id__once)) {
		GType gtkon_parser_type_id;
		gtkon_parser_type_id = gtkon_parser_get_type_once ();
		g_once_init_leave (&gtkon_parser_type_id__once, gtkon_parser_type_id);
	}
	return gtkon_parser_type_id__once;
}

gpointer
gtkon_parser_ref (gpointer instance)
{
	GtkonParser * self;
	self = instance;
	g_atomic_int_inc (&self->ref_count);
	return instance;
}

void
gtkon_parser_unref (gpointer instance)
{
	GtkonParser * self;
	self = instance;
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
		GTKON_PARSER_GET_CLASS (self)->finalize (self);
		g_type_free_instance ((GTypeInstance *) self);
	}
}

static void
_vala_array_destroy (gpointer array,
                     gssize array_length,
                     GDestroyNotify destroy_func)
{
	if ((array != NULL) && (destroy_func != NULL)) {
		gssize i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}

static void
_vala_array_free (gpointer array,
                  gssize array_length,
                  GDestroyNotify destroy_func)
{
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}

static gssize
_vala_array_length (gpointer array)
{
	gssize length;
	length = 0;
	if (array) {
		while (((gpointer*) array)[length]) {
			length++;
		}
	}
	return length;
}

